### ISSUE TITLE
Routing based upon queries matches incorrect query.

### ISSUE THREAD

**Issue by dkumor** [gorilla/mux#109]
```go
subrouter.HandleFunc("/blah/blah", myfunc1).Methods("GET").Queries("i1", "{i1}")
subrouter.HandleFunc("/blah/blah", myfunc2).Methods("GET").Queries("t1", "{t1}")
```

- Expectation: `GET /blah/blah?t1=0` will call `myfunc2`
- What happens: `myfunc1` is called

The issue appeared within the last 24 hours - the code functioned according to the expectations yesterday (7/15).

**Comment by kisielk** [comment]
@burrbd any chance you can have a look at this?

**Comment by burrbd** [comment]
I think the query parameter ```defaultPattern``` change from #108 is causing this.

Queries("t1", "{t1}") creates ```^t1=[^?&]*$```. The string from the request to match against will be ```t1=``` even if the parameter wasn't present in the URL.

**Comment by dkumor** [comment]
The merged PR fixed the issue. Thanks a lot!
