### ISSUE TITLE
Getting Route URLs from templates

### ISSUE THREAD

**Issue by fesja** [gorilla/mux#123]
Hi,

I wonder how are you getting the Route URLs from templates? I don't want to use

    <a href="/posts/{{ .post.Id }}/edit">Edit post</a>

but something like

    <a href="{{ router.Get("PostEdit").URL("id", .post.Id }}">Edit post</a>

Is it possible somehow?

thanks!

**Comment by kisielk** [comment]
These kind of questions are better suited for the mailing list (https://groups.google.com/forum/#!forum/gorilla-web). I usually pass in functions to generate URLs via http://golang.org/pkg/html/template/#FuncMap
