### ISSUE TITLE
undocumented behaviour: HeadersRegexp wraps regexp in wildcard by default

### ISSUE THREAD

**Issue by bluehallu** [gorilla/mux#124]
Not sure if this is intended, but using this regexp `abc`, actually means you're using `.*abc.*`. I don't think this is appropriate since it doesn't let me specify I want certain order on the Accept header, for instance.

**Comment by themihai** [comment]
I find this kind of behaviour/regex flavour quite disturbing especially because it's not documented. For example using `signin.api{_:(^$|^\.sandbox$)}.example.co.uk` with the standard regexp package matches ``sigin.api.example.co.uk`` and ``signin.api.sandbox.example.co.uk`` but on route.Host that doesn't happen.

**Comment by elithrar** [comment]
@themihai If you can submit a PR documenting this it'd be hugely appreciated. I don't think we can (safely) change this behaviour given applications depending on it in the wild.

**Comment by bluehallu** [comment]
@elithrar The problem is that it's not just undocumented behaviour, it's actually preventing you from supplying your own raw regex!

**Comment by elithrar** [comment]
@bluehallu I get that: but changing it would impact other applications out there. I'm not defending code I wrote (I didn't write it), I'm just making sure we don't make breaking changes where we can avoid that.

**Comment by bluehallu** [comment]
What about an optional flag to change this behaviour?

**Comment by elithrar** [comment]
I'm open to that, if you have a proposal?

**Comment by bluehallu** [comment]
I'm afraid I only used Go once in my life, spotted this weird behaviour in one of the main libraries and reported it, but that's where my Mux knowledge ends :(

**Comment by themihai** [comment]
I think a method on Router[0] would work best. It would be in line with StrictSlash[1]. What do you think?

// StrictRegex defines the behaviour of HeadersRegexp, Host and regular expressions within the route paths. The initial value is false which means it wraps regexp in wildcard by default.
[0] ``func (r *Router) StrictRegex(value bool) *Router ``


[1] [https://godoc.org/github.com/gorilla/mux#Router.StrictSlash](https://godoc.org/github.com/gorilla/mux#Router.StrictSlash)

**Comment by elithrar** [comment]
@themihai That would be great.

**Comment by mtso** [comment]
I'd like to add two examples to the documentation for `Route.HeadersRegexp`. I'm thinking of adding a new file named `example_route_test.go` using this article as a guide: https://blog.golang.org/examples.

The example file would contain two runnable examples:  
1. `func ExampleRoute_HeadersRegexp()` for the general behavior where the given pattern matches any substring of the header value.
1. `func ExampleRoute_HeadersRegexp_exactMatch()` to show how to do a strict pattern that does an exact match with `^pattern$`.

**Comment by kisielk** [comment]
@mtso go for it!
