### ISSUE TITLE
Is there a way to generate a "sitemap" of a REST API?

### ISSUE THREAD

**Issue by tleyden** [gorilla/mux#129]
I have a REST api defined with Gorrillamux, and want to show a hierarchical view of the entire REST api in HTML.  Does Gorillamux provide any API calls that would make that relatively easy?

**Comment by derekdowling** [comment]
Even just being able to do this for debugging via `fmt.Printf("%+v", router.Tree())` would be super helpful when dealing with subrouters.

**Comment by elithrar** [comment]
You can use [`Router.Walk`](https://godoc.org/github.com/gorilla/mux#Router.Walk) for this with a `Router.WalkFunc` to walk through the URLs (and then build a map/slice of structs with the results).

**Comment by elico** [comment]
@elithrar I have tried to use the Walk function to print the list of pathes which the router handles but something is wrong, every single route have an empty name: https://gist.github.com/elico/170b4d98b52b1da58d56
Am I doing something wrong?

**Comment by nicowernli** [comment]
You have to add the name to the routes if you want to get it later using the Name() method

**Comment by elico** [comment]
@nicowernli OK, from the code I was suspecting that this is what I would be required to do.
Isn't there any other way to get the route path?matcher without setting the name??

**Comment by nicowernli** [comment]
I'm sory @elico, I'v been reading the source code and it looks like you can't access the path but not 100% sure

**Comment by elico** [comment]
@nicowernli @elithrar I am thinking about patching the source and to add a getMatchers to kind of solve the issue.

**Comment by elithrar** [comment]
Refer to #104 for an upcoming approach for addressing this.
