### ISSUE TITLE
No way to build https:// URLs with URL()

### ISSUE THREAD

**Issue by kisielk** [gorilla/mux#13]
As far as I can tell there's no way to generate a reverse route with an https:// URL. The only code I can find related to the scheme is in https://github.com/gorilla/mux/blob/master/route.go#L405, which sets it to the default of http, but there doesn't seem to be a way to have it generate one with https instead.

**Comment by fluffysquirrels** [comment]
> What if we default to http, but if there's a schemesMatcher in the route, use the first scheme defined there?

+1 @kisielk

**Comment by ADone** [comment]
Any opinions for this solutions?

**Comment by ChrisHines** [comment]
I am interested in moving this PR forward. I can work on adding the tests.
