### ISSUE TITLE
mux.Vars() returns empty dictionary if handler function is in separate package from router.

### ISSUE THREAD

**Issue by tonycosentini** [gorilla/mux#135]
If I create a new router like this:

```go
package main

import (
  "github.com/gorilla/mux"
  "net/http"
  "fmt"
)

func main() {
  	r := mux.NewRouter().StrictSlash(true)
    r.Methods("GET").Path("/hello/{param:[0-9]+}”).HandlerFunc(Handler)
    http.ListenAndServe(":8000", r)
}

func Handler(w http.ResponseWriter, r *http.Request) {
  fmt.Println("Vars:", mux.Vars(r))
}
```

The variables dictionary contains the correct values.

However, if I move the Handler function to another package, outside of the package that contains the router, `mux.Vars(r)` always returns an empty map.

Am I missing something here? Apologies if there is a clear error on my part here.

Thanks!

**Comment by elithrar** [comment]
Are you accidentally importing a vendored copy of mux in the other package? Importing a handler from another package shouldn't change the behaviour.

See here for a small demo of the (working, correct) behaviour - just unzip it into your `$GOPATH/github.com/tonycosentini/muxdemo`, move `handlers.go` into a `handlers` directory and build it: https://gist.github.com/elithrar/077ce461183517c2f73b

(does your program differ from that in terms of structure?)

**Comment by tonycosentini** [comment]
I totally missed this :(, it was Godeps vendoring in one file, but not a new file.

Sorry - and huge thanks for clarifying.

**Comment by marcelloh** [comment]
I somehow have this behavior too.
Strange thing is, when this line runs:
fmt.Fprintf(w, "Vars: %v\n%v", mux.Vars(r), r.URL.Path)
this is my output
map[]
/hello/testnaam
Normally it runs coeerect, but when debugging a testscenario, it has empty Vars.
Can't figure out how to solve this.

**Comment by kisielk** [comment]
@marcelloh Please open a new bug with a fully reproducible example
