### ISSUE TITLE
Will this support fasthttp and google context?

### ISSUE THREAD

**Issue by pjebs** [gorilla/mux#140]
For version 2 of gorilla mux

https://github.com/valyala/fasthttp is x10 faster than net/http
http://godoc.org/golang.org/x/net/context
https://blog.golang.org/context

**Comment by elithrar** [comment]
https://github.com/gorilla/muxy (the eventual successor to mux) supports net/context out of the box. 

It is (very) unlikely to support fasthttp: fasthttp is very different from net/http and therefore incompatible with the large number of existing libraries that use the `http.Handler` interface.

The "10x" benchmarks are also unlikely to be realized into actual "request per second" gains, and in many cases template rendering or DB connections will limit your application well before net/http does. Something like 80k/req/sec returning static JSON will drop to sub-15k/req/sec once you start rendering templates.
