### ISSUE TITLE
Path Cleaning Causes Re-Direct

### ISSUE THREAD

**Issue by tomwilkie** [gorilla/mux#142]
We have [an app](http://github.com/weaveworks/scope) that needs to accept arbitrary URL-encoded variables in its path; we ran in the the usual go-bug (https://github.com/golang/go/issues/10887) of encoded slashes not being handled correctly, and wrote a custom [URLMatcher](https://github.com/weaveworks/scope/blob/master/app/router.go#L31) to deal with this.  All was good.

It turns out that if our variable containing a url encoded slash starts with a slash, we hit the [cleanPath code path](https://github.com/gorilla/mux/blob/master/mux.go#L77) as go decodes the `%2F` to a slash, the cleanPath dedupes `//` to a single slash and gorilla does a redirect.

This may be a dupe of https://github.com/gorilla/mux/issues/94, but I'm inclined to say its more serious as I don't seem to be able to override this with my own URLMatcher, which is kinda the whole reason we use gorilla in the first place.

Any thoughts on how to deal with this?

**Comment by elithrar** [comment]
See https://github.com/gorilla/mux/pull/154
