### ISSUE TITLE
Hope add a new feature

### ISSUE THREAD

**Issue by suanlihong** [gorilla/mux#146]
When i use mux,I think some features are not perfect.I hope join the interceptor for monitor.

**Comment by elithrar** [comment]
What features do you have in mind?

We're always happy to consider new features, but raising an Issue to
discuss/debate first will help to make sure you don't do work that won't be
merged!

**Comment by suanlihong** [comment]
I think your viewpoint is right.
Here are some of my thoughts：

1.When I developed my blog, I can not use the mux to intercept login.Perhaps, your design is at the back end of the service. But, I  found mux can parse HTML. So I think the mux will be better after add the interceptor.
2.Interceptor not only can intercept login,I hope it can intercept the recipient before and after.

Examples:

`func (i *MyInterceptor) Before() int {
}`
`func Login(w http.ResponseWriter, r *http.Request) {
}`
`func (i *MyInterceptor) After(status int) int {
}`
3. Interceptor often do not intercept a request, compare to url for Interceptor.

Examples:
`r.HandleFunc(/hello/a, Login)`
`r.HandleFunc(/hello/b, Login)`
`r.HandleFunc(/hello/c, Login)`

These three use the same interceptor.

**Comment by elithrar** [comment]
This is typically referred to as middleware and you can do this in mux today - e.g.

```go
func main() {
    r := mux.NewRouter()

    // Single handler
    r.HandleFunc("/form", use(http.HandlerFunc(formHandler), csrf, logging)

    // All handlers
    http.Handle("/", recovery(r))

    // Sub-routers
    apiMiddleware := []func(http.Handler) http.Handler{logging, apiAuth, json}
    api := router.PathPrefix("/api").Subrouter()
    api.Handle("/users", use(usersHandler, apiMiddleware...))
}

// You could also create a type for this
type Chain []func(http.Handler) http.Handler

// Middleware chainer
func use(h http.Handler, middleware ...func(http.Handler) http.Handler) http.Handler {
    for _, m := range middleware {
        h = m(h)
    }
    return h
}

// Middleware (just a http.Handler)
func AddHeaders(h http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // do stuff before
        w.Header().Set("X-Some-Header", "Value")
        h.ServeHTTP(w, r)
        // do stuff after
    })
}

// Basic handler at the end of it all.
func formHandler(w http.ResponseWriter, r *http.Request) {
      // do stuff
}
```

Libraries like https://github.com/justinas/alice can help simplify it as well.

**Comment by suanlihong** [comment]
Thanks.

**Comment by ElvizLai** [comment]
func main() {
    r := mux.NewRouter()

    admin:=outer.PathPrefix("/admin").Subrouter()
    //need some to filter if req is authorized
 	//if unauthorized, it blocked and return 401

	admin.Handle("/add", AddHandler)
	admin.Handle("/delete", DelHandler)
    admin.Handle("/list", ListHandler)
}

**Comment by elithrar** [comment]
Wrap `admin` with middleware that inspects the request.

**Comment by bezrukovspb** [comment]
@suanlihong @ElvizLai what do you think about something like this?

```go
router := NewRouter().Use(globalMiddleware)
router.Path("/use-global-middleware-only").HandlerFunc(requestHandlerFuncA)

subRouter := router.PathPrefix("/admin").Subrouter().Use(middlewareA, middlewareB)
subRouter.Path("/hello").HandlerFunc(requestHandlerFuncB)
subRouter.Path("/hi").HandlerFunc(requestHandlerFuncC)
subRouter.Path("/login").HandlerFunc(requestHandlerFuncD)
```

It's implemented [here](https://github.com/bezrukovspb/mux)

**Comment by cescoferraro** [comment]
@bezrukovspb :+1: :100:

**Comment by elithrar** [comment]
Closing as this can already be achieved.

**Comment by cescoferraro** [comment]
@elithrar is it on the docs?

**Comment by bezrukovspb** [comment]
@elithrar, don't know how many people needs this.. But I can make PR with this "Use" feature if needed.

**Comment by elithrar** [comment]
I don't think this is worth extending the public API - you can write a helper like `Use` in your own code, or look at a mature library like [justinas/alice](https://github.com/justinas/alice).

**Comment by mikijov** [comment]
@elithrar I think the point is that people are used to chaining in node.js, and it is really powerful feature. I don't think I ever created a with a route where I did not use middleware. Authentication, logging, decoding etc. all middleware that is ubiquitous. I think we are confused by "wontfix" attitude. @bezrukovspb already implemented it... why not add it and make it simple than make people learn new way of dong things or add more dependencies?

**Comment by elithrar** [comment]
@mikijov I get that, but gorilla/mux has a fairly large API as-is. Do we then add `UseHandleFunc` and `UseHandler` functions? What is the ordering? (first added?)

There are some great libraries out that work well with mux, and if someone has authored a PR without checking first, I can't be responsible for that.

Sorry to be blunt, but I can't say "yes" to every well-intentioned PR.

**Comment by mikijov** [comment]
Fair enough. Let's hope it is only little growing pains getting used to the new platform.  I have an aversion towards having too many dependencies, so that is my big argument. But, I will take your word as someone who has spent more time on the platform. Let's hope you are still right in a year's time. :-)
