### ISSUE TITLE
what is the behavior of Queries() ?

### ISSUE THREAD

**Issue by morenoh149** [gorilla/mux#147]
https://github.com/gorilla/mux/blob/2aad27d3101b8183f8fa1bebdbc2cdb74fcef090/mux_test.go#L584

what should we expect if we execute
```go
		{
			title:       "Queries route with empty args should (?)",
			route:       new(Route).Queries(),
			request:     newRequest("GET", "http://localhost?"),
			vars:        map[string]string{},
			host:        "",
			path:        "",
			shouldMatch: true,
		},
```

**Comment by elithrar** [comment]
You should get nothing. Are you seeing otherwise?

**Comment by morenoh149** [comment]
nope just have a codebase I inherited and it was difficult to inspect this behaviour, so I was hoping the test suite covered it.
