### ISSUE TITLE
StrictSlash and Paths with empty variables do not work together

### ISSUE THREAD

**Issue by benma** [gorilla/mux#153]
``` Go
router := mux.NewRouter().StrictSlash(true).PathPrefix("/prefix/").Subrouter()
router.Path(`/`).Handler(handler)
```

This behaves like expected:
`http://localhost/prefix` is redirected to `http://localhost/prefix/`, and the handler is executed.

On the other hand, if the route contains a variable that can be empty, the route stops working:

``` Go
router := mux.NewRouter().StrictSlash(true).PathPrefix("/prefix/").Subrouter()
router.Path(`/{rest:.*}`).Handler(handler)
```

This will result `http://localhost/prefix/` to be redirected to `http://localhost/prefix`, but this results in a `404 not found` error.

I expected it to work the same as the first example, as the `{rest:.*}` left empty should be equivalent to the `/` route.

My workaround was to add both routes for the same handler, and StrictSlash() was supposed to solve defining two routes for one handler.

Thoughts?

**Comment by elithrar** [comment]
This is similar to #145 #79 #78 and #31 - that is, the root path of a sub-router isn't routable.

I'd love to see a PR for this (I haven't got the time myself) that:

* Makes the root path of a Subrouter routeable
* Plays well with StrictSlash
* Has tests to cover each combination.

**Comment by benma** [comment]
Thanks. #31 sounds the most similar, though in my case, everything works as expected until I add a variable to the route. Is that still the same root cause?

**Comment by elithrar** [comment]
@benma Likely - as above there are a number of issues related to this. I can't confirm until I have time to dig into the source.

**Comment by elithrar** [comment]
does https://github.com/gorilla/mux/issues/215 resolve this for you now? a failing test case will help.

**Comment by elithrar** [comment]
Confirming that this works:

```go
	r := mux.NewRouter().StrictSlash(true)
	r.Use(Logger)
	r.HandleFunc("/", handler)
	r.HandleFunc("/{name}", handler)

	// Internal metrics
	metrics := r.PathPrefix("/metrics").Subrouter()
	metrics.HandleFunc("/{variable:.*}", handler)
```

Output:
```sh
➜  ~  curl localhost:8080/metrics/hello
hello: /metrics/hello
➜  ~  curl localhost:8080/metrics
hello: /metrics
```
