### ISSUE TITLE
Do a repository release

### ISSUE THREAD

**Issue by apremalal** [gorilla/mux#156]
Go dependency management tools like Gom use a particular commitid/ tag to checkout the dependencies. Since this repo doesn't have a tag users have to stick to commitids, which is not clean and hard to track.

**Comment by onlyjob** [comment]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by elithrar** [comment]
Thankfully, I know what software versions are ;)

I'll look at doing a release/tag this weekend.

**Comment by onlyjob** [comment]
Thank you. :)

**Comment by elithrar** [comment]
Done.

@onlyjob — just to be clear, versioning is useful when vendoring using Go's vendoring capabilities. Given that gorilla/mux is a library, building it into a Debian package would be a bad idea, and would island users relying on it/rely on a third party to update it.

It's extremely unlikely gorilla/mux will ever have a truly breaking version (a "2.0") due to the age of the library (pre-dating vendoring) and goals of the Gorilla project.

> We're now tagging releases with SemVer, something that was long overdue. gorilla/mux has strict API compatibility guarantees, excepting any security issues, but we understand that being able to vendor specific versions is a useful feature.
> 
> Minor breaking changes (i.e. regex functionality) will be treated as minor releases.
> 
> We also strongly recommend that you stay up to date: although this project has not had any security issues to date, back-porting security patches across multiple releases (v1.1.1, v1.2.1, etc.) is not maintianable for us.

**Comment by onlyjob** [comment]
> versioning is useful when vendoring using Go's vendoring capabilities.

Indeed. Versioning can provide additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

> Given that gorilla/mux is a library, building it into a Debian package would be a bad idea, and would island users relying on it/rely on a third party to update it.

Packaging build dependencies is useful to reduce duplication and to run tests properly on build -- a something often neglected for vendored libraries.

It is absolutely normal for users of GNU/Linux distributions to rely on pre-built binary packages provided by OS from native repositories.

Developers can still fetch latest sources themselves. Packaging can't stop them from doing that.

> v.1.1

Thank you. :)

**Comment by elithrar** [comment]
> It is absolutely normal for users of GNU/Linux distributions to rely on pre-built binary packages provided by OS from native repositories.

Just to be clear: a binary (application) that vendored gorilla/mux would make sense, as that binary should not be fetching dependencies at install time (bad).

Something like lib-gorilla-mux would be bad for users as it becomes an islanded version of the library.

**Comment by onlyjob** [comment]
Don't you worry, we always want to do the right thing. :)
Of course primary purpose of source packages is to provide build (not run-time) dependencies.
Golang produces static executables with all libraries built-in. Resulting binary package have no dependencies on source library packages.

As for concept of "islanded" libraries I think it is worth reading about problems with static linking:

  https://wiki.debian.org/StaticLinking

**Comment by elithrar** [comment]
> Golang produces static executables with all libraries built-in. Resulting binary package have no dependencies on source library packages.

Not true as of Go 1.5 ;)

**Comment by onlyjob** [comment]
Unfortunately true.  :(
You can not yet make a dynamic Golang library even with Golang 1.5 or 1.6.
Executables generated by Golang-1.5 at least depend on _libc6_ but not on precompiled object go-libraries...
Maybe eventually Golang will evolve to support dynamic linking properly but until then abuse of best practices in software engineering will continue... :(

**Comment by tpiron** [comment]
Having a mux release version that I could have use with gom would have prevent me for getting this issue btw : https://github.com/gorilla/mux/issues/194
