### ISSUE TITLE
Question about Mux Query Matching

### ISSUE THREAD

**Issue by akutz** [gorilla/mux#157]
Hi,

If I register two routes for `/volumes/{service}` where one has no constraints other than the route path and method type (`POST`) and the other has the same route path and method type in addition to the query constraint `detach`, what's the expected behavior?

What's occurring is that the first route (the one sans query string constraint) is matching `/volumes/{service}` *and* `/volumes/{service}?detach`. That's not what I understood should happen. Is this the expected behavior?

Thank you!

**Comment by elithrar** [comment]
Are you explicitly using `.Queries("detach", "")` here?

**Comment by akutz** [comment]
Hi @elithrar,

I am. You'd have to trace it, but it [starts here](https://github.com/akutz/libstorage/blob/feature/dadd/api/server/router/volume/volume.go#L136) where you'll note I'm only calling `Queries("detach")`. Well, that's because I created a wrapper for a `Route` and when you invoke `Queries(q ...string)`, if `len(q) == 1` then an additional, zero-length string is appended to the wrapper Route's internal `queries []string` collection.

Finally, [this](https://github.com/akutz/libstorage/blob/feature/dadd/api/server/server.go#L367) is where I'm invoking the Gorilla toolkit's `Queries` function.

```
			f := s.makeHTTPHandler(ctx, r)
			mr := m.Path(r.GetPath())
			mr = mr.Name(r.GetName())
			mr = mr.Methods(r.GetMethod())
			mr = mr.Queries(r.GetQueries()...)
			mr.Handler(f)
			ctx.Log().WithField("route", r.GetName()).Debug("registered route")
```

While I'm only emitting the name of the route in the log at the moment, the log statement used to look like this:

```
			ctx.Log().WithFields(log.Fields{
				"route":        r.GetName(),
				"path":         r.GetPath(),
				"method":       r.GetMethod(),
				"queries":      r.GetQueries(),
				"len(queries)": len(r.GetQueries()),
			}).Debug("registered route")
```

In fact, for giggles I added that back and am including the relevant portion of the logs:

```
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=GET path=/snapshots/{service} queries=[] route=shapshotsForService tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=GET path=/snapshots/{service}/{snapshotID} queries=[] route=snapshotInspect tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=POST path=/snapshots/{service}/{snapshotID}?create queries=[] route=snapshotCreate tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=POST path=/snapshots/{service}/{snapshotID}?copy queries=[] route=snapshotCopy tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=DELETE path=/snapshots/{service}/{snapshotID} queries=[] route=snapshotRemove tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=GET path=/volumes queries=[] route=volumes tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=GET path=/volumes/{service} queries=[] route=volumesForService tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=GET path=/volumes/{service}/{volumeID} queries=[] route=volumeInspect tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service} queries=[create ] route=volumeCreate tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service}/{volumeID} queries=[copy ] route=volumeCopy tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service}/{volumeID} queries=[snapshot ] route=volumeSnapshot tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service}/{volumeID} queries=[attach ] route=volumeAttach tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes queries=[detach ] route=volumesDetachAll tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service} queries=[detach ] route=volumesDetachForService tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=2 method=POST path=/volumes/{service}/{volumeID} queries=[detach ] route=volumeDetach tls=true
DEBU[0000] registered route                              host=tcp://127.0.0.1:7979 len(queries)=0 method=DELETE path=/volumes/{service}/{volumeID} queries=[] route=volumeRemove tls=true
INFO[0000] api listening                                 host=tcp://127.0.0.1:7979 tls=true
```

As you can see, the routes with the `detach` query string do note that there are two query elements, and the output shows the second is an empty string.

FWIW, I have it working temporarily by making it necessary to use the `create` query string to `POST` a new object to a collections resource. Ideally the default action should be `create`, without the need for an explicit query string. However, this alleviates the issue by making nothing use the default Path/Method combination, sans query string constraint.

**Comment by akutz** [comment]
I wonder if it's the order in which the routes are registered? I'm going to try registering the more specific ones first, specifically this use case.

**Comment by akutz** [comment]
Ha! That was it! This new order works as expected:

```
		// POST

		// detach all volumes for a service
		router.NewPostRoute(
			"volumesDetachForService",
			"/volumes/{service}",
			r.volumeDetachAllForService,
			handlers.NewServiceValidator(r.services),
			handlers.NewSchemaValidator(
				schema.VolumeDetachRequestSchema,
				schema.VolumeMapSchema,
				func() interface{} { return &httptypes.VolumeDetachRequest{} }),
		).Queries("detach"),

		// create a new volume
		router.NewPostRoute(
			"volumeCreate",
			"/volumes/{service}",
			r.volumeCreate,
			handlers.NewServiceValidator(r.services),
			handlers.NewSchemaValidator(
				schema.VolumeCreateRequestSchema,
				schema.VolumeSchema,
				func() interface{} { return &httptypes.VolumeCreateRequest{} }),
			handlers.NewPostArgsHandler(),
		), //.Queries("create"),
```

**Comment by akutz** [comment]
I'll let you verify the behavior is a bug / by design based on my feedback and then leave it up to you to close this as by design or track it as a bug. Either way, there appears to be a fairly simple workaround :)

**Comment by elithrar** [comment]
That's the correct behaviour (the same as `net/http`)—the docs could be clearer here.

(mux is probably the Gorilla library I've had the least exposure to, so I often have to check the behaviour myself!)

**Comment by akutz** [comment]
Thank you for the answer!

**Comment by dselans** [comment]
Just ran into this myself - thank you @akutz for bringing this up (and documenting the resolve).
