### ISSUE TITLE
mux headers do not support regex

### ISSUE THREAD

**Issue by rbucker** [gorilla/mux#16]
since accept headers can be complex with all sorts of version information embedded it would be better if it supported regex in the value portion of the pair.

**Comment by eastwood** [comment]
I've added regex support. An example of usage is as follows:
```
	r := mux.NewRouter()
	r.HandleFunc("/", RootHandler).Headers("Content-Type", "application/json.*")
	http.ListenAndServe(":8080", r)
}
```
Now both requests will work:
```
curl -X GET -H "Content-Type: application/json" localhost:8080
curl -X GET -H "Content-Type: application/json;charset=UTF-8" localhost:8080
```
My personal uses were for handling `application/(json|text)`

**Comment by bluehallu** [comment]
@eastwood isn't HeadersRegexp what should be used here?

**Comment by eastwood** [comment]
@bluehallu  That's correct. Above comment is out of data. The documentation should be up to date with this, if anybody requires it

**Comment by bluehallu** [comment]
@eastwood I've tested the code and it behaves as you'd expect, but the docs are in sync with your comment above:

"...Alternatively, you can provide a regular expression and match the header as follows..."

**Comment by eastwood** [comment]
Ah I see :) Good pickup, sorry about the confusion, must of been a legacy commit. I'll clean that up right away to fix the confusion. Alternatively, you can fix the change and make a pull request, the more contributors the merrier!

**Comment by eastwood** [comment]
#125 Should fix this up for us

**Comment by bluehallu** [comment]
I wanted to make sure I wasn't misunderstanding this before doing a PR. All
fixed now so thanks :)

**Comment by jmassara** [comment]
It would be nice to support capturing regex matches in `mux.Vars()` (see my previous comment), similiar to how the `router.HandlerFunc` does it.

**Comment by kisielk** [comment]
@jmassara please open a separate issue for that.
