### ISSUE TITLE
License is not clear

### ISSUE THREAD

**Issue by sevaivanov** [gorilla/mux#164]
"this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution."
I want to make sure that it is GPLv3 compatible. There doesn't seems to be any documentation and/or other material beside the LICENSE file. Would you confirm me this? Also, why not using GPLv3 or MIT license instead of a short notice?

**Comment by elithrar** [comment]
The [LICENSE](https://github.com/gorilla/mux/blob/master/LICENSE) is the 3-Clause BSD license. The FSF indicate that it is indeed GPL-compatible: http://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

I wasn't the original author, but I suspect the 3-Clause BSD license was used for the third clause (re: preventing endorsement), which is the same reason I use it for many of my own projects.

**Comment by sevaivanov** [comment]
Thank you. It may be a good idea to state that it is a 3-Clause BSD license. It is very clear now!
