### ISSUE TITLE
How to set URL parameters for unit tests?

### ISSUE THREAD

**Issue by bhirbec** [gorilla/mux#167]
Hi,

I need to set up URL parameters for my unit tests. I'm using context.Set() to do so and my test looks something like this:

```
context.Set(r, 0, map[string]string{"param1": "123"})
req , _ := http.NewRequest()
w = := httptest.NewRecorder()
myhandler(w, req)
```

The HTTP handler uses mux.Vars() to retrieve the parameters but it doesn't get any. The problem is explained in great details in [this post](http://stackoverflow.com/questions/34435185/unit-testing-for-functions-that-use-gorilla-mux-url-parameters):

> Trouble is, even when you use 0 as value to set context values, it is not same value that mux.Vars() reads. mux.Vars() is using varsKey (as you already saw) which is of type contextKey and not int.

> Sure, contextKey is defined as:

> `type contextKey int`

> which means that it has int as underlying object, but type plays part when comparing values in go, so int(0) != contextKey(0).

I'm aware I could solve my problem by either starting a web server or by calling the mux directly (as mentioned in SO). However, I don't want to do so. I'd like to call the handler directly in my test.

I see two options to solve this:
-  add a mux.SetVar() method to explicitly set URL parameters for a given request (there's already a private setVar() method)
- use `int` instead of `contextKey` type when defining `varsKey`. This way `context.Set(r, 0, map[string]string{"param1": "123"})` would be a valid way to set up URL parameters. 

Hope this help. Thanks for making Gorilla :)

Ben

**Comment by elithrar** [comment]
Note: also discussed in https://github.com/gorilla/mux/pull/112

The short answer: using https://golang.org/pkg/net/http/httptest/#Server + setting `server.URL = /your/test/url` is the right way to test this. You can still test multiple handlers, use table driven tests for testing different route variables, etc - without tying your tests to mux's implementation.

The long answer: changing the type of `contextKey` to `int` would cause collisions with other packages also using the request context. The [gorilla/context docs](http://www.gorillatoolkit.org/pkg/context) cover this. Making the key type public would also add to the API and prevent us from ever changing things.

**Comment by bhirbec** [comment]
@elithrar thanks for the reply. I'm not sure to understand your solution. How does the context get populated if the mux isn't involved? Can you please provide more informations or point to an example?

**Comment by elithrar** [comment]
@bhirbec You populate the context by passing the correct URL - e.g.

```go
	r := mux.NewRouter()
	r.HandleFunc("/hello/{name}", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Hello, client")
	}))

	ts := httptest.NewServer(r)
	defer ts.Close()

	// Table driven test
	names := []string{"kate", "matt", "emma"}
	for _, name := range names {
		url := ts.URL + "/hello/" + name
		resp, err := http.Get(url)
		if err != nil {
			t.Fatal(err)
		}

		if status := resp.Code; status != http.StatusOK {
			t.Fatalf("wrong status code: got %d want %d", status, http.StatusOK)
		}
	}
```

This way—regardless of whether you use gorilla/mux or not—you're still testing that your application handles the route variables you're passing.

**Comment by elithrar** [comment]
Closing this out for now. Re-open if any questions!

**Comment by bkeroackdsc** [comment]
@elithrar For the love of all that is holy, please just expose a `SetVars` function. The implementation behind it will be opaque so it preserves separation of concerns, and it will allow us to test our handlers in isolation without having to spin up an entire HTTP server just to test a single function!

**Comment by astromahi** [comment]
It would be great help, if you guys export the `setVars`. It forcing me to do functional testing.

```
func setVars(r *http.Request, val interface{}) *http.Request {
	return contextSet(r, varsKey, val)
}
```

**Comment by vincent6767** [comment]
Any update on this?

**Comment by elithrar** [comment]
@vincent6767 - https://godoc.org/github.com/gorilla/mux#SetURLVars

**Comment by vincent6767** [comment]
Yep. I have just seen them several hours ago. Thank you!

**Comment by palsivertsen** [comment]
Handy function for testing!
[testing-handlers](https://github.com/gorilla/mux#testing-handlers) section in Readme could use this update

**Comment by elithrar** [comment]
@palsivertsen Would you like to PR that? :)

**Comment by palsivertsen** [comment]
@elithrar Sure. See pull 342
