### ISSUE TITLE
Recent merge for Go 1.7 Contexts causes deadlocks

### ISSUE THREAD

**Issue by anacrolix** [gorilla/mux#172]
My webservers running a go version between 1.6 and 1.7 lock up with this change. I've isolated it to e84fac997f7f9015ca0c5a35bf0e7922070c98cb.

**Comment by anacrolix** [comment]
It also occurs with golang master, so I believe behaviour has changed significantly when context_native is in use.

**Comment by elithrar** [comment]
Can you provide example code that demonstrates the deadlock behavior?

**Comment by elithrar** [comment]
@anacrolix Are you still seeing this issues? Definitely want to get to the bottom of it if you are.

**Comment by anacrolix** [comment]
Sorry I switched to another muxer rather than go back to Go 1.6. It may be because a panic was occurring in my code, because the *Request changed when the http.Request.WithContext() call is used in the Go 1.7 specific implementation. Perhaps a test could be added for a panic in a handler with an altered Context if one does not exist already. Sorry I can't be of further help.

**Comment by elithrar** [comment]
Closing for now, as haven't had any other reports, but re-open if you're able to share some code/stack tracks.
