### ISSUE TITLE
Register Routes on multiple packages

### ISSUE THREAD

**Issue by cescoferraro** [gorilla/mux#173]
I want to avoid having a separate package to handle the routes.
I used to do this with a pointer receiver, inside a router folder. But as I sson as I move them around. The compiler complains about attaching method to a non local type.     

My api is growing really big and I want to keep all the package logic inside it. So I can easily replicate a pattern by copying a folder, change resource name, wire it to the router and done. The below approach works for one package. As soon as I add wrap the router again with another function it fails.

```
func InitRouter() *util.MyRouter {
	routeCollection := user.Routes(mux.NewRouter())
     // This would not work!
        wsCollection := ws.Routes(routeCollection)
	router := &util.MyRouter{wsCollection}
     // This works
	router := &util.MyRouter{routeCollection}




	return router
}
```

### Initialization
`http.ListenAndServe("0.0.0.0:"+viper.GetString("port"), handlers.CombinedLoggingHandler(os.Stdout, InitRouter()))`

### util.MyRouter
```
type MyRouter struct {
	*mux.Router
}
```

### ws,Routes 
```
func Routes(router *mux.Router) *mux.Router {

	go DashboardHub.Run()
	wsRouter := router.PathPrefix("/iot/ws").Subrouter()
	wsRouter.Handle("/lights", util.Adapt(WSHandler(router),
		util.EnableCORS(),
	))
	go AdminHub.Run()
	wsRouter.Handle("/admin", util.Adapt(AdminWSHandler(router),
		util.EnableCORS(),
	))

	return wsRouter

}
```

### user,Routes
func Routes(router *mux.Router) *mux.Router {

	cesco := router.PathPrefix("/iot/user").Subrouter()
	cesco.Handle("/all", util.Adapt(AllHandler(router),
		iot.IotMongoDatabaseConnection(),
		util.ExpectGET(),
		util.EnableCORS(),
	))
        ....

	return cesco

}

**Comment by elithrar** [comment]
> I used to do this with a pointer receiver, inside a router folder. But as I sson as I move them around. The compiler complains about attaching method to a non local type.

Can you show this error, and which line(s) it points to?

**Comment by cescoferraro** [comment]
On diferent packages, it does not error. I just does not register the routes.
Doing it a single time works

There is no way o doing this with a pointer receiver, as the compiler wont let you extend a non-local type.
Unless on the same package.

**Comment by cescoferraro** [comment]
I got it to work. 

```
func InitRouter() *util.MyRouter {
	router := mux.NewRouter()
	user.UserRoutes(router)
	ws.WsRoutes(router)
	return &util.MyRouter{router}
}
```

Somewhy you cant return the pointer, the function has to have nothing to return.

```
func UserRoutes(router *mux.Router) {}
func WsRoutes(router *mux.Router) *mux.Router {}
```

And you cant return the function argument directly, you need to create another variable

Wont work, No errors
```
func WsRoutes(router *mux.Router) *mux.Router {
	go DashboardHub.Run()
	router.PathPrefix("/iot").Subrouter()
	router.Handle("/lights/ws", util.Adapt(WSHandler(router),
		util.EnableCORS(),
	))
	return router
}

```

Works!
```
func WsRoutes(router *mux.Router) *mux.Router {
	go DashboardHub.Run()
	wsRouter := router.PathPrefix("/iot").Subrouter()
	wsRouter.Handle("/lights/ws", util.Adapt(WSHandler(router),
		util.EnableCORS(),
	))
	return wsRouter
}
```
