### ISSUE TITLE
Best Practice

### ISSUE THREAD

**Issue by pjebs** [gorilla/mux#174]
I have a question.

Which is better practice from a garbage collection/memory management Point of View:

Setting the handler like this:

`appRoutes.Methods("GET").Path("/customer/\").HandlerFunc(cAc.CreateCode)`

```
func CreateCode(w http.ResponseWriter, r *http.Request) {
...
}
```

OR like this

```
func Handler1() func(http.ResponseWriter, *http.Request) {
    return func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprint(w, "/api -> Handler1 - protected by RestGate (Static Mode)\n")
    }
}
```

**Comment by elithrar** [comment]
Creating package functions instead of closures should be better, but the
difference is tiny (and using fmt.Fprintf is probably more of a
bottleneck).

In short: premature optimization :)

**Comment by pjebs** [comment]
I believe it may not be that simple.
I'm only speculating but I think in top example the package level function is kept in memory the whole time.
I think in second example, the closure is garbage collected and recreated every time the route is called.

I'm only speculating and haven't properly looked into it but my handlers are very large and I have almost 50 routes. I think I noticed my memory usage decrease significantly when I changed it to type 2.

**Comment by elithrar** [comment]
Have you profiled? And yes, closures are heavier on the GC, but total GC
impact is likely to be insignificant compared to other parts of your
program.

**Comment by pjebs** [comment]
I haven't profiled. What I'm trying to say is the closure version in lighter - not heavier.

**Comment by elithrar** [comment]
Closing out, but please re-open if any questions.
