### ISSUE TITLE
API to limit request body size

### ISSUE THREAD

**Issue by vadmeste** [gorilla/mux#178]
It is an important feature to secure our servers from malicious clients sending very large requests. 
Though, we can do that in our handlers, it would still be good to be able to set the maximum body size only one time via a new mux API.  

https://golang.org/pkg/net/http/#MaxBytesReader

**Comment by elithrar** [comment]
Why not middleware on your router?

**Comment by vadmeste** [comment]
It depends on whether mux waits for the request to be completely received before dispatching to handlers or not.

**Comment by elithrar** [comment]
mux itself doesn't buffer the request - it works just like net/http in that regard. You could just write some middleware that wraps mux and enforces the limit.

**Comment by elithrar** [comment]
Hi @vadmeste - do you need any further help with this? If you're still stuck, open an issue on http://stackoverflow.com/questions/tagged/go - will get you a more complete response than I have time for right now.

**Comment by vadmeste** [comment]
@elithrar, your answer is convincing but I didn't test anything yet, thanks for assisting me..
