### ISSUE TITLE
Problem with ajax and mux

### ISSUE THREAD

**Issue by ahmdrz** [gorilla/mux#183]
Hi ,
I make an api with mux and i want to use it on ajax code
`jQuery.ajax({
            url: url,
            type: "POST",
            data: data,
            dataType: "json",
            contentType: "application/json",
            success: function () {
                alert("success")
            }
        });`
and mux router config : 
`router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(route.HandlerFunc)
	}
	router.Headers("Access-Control-Allow-Origin", "*")`

when i use ajax , console log print : 

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.

how can i fix it ?

**Comment by ahmdrz** [comment]
I added `w.Header().Add("Access-Control-Allow-Origin", "*") w.Header().Set("Access-Control-Allow-Origin", "*")` and i saw my network header on chrome.
i didn't saw Access-Control-Allow-Origin on response header ...

**Comment by elithrar** [comment]
router.Headers (https://godoc.org/github.com/gorilla/mux#Route.Headers)
doesn't add headers to the router.

Where are you adding w.Header().Add(...) - can you show a more complete
example?

Also see https://godoc.org/github.com/gorilla/handlers#CORS and
https://github.com/rs/cors that can handle this for you.

**Comment by ahmdrz** [comment]
I added my header on :
`func GetNewsListHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Origin", "*")`

headers still not changed !
but i think i can solve it by cors...

**Comment by ahmdrz** [comment]
but i don't know how can i use cors ! :|

**Comment by elithrar** [comment]
Post your full handler code.

**Comment by ahmdrz** [comment]
Okay !
Here is my router.go file
```
package main

import (
	"net/http"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {

	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(route.HandlerFunc)
	}
	return router
}

var routes = Routes{
	Route{
		"GetNewsList",
		"POST",
		"/GetNewsList/",
		GetNewsListHandler,
	},
	Route{
		"GetNews",
		"POST",
		"/GetNews/",
		GetNewsHandler,
	},
}
```

**Comment by elithrar** [comment]
Is the CORS middleware package working for you now?

**Comment by ahmdrz** [comment]
Absolutely yes. It's working for me !
I want to close this issues
Thank a lot for making powerful router. :+1:
