### ISSUE TITLE
mux.Vars is Empty don't understand why

### ISSUE THREAD

**Issue by Boichenko** [gorilla/mux#191]
Hello, i'm using you powerful package, it's very good, but i have a problem when i try to implement basic authentication (https://github.com/abbot/go-http-auth)

folowing lines:
htpasswd := auth.HtpasswdFileProvider(authFile)
authenticator := auth.NewBasicAuthenticator("Basic Realm", htpasswd)

r := mux.NewRouter()
r.HandleFunc("/licenses/{key}/status", authenticator.Wrap(apilsd.CancelLicenseStatus)).Methods("PATCH")

func CancelLicenseStatus(w http.ResponseWriter, r *auth.AuthenticatedRequest) {
    vars := mux.Vars(&r.Request)
    fmt.Printf(" %#v", &r.Request)
    licenseFk := vars["key"]
}

in this case licenseFk equals empty string

**Comment by elithrar** [comment]
What Go version are you using? I see the expected URL variable.

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	auth "github.com/abbot/go-http-auth"
	"github.com/gorilla/mux"
)

func Secret(user, realm string) string {
	if user == "john" {
		// password is "hello"
		return "$1$dlPL2MqE$oQmn16q49SqdmhenQuNgs1"
	}
	return ""
}

func handle(w http.ResponseWriter, r *auth.AuthenticatedRequest) {
	vars := mux.Vars(&r.Request)
	fmt.Fprintf(w, "key: %s\n", vars["key"])
	fmt.Fprintf(w, "<html><body><h1>Hello, %s!</h1></body></html>", r.Username)
}

func main() {
	r := mux.NewRouter()
	authenticator := auth.NewBasicAuthenticator("example.com", Secret)
	r.HandleFunc("/{key}", authenticator.Wrap(handle))
	log.Fatal(http.ListenAndServe(":8080", r))
}
```

Output:
```
key: thing
<html><body><h1>Hello, john!</h1></body></html>
```

**Comment by Boichenko** [comment]
I use go version 1.6.2 windows/amd64

Need to notice once again that this code works fine without basic authentication. i checked a lot of times.

**Comment by elithrar** [comment]
Can you show a `curl` that demonstrates the input / output? Are you using `PATCH`? I wasn't able to replicate the issue.

**Comment by Boichenko** [comment]
func Secret(user, realm string) string {
	if user == "john" {
		// password is "hello"
		return "$1$dlPL2MqE$oQmn16q49SqdmhenQuNgs1"
	}
	return ""
} //(this is from your example, the same result)
basicAuth:= auth.NewBasicAuthenticator("Basic Realm", Secret)
r.HandleFunc("/licenses/{key}/status", basicAuth.Wrap(apilsd.CancelLicenseStatus)).Methods("PATCH")
func CancelLicenseStatus(w http.ResponseWriter, r *auth.AuthenticatedRequest) {
	vars := mux.Vars(&r.Request)
	fmt.Printf(" %#v", &r.Request)
	licenseFk := vars["key"]
	grohl.Log(grohl.Data{"fk": licenseFk}) //fk=nil
}

http://localhost:8990/licenses/4707f1fe-98b9-40bc-835d-4f0db678ec4c/status - to check

can you help me via skype, if you don't mind? i just "broke" my head trying to solve this problem :(

**Comment by elithrar** [comment]
```sh
~/Desktop curl -XPATCH http://localhost:8080/licenses/4707f1fe-98b9-40bc-835d-4f0db678ec4c/status -u john:hello
key: 4707f1fe-98b9-40bc-835d-4f0db678ec4c
<html><body><h1>Hello, john!</h1></body></html>% 
```

Can you provide an example I can run without modification - so I can replicate exactly what you are seeing?

**Comment by Boichenko** [comment]
https://1drv.ms/u/s!AiHa-7v0RdbXnGpziq20pSHqwL6F

this is an example.

**Comment by elithrar** [comment]
- Are you getting nothing back for the key, but otherwise a successful HTTP
200?
- Are you getting a status code other than HTTP 200?
- What are you using to make the request? A browser? curl? Can you show
both the request (URI, headers) and the response (headers, body) you get?
- If you run *my* example below - does it work as expected?

```go
package main

import (
"fmt"
"log"
"net/http"

auth "github.com/abbot/go-http-auth"
"github.com/gorilla/mux"
)

func Secret(user, realm string) string {
if user == "john" {
// password is "hello"
return "$1$dlPL2MqE$oQmn16q49SqdmhenQuNgs1"
}
return ""
}

func handle(w http.ResponseWriter, r *auth.AuthenticatedRequest) {
vars := mux.Vars(&r.Request)
fmt.Fprintf(w, "key: %s\n", vars["key"])
fmt.Fprintf(w, "<html><body><h1>Hello, %s!</h1></body></html>", r.Username)
}

func main() {
r := mux.NewRouter()
authenticator := auth.NewBasicAuthenticator("example.com", Secret)
r.HandleFunc("/licenses/{key}/status",
authenticator.Wrap(handle)).Methods("PATCH")
log.Fatal(http.ListenAndServe(":8080", r))
}
```

I can't replicate this (and your server has a lot of hard-coded config -
it's not a minimal example!). I'd love to help more but my testing doesn't
show a problem.

**Comment by Boichenko** [comment]
checked your example (to make more useful to me add 
grohl.Log(grohl.Data{"fk": vars["key"]})
after 
fmt.Fprintf(w, "<html><body><h1>Hello, %s!</h1></body></html>", r.Username))

the result: fk is nil
i'm testing it using advanced REST client (chrome extension)

**Comment by elithrar** [comment]
Can you answer my other questions? Are you on the latest gorilla/mux?

**Comment by Boichenko** [comment]
made go get github.com/gorilla/mux again. the result is the same
1)- Are you getting nothing back for the key, but otherwise a successful HTTP
200?  - yes i get 200 status code, because i insert the code and leave only getting {key} route value.
2) - What are you using to make the request? A browser? curl? Can you show
both the request (URI, headers) and the response (headers, body) you get? - advanced REST client (chrome extension) request headers - http://prntscr.com/cf3cfv response headers - http://prntscr.com/cf3cl8
response and request above - your example of code that you wrote

**Comment by Boichenko** [comment]
Have you ideas how to resolve this problem?

**Comment by elithrar** [comment]
To be honest, I'm stumped. Can you run a curl to rule out your REST client?

```
curl -XPATCH http://localhost:8080/licenses/4707f1fe-98b9-40bc-835d-4f0db678ec4c/status
```

**Comment by Boichenko** [comment]
Ran this code:
`package main

import (
"fmt"
"log"
"net/http"

auth "github.com/abbot/go-http-auth"
"github.com/gorilla/mux"
"github.com/technoweenie/grohl"
)

func Secret(user, realm string) string {
if user == "john" {
// password is "hello"
return "$1$dlPL2MqE$oQmn16q49SqdmhenQuNgs1"
}
return ""
}

func handle(w http.ResponseWriter, r *auth.AuthenticatedRequest) {
vars := mux.Vars(&r.Request)
fmt.Fprintf(w, "key: %s\n", vars["key"])
fmt.Fprintf(w, "<html><body><h1>Hello, %s!</h1></body></html>", r.Username)
grohl.Log(grohl.Data{"fk": vars["key"]})
}

func main() {
r := mux.NewRouter()
authenticator := auth.NewBasicAuthenticator("example.com", Secret)
r.HandleFunc("/licenses/{key}/status",
authenticator.Wrap(handle)).Methods("PATCH")
log.Fatal(http.ListenAndServe(":8080", r))
}`

the result is:
C:\curl-7.50.2-win64-mingw\bin>curl --user john:hello -XPATCH http://localhost:8080/licenses/4707f1fe-98b9-40bc-835d-4f0db678ec4c/status
key:
<html><body><h1>Hello, john!</h1></body></html>

As you can see, the key is empty

**Comment by Boichenko** [comment]
This is very strange behavior, the same code and different result...

**Comment by Boichenko** [comment]
https://github.com/goji/httpauth - about this package - i didn't find the posibility to use .htpasswd files. So this package doesn't macth to our functionality.
Yesterday i also tried to find the answer why it works if this way and have no results.
Maybe you find some way to solve it problem?

**Comment by elithrar** [comment]
I'm stumped. I can't replicate your issue, and if you're using the latest version of gorilla/mux (`0a192a1`) then I can't see why this is happening. Are you also on the latest version of go-http-auth (`cb43723`) as well?

**Comment by Boichenko** [comment]
We didn't resolve the problem with wrapping of the request. We use this code befole calling function, because we found that request is created again with wrapping:
```
if username = authenticator.CheckAuth(r); username == "" {
			grohl.Log(grohl.Data{"error": "Unauthorized", "method": r.Method, "path": r.URL.Path})
			w.Header().Set("WWW-Authenticate", `Basic realm="`+authenticator.Realm+`"`)
			problem.Error(w, r, problem.Problem{Type: "about:blank", Detail: "User or password do not match!"}, http.StatusUnauthorized)
			return
		}
```

**Comment by ilius** [comment]
I have the same exact problem.
It works fine without authentication, but `mux.Vars(&r.Request)` gives `map[]` when I enable the authentication, while `r.URL.Path` is showing the variable.
Here is my code: https://github.com/ilius/starcal-server/blob/server/src/scal/rest_server/task.go#L98

**Comment by russelldc** [comment]
I'm running into a similar issue, although it's when using our own auth service, which alters the context like:

```go
ctx := context.WithValue(req.Context(), UserContextKey, user)
req = req.WithContext(ctx)
return next(res, req)
```

Later on in the request, mux.Vars is nil, unless I remove the line altering the context.

**Comment by elithrar** [comment]
Are you using the latest gorilla/mux?

Older versions still using gorilla/context have this problem (it's
unavoidable).

**Comment by grkuntzmd** [comment]
I found the same problem yesterday. It appears that using the new `context` package interferes with using `mux`, because it uses the Gorilla context package. I am creating a test case now.

**Comment by elithrar** [comment]
Please update the version of mux you are using.

**Comment by grkuntzmd** [comment]
@elithrar: I just did. The problem is resolved. Thanks.
