### ISSUE TITLE
can't match %0A

### ISSUE THREAD

**Issue by squallcx** [gorilla/mux#192]
/{url},someHandler
/123%0A123/
Result:
The url "/123 123/" does not match any handlers.

I hope the expect  url is 123%0A123
but  /123%0A/ is expected

**Comment by elithrar** [comment]
What is the actual URL you are trying to match with?

**Comment by squallcx** [comment]
r := mux.NewRouter().StrictSlash(true)
	r.HandleFunc("/{context}", noteHandler)

 http://127.0.0.1:8080/title%0Asome

**Comment by squallcx** [comment]
http.HandleFunc("/",someHandler)
handler use  r.URL.Path[1:]
is work

**Comment by kushmansingh** [comment]
Have you tried using http://www.gorillatoolkit.org/pkg/mux#Router.UseEncodedPath ? `%0A` is a newline character so the router probably needs to match against the encoded path.

**Comment by yaozongyou** [comment]
try with this
```golang
r.HandleFunc("/{context:(?s).*}/", noteHandler)
```
in go https://pkg.go.dev/regexp/syntax, dot will match any character, including newline only when the flag s is set.
