### ISSUE TITLE
regexp.go:314 slice bounds out of range

### ISSUE THREAD

**Issue by tpiron** [gorilla/mux#194]
Hi,

I was using mux a few weeks ago, and wrote a test case, and everything was ok.

Now, when I run this code sample, I get a "slice bounds out of range", and I'm pretty sure it used to work before (aka `from` was accessible and empty)

Any ideas ?

Run it locally : https://play.golang.org/p/HKsqjbgXSg

http://localhost:8000/exception/?to=42 throw an exception, and I used to have access to from in my code using `mux.Vars(r)["from"]`

**Comment by kisielk** [comment]
Seems this is a result of 0b13a922203ebdbfd236c818efcd5ed46097d690 
It works fine with the commit just prior.

Pinging @neelance to see if he has any ideas why this is happening.

**Comment by neelance** [comment]
The reason for the exception is that the regexp contains capturing groups `(...)` while it is only allowed to contain non-capturing ones `(?:...)`. The fixed regexp looks like this: `/exception/{from:(?:[0-9]+)?}{to:(?:\/to\/[0-9]+)?}`.

Note: The given regexp does not fit to the URL http://localhost:8000/exception/?to=42 mentioned above. I tested with http://localhost:8000/exception/11/to/42 instead.

**Comment by tpiron** [comment]
@neelance Thanks for the fix, it works. 

Should it be possible to tag the Mux releases? I'm using Gom (not probably the only one) to manage my go dependencies with Docker, and it would be awesome to be able to select a specific version/tag. (and it would probably have prevent me from having this issue)

Thanks again for the hard work on mux! (thanks @kisielk)
