### ISSUE TITLE
gorilla/context leaking memory

### ISSUE THREAD

**Issue by nvartolomei** [gorilla/mux#198]
Looks like when building `gorilla/mux` with go 1.7 the [context](http://www.gorillatoolkit.org/pkg/context) is leaking memory.

> The Routers from the packages gorilla/mux and gorilla/pat call Clear() so if you are using either of them you don't need to clear the context manually.

But when compiling gorilla/mux with go 1.7 this isn't true anymore, because it builds with [context_native.go](https://github.com/gorilla/mux/blob/master/context_native.go) which does not have `gorilla/context.Clear()` call.

**Comment by nvartolomei** [comment]
Or this is because I'm using old gorilla/context?

**Comment by elithrar** [comment]
That would be because you are using the old context. You would need to
clear it manually, but as per the context docs, I do not recommend mixing
context types.

**Comment by nvartolomei** [comment]
I just recompiled the app using 1.7.1 compiler and it caused memory leaks.
I'm not mixing anything, gorilla/mux together with gorilla/context does.

**Comment by elithrar** [comment]
gorilla/mux uses the new http.Request.Context as of Go 1.7 - failing to do
so means that any users (or libraries imported by the user!) using
http.Request.Context would break when mixed with gorilla/context.

I'm suggesting that you remove gorilla/context from any 1.7+ application,
and especially so those with mux

**Comment by nvartolomei** [comment]
> You should either use just gorilla/context, or moving forward, the new http.Request.Context().

So this actually should say: do not use gorilla/context with Go 1.7

**Comment by elithrar** [comment]
That's not entirely true, if you control the situation and know the risks. We're probably picking nits at this point though.
