### ISSUE TITLE
Router.NotFoundHandler is not used when the router is a subrouter

### ISSUE THREAD

**Issue by ghost** [gorilla/mux#20]
I defined specific NotFoundHandler for several subrouters but the NotFoundHandler from the main Router is always used.

**Comment by error10** [comment]
I've worked around this by using a `PathPrefix()` after the home page route for the subroute.

```
    r := mux.NewRouter()
    s := r.Host("{subdomain}." + domain).Subrouter()
    //...more routes..
    s.Handle("/", commonChain.Then(subdomainHomepageHandler()))
    s.PathPrefix("/").Handler(commonChain.Then(http.HandlerFunc(subdomainNotFound)))
```

Later, `subdomainNotFound()`, which for me does some extra work, will generate a (nicely templated) 404 if necessary.

**Comment by elithrar** [comment]
I'm going to close this as wontfix: if you do need separate a `NotFoundHandler` you can use nested routers (via `mux.NewRouter()`). Happy to open it again if there's a desire to.
