### ISSUE TITLE
[matching] Capture Groups Broken?

### ISSUE THREAD

**Issue by darrenmcc** [gorilla/mux#200]
I have an endpoint that looks like this `/{type:(promo|special)}/{promoId}.json` that is now broken. `type` and `promoId` are both what was set in the `type` group.

e.g.

calling /promo/foo.json yields `map[type:promo promoId:promo]`

**Comment by kallekrantz** [comment]
Hey

We're facing he same issue on our project https://github.com/thiderman/drunkenfall on master. 
Our subrouter is defined as,```/tournament/{id}/{kind:(tryout|runnerup|semi|final)}/{idx:[0-9]+}```

With the input ```/api/towerfall/tournament/lii/tryout/6/start/``` we're getting the following output ```map[id:lii kind:tryout idx:tryout]``` from ```mux.Vars```

Whereas the correct one would be ```map[id:lii kind:tryout idx:6]```

We managed to track down the revision where the issue was introduced to the following revision 0b13a922203ebdbfd236c818efcd5ed46097d690, where it's probably the simplification that is causing  the issue.

**Comment by elithrar** [comment]
@darrenmcc @kallekrantz If you can submit a PR with an additional test case (e.g. your example), and that doesn't break existing tests, it'd be hugely appreciated.

**Comment by kallekrantz** [comment]
Hey, @elithrar, created #202 which adds a test for it. 

Sorry if I added it to the wrong place, pretty new to Go!

**Comment by elithrar** [comment]
@kallekrantz Test looks good. Did you want to also add a commit that reverts the simplification in 0b13a92 to the same PR?

(thanks heaps!)

**Comment by kallekrantz** [comment]
@elithrar Sure! I'll do it during the weekend.

**Comment by kallekrantz** [comment]
@elithrar reverted the commit, tests seem to be passing as well. Sorry for taking a bit longer than expected.

**Comment by elithrar** [comment]
We should consider calling `panic()` if [`regexp.NumSubexp()`](https://golang.org/pkg/regexp/#Regexp.NumSubexp) != 0 - and providing a useful error message in the trace.

**Comment by aeijdenberg** [comment]
Matt, I'd be happy to volunteer to write a PR including tests to do as you suggested. Would that be helpful?

**Comment by elithrar** [comment]
Of course @aeijenberg - send a PR when you're ready.

**Comment by aeijdenberg** [comment]
First cut of pull request added here:
https://github.com/gorilla/mux/pull/218

The documentation change appears to have already been made last September in 14f5df0128b7c89faab437c00d0ea98fb56e03a0.

**Comment by elithrar** [comment]
Thanks. We should document the "panics if capture groups are provided" piece however as the failure is harsher, but more explicit.

**Comment by elithrar** [comment]
Closed via #218 and tagged as v1.3.0 - https://github.com/gorilla/mux/releases/tag/v1.3.0
