### ISSUE TITLE
How i get the URL without vars?

### ISSUE THREAD

**Issue by Fruchtgummi** [gorilla/mux#201]
I set 

`router.HandleFunc("/foo/bar/edit/{key}", myHandler)`

If i get the URL with `request.URL.Path` will give me back the Path with {key}-values. 

How is it without values?

**Comment by danhardman** [comment]
Surely you know the path to have routed the handler to it. Why don't you hardcode it in?

**Comment by elithrar** [comment]
https://godoc.org/github.com/gorilla/mux#Route.GetPathTemplate

**Comment by Fruchtgummi** [comment]
`var g *mux.Route
ff, _ := g.GetPathTemplate()

log.Println(ff)`

I unterstand :/

`2016/10/13 19:12:51 http: panic serving [::1]:61148: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
net/http.(*conn).serve.func1(0xc0821eb600)
	c:/go/src/net/http/server.go:1389 +0xc8
panic(0x8b8240, 0xc082008090)
	c:/go/src/runtime/panic.go:443 +0x4f7
main.seminarortePage(0xfd9ed0, 0xc08210f040, 0xc0821ee620)
	c:/goworkspace/src/Promillo/seminarorte.go:39 +0x95
net/http.HandlerFunc.ServeHTTP(0xa33f18, 0xfd9ed0, 0xc08210f040, 0xc0821ee620)
	c:/go/src/net/http/server.go:1618 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc08200ab90, 0xfd9ed0, 0xc08210f040, 0xc0821ee620)
	c:/goworkspace/src/github.com/gorilla/mux/mux.go:107 +0x28c
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc08213edc0, 0xfd9ed0, 0xc08210f040, 0xc0821ee620)
	c:/goworkspace/src/github.com/gorilla/csrf/csrf.go:264 +0x86f
net/http.serverHandler.ServeHTTP(0xc082174400, 0xfd9ed0, 0xc08210f040, 0xc0821ee620)
	c:/go/src/net/http/server.go:2081 +0x1a5
net/http.(*conn).serve(0xc0821eb600)
	c:/go/src/net/http/server.go:1472 +0xf35
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:2137 +0x455`

**Comment by elithrar** [comment]
@Fruchtgummi You can't get the template for an empty route.
