### ISSUE TITLE
mux.CurrentRoute fails if context added

### ISSUE THREAD

**Issue by captncraig** [gorilla/mux#204]
Lets say I have a middleware function that adds something to the request context:

```
func M(next http.Handler)http.Handler{
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request){
     r = r.WithContext(context.WithValue(r.Context(), "something",42))
     next(r,w)
  })
}
```

`mux.Handle("/foo",M(myHandler)).Name("Foo")`

if `myHandler` looks for `mux.CurrentRoute(r)`, it will get a nil result. Is there any workaround for this?

**Comment by elithrar** [comment]
@captncraig Did you resolve?
