### ISSUE TITLE
"1.1" is not a valid SemVer 2.0.0 version

### ISSUE THREAD

**Issue by rogerwelin** [gorilla/mux#206]
I'm using gb as build tool / dependency manager. I'm listing this lib in my depfile as such (which is the only available tag):

_github.com/gorilla/mux version=1.1_ 

And I'm getting:

_FATAL: unable to construct context: github.com/gorilla/mux: "1.1" is not a valid SemVer 2.0.0 version_

Please add a tag that's support semver

**Comment by elithrar** [comment]
What is a valid semver version that gb supports? 1.1.0 - ?

**Comment by rogerwelin** [comment]
Yes, major.minor.patch. So 1.1.0 would work fine

**Comment by elithrar** [comment]
Fixed - https://github.com/gorilla/mux/releases/tag/v1.2.0
