### ISSUE TITLE
Google Named in BSD License

### ISSUE THREAD

**Issue by sharonlcorbett** [gorilla/mux#208]
Hi;

I'm trying to understand why Google is referenced in the license no endorsement clause?  Is this in error, or?

Thanks,
Sharon

**Comment by kisielk** [comment]
That's a question for @moraes

**Comment by sharonlcorbett** [comment]
@moraes Are you able to help clarify this matter? Thanks!

**Comment by slemeur** [comment]
Hi @kisielk any updates on this? 
Would you be able to handle that?

**Comment by elithrar** [comment]
We can't modify the license ad-hoc. Does this impact you using the library?

**Comment by sharonlcorbett** [comment]
We were trying to ascertain if it was a mistake or not.  If it is not, then that is fine.  We are not asking for a change to the license.

**Comment by kisielk** [comment]
I can't really say whether it was a mistake or intentional, I'm not the original author of the project, @moraes is. AFAIK the license has been like that all along.

**Comment by elithrar** [comment]
Closing. I don't see this as an issue.
