### ISSUE TITLE
If a route is matched by everything except the method, router should return a 405 listing the available methods

### ISSUE THREAD

**Issue by johnnadratowski** [gorilla/mux#21]
I have some routes that I only allow certain methods for.  When I try another method for the same URI, I get a 404.  As per the HTTP 1.1 spec, I should get a 405 with the proper Allow header listing the allowed methods.

Reference: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6

UPDATE:
I also noticed that seemingly unexpected behavior occurs when routes don't match on headers or on queries.  On queries I'd think you'd want to return a 400 with some information about how certain queries aren't allowed.  On headers it might be harder as it seems depending on the header you might want to return a 406, 412, 415, 416, or a 417? I'm not sure with that one.

Feedback is appreciated.  When I get some time, if you guys like the idea, I might make a pull request and do it myself.

**Comment by kisielk** [comment]
Closing in favour of #6
