### ISSUE TITLE
Testing setup & structure

### ISSUE THREAD

**Issue by odlp** [gorilla/mux#210]
Would you be open to adopting a testing framework like [Ginkgo](http://onsi.github.io/ginkgo/)? I think this could make contributing to mux easier because it:

- Has a clearer output when a test is failing (and catches panics, marking that test as a failure).
- Provides structure to the tests (`Describe`, `Context`)
- Has [table driven tests](http://onsi.github.io/ginkgo/#table-driven-tests) which could allow [these tests to be declared more succinctly](https://github.com/gorilla/mux/blob/master/mux_test.go#L53:L237)

Splitting out groups of tests into distinct files could be helpful too, as `mux_test.go` for example is now > 1500 lines long.

**Comment by elithrar** [comment]
The tests we have now are table driven tests.

What would Ginkgo improve in that regard?

**Comment by odlp** [comment]
Yes, valid point that these are table tests today - there is less to be gained from Ginkgo on this point. I think clearer test failures & catching panics as failures can still be of benefit. 

One other advantage to consider is that using Gomega with Ginkgo could make assertions more readable:

[Before](https://github.com/gorilla/mux/blob/master/mux_test.go#L1382:L1388)
```go
if path != "" {
    u, _ := route.URLPath(mapToPairs(match.Vars)...)
        if path != u.Path {
            t.Errorf("(%v) URLPath not equal: expected %v, got %v -- %v", test.title, path, u.Path, getRouteTemplate(route))
            return
        }
}
```

After
```go
if path != "" {
    u, _ := route.URLPath(mapToPairs(match.Vars)...)
    Expect(u.Path).To(Equal(path), "Error message...")
}
```

This reduces indentation, and prevents the need for explicit early returns on failures. However I can see these are subjective benefits. 

For context, I was trying to help out and write tests for [PR#161](https://github.com/gorilla/mux/pull/161) but found it tough to get going. I just thought I'd see if there was any appetite for using Ginkgo but appreciate it'd quite a lot of work to migrate.

**Comment by kisielk** [comment]
I appreciate some of the befits of Ginkgo even though it's not really my preferred style of testing. However I'd rather not add any external dependencies to the project, even if it's only for tests.
