### ISSUE TITLE
[question] Context passing across middlewares

### ISSUE THREAD

**Issue by grsmv** [gorilla/mux#211]
Hi,

I'm wondering about passing `request.Context` across several middlewares. 
Right now it's seems impossible for some reason. 
For example:

```go
func ContextSet(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), "key", 42)
		h.ServeHTTP(w, r.WithContext(ctx))
	})
}

func ContextGet(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		println(r.Context().Value("key")) // gives nil
		h.ServeHTTP(w, r)
	})
}

func main(){
	router = mux.NewRouter()
	// ... 
	preparedRouter := ContextSet(router)
	preparedRouter =  ContextGet(preparedRouter)
	// ...
}
```

Under `context` I mean Go' 1.7+ native `context` package
Thank you

**Comment by garyburd** [comment]
The context setting wrapper is ignored. I think you want:

	preparedRouter := ContextSet(router)
	preparedRouter =  ContextGet(preparedRouter)

**Comment by grsmv** [comment]
@garyburd - sure, sorry for typo - I've edited initial message. In my code I have correct version and unfortunately, this isn't a working variant.

**Comment by kisielk** [comment]
Your wrappers are being applied in the wrong order. Assuming you are serving `preparedRouter`, then `ContextGet` is the top-level handler and will be called first, after which it will call `ContextSet` and then finally the `mux` router. This is probably something better discussed on the mailing list.

**Comment by grsmv** [comment]
@kisielk - Moving middlewares in opposite direction fixes this problem.
Thank you!
