### ISSUE TITLE
Document how PathPrefix Works

### ISSUE THREAD

**Issue by elithrar** [gorilla/mux#219]
Use the familiar "wildcard" term to show what a 'wildcard' route looks like and how PathPrefix does it.

**Comment by eticzon** [comment]
@elithrar do you mind if I pick this up? I'd like to help out.

**Comment by elithrar** [comment]
Sure, you're more than welcome to!

**Comment by elithrar** [comment]
Covered in a previous change to the README: https://github.com/gorilla/mux#static-files
