### ISSUE TITLE
Incorrect regexp failfast breaking downstream code

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gorilla/mux#220]
The last commit 392c28f (#218) is breaking some downstream code we had (which worked just fine by the way):

    	r.HandleFunc(`/delay/{n:\d+(\.\d+)?}`, DelayHandler).Methods("GET")

This gives error:

    panic: route /delay/{n:\d+(\.\d+)?} contains capture groups in its regexp.
      Only non-capturing groups are accepted: e.g. (?:pattern) instead of (pattern)

This does not seem to be a backwards-compatible change. Any ideas on how to fix this regexp?

cc: @elithrar if this project is using SemVer, I think this should be tagged with a new major version (v2.x) instead of v1.3.0.

**Comment by elithrar** [comment]
This (capture groups) was already broken: we now just fail fast to prevent incorrect behavior. 

This project does use SemVer but we considered this a bugfix.

**Comment by kisielk** [comment]
For your existing regexp the fix is easy:

```
r.HandleFunc(`/delay/{n:\d+(?:\.\d+)?}`, DelayHandler).Methods("GET")
```

**Comment by ahmetalpbalkan** [comment]
@kisielk thanks!
