### ISSUE TITLE
Router.AddSubrouter as a new feature

### ISSUE THREAD

**Issue by tro3** [gorilla/mux#223]
A function with the signature `func (r *Router) AddSubrouter(path string, child *Router) *Router` would provide the Router-based version of the `Route.Subrouter()`.  This allows a structure along the lines of:

    users.go:
      func CreateUserEndpoint() *mux.Router {
        router := mux.NewRouter()
        ...
        return router
      }

    endpoints.go:
      type endpoint struct {
        path string
        fn   func() *mux.Router
      }

      func CreateEndpoints() *mux.Router {
        endpoints := []endpoint{
          endpoint{"/users", CreateUserEndpoint},
          ...
        }
        router := mux.NewRouter()
        for _, endp := range endpoints {
          router.AddSubrouter(endp.path, endp.fn())
        }
        return router
      }

    server.go:
      func NewRouter() *mux.Router {
        router := mux.NewRouter()
        router.AddSubrouter("/api", CreateEndpoints())
        ...
        return router
      }

I have this running in my repo - I'll submit a PR, and if this is a bad idea, feel free to close the submissions unceremoniously. :-)

**Comment by elithrar** [comment]
Thanks for this + the related PR. I'll take a look this week - at a high-level it looks good.

**Comment by tro3** [comment]
Okay - not as simple as I thought.  The templates are created looking upward when a new Route is attached.  So if you have a Router with a bunch of Routes created _before_ that Router is added to a parent, none of the Routes below will have the proper prefixes.  This would require a recurvise-downward prefix adder function.  I may take a look at this when time allows.

PR closed for now, as it is broken.

**Comment by elithrar** [comment]
No problems. Can keep the original issue open to track this in future.
Appreciate the investigation!
