### ISSUE TITLE
How to handle  variables passed as ../

### ISSUE THREAD

**Issue by krasi-georgiev** [gorilla/mux#226]
I am trying to solve an issue with the docker api where the endpoint takes a param like
/containers/{name:.*}/checkpoints

if name is passed as "../"
instead of serving /containers/..//checkpoints the path becomes /checkpoints
and doesn't get passed to the handler function because it doesn't match the added route path.

There are too many endpoints that are affected and I would be interested to hear if there would be an easy way to solve this globally.

**Comment by elithrar** [comment]
SkipClean?

**Comment by krasi-georgiev** [comment]
thanks I will try it

**Comment by krasi-georgiev** [comment]
it does the trick , Docker uses an older version of the gorila lib so need to check what is the procedure with the upgrades.

**Comment by krasi-georgiev** [comment]
the PR was rejected due to some security implications.
https://github.com/docker/docker/pull/30933


I am back to the original request.

would it make sense to allow running some variable validation before passing the reuqest to url cleanup and redirecting the ../

**Comment by elithrar** [comment]
It's not immediately clear why "../" exists in your URLs? I can understand
why the Docker team might see it as a possible security issue.

**Comment by krasi-georgiev** [comment]
It is marked as bug in the docker issues and I am trying to solve it.

even if it is not ../ , if that part of the url is set to be a variable it shouldn't be considered to be part of the url right ?

/containers/{name:.*}/checkpoints

you don't think that the option to validate the var before doing an url cleanup is going to be worth the effort ?

**Comment by elithrar** [comment]
I think you should - as per the discussion in the PR you linked -
https://github.com/docker/docker/pull/30933 - not use "../" as a container
name.

(It's still not clear why you must accept that container name as valid?)

**Comment by krasi-georgiev** [comment]
@elithrar I am just trying to solve a problem marked as a bug. It is not my use case.
even if you ignore this use case , I thought that an option to validate {name:.*} would be helpful as many docker api endpoints have similar format  and maybe some other weird characters will cause other issues.

**Comment by elithrar** [comment]
OK, but there's nothing to fix on this side, and I don't think Docker has anything to fix either.
