### ISSUE TITLE
Rate limiting incoming requests?

### ISSUE THREAD

**Issue by rogierlommers** [gorilla/mux#227]
Not really an issue, but do you know if it's possible to create some kind of middleware / chained handler which can be used to rate-limit the incoming requests?

**Comment by kisielk** [comment]
I think that's outside the scope of mux itself. You need to find another handler that does that and wrap mux with it.

**Comment by matthewvalimaki** [comment]
Wanted to log this here as an solution: https://github.com/didip/tollbooth.
You would use `tollbooth` with `mux` somehow like this:
```
r *mux.Router
r.Handle("/my/route", tollbooth.LimitHandler(
  tollbooth.NewLimiter(1, time.Second),
  &handler.MyHandler{},
)).Methods("POST")
```

**Comment by cseeger-epages** [comment]
Another option is to use https://github.com/throttled/throttled. This worked well for me with gorilla mux
` 
   r *mux.Router
  store, err := memstore.New(65536)
  if err != nil {
    log.Fatal(err)
  }

  quota := throttled.RateQuota{throttled.PerMin(20), 5}
  rateLimiter, err := throttled.NewGCRARateLimiter(store, quota)
  if err != nil {
    log.Fatal(err)
  }

  httpRateLimiter := throttled.HTTPRateLimiter{
    RateLimiter: rateLimiter,
    VaryBy:      &throttled.VaryBy{Path: true},
  }

  r.Handle("/my/route", httpRateLimiter.RateLimit(handler))
`

**Comment by ae6rt** [comment]
For posterity, when using tollbooth, this might also work

```
	r := mux.NewRouter()
	r.HandleFunc("/v1/user", s.getUser).Methods("GET")
	r.HandleFunc("/v1/user", s.registerUser).Methods("POST")

	lmt := tollbooth.NewLimiter(float64(maxRequestsSec), nil)
	lmt.SetIPLookups([]string{"RemoteAddr", "X-Forwarded-For", "X-Real-IP"}).SetMethods([]string{"POST", "PUT"})

	return tollbooth.LimitHandler(lmt, r)
```

where this return value can be used to start the server

```
	if err := http.ListenAndServeTLS(fmt.Sprintf(":%d", cfg.GetInt("serverPort")), cfg.GetString("certficateFile"), cfg.GetString("keyFile"), handler); err != nil {
		parentLogger.Fatal("ListenAndServe", zap.Error(err))
	}
```
