### ISSUE TITLE
Add "Used By" badge

### ISSUE THREAD

**Issue by jawnsy** [gorilla/mux#228]
Sourcegraph recently announced ["used by" badges](https://text.sourcegraph.com/see-how-many-people-use-your-library-with-sourcegraph-badges-9750e56e7b2f) for projects and used gorilla/mux as an example, so it seems fitting for the project to add these badges. I'm happy to submit PRs to the various projects if you're interested.

**Comment by kisielk** [comment]
Hi jonathan,

PRs would be great!
