### ISSUE TITLE
How about the performance of gorilla mux ?

### ISSUE THREAD

**Issue by iamybj** [gorilla/mux#231]
I heard that grollia/mux is not very fast.

**Comment by kisielk** [comment]
You should benchmark it with your intended use case and see if it's fast enough for you.

**Comment by elithrar** [comment]
To further note, if gorilla/mux is the bottleneck in your application,
please file an issue with profile output.

Routers are rarely the bottleneck in any networked-application.

**Comment by iamybj** [comment]
Fuck.
Your know why we China becomes the most advanced internet/mobile country in the world ?
 We China have the most amount users of internet, so the programmers in China are all like and  write high performance codes.
Roll out of IT industry if you cannot write hight performance code.

**Comment by kisielk** [comment]
In that case I look forward to your contributions with performance improvements.
