### ISSUE TITLE
Public test API to set URL params

### ISSUE THREAD

**Issue by achiku** [gorilla/mux#233]
Thank you for creating such a wonderful library!! I have gone through issues/prs, and now put a proposal up. Any comments are welcomed!

### Proposal
How do you think about adding a function to set URL params in context, which is implicitly declared as an API only for test. Testing as a public API is borrowed from this slide [Advanced Testing with Go](https://speakerdeck.com/mitchellh/advanced-testing-with-go?slide=53).

### Background
First of all, as it's discussed in several issues, it's not good idea to make context key public or basic type since it may conflict with other keys set from different packages, and accidentally overwrite values. Secondally, it is also not good idea to make a `setVars` function public, since it is fundamentally not necessary for this library to work as intended, and widen its API boundary, which tend to increase difficulty to maintain a clean project.

However, it is still useful if library users can add URL params to context for testing. The main reason is that users can separate middlewares, and other routing mechanism aside when they test a function that implements `http.Handler` interface.

### Implementation

Below is just an example.

- https://github.com/achiku/mux/commit/f8f4828232971c798713d8c4f7bb9739f9950dc4

### Related issues/prs
* https://github.com/gorilla/mux/issues/187
* https://github.com/gorilla/mux/issues/167
* https://github.com/gorilla/mux/pull/112

**Comment by elithrar** [comment]
What's the difference between a public SetVars() and this proposal? :)

**Comment by achiku** [comment]
No difference in implementation, but clearly stating "this function is for test" by making it public test API like `TestSetURLParam(r *http.Request, val map[string]string) *http.Request`, the library can provide a feature making unit test finer grain without encouraging misuse of `context.Context` modification in production code.

**Comment by andrefsp** [comment]
Is there any development on this? IMO this is a quite important issue to be solved as it makes unittest a lot more complicated than it should.

**Comment by grim-fendango** [comment]
I think the provided implementation strikes a good balance between testibility and discouraging bad behaviour. Could we please get this into a PR and merged ASAP?

**Comment by grim-fendango** [comment]
Hey peeps, I've cherry picked the commit provided by achiku and spun up a [PR](https://github.com/gorilla/mux/pull/322) would love to hear your feedback 😸

**Comment by grim-fendango** [comment]
Hey we can close this now 🎉 since this [PR](https://github.com/gorilla/mux/pull/322) has been merged.

**Comment by kisielk** [comment]
Right on :)
