### ISSUE TITLE
How get CgiParam using Mux+Go?

### ISSUE THREAD

**Issue by questionpython** [gorilla/mux#236]
hi
How get CgiParam using Mux+Go?

example in nginx conf:
>fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;

i want get value of `SCRIPT_FILENAME`

```
func (c *customHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    html := "Hello"
    fmt.Println(w,r)
    r.ParseForm()
    log.Println("header :",r.Header)
    log.Println("request url:",r.RequestURI)
    log.Println("form :‌",r.Form)
    log.Println("reffer :",r.Referer())
    log.Println("path :",r.URL.Path)
    log.Println("path :",r.URL)
    log.Println("host :",r.Host)
    log.Println("fullpath :",r.URL.RequestURI())
    log.Println("method :",r.Method)
    log.Println("lenght :",r.ContentLength)
    log.Println("enoding :",r.TransferEncoding)
    log.Println("body :",r.Body)
    log.Println("user :",r.UserAgent())
    log.Println("cookie :",r.Cookies())

    headers := w.Header()
    headers.Add("Content-Type", "text/html")
    fmt.Println("----------------------------------------------")
    io.WriteString(w,html)
}
```

and also i want get content of file(SCRIPT_FILENAME).

help me.

**Comment by micahkwillard** [comment]
I don't think getting the value of an env variable has anything to do with Mux. Try these to get what you need:
https://golang.org/pkg/os/#Getenv
```scriptFilename := os.Getenv("SCRIPT_FILENAME")```
https://golang.org/pkg/os/#Open
```file, err := os.Open(scriptFilename)```
From there you should be able to Google how to read the file the way you need to.

**Comment by elithrar** [comment]
Answered above - closing.
