### ISSUE TITLE
Calling an unnamed route results in a panic

### ISSUE THREAD

**Issue by deltaskelta** [gorilla/mux#239]
I was writing some code and forgot to name a route, but I was calling it by its intended name. THis caused a panic that took me a while to track down in my code. 

I haven't looked around in the internals too much yet, but I am wondering if there is a way to give a clear error for this situation to avoid confusion and save some time?

Thanks

**Comment by kisielk** [comment]
Please provide a small example to reproduce the error.

**Comment by deltaskelta** [comment]
Ahh I can't reproduce it and it was a while ago in my code. closing, will reopen if it happens again and I can reproduce it.
