### ISSUE TITLE
Profiling with Mux

### ISSUE THREAD

**Issue by theobouwman** [gorilla/mux#242]
How can I implement http://blog.ralch.com/tutorial/golang-performance-and-memory-analysis/ in my application which uses the Mux router.

Thanks

**Comment by elithrar** [comment]
https://dave.cheney.net/2013/07/07/introducing-profile-super-simple-profiling-for-go-programs
may help. Profiling a Go program is no different when using mux.

**Comment by theobouwman** [comment]
Thanks
