### ISSUE TITLE
Subrouter with static files

### ISSUE THREAD

**Issue by theobouwman** [gorilla/mux#243]
I want to create a static folder `/storage` to store different files, but I also want `/storage` to be a subrouter so I can serve files to users and add logic/middleware to it.
This is what I want to accomplish:
```
router.PathPrefix("/storage/").Handler(http.StripPrefix("/storage/", http.FileServer(http.Dir(helpers.GetMakePath("/storage")))))
apiRouter := router.PathPrefix("/storage/").Subrouter()
```
And then attach routes like `/contract?contractid=1234` to serve the user a specific contract. And maybe log in a database when a user accessed/ downloaded that file.

**Comment by elithrar** [comment]
What have you tried so far? :)

**Comment by theobouwman** [comment]
I have a subrouter with routes that just serves the specific files to the user, which is actually what I want.
