### ISSUE TITLE
Concurrent Map Issue

### ISSUE THREAD

**Issue by zoltan123** [gorilla/mux#246]
Hi,

I have just got a concurrency error while adding a new route.

There were a few other goroutines running, but none of them was using the gorilla mux.

main.newDataSeriesGen() is a handler function already installed on the muxer that can add new routes/handlers to the muxer (via main.AddRoute()).

I have been using this program for a long time, never had the issue. This time I was using it on a slow processor (intel atom N475), and I had this issue once.

The gorilla muxer was go get installed 2017 Mar 26 05:16.
go version go1.7.4 linux/amd64

ERROR LOGS:
============

fatal error: concurrent map writes

goroutine 26 [running]:
runtime.throw(0x6df090, 0x15)
    /usr/lib/go-1.7/src/runtime/panic.go:566 +0x95 fp=0xc420161628 sp=0xc420161608
runtime.mapassign1(0x68aee0, 0xc42000c7b0, 0xc420161750, 0xc420161748)
    /usr/lib/go-1.7/src/runtime/hashmap.go:458 +0x8ef fp=0xc420161710 sp=0xc420161628
github.com/gorilla/mux.(*Route).Name(0xc4201269a0, 0xc420063ae6, 0x9, 0xc4201269a0)
    /home/user/prg/go/src/github.com/gorilla/mux/route.go:122 +0xf6 fp=0xc4201617a0 sp=0xc420161710
main.AddRoute(0xc420054320, 0xc420063ae0, 0x6, 0xc420061680, 0x6b1140, 0xc42005eba0) <- panic
    /home/user/prg/go/src/serverproject/router.go:39 +0x169 fp=0xc4201617f8 sp=0xc4201617a0
main.newDataSeriesGen.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/handlers_generic.go:210 +0x95b fp=0xc420161978 sp=0xc4201617f8
net/http.HandlerFunc.ServeHTTP(0xc420010990, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc4201619a0 sp=0xc420161978
main.CORS.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/cors.go:134 +0x1f8 fp=0xc420161a88 sp=0xc4201619a0
net/http.HandlerFunc.ServeHTTP(0xc420012d80, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc420161ab0 sp=0xc420161a88
main.Logger.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/logger.go:30 +0xae fp=0xc420161b88 sp=0xc420161ab0
net/http.HandlerFunc.ServeHTTP(0xc42000cc60, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc420161bb0 sp=0xc420161b88
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054320, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/github.com/gorilla/mux/mux.go:114 +0x10d fp=0xc420161cb0 sp=0xc420161bb0
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc4200132e0, 0x803e60, 0xc4200ed520, 0xc4200d70e0)
    /home/user/prg/go/src/github.com/braintree/manners/server.go:277 +0x8f fp=0xc420161ce0 sp=0xc420161cb0
net/http.serverHandler.ServeHTTP(0xc4200f6780, 0x803e60, 0xc4200ed520, 0xc4200d70e0)
    /usr/lib/go-1.7/src/net/http/server.go:2202 +0x7d fp=0xc420161d28 sp=0xc420161ce0
net/http.(*conn).serve(0xc420076580, 0x804460, 0xc4200155c0)
    /usr/lib/go-1.7/src/net/http/server.go:1579 +0x4b7 fp=0xc420161f88 sp=0xc420161d28
runtime.goexit()
    /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420161f90 sp=0xc420161f88
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d
    

    func AddRoute() {
        var handler http.Handler

        handler = route.HandlerFuncGen(router, name, data)                                    
        handler = CORS(handler)                                    
        handler = Logger(handler, route.Name)

        router.
            Methods(route.Method).
            Path(route.Pattern).
            Name(route.Name).
            Handler(handler) <- /home/user/prg/go/src/serverproject/router.go:39 +0x169 fp=0xc4201617f8 sp=0xc4201617a0
    }

**Comment by elithrar** [comment]
How are you validating that the mux isn't being modified by another goroutine also calling AddRoute or otherwise mutating the router?

**Comment by zoltan123** [comment]
@elithrar I have checked the stacktrace after panic, and only this goroutine mentioned corresponding functions.

Your question implies that the gorilla mux does NOT support concurrent access to the router object. Is that right? So the intended usage is that any access to the router object must be synchronized by the user? I was not aware of that.

Unfortunately, I could not reproduce the error by running restarting the program/running it for a long time, it is probably a rare race condition. Probably heavy load on the machine is also a factor (2 chromium browsers were started right after this program when the problem manifested, but at later attempts even this was not enough to trigger the error).


I thought, it is overkill, but here is the full stack trace:

fatal error: concurrent map writes

goroutine 26 [running]:
runtime.throw(0x6df090, 0x15)
    /usr/lib/go-1.7/src/runtime/panic.go:566 +0x95 fp=0xc420161628 sp=0xc420161608
runtime.mapassign1(0x68aee0, 0xc42000c7b0, 0xc420161750, 0xc420161748)
    /usr/lib/go-1.7/src/runtime/hashmap.go:458 +0x8ef fp=0xc420161710 sp=0xc420161628
github.com/gorilla/mux.(*Route).Name(0xc4201269a0, 0xc420063ae6, 0x9, 0xc4201269a0)
    /home/user/prg/go/src/github.com/gorilla/mux/route.go:122 +0xf6 fp=0xc4201617a0 sp=0xc420161710
main.AddRoute(0xc420054320, 0xc420063ae0, 0x6, 0xc420061680, 0x6b1140, 0xc42005eba0)
    /home/user/prg/go/src/serverproject/router.go:39 +0x169 fp=0xc4201617f8 sp=0xc4201617a0
main.newDataSeriesGen.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/handlers_generic.go:210 +0x95b fp=0xc420161978 sp=0xc4201617f8
net/http.HandlerFunc.ServeHTTP(0xc420010990, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc4201619a0 sp=0xc420161978
main.CORS.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/cors.go:134 +0x1f8 fp=0xc420161a88 sp=0xc4201619a0
net/http.HandlerFunc.ServeHTTP(0xc420012d80, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc420161ab0 sp=0xc420161a88
main.Logger.func1(0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/serverproject/logger.go:30 +0xae fp=0xc420161b88 sp=0xc420161ab0
net/http.HandlerFunc.ServeHTTP(0xc42000cc60, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44 fp=0xc420161bb0 sp=0xc420161b88
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420054320, 0x803e60, 0xc4200ed520, 0xc4200d7e00)
    /home/user/prg/go/src/github.com/gorilla/mux/mux.go:114 +0x10d fp=0xc420161cb0 sp=0xc420161bb0
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc4200132e0, 0x803e60, 0xc4200ed520, 0xc4200d70e0)
    /home/user/prg/go/src/github.com/braintree/manners/server.go:277 +0x8f fp=0xc420161ce0 sp=0xc420161cb0
net/http.serverHandler.ServeHTTP(0xc4200f6780, 0x803e60, 0xc4200ed520, 0xc4200d70e0)
    /usr/lib/go-1.7/src/net/http/server.go:2202 +0x7d fp=0xc420161d28 sp=0xc420161ce0
net/http.(*conn).serve(0xc420076580, 0x804460, 0xc4200155c0)
    /usr/lib/go-1.7/src/net/http/server.go:1579 +0x4b7 fp=0xc420161f88 sp=0xc420161d28
runtime.goexit()
    /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420161f90 sp=0xc420161f88
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7eff5d117fb0, 0x72, 0x0)
    /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420110990, 0x72, 0xc420049c58, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420110990, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420110930, 0x0, 0x800720, 0xc420013980)
    /usr/lib/go-1.7/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4200280f8, 0x4438ee, 0xc420049d08, 0x4c446d)
    /usr/lib/go-1.7/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc4200280f8, 0x701c40, 0xc4200f6e00, 0x804520, 0xc42000d920)
    /usr/lib/go-1.7/src/net/tcpsock.go:222 +0x49
net/http.(*Server).Serve(0xc4200f6780, 0x803c60, 0xc4200280f8, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:2273 +0x1ce
github.com/braintree/manners.(*GracefulServer).Serve(0xc4200e6ae0, 0x803c60, 0xc4200280f8, 0x5, 0x803c60)
    /home/user/prg/go/src/github.com/braintree/manners/server.go:224 +0x1d3
github.com/braintree/manners.(*GracefulServer).ListenAndServe(0xc4200e6ae0, 0x3, 0x1d)
    /home/user/prg/go/src/github.com/braintree/manners/server.go:117 +0x9b
main.main()
    /home/user/prg/go/src/serverproject/main.go:131 +0x287

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
    /usr/lib/go-1.7/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
    /usr/lib/go-1.7/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
    /usr/lib/go-1.7/src/os/signal/signal_unix.go:28 +0x41

goroutine 4 [select, locked to thread]:
runtime.gopark(0x702200, 0x0, 0x6da7a9, 0x6, 0x18, 0x2)
    /usr/lib/go-1.7/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420025730, 0x0, 0x18)
    /usr/lib/go-1.7/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420025730)
    /usr/lib/go-1.7/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
    /usr/lib/go-1.7/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
    /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
main.InitGracefulServer.func1(0xc4200e6b40, 0xc4200e6ae0)
    /home/user/prg/go/src/serverproject/gracefuller.go:98 +0x44
created by main.InitGracefulServer
    /home/user/prg/go/src/serverproject/gracefuller.go:106 +0x2d0

goroutine 6 [chan send]:
github.com/braintree/manners.(*GracefulServer).Serve.func1(0xc4200e6ae0, 0xc4200132e0, 0x803c60, 0xc4200280f8)
    /home/user/prg/go/src/github.com/braintree/manners/server.go:161 +0x4e
created by github.com/braintree/manners.(*GracefulServer).Serve
    /home/user/prg/go/src/github.com/braintree/manners/server.go:166 +0xf8

goroutine 16 [select]:
main.(*localWriter).writerNormalMode(0xc4200e7740)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc4200e7740)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

goroutine 14 [runnable]:
syscall.Syscall(0x0, 0xc, 0xc42013e000, 0x1000, 0x1ce, 0x1000, 0x0)
    /usr/lib/go-1.7/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xc, 0xc42013e000, 0x1000, 0x1000, 0x72, 0x0, 0x0)
    /usr/lib/go-1.7/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0xc, 0xc42013e000, 0x1000, 0x1000, 0xffffffffffffff01, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/syscall/syscall_unix.go:161 +0x49
net.(*netFD).Read(0xc420110d20, 0xc42013e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/fd_unix.go:239 +0x10f
net.(*conn).Read(0xc420028138, 0xc42013e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc4200136a0, 0xc42013e000, 0x1000, 0x1000, 0xc4200f6e68, 0x100000000, 0xc420015201)
    /usr/lib/go-1.7/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc4200e7080)
    /usr/lib/go-1.7/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4200e7080, 0x4, 0x6da05b, 0x4, 0xc4200e6b01, 0x522ec9, 0xc4200e6b10)
    /usr/lib/go-1.7/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc4200f6e00, 0x804460, 0xc420015700, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc4200f6e00, 0x804460, 0xc420015700)
    /usr/lib/go-1.7/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 15 [select]:
main.(*localWriter).writerNormalMode(0xc4200e75c0)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc4200e75c0)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7eff5d117770, 0x72, 0x7)
    /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420126290, 0x72, 0xc42015da20, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420126290, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420126230, 0xc420142000, 0x1000, 0x1000, 0x0, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420072048, 0xc420142000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc4200135c0, 0xc420142000, 0x1000, 0x1000, 0xc420076568, 0x100000000, 0xc420015201)
    /usr/lib/go-1.7/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc4200e7140)
    /usr/lib/go-1.7/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4200e7140, 0x4, 0x6da05b, 0x4, 0xc4200e6b01, 0x522ec9, 0xc4200e6b10)
    /usr/lib/go-1.7/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc420076500, 0x804460, 0xc420015600, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc420076500, 0x804460, 0xc420015600)
    /usr/lib/go-1.7/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 27 [IO wait]:
net.runtime_pollWait(0x7eff5d1179b0, 0x72, 0x9)
    /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420126370, 0x72, 0xc420047a20, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420126370, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420126310, 0xc42013c000, 0x1000, 0x1000, 0x0, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420072058, 0xc42013c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc4200d0980, 0xc42013c000, 0x1000, 0x1000, 0xc420076668, 0x100000000, 0xc420060c01)
    /usr/lib/go-1.7/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc4200e6fc0)
    /usr/lib/go-1.7/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4200e6fc0, 0x4, 0x6da05b, 0x4, 0xc4200e6b01, 0x522ec9, 0xc4200e6b10)
    /usr/lib/go-1.7/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc420076600, 0x804460, 0xc420060cc0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc420076600, 0x804460, 0xc420060cc0)
    /usr/lib/go-1.7/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 28 [IO wait]:
net.runtime_pollWait(0x7eff5d1178f0, 0x72, 0xa)
    /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201263e0, 0x72, 0xc42004ba20, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201263e0, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420126380, 0xc420131000, 0x1000, 0x1000, 0x0, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420072060, 0xc420131000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc4200d0a60, 0xc420131000, 0x1000, 0x1000, 0xc4200766e8, 0x100000000, 0xc420060e01)
    /usr/lib/go-1.7/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc42005e3c0)
    /usr/lib/go-1.7/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42005e3c0, 0x4, 0x6da05b, 0x4, 0xc4200e6b01, 0x522ec9, 0xc4200e6b10)
    /usr/lib/go-1.7/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc420076680, 0x804460, 0xc420060e80, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc420076680, 0x804460, 0xc420060e80)
    /usr/lib/go-1.7/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 29 [IO wait]:
net.runtime_pollWait(0x7eff5d117830, 0x72, 0xb)
    /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420126450, 0x72, 0xc420163a20, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420126450, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201263f0, 0xc420141000, 0x1000, 0x1000, 0x0, 0x801ae0, 0xc4200620a0)
    /usr/lib/go-1.7/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420072068, 0xc420141000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc4200d0940, 0xc420141000, 0x1000, 0x1000, 0xc420076768, 0x100000000, 0xc420061001)
    /usr/lib/go-1.7/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc42005e480)
    /usr/lib/go-1.7/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42005e480, 0x4, 0x6da05b, 0x4, 0xc4200e6b01, 0x522ec9, 0xc4200e6b10)
    /usr/lib/go-1.7/src/bufio/bufio.go:129 +0x62
net/http.(*conn).readRequest(0xc420076700, 0x804460, 0xc420060c00, 0x0, 0x0, 0x0)
    /usr/lib/go-1.7/src/net/http/server.go:762 +0xdff
net/http.(*conn).serve(0xc420076700, 0x804460, 0xc420060c00)
    /usr/lib/go-1.7/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
    /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d

goroutine 30 [select]:
main.(*localWriter).writerNormalMode(0xc42005ea20)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc42005ea20)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

goroutine 32 [select]:
main.(*localWriter).writerNormalMode(0xc42005eba0)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc42005eba0)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

goroutine 33 [select]:
main.(*localWriter).writerNormalMode(0xc42005ed20)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc42005ed20)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

goroutine 34 [select]:
main.(*localWriter).writerNormalMode(0xc42005ef60)
    /home/user/prg/go/src/serverproject/localwriter.go:303 +0x4a9
main.(*localWriter).writer(0xc42005ef60)
    /home/user/prg/go/src/serverproject/localwriter.go:291 +0x2b
created by main.(*localWriter).Start
    /home/user/prg/go/src/serverproject/localwriter.go:264 +0x122

**Comment by renannprado** [comment]
where did this variable `router` come from?

**Comment by elithrar** [comment]
Can you show the code that caused this?

**Comment by kisielk** [comment]
Looks like you're trying to modify the router after the server is running. mux doesn't support that, since it's not needed in the vast majority of cases, and the locking required would unnecessary slow down the router.

**Comment by zoltan123** [comment]
@kisielk Sorry for reopening the thread. Just to clarify for anyone with the same problem.
(I have missed the notifications of this thread)

Yes, I am doing exactly what You suspect, I am adding new routes *after* starting the server:

    func YourHandler(w http.ResponseWriter, r *http.Request) {
        // modifying the router
        r.HandleFunc("/bla", YourHandler)
    }

    func main() {
        r := mux.NewRouter()
        r.HandleFunc("/", YourHandler)

        http.ListenAndServe(":8000", r)
    }

I have just re-read the README.md, but I did not find anything about this limitation. I think it would worth mentioning, since it seems to be a very rarely surfacing race condition, so users may assume no such limitation exists, but their code will fail mysteriously from time to time:

"After the server is started (e.g. through http.ListenAndServe()), the router must not be modified - i.e. HandleFunc() most not be called."
