### ISSUE TITLE
Getting the wrong function executed

### ISSUE THREAD

**Issue by facundomedica** [gorilla/mux#248]
Maybe I'm using this library wrong, but just in case this is a bug, I'm reporting it.

```go
r.HandleFunc("/locations/{location}/devices/delete/{device}", v1f.NeedsAuthorization(v1f.GetLocationDeleteDevice, db)).Methods("GET")
r.HandleFunc("/locations/{location}/devices", v1f.NeedsAuthorization(v1f.GetLocationDevices, db)).Methods("GET")
```

The problem is quite simple to explain, I have this two routes with functions but both go to the second one. If I change the route of the first one to `.../adevices/...` or something else it will work.

If you need an app that recreates this issue I can write one.

**Comment by elithrar** [comment]
What is the URL you are passing?

**Comment by facundomedica** [comment]
http://localhost:5001/locations/58ebc870242ac9d73eb6a23c/devices/delete/1491849169864000000

I've realized that with some values it works and with some it doesn't. I made a small test app but I can't recreate the problem.

**Comment by facundomedica** [comment]
Okay I recreated the issue in a new project, and it works exactly like the one I showed before.
I tested it by clicking the links in the above comment.

``` go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	router.HandleFunc("/locations/{location}/devices/delete/{device}", GetLocationDeleteDevice).Methods("GET")
	router.HandleFunc("/locations/{location}/devices", GetLocationDevices).Methods("GET")
	if err := http.ListenAndServe("localhost:5001", router); err != nil {
		log.Fatal(err)
	}
}

func GetLocationDevices(w http.ResponseWriter, r *http.Request) {
	fmt.Println("GetLocationDevices")
	w.Write([]byte("GET!"))
}

func GetLocationDeleteDevice(w http.ResponseWriter, r *http.Request) {
	fmt.Println("GetLocationDeleteDevice")
	w.Write([]byte("DELETE!"))
}
```

@elithrar am I using mux right?

**Comment by elithrar** [comment]
There is nothing here that points to mux.

Can you show how you're testing?

* Is the browser autocompleting?
* Have you added a `log.Println(r.URL)` statement to confirm the input URL is the one you actually input?

> Not working (prints "GET", meaning that is not working as expected, and it cuts off the last part):
> http://localhost:5001/locations/58ebc870242ac9d73eb6a23c/devices/delete/1491849169864000000
> http://localhost:5001/locations/58ebc870242ac9d73eb6a23c/devices/delete/1491922212261000000
> http://localhost:5001/locations/58ebc870242ac9d73eb6a23c/devices/delete/1491922220620000000

All of these work as intended for me and output `DELETE!`.

**Comment by facundomedica** [comment]
@elithrar I couldn't keep testing this issue and it seems that it is not related with mux but with the browser, so I'm closing it. If I encounter this problem in the future, I'll let you know. Thanks!
