### ISSUE TITLE
installation not working on IDEA

### ISSUE THREAD

**Issue by connelevalsam** [gorilla/mux#249]
Just started GoLang, got into web dev. Did `go get -u github.com/gorilla/mux/` in terminal to my path, it worked. Downloaded the package in src directory. But when I tried using the router and importing `"github.com/gorilla/mux/"` package IDEA shows error asking to download it, tried it it shows `GOROOT=/usr/local/go
GOPATH=/usr/local/go:/usr/local/go/src
/usr/local/go/bin/go get -t github.com/gorilla/mux/...
package github.com/gorilla/mux/...: cannot download, $GOPATH must not be set to $GOROOT. For more details see: go help gopath`
Any idea?

**Comment by elithrar** [comment]
What does echo $GOPATH show on your shell?

IDEA indicates that your GOROOT & GOPATH are at the same location, which is
almost certainly not correct.

**Comment by connelevalsam** [comment]
shows nothing
![screenshot from 2017-04-18 09-05-34](https://cloud.githubusercontent.com/assets/13662770/25120514/53d8e160-2416-11e7-9508-5fe8031763c5.png)

**Comment by elithrar** [comment]
How did you install Go?

You should update to Go 1.8, which sets the GOPATH for you.

**Comment by connelevalsam** [comment]
Downloaded `go1.4.linux-amd64.tar.gz` then extracted it `tar -C /usr/local -xzf go1.4.linux-amd64.tar.gz` for the go tree. I then tested it by running normal GoLang programs, it worked well. Decided to do web, worked well not until i decided to use `github.com/gorilla/mux` package for routing.
-
How do i update it now? can that fix this issue for me cos i'm getting tired.

**Comment by elithrar** [comment]
Did you set your GOPATH as per https://github.com/golang/go/wiki/GOPATH -?
Your previous code indicated you had not.

Go 1.4 is also very old. See https://golang.org/doc/install for updated
versions

**Comment by connelevalsam** [comment]
Thanks. I removed the former and extracted the new into usr/local/go. Now it's working. Thanks

**Comment by dlsniper** [comment]
Not sure which editor / plugin you are using, but this is definitely not a ` mux ` issue, ping me on Slack if you need further help on this or please open an issue on: https://youtrack.jetbrains.com/issues/Go and I'll be happy to help you out.
