### ISSUE TITLE
Get registered routes

### ISSUE THREAD

**Issue by thalesfsp** [gorilla/mux#252]
Hello!

 Is it possible to get a list of registered routes against a router?

Thank you!

**Comment by elithrar** [comment]
Yes: https://godoc.org/github.com/gorilla/mux#Router.Walk will walk through
every route and pass it to the provided WalkFunc.

**Comment by thalesfsp** [comment]
Thank you! My idea is to, when someone hit `/`, it returns a JSON with the available resources/endpoints. Is there a plugin for it?

**Comment by thalesfsp** [comment]
Thank you @elithrar! My idea is to, when someone hit `/`, it returns a JSON with the available resources/endpoints. Is there a plugin for it?

**Comment by thalesfsp** [comment]
@elithrar is there some way to not only get the routes but the registered verbs? Example:

`GET /product/{id:[0-9]+}`

**Comment by elithrar** [comment]
https://godoc.org/github.com/gorilla/mux#Route.GetPathTemplate

**Comment by elithrar** [comment]
Closing out.
