### ISSUE TITLE
Not matching headers should return a 406 instead of a 404

### ISSUE THREAD

**Issue by hodgesds** [gorilla/mux#253]
I think this applies to [`HeadersRegexp`](https://github.com/gorilla/mux/blob/master/route.go#L238) and [`Headers`](https://github.com/gorilla/mux/blob/master/route.go#L213). If there in not a match it currently returns a `404`, but should probably return a `406` instead to be more HTTP compliant:

> 10.4.7 406 Not Acceptable
>The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request.

>Unless it was a HEAD request, the response SHOULD include an entity containing a list of available entity characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. Depending upon the format and the capabilities of the user agent, selection of the most appropriate choice MAY be performed automatically. However, this specification does not define any standard for such automatic selection.

See [W3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

**Comment by elithrar** [comment]
Based on the RFC, that would only apply to the *Accept* header, not to all
headers. The Headers/HeadersRegexp expand beyond that, so it's not clear
that we should send a 406 in those cases.

I would say that users should use middleware to 406 in front of us if the
Accept doesn't match.

**Comment by hodgesds** [comment]
Yeah, I guess doing the extra match of the `Accept` header might be a little heavy and middleware seems like a decent option. Closing.
