### ISSUE TITLE
how to Convert http.HandleFunc to *mux.Router

### ISSUE THREAD

**Issue by kamal-github** [gorilla/mux#256]
I am using [nrgorilla](https://github.com/newrelic/go-agent/blob/master/_integrations/nrgorilla/v1/nrgorilla.go) and [gokit](https://github.com/go-kit/kit)(having **mux** as router) how to Convert http.HandleFunc to *mux.Router.

So to instrument all routes I need to pass `*mux.Router` to `InstrumentRoutes` function, but I have http.Handler which I want to assert to `*mux.Router` to make it run. 

```
func InstrumentRoutes(r *mux.Router, app newrelic.Application) *mux.Router {
	r.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		h := instrumentRoute(route.GetHandler(), app, routeName(route))
		route.Handler(h)
		return nil
	})
	if nil != r.NotFoundHandler {
		r.NotFoundHandler = instrumentRoute(r.NotFoundHandler, app, "NotFoundHandler")
	}
	return r
}
```

Any help would be appreciated. Thanks!

**Comment by elithrar** [comment]
Where does http.Handler come into play in your example here?

*mux.Router already satisfies the http.Handler interface.

**Comment by kamal-github** [comment]
I am using `go-kit` for our micro services, so in my `transport.go` it is returning `http.Handler`,  but     nrgorilla's `func InstrumentRoutes(r *mux.Router, app newrelic.Application) *mux.Router{...}` function accepts one `*mux.Router`, but I  am getting below error.


```
can not convert http.HandlerFunc to *mux.Router
```

**Comment by elithrar** [comment]
You can't - a Router satisfies the http.Handler interface, but also has a
number of additional methods.

You should pass your base mux.Router instance to that function.

**Comment by elithrar** [comment]
@kamal-github Let me know if you still need help w/ this.

**Comment by kamal-github** [comment]
Thanks for fast response.
