### ISSUE TITLE
Add ability to register callback to get result of path match

### ISSUE THREAD

**Issue by nmiyake** [gorilla/mux#258]
I have a scenario in which I want every handler that is executed by the router to perform some piece of work before it executes the handler. My specific scenario involves wanting to store/process information about the matched route (the results of `setVars()` and `setCurrentRoute` for the matched route) for every match.

Right now, this is a fairly tedious process. I have defined a function that decorates an `http.Handler` to provide this functionality, but right now every time somebody registers a handler on the router they need to remember to manually decorate their handler:

```go
r.HandleFunc("/products/{key}", my.DecoratorFunc(ProductHandler))
```

If any developer forgets to decorate the function, everything compiles but the extra functionality we need is just silently dropped.

It would be great if there was the ability to register a "Before" handler on the root router that would always be invoked before the actual handler. That way, one could just add the functionality to the root router and then everything else would "just work":

```go
r := mux.NewRouter()
r.BeforeHandler = my.Handler
...
r.HandleFunc("/products/{key}", ProductHandler)
```

The implementation would be pretty simple -- the router's `ServeHTTP` function would simply invoke the `BeforeHandler` (as long as it's non-nil) before the final `handler.ServeHTTP` call. The contract would be that only the root router (the one that executes `ServeHTTP` to find the match) invokes the `BeforeHandler` (any `BeforeHandler` values on subrouters would be ignored).

**Comment by kisielk** [comment]
I don't really like these kind of special-cased handler insertions. Does this mean we need an `AfterHandler` too? And then what if some routes need exceptions to those? etc.

Couldn't the decorator problem be solved by just wrapping the call to `r.HandleFunc` instead of calling it directly? Then it can be solved without adding to the mux API.

**Comment by nmiyake** [comment]
Yup, I definitely understand the concerns around special-casing like this, and understand if ultimately you don't think this is a good fit for the library. However, thought it would be worth discussing.

By "wrapping the call", I assume you mean something like:

```go
func RegisterHandler(r *mux.Route, handler http.Handler) *Route {
   r.Handler(my.DecoratorFunc(handler))
}
```

This certainly works, but the main drawback is that it still requires a programmer to remember to register all handlers using this function. If they happen to forget to register a handler using this function and call `r.Handler` directly instead, then it won't work. In any large project, I don't have confidence that programmers (even with CR) can be protected from this (I could add linting rules to flag all uses of `r.Handler`, but that's a project-level modification that's heavier-weight).

I could type alias/wrap `mux.Route` and only expose the "wrapper" function there, but because there are multiple `mux.Route` and `mux.Router` functions that return `mux.Route` , I'd basically have to define wrapper functions for all of it, which would get pretty tedious.

Adding a `Before` handler (or some other mechanism to inject logic after the variables and routes are processed for a matched handler) seemed much cleaner/easier compared to these approaches.

**Comment by nmiyake** [comment]
Also, to zoom out a bit -- the underlying objective that I'm ultimately trying to accomplish is to be able to store the current route and path parameter variables for every matched route. The approach outlined in this issue seemed like the most generic/cleanest way to enable this in a manner that doesn't require auditing every caller, but if you have other ideas for how to solve this underlying issues I'd be open to suggestions!

**Comment by nmiyake** [comment]
Alternate approach that I just thought of that is similar to this but would be a bit more scoped and may not have the baggage of a before/after:

Instead of `BeforeHandler`, add `MatchCallback func(*http.Request, RouteMatch)`

* On any match, `ServeHTTP` would invoke `r.MatchCallback(req, match)`

This gets at the underlying issue (add a way to extract information about the match outside of the scope of the handler itself) without opening the pandora's box of full-blown special-case matchers.

**Comment by elithrar** [comment]
Why not just wrap the router?

r := mux.NewRouter()
// add routes

http.ListenAndServe(":8000", YourMiddleware(r))

-

That would always be executed, doesn't require you to decorate each route,
and can implement before/after logic.

**Comment by ChrisHines** [comment]
What about using `Router.Walk` to decorate post-facto? You could write a function like this:

```go
func DecorateHandlers(r *mux.Router, decorate func(http.Handler) http.Handler) error {
    return r.Walk(func(route *Route, router *Router, ancestors []*Route) error {
        return route.Handler(decorate(route.GetHandler)).GetError()
    }
}
```

Given that, you build your routes undecorated then make one call to `DecorateHandlers(r, my.DecoratorFunc)` at the end.

**Comment by nmiyake** [comment]
@elithrar wrapping the route doesn't work because the matched variables are only available within the scope of the handler itself. Per the documentation on `CurrentRoute`:

```
// This only works when called inside the handler of the matched route
// because the matched route is stored in the request context which is cleared
// after the handler returns, unless the KeepContext option is set on the
// Router.
```

I have verified that this is the case -- because the router's `ServeHTTP` copies the context before setting the variables on it (which I agree is the correct approach), they aren't visible before or after in middleware calls. FWIW, I'm guessing that something like this is the motivation behind the PR https://github.com/gorilla/mux/pull/240 as well.

@ChrisHines I considered that solution as well, and it's definitely still in the running as it does work. The one case where it doesn't work is if people attach more handlers to the router after the server has started/`DecorateHandlers` have been called. That probably isn't great practice so not quite as worried about it, but it still isn't as foolproof at intercepting at the call site itself (which effectively provides the guarantee that any match provided by the root router will be intercepted).

If something like this isn't a good fit, I'll likely go with either walking to decorate (and warning people not to attach routes afterwards) or defining my own "root router" (effectively a copy `mux.Router` that adds what I want here), return that in my library and have clients attach all routes/subrouters etc. to that base router (since only the top-level `ServeHTTP` needs to be intercepted, all the subrouters and routes underneath it can still be vanilla `mux.Router` or `http.Handler` and be fine).

**Comment by kisielk** [comment]
mux doesn't support changing the routes while the server is running (it's a race condition) so you don't really need to worry about that ;)

**Comment by nmiyake** [comment]
Good to know! In that case, walking the handlers and decorating them is probably a sufficient solution for me. Will close out this issue -- thanks for the help!

**Comment by nmiyake** [comment]
@ChrisHines your solution worked in simple cases, but unfortunately it looks like there are some valid constructions of handlers where `Walk` will not return the handler even though one is clearly registered. Example code:

```go
func TestWalk(t *testing.T) {
	router := mux.NewRouter().StrictSlash(true)
	v1 := router.PathPrefix("/v1").Subrouter()

	stacks := v1.PathPrefix("/products").Subrouter()
	stackInstance := stacks.PathPrefix("/{product}").Subrouter()

	handlerInvoked := false
	stackInstance.Methods("GET").Handler(http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		handlerInvoked = true
	}))

	server := httptest.NewServer(router)
	defer server.Close()

	if handlerInvoked == true {
		t.Errorf("handler should not be invoked")
	}

	http.Get(server.URL + "/v1/products/myProduct")

	if handlerInvoked != true {
		t.Errorf("handler should have been invoked")
	}

	router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		tmpl, _ := route.GetPathTemplate()
		fmt.Printf("route: %s, handler: %v\n", tmpl, route.GetHandler())
		return nil
	})
}
```

Output:

```
route: /v1, handler: <nil>
route: /v1/products, handler: <nil>
route: /v1/products/{product}, handler: <nil>
```

As you can see, the test passes (so the handler is clearly invoked), but `handler` reports as `nil` when walking the routes, so the decoration approach is out (I could try to figure out the issue in the walk, but I remain concerned that there may be edge cases I am missing).

@kisielk what do you think about the notion of adding a callback hook/function? Concretely:

```go
type Router struct {
	// Configurable Handler to be used when no route matches.
	NotFoundHandler http.Handler
        // MatchCallback is invoked on any route match before the handler is invoked
        MatchCallback func(*http.Request, RouteMatch)
        ...
}

func (r *Router) ServeHTTP(w http.ResponseWriter, req *http.Request) {
     ...
     if r.Match(req, &match) {
		handler = match.Handler
		req = setVars(req, match.Vars)
		req = setCurrentRoute(req, match.Route)
                if r.MatchCallback != nil {
                      r.MatchCallback(req, match)
                }
     }
     ...
}
```

I can work around this in my own library by duplicating the top-level code for router, but I do think this is a more general concern (for example, this mechanism would allow https://github.com/gorilla/mux/issues/257 to be solved as well), and think that providing some kind of first-class mechanism to enable this would be nice.

**Comment by ChrisHines** [comment]
>As you can see, the test passes (so the handler is clearly invoked), but handler reports as nil when walking the routes, so the decoration approach is out -- although I'm sure I could debug this/figure out a way to try to get at all the handlers in the walk, I'm weary of adding too much logic there and would be afraid of the consequences of missing an edge case where some handler would not be found by the walk and thus not wrapped properly.

If `Walk` is broken I don't think the solution is to add more API surface area as a work around. Let's fix `Walk` first.

**Comment by nmiyake** [comment]
Filed https://github.com/gorilla/mux/issues/261 for the `Walk` issue.

Fixing `Walk` would fix the decorator approach, but I think that the general issue/request may still make sense independently, so keeping the issue open for now. However, if we come to the conclusion that this kind of API hook does not make sense for the project (whether it be because the primary use case cited can be solved by another approach or just that it doesn't make sense as part of the API), then fine with closing this out without further action.

**Comment by nmiyake** [comment]
Dug around more and understand what's going on now -- the issue is that `Walk` only walks routes/subroutes with concrete paths registered, so if a path has subrouters with method handler registered, those are never visited.

Filed #262 to provide a proposal for exposing a way to walk all routes, and updated #261 to track the fact that the current behavior of `Walk` is inconsistent with the documentation.

**Comment by nmiyake** [comment]
After investigation, I believe that, as long as other issues are fixed, there are sufficient mechanisms to work around this.

Once #261 and #263 are fixed, it should be possible to walk all routes and decorate the handlers with the closest non-empty path from the ancestor routes.

It is also possible to wrap the root Router and use its `Match` function to extract the match and path variable information:

```go
type RootRouter mux.Router

func (r *RootRouter) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	var match mux.RouteMatch
	if (*mux.Router)(r).Match(req, &match) {
		// match.Route.GetPathTemplate() may return error/no path template: need #266 to be fixed so that,
		// if that is the case, first non-nil path template from ancestor can be retrieved
		matchCallback(match)
	}
	(*mux.Router)(r).ServeHTTP(w, req)
}
```

Currently, this has the issue that, if the matched route doesn't have a path defined, there's no way to retrieve the matched path template. However, if #266 is fixed, this would be possible as well and it would be a plausible workaround.

Closing out this issue in favor of the other ones.
