### ISSUE TITLE
Walk does not walk all routes and subroutes

### ISSUE THREAD

**Issue by nmiyake** [gorilla/mux#261]
The current documentation on `Walk` says the following:

```
// Walk walks the router and all its sub-routers, calling walkFn for each route
// in the tree. The routes are walked in the order they were added. Sub-routers
// are explored depth-first.
```

However, this is not true: currently, `Walk` only walks routes with paths/regexps on them. This can cause `Walk` to omit subroutes that have method matchers.

Example:

```go
router := mux.NewRouter().StrictSlash(true)
products := router.PathPrefix("/{products}").Subrouter()

products.Methods("GET").Handler(...)
products.Methods("POST").Handler(...)
```

Now, call `Walk` on the router:

```go
router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
	tmpl, _ := route.GetPathTemplate()
	fmt.Printf("route: %s, handler: %v\n", tmpl, route.GetHandler())
	return nil
})
```

Output:

```
route: /{products}, handler: <nil>
```

In this case, `GET` and `POST` are actually subrouters/subroutes, but are never invoked by `Walk`.

To be consistent with the documentation, these routes/routers should be visited as well. Although the `GetPathTemplate` for the routes will return `nil`/empty, it should be possible to walk the ancestors to find the nearest `Route` with a non-empty path template to determine the actual path.

This change would alter existing behavior, so it may be necessary to keep as-is and update the documentation on the function to make it clear that it is invoked only on paths (and not all routes/subroutes) and introduce a new `Walk` function for walking all of the routes.

**Comment by nmiyake** [comment]
May be related to https://github.com/gorilla/mux/issues/166

**Comment by nmiyake** [comment]
OK, dug around a  bit and understand what's going on now.

The `Walk` function as currently constituted walks only concrete routes. This is correct for the purpose of route listing, but is insufficient for the purposes of getting all handlers. This is because a single concrete route may have multiple handlers depending on other matchers like method matchers.

For example:

```go
router := mux.NewRouter().StrictSlash(true)
products := router.PathPrefix("/{product}").Subrouter()
products.Methods("GET").Handler(...)
products.Methods("PUT").Handler(...)
```

In this case, `/product` is the only path, but it actually has 2 handlers: 1 for "GET" and 1 for "PUT".

As it stands, `Walk` is functionally correct. However, I'm looking for functionality that would allow me to enumerate all handlers, which would basically be a different `Walk` function. Will close this issue and open a new one to track that.

**Comment by nmiyake** [comment]
Note that fixing this issue will cause a behavioral change in the API -- the previous implementation had the effective invariant that, for any `route` passed to `WalkFunc` by `Walk`, `route.GetPathTemplate()` would return a non-empty template (and `nil` error).

After this issue is resolved, if callers want their `WalkFunc` implementations to preserve the previous behavior, they can add the following to the beginning of their `WalkFunc`:

```go
// skip routes that do not have a path template defined to match previous Walk behavior
if _, err := route.GetPathTemplate(); err != nil {
   return nil
}
```

**Comment by elithrar** [comment]
Waiting on #265 to be reviewed+merged.
