### ISSUE TITLE
Proposal: add WalkAll function that will walk all routes/subroutes

### ISSUE THREAD

**Issue by nmiyake** [gorilla/mux#262]
Currently, the `Walk` function only walks routes/subroutes that have regexp paths on them. This is insufficient to walk all routes, because a single concrete route like `/product` may have method-based sub-routes with handlers that would not be called.

Modifying the current `Walk` functionality would change existing behavior, so should probably be avoided. However, I think there are valid use cases for the underlying functionality here.

I propose adding a `WalkAll` function:

```go
// WalkAll walks the router and all its sub-routers, calling walkFn for each route
// in the tree. The routes are walked in the order they were added. Sub-routers
// are explored depth-first.
func (r *Router) WalkAll(walkFn WalkFunc) error {
	return r.walk(walkFn, []*Route{}, true)
}

// Walk walks the router and all its sub-routers with paths, calling walkFn for each 
// route in the tree that has a path. The routes are walked in the order they were 
// added. Sub-routers are explored depth-first.
func (r *Router) Walk(walkFn WalkFunc) error {
	return r.walk(walkFn, []*Route{}, false)
}
```

This would provide a mechanism to explicitly walk all routes (whether or not they have a path). `walk` would be modified to be:

```go
func (r *Router) walk(walkFn WalkFunc, ancestors []*Route, walkAll bool) error {
     	for _, t := range r.routes {
		if !walkAll && (t.regexp == nil || t.regexp.path == nil || t.regexp.path.template == "") {
			continue
		}
        ...
}
```

**Comment by kisielk** [comment]
I really would like to avoid increasing the already massive API surface of this package. I don't see a problem with changing the Walk behaviour if it fixes a bug...

**Comment by nmiyake** [comment]
OK. I'm personally fine with either approach, but was just flagging that fixing this bug will create a behavioral difference in API behavior for existing clients -- previously, it happened to be the case that every `route` passed to `WalkFunc` would have `t.regexp.path.template != ""`, so any existing consumers that make this assumption would be broken by a change here -- to preserve it, they would need to add the following to their `WalkFunc`:

```go
_, err := route.GetPathTemplate()
if err == nil {
    return nil
}
```

If you guys are fine with this, then it works for me -- I've opened https://github.com/gorilla/mux/pull/265 to implement the fix in this manner.

If you want to preserve the old behavior for back-compat, then I would like to propose implementing this "fix" via the method outlined above (and can update my PR to do so).

**Comment by elithrar** [comment]
I'm OK with a minor behavioural change as well to keep the API surface
sane(r). I'll tag the version as a minor release (1.x+1) to signal that.

(Thanks for the proposal Nick)

**Comment by nmiyake** [comment]
OK great -- in that case, will close this issue out in favor of #261. Thanks!
