### ISSUE TITLE
    r.Methods("GET").HandleFunc("/articles", handler);   cannot work

### ISSUE THREAD

**Issue by bilc** [gorilla/mux#267]
Methods() returns *Route,  but Route doesnot have function HandleFunc. It has function:
`func (r *Route) HandlerFunc(f func(http.ResponseWriter, *http.Request)) *Route {`

**Comment by elithrar** [comment]
Yes, that is by design.

Call HandleFunc on a Router, or call HandlerFunc(...).Path(...) if you are
building up a Route manually.

**Comment by nickhudkins** [comment]
@bilc please see #269 which I suspect may be the reason you were asking. This question appears in a few issues, so hopefully this will clarify.

**Comment by bilc** [comment]
@nickhudkins OK. I think readme should be updated.
