### ISSUE TITLE
405 method not allowed vs. 404 not found

### ISSUE THREAD

**Issue by solarfly73** [gorilla/mux#271]
When .Method("GET") is specified and "POST" is called on that endpoint, a 404 is returned instead of a 405. The only function I can see for handling missing stuff is the NotFound() and the handler wrapper. Can we get a 405 on missing methods instead?

**Comment by kisielk** [comment]
I think #26 implemented this but it's way out of date now.

**Comment by solarfly73** [comment]
That's 2013. Can we reinvigorate that effort? I'm willing to dive into it to get a 405 instead of a 404, since it both makes unit testing more precise and returns the correct code to 3rd party API integrators. Also I didn't see a 405 in the code diff, but I'm still getting familiar with the code (as of this morning).

**Comment by kisielk** [comment]
Sure, if you want to refresh the PR to work with the current codebase we'll review it.

**Comment by Jamesxql** [comment]
+1
This should return 405 instead of 404

**Comment by maknahar** [comment]
Is anybody working on this? If not I would like to give it a shot.

**Comment by jimmyislive** [comment]
+1
