### ISSUE TITLE
Returning route's elapsed time in JSON body

### ISSUE THREAD

**Issue by Collinux** [gorilla/mux#272]
I'm trying to implement a feature that will benchmark the time it takes to handle a route and return the result. For example, when the `GET /api/info` route is visited then a timer will start, the handler to get the info will be called, then the elapsed time will be appended to the JSON body response. This is similar to [golang.org/pkg/testing/benchmark](https://golang.org/pkg/testing/#hdr-Benchmarks) except I would like to avoid having to start a timer within every single route's handler.

Does mux have a way to add this underlying feature to all routes?

**Comment by elithrar** [comment]
Write middleware - e.g.

func TimeRequest(h http.Handler) http.Handler {
    return http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {
        // start := startTimer()
        h.ServeHTTP(w, r) // call handler
        // duration := stopTimer(start)
    }
}
