### ISSUE TITLE
No field or method Name

### ISSUE THREAD

**Issue by RobGraham** [gorilla/mux#273]
Bear in mind i'm very new to Go. and I believe this may completely be the linters fault but i'm having a hard time understanding why i'm seeing this error
![linterr](https://user-images.githubusercontent.com/1311204/26910688-479295c6-4bbd-11e7-8049-d6c424bb8191.png)

If I move the `Name` chain below any of the other methods here, the linter won't complain even though `Name` is returning `*Router` just like the other methods... 

To provide a larger view of a tutorial i'm following, here is the code, i just wanted the order of the methods to match my `Route` struct

```
type Route struct {
    Name        string
    Method      string
    Pattern     string
    HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {

    router := mux.NewRouter().StrictSlash(true)
    for _, route := range routes {
        router.
            Methods(route.Method).
            Path(route.Pattern).
            Name(route.Name).
            Handler(route.HandlerFunc)
    }

    return router
}

var routes = Routes{
    Route{
        "Index",
        "GET",
        "/",
        Index,
    },
    Route{
        "TodoIndex",
        "GET",
        "/todos",
        TodoIndex,
    },
    Route{
        "TodoShow",
        "GET",
        "/todos/{todoId}",
        TodoShow,
    },
}
```

**Comment by elithrar** [comment]
Name is defined on a *Route, not a *Router -
https://godoc.org/github.com/gorilla/mux#Route.Name

**Comment by RobGraham** [comment]
Aha! While your answer was sort of helpful, I started digging back in the source code and realized you have mux.go which is your `*Router` and route.go (`*Route`) which shares some method names that caused my confusion. Thank you
