### ISSUE TITLE
PathPrefix with for ... range will confusion

### ISSUE THREAD

**Issue by robbinhan** [gorilla/mux#274]
I load route path config, and loop them to `PathPrefix` function.

```json
{
"/A/": "AA",
"/B/": "BB"
}
```

```golang
for routPath, value := range config {
    r.PathPrefix(routPath).HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        fmt.Println(value)
    })
}
```

Then I use Postman to request , sometimes call `http://localhost:8000/A` will print `BB`, and sometimes call `http://localhost:8000/B` will print `AA`

I dont where it was wrong

**Comment by iron-s** [comment]
This behavior is described here: https://golang.org/doc/faq#closures_and_goroutines
Relevant excerpt is 

> each iteration of the loop uses the same instance of the variable v, so each closure shares that single variable

So both paths will return the same value - either "AA" or "BB" (depending on the order in which config was iterated).
It can be fixed this way:

```go
for routPath, value := range config {
    value := value // we create new variable here
    r.PathPrefix(routPath).HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        fmt.Println(value)
    })
}
```
