### ISSUE TITLE
route.URL() does not use scheme of parent router.

### ISSUE THREAD

**Issue by ChrisHines** [gorilla/mux#279]
The feature added in https://github.com/gorilla/mux/pull/260 works for routes with a defined scheme, but not when the scheme is inherited from a parent router.

Reproducer:

```go
package main

import (
	"fmt"
	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter().Schemes("https").Host("localhost").Subrouter()
	route := router.NewRoute().Path("/api").BuildOnly()

	u, err := route.URL()

	fmt.Println(u, err)
}
```

The above code outputs `http://localhost/api <nil>`, but I was expecting `https://localhost/api <nil>`.

I have reproduced this with a new test case and will submit a PR when the implementation is working.

**Comment by kisielk** [comment]
Fixed by #280
