### ISSUE TITLE
Redirect should use 308 code for non-GET methods

### ISSUE THREAD

**Issue by nmiyake** [gorilla/mux#285]
In projects using Go 1.7+, `gorilla/mux` should use 308 as the response code for redirects for non-`GET` methods.

Currently, when the redirect behavior is turned on, the redirection is always done with a 301: `m.Handler = http.RedirectHandler(u.String(), 301)` (https://github.com/gorilla/mux/blob/18fca31550181693b3a834a15b74b564b3605876/regexp.go#L293)

Per the RFC and other online resources, the method behavior for 301 retries is not strictly defined, and there exist user agents that will always retry a 301 using GET.

The 308 response code was created for non-get methods to specifically indicate that the method and body must not be changed. Support for this was added in Go 1.7.

**Comment by elithrar** [comment]
Many clients do not understand 308, and thus I'm hesitant to set that as
the default.

**Comment by elithrar** [comment]
Timing out. Please re-open if you have further questions!

**Comment by oswcab** [comment]
It should at least support 307 so that the method and the load are kept.

**Comment by elithrar** [comment]
See the middleware. Not all clients handle 307/308 as they were later
additions.
