### ISSUE TITLE
Can't find import

### ISSUE THREAD

**Issue by Pobepto** [gorilla/mux#286]
I have issue with package importing. Error - `can't find import: "github.com/gorilla/mux"`. I'm tried to reinstall, but it doesn't help. Here is my Go version and environments. If you want to I can attach my code.

`$ go version` 
```
go version go1.6.2 linux/amd64
```

`$ go env` 
```
GOARCH="amd64"
GOBIN="/home/rob/Desktop/Go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rob/Desktop/Go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by elithrar** [comment]
What does

$ go get -u github.com/gorilla/mux

... show?

Does it appear in $GOPATH/src after that?

**Comment by Pobepto** [comment]
> What does
> $ go get -u github.com/gorilla/mux
> ... show?

Nothing

> Does it appear in $GOPATH/src after that?

Yes

**Comment by elithrar** [comment]
Where are you running your code? Are you sure the environment you printed
above is available where you are running it?

What does the *full* error say?

**Comment by Pobepto** [comment]
I found where there was a problem. I had another name for the package, not "main". When I change package to "main" this solved problem.

Thanks!
