### ISSUE TITLE
Ability to get the query template from a route

### ISSUE THREAD

**Issue by lukeng** [gorilla/mux#287]
Hi,
I have a route with query inside, and I would like to generate a URL for reference but I can't find a way to retrieve the query template:
```
r := mux.NewRouter()
p := r.Path("/api").Queries("foo", "{foo}", "bar", "{bar}")
fmt.Println(p.GetPathTemplate()) // only returns "/api", but not "/api?foo={foo}&bar={bar}"
```

may it be better if GetPathTemplate() also returns the query template, or add a new GetQueriesTemplate() ?

**Comment by paulbes** [comment]
We are also interested in this type of functionality, is it best to open a PR for this?

**Comment by elithrar** [comment]
@paulbes I'd happily accept a PR for `GetQueriesTemplate()` functionality.

**Comment by paulbes** [comment]
@elithrar, as a side-note, is there any intention for adding optional query parameters, e.g., a more concise way of achieving this: https://stackoverflow.com/questions/45378566/gorilla-mux-optional-query-values

**Comment by elithrar** [comment]
No current plans, but open to a proposal that doesn't complicate the API.

mux has a large API, and the more we add, the higher the barrier to
newcomers as well as the more we need to document, maintain, test.
