### ISSUE TITLE
Double encoding URL parameters when cleaning paths

### ISSUE THREAD

**Issue by lekoder** [gorilla/mux#290]
Path cleaning causes URL encoded parameters in path to be encoded twice in `HTTP/1.1 301` response. This causes problems when using `UseEncodedPath()`.

**Actual behavior**
```
curl -v http://localhost:8080//v1/k%3Av
> GET //v1/k%3Av HTTP/1.1
< HTTP/1.1 301 Moved Permanently
< Location: /v1/k%253Av
```
**Expected behavior**
```
curl -v http://localhost:8080//v1/k%3Av
> GET //v1/k%3Av HTTP/1.1
< HTTP/1.1 301 Moved Permanently
< Location: /v1/k%3Av
```

**Comment by adamo57** [comment]
I could take a look at this

**Comment by kisielk** [comment]
@adamo57 if you have time, please do. It would be much appreciated.

**Comment by adamo57** [comment]
@lekoder I think the problem here is that you used an already urlencoded string as input to the router, one solution that I was thinking of was to add a check to see if the input url was already encoded, only to find that determining that would be near to impossible.
