### ISSUE TITLE
Release minor version

### ISSUE THREAD

**Issue by galdor** [gorilla/mux#295]
It would be nice to have minor versions released for small features and bug fixes. For example, I could really use the fix for #271, but it forces me to abandon my dependency on a stable release  (v1.4.0 from May 31).

**Comment by elithrar** [comment]
I'll tag a new version w/ release notes soon (today)

**Comment by galdor** [comment]
Thank you very much !

**Comment by elithrar** [comment]
https://github.com/gorilla/mux/releases/tag/v1.5.0 done!
