### ISSUE TITLE
License requirements for compiled open source tool

### ISSUE THREAD

**Issue by dustingraham** [gorilla/mux#298]
I'm beginning to work on an open source project that may pull in gorilla/mux.

I'm not sure what that means from my end as far as keeping the copyright in compiled binaries? I think we are expecting to simply compile the app to linux, mac, windows, and provide tagged downloads on github, as well as the github source.

What does that mean we need to do in order to respect the bsd license on gorilla mux?

Thanks.

**Comment by elithrar** [comment]
* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.

Commonly you'll see a LICENSES file or similar that references the licenses
of other projects. Given that the license is included with a source
distribution (by nature of mux being a dependency, or vendored), then I'd
say that this isn't entirely necessary. Anyone who needs to build your
project has a copy of mux w/ its license.


     * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.

Suggestion: a --copyright flag or way of showing the copyright notice +
licenses for all contributing projects. Look at how iOS and Android apps
recognize OSS libraries used for a good example.

**Comment by dustingraham** [comment]
Right.

> Redistributions in binary form must reproduce the above copyright notice

Is specifically what I'm asking about. I suppose that copyright flag idea makes sense. Thanks.
