### ISSUE TITLE
Can you explain performance bottleneck in using context map when processing requests

### ISSUE THREAD

**Issue by vit1251** [gorilla/mux#299]
I think that using context without change contract may be a bottleneck. Could you explain more about mutex and blocking global context variable and may be it a bottleneck in highload solutiuon? Thanks.

**Comment by elithrar** [comment]
The mutex overhead is extremely minimal; some previous benchmarks show how
fast the locking/unlocking is (https://github.com/gorilla/context/pull/10).

Further, mux on Go 1.7+ does not use gorilla/context with a global map.

**Comment by vit1251** [comment]
Sorry for duplicate question.
