### ISSUE TITLE
Optionally Match trailing slash in the URL and HTTP Method based matching

### ISSUE THREAD

**Issue by srinathgs** [gorilla/mux#30]
Lets say we have a URL like

`http://www.hostname/upload/`

Considering that the user types in 

`http://www.hostname/upload` (note no trailing slash)

Possibly we can redirect the user from the no-slash one to the slashed one by registering different handlers.`StrictSlash` does this. But is there a way to match both of them?

we use mux like this

```
package main
import (
       "fmt"
       "github.com/gorilla/mux"
       "net/http"
)
func uploadHandler(w http.ResponseWriter, r * Request){
        fmt.Fprintf(w,"Upload page")
}

func main(){
    routes := mux.NewRouter()
    routes.HandleFunc("/upload",uploadHandler) //this doesnot match the trailing slash case
    http.Handle("/",routes)
    http.ListenAndServe("0.0.0.0:8081",nil)
}
```

How do we write the matching condition so that it accepts both `http://www.hostname/upload/` and `http://www.hostname/upload` ?

Another question. How do we execute different handlers based on the request method?

e.g., the `GET` request to upload can be handled by different handler and `POST` can be handled by another function.

I already know that we can check request.Method in the handler and do different things accordingly. But is there a way to do such HTTP method based matching?

**Comment by tnine** [comment]
+1 to the question from @fbjork.  I also want to have this behavior

**Comment by ItsLeeOwen** [comment]
This is working on GET requests, but not POST

**Comment by m90** [comment]
FWIW, you can do this using patterns:

```
m.Handle("{route:route\\/?}", handler)
```

will handle `/route` as well as `/route/`

**Comment by babolivier** [comment]
> FWIW, you can do this using patterns:
> ```
> m.Handle("/{route:route\\/?}", handler)
> ```
> will handle `/route` as well as `/route/`

Is there a way to do this when the last part in your path is a variable, for example, if I want the same route to match for `/{var}` and `/{var}/`? Or does it necessary lead to code duplication?

**Comment by elithrar** [comment]
Does the trailing slash need to be in the regular expression?

If it absolutely must, use an optional non-capturing group to indicate it
as optional only.

**Comment by babolivier** [comment]
How would you do that in my case? Sorry for asking, I might not be familiar enough with the groups' syntax.

**Comment by elithrar** [comment]
e.g.

```
"/{route:route(?:\\/)?}"
```

```sh
➜  ~ curl http://localhost:8080/route
Hello
➜  ~ curl http://localhost:8080/route/
Hello
```

If that doesn't make sense, provide an example of what you think the duplicate is.

**Comment by babolivier** [comment]
My use case is that the last part of the root path is a variable, while your example shows the case of a static last part. I'd like the route to match both `/{myVar}` and `/{myVar}/` but without capturing the trailing slash in the `myVar` variable.

**Comment by m90** [comment]
The second part of the pattern is not really static, it's a regular expression (`route` is a very strict one). Consider the following example:

```go
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	m := mux.NewRouter()
	m.HandleFunc("/things/{id:[0-9](?:\\/)?}", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("match"))
	})
	log.Fatal(http.ListenAndServe(":1337", m))
}
```

This will match `/things/9` just like `/things/7/`

**Comment by babolivier** [comment]
I understand that (sorry for not being specific enough between static/strict regular expression). However, a regular expression isn't declared the same way a variable is in a route. eg:

```
m.HandleFunc("/things/{thing:[a-z]}", handler)
```

isn't, from what I understand, the same as

```
m.HandleFunc("/things/{thing}", handler)
```

my case is the second one. Sorry if I'm not clear enough.

I perfectly understand how to do it with a regular expression, but not how to do it with just the variable name.

**Comment by PierBover** [comment]
Wouldn't it be simpler to just have a parameter to ignore trailing slashes?

**Comment by benyanke** [comment]
Any updates on this one? This seems like prime real estate for a simple parameter.

**Comment by elithrar** [comment]
What would that parameter look like?

Each new parameter we add is more API surface for users to learn and understand.

This can be achieved via existing pattern support here: https://github.com/gorilla/mux/issues/30#issuecomment-321045004

**Comment by tfbirk** [comment]
> FWIW, you can do this using patterns:
> 
> ```
> m.Handle("/{route:route\\/?}", handler)
> ```
> 
> will handle `/route` as well as `/route/`

Ran into this issue. This solution is great and so underrated! Lots of other blog solution recommend middleware to handle the trailing slash without a redirect (from using `StrictSlash(true)`). This simple regex pattern solves the problem without middleware.

**Comment by samifouad** [comment]
> What would that parameter look like?
> 
> Each new parameter we add is more API surface for users to learn and understand.
> 
> This can be achieved via existing pattern support here: [#30 (comment)](https://github.com/gorilla/mux/issues/30#issuecomment-321045004)

I honestly think treating the trailing slash as optional should be the default behaviour. And indicating you want to treat the route with a trailing slash different I feel is the much less common use case, and that should be what needs to be turned on. But, if the plan/ideal goal is to stick with current behaviour, what about something like this:
	
	r := mux.NewRouter()
	
	// default = false
	r.TrailingSlash(true)

**Comment by rubenvannieuwpoort** [comment]
If you want `api/hello` to behave the same as `api/hello/` you can insert a bogus variable that matches the trailing slash:
```
m.HandleFunc("/api/{message:[a-z]*}{trailingslash:\\/?}", apiHandler)
```
Both routes will now call the apiHandler with `message` set to `"hello"`.

**Comment by mcgtrt** [comment]
I think I found a solution to the issue with the trailing slash.

Trailing slash is the most annoying thing when the request method is different than `"GET"`.

Instead of writing any complex solutions or the inelegant way of multiplying the `r.HandlerFunc` routes for `"/path"` and `"/path/"`, a middleware might come useful:

```
func routingMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		url := *r.URL
		url.Path = strings.TrimSuffix(r.URL.Path, "/")
		r.URL = &url

		h.ServeHTTP(w, r)
	})
}
```

And whenever your `mux.Router` is do this:

```
r := mux.NewRouter()
r.Use(routingMiddleware)
```

Hope it helps!

**Comment by wakaztahir** [comment]
I can't make this function work, How do I make the trailing slash optional in this

func servePublicFolder() {
	fs := http.FileServer(http.Dir("public"))
	router.PathPrefix("/").Handler(fs)
}
