### ISSUE TITLE
Vars not found

### ISSUE THREAD

**Issue by oytunistrator** [gorilla/mux#305]
`../evaluator/builtins.go:319:37: mux.Vars undefined (type *mux.Router has no field or method Vars)`

**Comment by elithrar** [comment]
.Vars is defined as a package-level function, not a method on *Router. Are
you also calling your Router “mux” and thus shadowing the import?

**Comment by oytunistrator** [comment]
Yes. I already imported. And go get success.

My other test code same;
```
import (
   "http"
   "github.com/gorilla/mux"
)

func TestHandler(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "Test Parameter: %v\n", vars["name"])
}

func main(){
      r := mux.NewRouter()
      r.HandleFunc("/hello/{key}", TestHandler)
      srv := &http.Server{
		Handler:      r,
		Addr:         "127.0.0.1:8000",
		WriteTimeout: 15 * time.Second,
		ReadTimeout:  15 * time.Second,
	}

	log.Fatal(srv.ListenAndServe())
}
```

Same error:  `mux.Vars undefined (type *mux.Router has no field or method Vars)`

**Comment by elithrar** [comment]
Is this your exact code? There is no “http” package, only “net/http”.

The code you posted would not generate this error. Can you post the code &
the full error, including the line number?

**Comment by kisielk** [comment]
Please reopen with a real example if you're still having the problem.
