### ISSUE TITLE
Can't create "root" route on a subrouter

### ISSUE THREAD

**Issue by jagregory** [gorilla/mux#31]
``` go
r := mux.NewRouter()
sr := r.PathPrefix("/foo")
sr.Path("/").HandlerFunc(...)

// GET /foo/ -> OK
// GET /foo -> 404 Not Found
```

I can't find a way to get the second request to work. I thought `StrictSlash` might help, but it doesn't. Any suggestions?

**Comment by anacrolix** [comment]
Is there any update on this?

I have the situation where I want to handle just the path prefix for a subrouter, but I can't unless there's a trailing /. I think that's the same as this issue.
```
s := r.PathPrefix("/path")
s.Handle("", handler) // Here I want to set the handler for "/path" alone.
```

**Comment by corey-garvin** [comment]
Having a similar issue.  
Router with strictslash = true, and seems to properly propagate to subrouter
However, the path "/" on the sub redirects OK, but POSTs are being redirected to GET, which is bad

Is this a known issue?

**Comment by kisielk** [comment]
@corey-garvin can you provide a runnable code example that demonstrates?

**Comment by victorcoder** [comment]
Getting the same behaviour.

As a workaround I'm declaring the root path for the prefix outside the subrouter, and the subrouter with the path prefix for the other routes just after, like:

```
r.Path("/v1").HandlerFunc(a.indexHandler)
subver := r.PathPrefix("/v1").Subrouter()
```

**Comment by krak3n** [comment]
This is the best solution I can come up with to get the desired behaviour:

``` go
r := mux.NewRouter()

r.HandleFunc("/a", func(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("/a"))
})

s := r.PathPrefix("/a").Subrouter()

s.HandleFunc("/a", func(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("/a/foo"))
})
```

```
GET /a       => 200
GET /a/      => 404
GET /a/foo   => 200
```

**Comment by smaxwellstewart** [comment]
I need a fix for this as well!

**Comment by fvosberg** [comment]
I have the same problem and wanted to start writing some tests, because I am quite new to go. 

Can somebody check my commit before I start to implement this?

Thanks in advance

https://github.com/fvosberg/mux/commit/24794edfcc6d48816df40f958cd5e3bc186caea5

**Comment by kisielk** [comment]
Hi @fvosberg , I left a comment on your commit.

**Comment by elithrar** [comment]
See https://github.com/gorilla/mux/issues/215

**Comment by ORESoftware** [comment]
was there a fix for this?

**Comment by IvanDelsinne** [comment]
As far as I see it (#215), it seems to impose using an empty string to avoid the trailing slash, which kind of makes sense
