### ISSUE TITLE
Exclude path prefix

### ISSUE THREAD

**Issue by sinnlosername** [gorilla/mux#310]
Hello.

Could you implement a feature to exclude a specific path prefix? Currently I solved it with a custom matcher function, but it would be nice if you could implement it, so it's less code. :)

**Comment by kisielk** [comment]
I don't think it's necessary to extend the API to do this. One way it could be achieved is with a top-level handler that matches the path prefix and does whatever you need with it there, otherwise passes the handling to the mux.
