### ISSUE TITLE
Path - string length expression is not working

### ISSUE THREAD

**Issue by x1unix** [gorilla/mux#316]
Given route path (`/api/menu/20171121/dishes`) is not working:
```
"/api/menu/{date:[0-9]{8}+}/dishes"
```

`[0-9]{8}+` is a valid PCRE expression

Also, I've tested on [Regex101](https://regex101.com/) this regex (in Golang mode) - `[0-9]{8}$`, but it's also ignored by Mux.

**Comment by elithrar** [comment]
Go uses RE2 regular expressions, not PCRE.

You’ll find that {8}+ is not a valid quantifier:
https://regex101.com/r/GMwvYP/1

**Comment by CarsonSlovoka** [comment]
try

> "/api/menu/{date:(?:[0-9]{8})}/dishes"
