### ISSUE TITLE
How to pass of the filled structure inside to the handler?

### ISSUE THREAD

**Issue by sttyru** [gorilla/mux#319]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.8.3 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
bb285ea687c5c77bb6935fdb2402b121d8efcbec

**Describe your problem** (and what you have tried so far)
Hello! I want to migrate of my makeshift source code from `julienschmidt/httprouter` to `mux` and I need of the little help. How I can to passing a filled structure to inside to a handler? At `julienschmidt/httprouter` code was look like:
```
package main
import (
	"context"
	"fmt"
	"net/http"
	"github.com/julienschmidt/httprouter"
)
func main() {
	r := httprouter.New()
	index := settingsMiddleware(http.HandlerFunc(getIndex))
	r.GET("/index", wrapHandler(index))
	http.ListenAndServe(":8080", r)
}
func wrapHandler(h http.Handler) httprouter.Handle {
	return func(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
		// Take the context out from the request
		ctx := r.Context()
		ctx = context.WithValue(ctx, "params", ps)
		r = r.WithContext(ctx)
		h.ServeHTTP(w, r)
	}
}
func settingsMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var s = "/var/bin"
		ctx := r.Context()
		ctx = context.WithValue(ctx, "settings", s)
		r = r.WithContext(ctx)
		h.ServeHTTP(w, r)
	})
}
func getIndex(w http.ResponseWriter, r *http.Request) {
	s, ok := r.Context().Value("settings").(string)
	if !ok {
		fmt.Println("s is not type string")
	}
	fmt.Println(s) // "/var/bin"
}
```
__I'm sorry for excess source code.__

How I can to  create of the something similar? 

Thank you!

**Comment by elithrar** [comment]
You’ll want to change 

* `func wrapHandler(h http.Handler) httprouter.Handle` to return `http.Handler` instead, and use `mux.Vars(r)` to fetch params.
* create a new router via `mux.Router()`
* use (e.g) `Handle(“/“, yourFunc).Methods(“GET”)` in place of your GET methods on the httprouter instance

**Comment by elithrar** [comment]
(Let me know if any more questions; traveling but wanted to get you started)

**Comment by sttyru** [comment]
Thank you! But at now I can't to find an solution :(
If it's not too much trouble, can you to write a short example?
/ I can't to rewrite an wrapHandler by your recommends./

**Comment by elithrar** [comment]
Can you show me what you’ve tried so far?

**Comment by elithrar** [comment]
Timing out. Please re-open if you have further questions!

**Comment by mengdodo** [comment]
func Authenticate(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		ctx := context.WithValue(r.Context(), "userId", 1)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
