### ISSUE TITLE
"Listing Routes" example does not work: mux: route doesn't have queries

### ISSUE THREAD

**Issue by armhold** [gorilla/mux#323]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.9.2 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

`5ab525f4fb1678e197ae59401e9050fa0b6cb5fd`

**Describe your problem** (and what you have tried so far)

The example given for [Listing Routes](https://github.com/gorilla/mux#listing-routes) on the main project page does not work. Rather than listing routes, it prints nothing. If err is checked from r.Walk(), we get `mux: route doesn't have queries`. This is a somewhat unfriendly documentation experience for new users.

I'm new to mux, so this is maybe a naive suggestion, but why not simply return a 0-length slice from GetQueriesTemplates() rather than returning an error?

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```
package main

import (
    "fmt"
    "net/http"
    "strings"

    "github.com/gorilla/mux"
)

func handler(w http.ResponseWriter, r *http.Request) {
    return
}

func main() {
    r := mux.NewRouter()
    r.HandleFunc("/", handler)
    r.HandleFunc("/products", handler).Methods("POST")
    r.HandleFunc("/articles", handler).Methods("GET")
    r.HandleFunc("/articles/{id}", handler).Methods("GET", "PUT")
    r.HandleFunc("/authors", handler).Queries("surname", "{surname}")
    err := r.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
        t, err := route.GetPathTemplate()
        if err != nil {
            return err
        }
        qt, err := route.GetQueriesTemplates()
        if err != nil {
            return err
        }
        // p will contain regular expression is compatible with regular expression in Perl, Python, and other languages.
        // for instance the regular expression for path '/articles/{id}' will be '^/articles/(?P<v0>[^/]+)$'
        p, err := route.GetPathRegexp()
        if err != nil {
            return err
        }
        // qr will contain a list of regular expressions with the same semantics as GetPathRegexp,
        // just applied to the Queries pairs instead, e.g., 'Queries("surname", "{surname}") will return
        // {"^surname=(?P<v0>.*)$}. Where each combined query pair will have an entry in the list.
        qr, err := route.GetQueriesRegexp()
        if err != nil {
            return err
        }
        m, err := route.GetMethods()
        if err != nil {
            return err
        }
        fmt.Println(strings.Join(m, ","), strings.Join(qt, ","), strings.Join(qr, ","), t, p)
        return nil
    })

    if err != nil {
       fmt.Println(err)
    }

    http.Handle("/", r)
}
```

Thanks for your attention.

**Comment by elithrar** [comment]
Good catch. An empty slice vs. error is debatable; the error makes it clear, and the code to handle a nil slice vs. an explicit error is about the same.

I'll make a plan to update the docs to include a route with a query-string.

**Comment by armhold** [comment]
Thanks!
