### ISSUE TITLE
reference error when attempting to run get or test

### ISSUE THREAD

**Issue by ScottHale** [gorilla/mux#324]
**What version of Go are you running?** (Paste the output of `go version`)
go version xgcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
5ab525f4fb1678e197ae59401e9050fa0b6cb5fd

**Describe your problem** (and what you have tried so far)
I am new to go, but when I attempt to run 'go get' or 'go test' I get the following error. I am not sure how to proceed any help you can provide would  be appreciated.

```
bitnami@ip:~/gocode/src/github.com/gorilla/mux$ go get
# github.com/gorilla/mux
./mux.go:114:18: error: reference to undefined field or method ‘EscapedPath’
    path = req.URL.EscapedPath()
                  ^
./regexp.go:165:18: error: reference to undefined field or method ‘EscapedPath’
    path = req.URL.EscapedPath()
                  ^
./regexp.go:275:17: error: reference to undefined field or method ‘EscapedPath’
   path = req.URL.EscapedPath()
                 ^
**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
```

**Comment by elithrar** [comment]
You're running a version of Go older than 1.5 - which was when `URL.EscapedPath` was introduced. Go 1.5 was released in August 2015 (https://blog.golang.org/go1.5) and is no longer supported.

I'd recommend uninstalling your system-provided Go and installing an up-to-date version via https://golang.org/doc/install

**Comment by ScottHale** [comment]
Thanks for the help! It worked perfectly.
