### ISSUE TITLE
mux.Vars empty

### ISSUE THREAD

**Issue by alexellis** [gorilla/mux#325]
I'm really not sure what is happening here, but mux.Vars is empty in some projects and not others. It's not in my GOPATH, just in the vendor directory and I've also tried cloning the master version of your code. Let me know if I can help with additional info on the issue. 

**What version of Go are you running?** (Paste the output of `go version`)

go version go1.9.2 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

b9f261986a88ce62bbca20af2ff2dcf1d46a8df8

**Describe your problem** (and what you have tried so far)

Never get vars populated in the mux

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

This works fine in other projects but not in a new one I am starting.

https://github.com/openfaas/faas-provider/blob/0.4/serve.go#L29

Always empty:

https://github.com/openfaas/faas-swarm/blob/master/handlers/proxy.go#L57

Always works:

https://github.com/openfaas/faas-netes/blob/master/handlers/proxy.go#L47

Edit: I have looked at old issues. These didn't help resolve any issues.

**Comment by kisielk** [comment]
Where do you set up the routes in faas-swarm, where it doesn't work?

**Comment by elithrar** [comment]
Also - b9f261986a88ce62bbca20af2ff2dcf1d46a8df8 - is not a valid commit ID
within the mux repository.

Can you make sure:

1. You're on master
2. You have done a `go get -u github.com/gorilla/mux` or a `git pull`
3. That you end up on the commit ID below:

$ git rev-parse HEAD
5ab525f4fb1678e197ae59401e9050fa0b6cb5fd

**Comment by alexellis** [comment]
It's the function route (linked in the source) the vars are completely empty.

**Comment by kisielk** [comment]
I understand that, but where is the code that attaches that function to the router?

**Comment by alexellis** [comment]
It's linked above... I.e. here https://github.com/openfaas/faas-provider/blob/0.4/serve.go#L29

**Comment by kisielk** [comment]
I'm not really clear on how that ends up calling the result of `FunctionProxy`, it's a lot of indirection to follow and I'm not familiar with your codebase. Maybe you can reduces this to a more minimal reproducer?

**Comment by alexellis** [comment]
faas-provider sets up the mux etc... with a struct passed in with all the handlers we want. That means whoever wants to implement the "FaaS" interface only needs to setup a config struct and call Serve.

Here is where each route is setup up

https://github.com/openfaas/faas-provider/blob/0.4/serve.go#L32

Here is where client code sets up its handler for FunctionProxy:

 https://github.com/openfaas/faas-netes/blob/master/server.go#L49

Here Serve is called

https://github.com/openfaas/faas-netes/blob/master/server.go#L66


Summary:

faas-provider exists to bind a set up handlers to pre-defined routes
faas-swarm or faas-netes only have to provide handlers in a struct and call Serve - nothing more or less. The faas-netes one works perfectly and faas-swarm (new) fails to show mux.Vars as anything but empty.

**Comment by elithrar** [comment]
@alexellis - did you manage to resolve this, or still seeing issues?

**Comment by alexellis** [comment]
I am not sure what caused this but I suspect it may be related to the `dep` vendoring tool for `go` adding an old mux version somewhere in the vendor hierarchy.

**Comment by elithrar** [comment]
Ah - glad you managed to get it sorted!

**Comment by deviantony** [comment]
FYI just hitted the same problem when leveraging `gorilla/mux` inside a library using `dep` to vendor it.

I then tried to use that library in another project and had the same problematic behavior. Removing the vendor folder of the library fixed the issue.

Not sure about the root cause here.
