### ISSUE TITLE
Proposal: Drop Support for Go < 1.7 as of Go 1.10

### ISSUE THREAD

**Issue by elithrar** [gorilla/mux#326]
**Summary**: Dropping Go < 1.7 will allow us to remove the shim for `gorilla/context`, simplifying the codebase and making ongoing maintenance easier.

* The aim of those proposal is to gather potential feedback and signal to users the intent for change
* Go 1.10 is scheduled for release in Feb 2018 - https://tip.golang.org/doc/go1.10
* I suspect a not-insignificant number of users are likely on Go 1.6 (Ubuntu 16.04 LTS default)

**Comment by kisielk** [comment]
I wish there was some way to tell how many people are still compiling with old Go versions

**Comment by roobre** [comment]
If Ubuntu LTS users are a concern, maybe we can wait to the release of 18.04, which is scheduled for April iirc.

**Comment by elithrar** [comment]
I think that’s what we’ll likely do. Once dep is in the official toolchain
we can also break out a v2.0 🌟

**Comment by elithrar** [comment]
I'm planning on doing this before the end of June.

**Comment by elithrar** [comment]
See #391
