### ISSUE TITLE
Feature request: custom StrictSlash redirect Handler

### ISSUE THREAD

**Issue by a-tal** [gorilla/mux#327]
It would be really nice if we could supply our own Handler for strict slash redirects.

https://github.com/gorilla/mux/blob/5ab525f4fb1678e197ae59401e9050fa0b6cb5fd/regexp.go#L293

**Comment by elithrar** [comment]
Do you have an example of what your custom handler would do here?

**Comment by a-tal** [comment]
send a metric, for one

**Comment by kisielk** [comment]
It's possible, not sure how much actual demand there is to maintain a feature like that.

Can't you get this by wrapping Mux and then inspecting the `Header` field of the `ResponseWriter` ?

**Comment by elithrar** [comment]
Going to suggest that application-level middleware + context may be a better approach here.
