### ISSUE TITLE
SetURLVars accepts *http.Handler and returns *http.Handler

### ISSUE THREAD

**Issue by fharding1** [gorilla/mux#334]
**What version of Go are you running?** (Paste the output of `go version`)
`go version go1.9.2 linux/amd64`

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
`5ab525f4fb1678e197ae59401e9050fa0b6cb5fd`

**Describe your problem** (and what you have tried so far)
SetURLVars returns an *http.Handler and accepts an *http.Handler. It is idiomatic if you are going to accept a pointer, you should modify, and if you really do want to pass by value instead of reference, you should use http.Handler, not *http.Handler.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"github.com/gorilla/mux"
)

func main() {
	req, _ := http.NewRequest("GET", "/bla", nil)
	rr := httptest.NewRecorder()

	printVars := func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(mux.Vars(r))
	}

	mux.SetURLVars(req, map[string]string{"test": "hello"})
	printVars(rr, req)

	// mux.SetURLVars(*req, map[string]string{"test": "hello"}) does not compile
	// printVars(rr, req)

	req = mux.SetURLVars(req, map[string]string{"test": "hello"})
	printVars(rr, req)

}
```

I would be more than happy to create a PR correcting this.

**Comment by garyburd** [comment]
The function mux.SetURLVars returns a shallow copy of the argument.

**Comment by fharding1** [comment]
Thanks for the quick response! In this circumstance if you are returning a modified shallow copy, what are the advantages of not just passing by value and modifying that? And even if you weren't, and actually modifying the http.Handler by pointer, what would be the point of returning the pointer again?

**Comment by elithrar** [comment]
To be clear, it accepts (and returns) a `*http.Request`, not a `*http.Handler` (which would be a pointer to an interface): rarely useful.

Returning the pointer is a common pattern to allow method chaining. You can ignore the returned variable, but you could also call `mux.SetURLVars(r, vars).AddCookie(cookie)`.

**Comment by garyburd** [comment]
The function argument and return type are *http.Request, not *http.Handler.

The mux.SetURLVars function creates the shallow copy by calling [Request.WithContext](https://godoc.org/net/http#Request.WithContext).

**Comment by fharding1** [comment]
My bad, meant and was thinking of `*http.Request`, just a typo.

@elithrar You cannot ignore the returned variable from mux.SetURLVars I don't think, otherwise it will not work as seen in my example. 

@garyburd hmm did not see that, might make it harder to do what I suggested then.

**Comment by kisielk** [comment]
The only thing that needs to change is the documentation has to be updated to indicate that it returns a copy of the request with the variables changed. An example should also be added to show how to use it. The function shouldn't modify its argument, that's by design.

**Comment by fharding1** [comment]
@kisielk okay, I still think that maybe if you aren't modifying it's argument you shouldn't use a pointer, but I understand you may not want to do that because http.Request is fairly large and for method chaining. If you want me to create a PR to update the docs, I'd be glad to.

**Comment by kisielk** [comment]
You should stop thinking that way, because that doesn't generally hold true in Go. For example nowhere in the `net/http` package is `Request` used, it's always `*Request`. I doubt you'd find code anywhere that passes it by value.

A PR for the docs would be appreciated.

**Comment by fharding1** [comment]
I think in that case it's because `Request` is such a large struct, but in most cases I'm pretty sure using a pointer receiver on a method (or passing a pointer in a function) that just reads is not idiomatic. One reason why is safety, see [this example](https://play.golang.com/p/AskglO7wjCH) and also clarity, you can just look at a function param or pointer receiver and see if any modification is going to be done. I do understand the +'s of using pointers though.

Will get to work on it! 🎉 yay OSS!

**Comment by kisielk** [comment]
I'm well aware of the differences (I've been programming go since before 1.0). This is actually covered in the Go FAQ: https://golang.org/doc/faq#methods_on_values_or_pointers

> Next is consistency. If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used.

There are other reasons as well. For example if a type contains a mutex or other kind of lock, you should never pass it by value because you will be copying the lock and that can lead to very bad things happening.

**Comment by fharding1** [comment]
Hmm, thanks for that link, didn't know that was recommended by the Go FAQ. Seems weird to me since you can use non-pointer receiver methods on pointers anyways, but I guess the uniformity makes sense. Also a good point about locks.
