### ISSUE TITLE
Avoid common memory leaks by explaining context.clearHandler in README

### ISSUE THREAD

**Issue by xolan** [gorilla/mux#343]
**What version of Go are you running?** (Paste the output of `go version`)
`go version go1.9.2 linux/amd64`

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
`d69df51eb5c73477cf01e81493b3750333f151d1`

**Describe your problem** (and what you have tried so far)
Context is by default not cleared after responses are given. This is probably fine, but it's not documented well enough (in my opinion). I was having apparent memory leaks, which I solved by using `context.ClearHandler`.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
Leaking memory:
```
log.Fatal(http.ListenAndServe("0.0.0.0:8000", handlers.RecoveryHandler()(loggedRouter)))
```

Fixed:
```
log.Fatal(http.ListenAndServe("0.0.0.0:8000", context.ClearHandler(handlers.RecoveryHandler()(loggedRouter))))
```

**Comment by xolan** [comment]
One or more examples in README should reflect this user (dev) responsibility.

**Comment by elithrar** [comment]
Note that mux does not use the global gorilla/context from Go 1.7 onwards,
so context.ClearHandler is a no-op under those conditions.

mux, by default, calls clearContext internally for versions of Go < 1.7.

**Comment by elithrar** [comment]
I'd suggest snapshotting your heap and goroutine profiles and seeing what's allocating or leaking. Useful resource if you're not familiar: https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/ @xolan

**Comment by xolan** [comment]
Thank for that! Turns out it was a third party library having trouble flushing messages.

Went from ~2GB while stress testing to ~40MB. :+1:
