### ISSUE TITLE
Form values in a slice

### ISSUE THREAD

**Issue by happilymarrieddad** [gorilla/mux#347]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.9.4 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
☁  mux [master] git rev-parse HEAD
c0091a029979286890368b4c7b301261e448e242
☁  mux [master] 

**Describe your problem** (and what you have tried so far)
I've been trying to get form values when using npm axios and the values send just fine but they are always inside a slice.. it's really weird. I have to do length checks on the form value and then grab [0]. It feels like I'm doing something wrong.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
![selection_017](https://user-images.githubusercontent.com/6416323/36398458-775e5ede-1584-11e8-8c65-28920194ffe8.png)

Server
```
package main

import (
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"log"
	"net/http"
	"os"
	"time"
)

const (
	DefaultWriteTimeout = 15 * time.Second
	DefaultReadTimeout  = 15 * time.Second
)

func SessionStore(w http.ResponseWriter, r *http.Request) {
	r.ParseForm()

	log.Println(r.Form)
	log.Println(r.PostForm)

	w.Write([]byte("TEST"))
}

func main() {
	port := "8001"
	r := mux.NewRouter().StrictSlash(true)

	r.HandleFunc("/session/store", SessionStore).Methods("POST")

	handler := handlers.LoggingHandler(os.Stdout, r)

	newServer := &http.Server{
		Handler:      handler,
		Addr:         "0.0.0.0:" + port,
		WriteTimeout: DefaultWriteTimeout,
		ReadTimeout:  DefaultReadTimeout,
	}

	log.Println("Starting server on port", port)
	log.Fatal(newServer.ListenAndServe())
}

```

Client
```
axios.post('http://localhost:8001/session/store',qs.stringify({email:"nkotenberg@fusionware.com",password:""}))
```

**Comment by happilymarrieddad** [comment]
Here is an example. It does not feel right.

![selection_018](https://user-images.githubusercontent.com/6416323/36398524-bd5b6e18-1584-11e8-9280-e1d11bfa87ec.png)

**Comment by elithrar** [comment]
This is normal. Keys in a form may not be unique, and so you get a slice of
values.

You can default to checking *only* the first possible instance by using
https://golang.org/pkg/net/http/#Request.FormValue - the docs explain the
behavior here.

**Comment by happilymarrieddad** [comment]
@elithrar oh cool thanks so much man!
