### ISSUE TITLE
Run Custom Middleware together with the Logging Handler

### ISSUE THREAD

**Issue by codehakase** [gorilla/mux#348]
**What version of Go are you running?** (Paste the output of `go version`)
> go version go1.8.3 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
> c0091a029979286890368b4c7b301261e448e242

**Describe your problem** (and what you have tried so far)
I tried using the `gorilla/handlers` middleware together with another custom middleware:

```go
 r := mux.NewRouter()
 log.Printf("Server started at port %v", os.Getenv("PORT"))
 log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), filterMiddleware(r)))

 func filterMiddleware(h http.Handler) http.Handler {
    fn := func(w http.ResponseWriter, r *http.Request) {
    h.ServeHTTP(w, r)
    // do main filter tasks here
    log.Println("filter middleware", r.URL)
 }
 handlers.LoggingHandler(os.Stdout, http.HandlerFunc(fn))
 return http.HandlerFunc(fn)
}
```

Running the program, only hits the `fn` clousure and doesn't call the `handlers.LoggingHandler` function.

What I really want is for both middlewares to run: `filter tasks -> logging`

**Comment by codehakase** [comment]
Middleware channing could be another way out, I want to know if gorilla Mux does it out of the box

**Comment by elithrar** [comment]
https://github.com/gorilla/mux/blob/master/README.md#middleware 😉
