### ISSUE TITLE
Gorilla Session does not work with latest version of App Engine SDK in testing (pinpointed issue to Mux)

### ISSUE THREAD

**Issue by rojakcoder** [gorilla/mux#352]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.8.5 linux/amd64 (App Engine: go version 1.8.5 (appengine-1.9.65) linux/amd64)

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

07ba1fd60e210dc5cc6f86ec25dc9ecc7c95c295

**Describe your problem** (and what you have tried so far)

Gorilla Sessions does not work with the latest version of the App Engine SDK. I pinpointed the issue to the address of the request being the cause.

In mux.go, inside ServeHTTP(), the check for a route match causes the request to be re-created, thus resulting in a different pointer address. Specifically, the lines `req = setVars(req, match.Vars)` and `req = setCurrentRoute(req, match.Route)` change the instance such that a new instance is returned from each of the lines with different pointer addresses.

I think that because of this change, in my middleware (`isauth()`) that checks for the session, the session is not found because it is technically mapped to a different request?

Funny thing is that in an earlier version of the App Engine SDK (go version 1.6.4 (appengine-1.9.57) linux/amd64), the request is not changed (i.e. the request instance has the same pointer address throughout ServeHTTP()). This means that my tests all pass because the session information can be seen by the middleware.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

With this handler:

```Go
func TestAPI(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
    fmt.Fprintf(w, `{"message":"I'm a teapot"}`)
}
```

and this router:

```Go
func makeRouter() *mux.Router {
    r := mux.NewRouter()
    rest := mux.NewRouter().PathPrefix("/api").Subrouter()
    rest.HandleFunc("/test", TestAPI).Methods(http.MethodGet)
    r.PathPrefix("/api").Handler(negroni.New(
        negroni.HandlerFunc(isauth),
        negroni.Wrap(rest),
    ))

    return r
}

var store = sessions.NewCookieStore([]byte("CHANGEME"))

func isauth(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
    session, err := store.Get(r, "sesslogin")
    if err != nil {
        w.WriteHeader(http.StatusInternalServerError)
    }
    _, has := session.Values["userid"]
    if !has {
        w.WriteHeader(http.StatusUnauthorized)
        fmt.Fprintf(w, `{"error":"not authorized"}`)
        return
    }
    next(w, r)
}
```
This test code

```Go
func TestTestAPI(t *testing.T) {
    inst, err := aetest.NewInstance(&aetest.Options{})
    if err != nil {
        t.Fatal(err)
    }
    defer inst.Close()

    mux := makeRouter()
    req, err := inst.NewRequest("GET", "/api/test", nil)
    if err != nil {
        t.Fatal(err)
    }
    rec := httptest.NewRecorder()
    uid := "123"
    //log in
    session, err := store.Get(req, "sesslogin")
    if err != nil {
        t.Fatal(err)
    }
    session.Values["userid"] = uid
    if e := session.Save(req, rec); e != nil {
        t.Fatal(e)
    }
    mux.ServeHTTP(rec, req)
    if rec.Code != 200 {
        t.Errorf("expect response code %d; got %d\n%v\n",
            200, rec.Code)
    }
}
```

With Go AppEngine 1.9.65, I get a 401 response instead of 200.

WIth Go AppEngine 1.9.57, I get a 200 response.

**Comment by rojakcoder** [comment]
I corrected some mistakes/omissions in the sample code that I wrote.

After some more investigation, it seems that version 1.9.57 of the SDK (which uses Go 1.6.4) uses `contextSet()` from "context_gorilla.go"

Version 1.9.65 of the SDK (which uses Go 1.8.5) uses `contextSet()` from "context_native.go"

I believe it is the native context that's causing the request to be re-created.

Since only the original request is registered in the Sessions registry, and the re-created requests are treated as different instances by the registry, they don't get the same session value attached to the original one.

I find it odd that I'm the only person encountering this problem.

I'm sure this has to to do the migration of the context package in Go 1.7

**Comment by rojakcoder** [comment]
I just noticed that context_gorilla.go is built for Go 1.6 and before whereas context_native.go is built for Go 1.7 onwards. Given that Gorilla Sessions uses the request in its registry to store the session values, I'm not sure if this is something to be fixed by Mux or Sessions.

**Comment by elithrar** [comment]
Closing as timed out.

For future readers: mixing applications that use the "old" pre Go 1.7 context implementation with `r.Context()` (which shallow clones the request, and thus changes the address) is *not* recommended.
