### ISSUE TITLE
Same path using `path`, `handler` and `methods`

### ISSUE THREAD

**Issue by magicalbanana** [gorilla/mux#357]
**What version of Go are you running?** (Paste the output of `go version`)
```
╰─$ go version
go version go1.10 darwin/amd64
```

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

**Describe your problem** (and what you have tried so far)
Is it possible to have the same path but different handles using `path` and `handler`? It seems I am unable to do this since I'm getting a method not allowed error when trying to make a request on the second path that uses a different method.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```
    // handler ...
    credACLS := handler.CredentialsUSACLSCertificate{}
    handlerBase = handler.Base{
        H: credACLS.Create,
        Opts: &handler.Opts{
            Prometheus: opt.Prometheus,
            Config:     opt.Config,
            DB:         opt.DB,
            FileStore:  opt.FileStore,
            Logger:     opt.Logger,
        },
    }
    h = alice.New(cmw.ContentType("application/json")).Then(handlerBase)
    router.Path("/api/v1/foo").Handler(h).Methods("POST")

    // handler ...
    credACLS = handler.CredentialsUSACLSCertificate{}
    handlerBase = handler.Base{
        H: credACLS.Get,
        Opts: &handler.Opts{
            Prometheus: opt.Prometheus,
            Config:     opt.Config,
            DB:         opt.DB,
            FileStore:  opt.FileStore,
            Logger:     opt.Logger,
        },
    }
    router.Path("/api/v1/foo").Handler(handlerBase).Methods("GET")
```

**Comment by kikihakiem** [comment]
@magicalbanana I have the same scenario (same path, different method and handler), and I also got the same error. What did you do to fix that?
