### ISSUE TITLE
Allow slashes inside variable regexps

### ISSUE THREAD

**Issue by opennota** [gorilla/mux#358]
**What version of Go are you running?**

go1.10 linux/amd64

**What version of gorilla/mux are you at?**

4dbd923b0c9e99ff63ad54b0e9705ff92d3cdb06

**Describe your problem**

`/` inside a variable regexp doesn't work.

**Paste a minimal, runnable, reproduction of your issue below**

https://play.golang.org/p/1gqiL9mvdBL

``` Go
package main

import (
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"net/http/httptest"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.URL.Path)
}

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/{js|js/lib}/{.*}", handler)
	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/js/1.js", nil)
	r.ServeHTTP(w, req)
	req, _ = http.NewRequest("GET", "/js/lib/2.js", nil)
	r.ServeHTTP(w, req)
	req, _ = http.NewRequest("GET", "/js%2Flib/3.js", nil)
	r.ServeHTTP(w, req)
}
```

Out of the three requests only the first one hits the handler.

It would be good if `{js|js/lib}` just worked (or at least panicked in Handle/HandleFunc, as it doesn't do what the programmer might be expecting anyway).

**Comment by elithrar** [comment]
r.HandleFunc("/{path:js|js/lib}/{.*}", handler)

Works for me (note the named route variable) - to workaround your issue in
the short term. I suspect the issue is because multiple unnamed groups are
ambiguous, but need to confirm.

**Comment by opennota** [comment]
Why is this issue closed? It is not fixed.

**Comment by opennota** [comment]
It's somewhat counter-intuitive. The user can't easily figure out that the pattern which doesn't work without a name somehow works if there *is* a name. So yes, a usability issue.

**Comment by elithrar** [comment]
Sure - what is your proposed, non-breaking fix?

Without names to assign to each route variable, you can’t address them in
the mux.Vars(r) map.

We should improve the docs here regardless.

**Comment by opennota** [comment]
Oh. I was under the false impression that one could use a regexp without a name. But the following works:

```
package main

import (
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"net/http/httptest"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.URL.Path)
}

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/{pattern}", handler)
	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/this-doesnt-have-to-match-pattern", nil)
	r.ServeHTTP(w, req)
}
```

So this is at most a documentation issue.
