### ISSUE TITLE
Disable middleware for some api

### ISSUE THREAD

**Issue by okabbas** [gorilla/mux#360]
Hi, I need to deactivate middleware in some api.

For example, I need to disable the auth user registry and use auth for other operations after the registry.

But in mux using r.Use (), all routers require auth operations.
How can I fix this problem ?

**Comment by elithrar** [comment]
https://godoc.org/github.com/gorilla/mux#Router.PathPrefix

* You can use r.PathPrefix(“/prefix”).Subrouter() to create a subrouter that only has specific middleware applied.

* Alternatively, your middleware can take a list of paths to skip.

**Comment by bminer** [comment]
Perhaps this behavior was changed after #431?

**Comment by Vitucho** [comment]
Hi @bminer, allow me to share an approach to tackle a quite similar scenario...

scenario
assuming i got one endpoint for login purposes **"/api/v1/user-login"** (there is no sense to apply a a validation check)
and several endpoints for authenticated operations that requires to check if the client is validated, all of them with the following prefix **"/api/v1/"**, for example "/api/v1/users" (to list all the users)

solution
```
func main() {
	r := mux.NewRouter()
	r.Path("/api/v1/user-login").Handler(http.HandlerFunc(UserLoginHandler))   // /api/v1/user-login will be NOT intercepted by ValidationMiddleWare
	api := r.PathPrefix("/api/v1").Subrouter()
	api.Use(ValidationMiddleware)
	api.Path("/users").Handler(http.HandlerFunc(UsersHandler)) // api/v1/users will be intercepted by ValidationMiddleWare
	
        ...
```
The trick is to define the fully qualified path "/api/v1/user-login" in the base route `r`, and then use the api `subrouter` for register the endspoints that requires a validation check.

Well, this work OK for me and hope it helps! 
Also if there is some flaw or code smell, please notify me! i would be  thankful!

Greetings
Víctor
