### ISSUE TITLE
The request is not being routed to the correct handler, if multiple query params are passed.

### ISSUE THREAD

**Issue by ashwiniverma** [gorilla/mux#362]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.9.4 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
6bf81362b51652b782c44e0113b246354f2ad4c7

**Describe your problem** (and what you have tried so far)
The request is not being routed to the correct handler, if multiple query params are passed.
But strangely if we use only one query param then the request is being directed correctly.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```
r.Handle(`/test/accounts/{id}/status`, hV2).
        Methods(http.MethodGet).
        Queries("foo", "bar", "id", "{id:[0-9]+}").
        HeadersRegexp("Accept", `\bv=2\b`)
```

CURL REQUEST
```
curl --url localhost:8000/test/accounts/abcd123/status?foo=bar&id=42 --get -s --header "profilereferenceid: xyz" --header "Accept: application/json;v=2"
```

Working code below (with only one query param) -

```
r.Handle(`/test/accounts/{id}/status`, hV2).
        Methods(http.MethodGet).
        Queries("foo", "bar").
        HeadersRegexp("Accept", `\bv=2\b`)
```
```
curl --url localhost:8000/test/accounts/abcd123/status?foo=bar --get -s --header "profilereferenceid: xyz" --header "Accept: application/json;v=2"
```

**Comment by elithrar** [comment]
If you use only the `id` query param, does that also work? Can you share a runnable example?

**Comment by ashwiniverma** [comment]
```package main

import (
	"net/http"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.UseEncodedPath()

	r.HandleFunc(`/credit-cards/accounts/recurring-merchants`, YourHandler).
		Methods(http.MethodGet)

	http.ListenAndServe(":8000", r)
}

func YourHandler(w http.ResponseWriter, r *http.Request) {
	v := r.URL.Query()
	a := v.Get("isRecurringOnly")
	b := v.Get("toDate")
	c := v.Get("fromDate")
	println("a ::: ", a)
	println("b ::: ", b)
	println("c ::: ", c)
}

This is the example I am using , curl command - 
curl -i -X GET localhost:8000/credit-cards/accounts/recurring-merchants?isRecurringOnly=true&toDate=true&fromDate=true
Output : 
a :::  true
b :::  
c :::

**Comment by elithrar** [comment]
OK - so note that [`Route.Queries`](https://godoc.org/github.com/gorilla/mux#Route.Queries) requires a match of *all* query parameters. If you have optional query parameters, that logic should belong in your handler.

From the docs:

>  The above route will only match if the URL contains the defined queries values, e.g.: ?foo=bar&id=42. 

If you have cases where only one is applied, you can match on that and then check the other via `v := r.URL.Query()` as you have used in your latest comment.

**Comment by ashwiniverma** [comment]
Sure Matt, I can try that. One more update - I just found that the issue was with the curl command

```curl -v -XGET 'http://localhost:8080/credit-cards/accounts/recurring-merchants?isRecurringOnly=abc&toDate=def&fromDate=ddd'```

Thanks Matt for helping me out, I will implement your suggestion and see how it goes.

**Comment by brunovlucena** [comment]
I have a similar problem. 

The following does not work for me
`
	router.HandleFunc("/search", QueryConfigs).Methods("GET").
		Queries("name", "{name}", "data", "{data}")
`
