### ISSUE TITLE
how to create a custom MethodNotAllowedHandler for a Subrouter with PathPrefix?

### ISSUE THREAD

**Issue by yadkit** [gorilla/mux#365]
What version of Go are you running?
- go version go1.9.2 linux/amd64

What version of gorilla/mux are you at? (Paste the output of git rev-parse HEAD inside $GOPATH/src/github.com/gorilla/mux)
- c0091a029979286890368b4c7b301261e448e242

Describe your problem (and what you have tried so far)
- I am trying to create a custom MethodNotAllowedHandler for a subrouter which is PathPrefix'd with /api but the program panics. It works well with main mux router.

Paste a minimal, runnable, reproduction of your issue below (use backticks to format it)

> func main() {
	mainMux := mux.NewRouter().StrictSlash(true)
	apiMux := mainMux.PathPrefix("/api").Subrouter()

>	apiMux.MethodNotAllowedHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("sorry pal"))
	})
. . .
. . .

Panic Trace:

> 2018/04/18 01:15:56 http: panic serving 127.0.0.1:41674: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc42018c000)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x686860, 0x84a470)
	/usr/local/go/src/runtime/panic.go:491 +0x283
main.main.func2.1(0x8210e0, 0xc42012e2a0, 0xc420135100)
	/home/me/go/src/Site/main.go:50 +0x256
net/http.HandlerFunc.ServeHTTP(0xc4201322a0, 0x8210e0, 0xc42012e2a0, 0xc420135100)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200fa000, 0x8210e0, 0xc42012e2a0, 0xc420135100)
	/home/me/go/src/github.com/gorilla/mux/mux.go:159 +0xed
net/http.serverHandler.ServeHTTP(0xc420084f70, 0x8210e0, 0xc42012e2a0, 0xc420134f00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42018c000, 0x821620, 0xc420128180)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

**Comment by elithrar** [comment]
Can you please show your code (a minimum runnable example), and the panic stack trace?

**Comment by berkantipek** [comment]
@elithrar updated the post.
