### ISSUE TITLE
No vars coming through

### ISSUE THREAD

**Issue by cybercrypt13** [gorilla/mux#367]
**What version of Go are you running?** (Paste the output of `go version`)
1.9.2

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
`18fca31550181693b3a834a15b74b564b3605876`

**Describe your problem** (and what you have tried so far)
I have server running but when I attempt the following:
vars := mux.Vars(r)

I get an empty map and attempting to println(vars) gives me a hex number and no map contents.  My code looks exactly like your examples so confused as to what I might be doing wrong.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
`
func main() {
router := mux.NewRouter()
	router.HandleFunc("/cashdrawer", OpenCash).Methods("GET")
	router.HandleFunc("/zebra", PrintZebra).Methods("GET")

	log.Fatal(http.ListenAndServeTLS(":8001", "cert.pem", "key.pem", router))
}

func PrintZebra(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	st := vars["labels"]
	println(vars)
	println(vars["labels"])
	if strings.TrimLeft(st, " ") == "" {
		var msg resp
		msg.Status = "Failure, no label sent."
		SendResponse(w, msg, 400)
		return
	}
}
`

**Comment by elithrar** [comment]
I don't see any route variables in those routes: neither "/cashdrawer" nor
"/zebra" have a route variable.

If the routes were "/cashdrawer/{labels}" - *then* you would expect to have
a route variable accessible via vars["labels"].

**Comment by elithrar** [comment]
- Mux stores *route* variables - e.g. variables in the path component of
the URI itself - in mux.Vars. Handling and matching on route variables is
what a router like mux is useful for.
- Query parameters aren't handled by mux (or most routers, to be clear) as
they are handled by the built-in r.ParseForm() and r.FormValue helpers on
the *http.Request

Hope that clarifies!

**Comment by cybercrypt13** [comment]
Yeah, I was trying to setup a REST server and might have chosen the wrong package.  Sorry for the confusion.

Glenn

**Comment by elithrar** [comment]
mux can definitely play part of building a RESTful API - e.g.

r.Handle("/products/{id}", UpdateProductHandler).Methods("PUT")
r.Handle("/products/{id}", GetProductHandler).Methods("GET")
r.Handle("/products", CreateProductHandler).Methods("POST")

... is exactly the use-case that mux can help with, by routing based on
path, method and injecting route params (e.g. the "id") into your handler.
