### ISSUE TITLE
How to have a global path prefix with wildcard?

### ISSUE THREAD

**Issue by nserrino** [gorilla/mux#368]
This is a question, not sure how to tag it myself as a question. 

I want to put all of my routes under a global prefix with a wildcard: /prefix/{id} and then have mux subrouters declare subpaths relative to this prefix. 

I am aware of PathPrefix which does not allow for extracting a variable {id} as far as I can tell, as well as making Handlers for individual routes e.g. /prefix/{id}/my-full-route. I have liked using mux subrouters for my various services though. Is there a suggested way to do this?

By the way thanks for everyone's effort on this library, it is really powerful/useful.

**Comment by elithrar** [comment]
Can you show the code you've attempted? You can create a Subrouter with a PathPrefix - e.g.

```go
subrouter := router.PathPrefix("/prefix").Subrouter()
```
