### ISSUE TITLE
Impossible to restart webserver

### ISSUE THREAD

**Issue by Maykonn** [gorilla/mux#372]
**What version of Go are you running?** (Paste the output of `go version`)
1.8

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
ded0c29b24f96f46cf349e6701b099db601cf8ec

**Describe your problem** (and what you have tried so far)
Restart/Compile when any *.go file changed, automatically. I'm using Make file, so I have a command in the makefile: 

```
compile:
	GOOS=linux go build -o ./build/api ./main.go

run: compile
	go run ./main.go

kill:
	killall PROCESS || echo "Process was not running."

restart:
	@make kill
	@make run

watch: restart
	find -name *.go | entr make restart
```

So I just execute on cli the `make watch` command to watch files and restart the server when files change. But not works.

OBS: With no web server code, a simple hello-world code in a main.go file works fine the watcher.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
I need to watch *.go files and then compile and restart the webserver when a file changes.

**Comment by elithrar** [comment]
This won't be specifically related to gorilla/mux, but in an effort to help:

- What does `entr make restart` do?
- Where do you specifically kill the `go` process?
- Have you considered using https://github.com/cespare/reflex ?

**Comment by elithrar** [comment]
(Closing as it's not a mux-related issue, but happy to answer any questions)
