### ISSUE TITLE
Subrouter starting with underscore prefix not registered

### ISSUE THREAD

**Issue by ribice** [gorilla/mux#380]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.10.2 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

c85619274f5d55a67491010f883a91f568b3a9b0

**Describe your problem** (and what you have tried so far)

Routes under a subrouter are not registered if subrouter's pathPrefix starts with `_`

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```go
router := mux.NewRouter().StrictSlash(true)
sr := router.PathPrefix("/_ah").Subrouter()
sr.HandleFunc("/test",handler).Methods("POST)
http.Handle("/", router)
```

POST to /_ah/test returns 404.

**Comment by ribice** [comment]
Alternatively, this works fine:

```go
router := mux.NewRouter().StrictSlash(true)
sr.HandleFunc("/_ah/test",handler).Methods("POST)
http.Handle("/", router)
```

**Comment by ribice** [comment]
For some reason, this does not work:

```go
router := mux.NewRouter().StrictSlash(true)
registerHandler(router)
http.Handle("/", router)

func registerHandler(r *mux.Router){
r.HandleFunc("/_ah/test",handler).Methods("POST)
}
```

**Comment by elithrar** [comment]
Thanks for the report `ribice`. I was able to replicate this. 

Next steps:

- Add a (failing) test - `TestPathPrefix_LeadingCharacters` (test underscores, hyphens, etc. for completeness)
- Investigate why `*Route.addRegexpMatcher` - https://github.com/gorilla/mux/blob/e3702bed27f0d39777b0b37b664b6280e8ef8fbf/route.go#L176 - is failing to either create the match, or why it's not being matched.

I'm tied up right now @ribice, but if you want to take a stab (creating the test would be a good first test) we'd appreciate it.

**Comment by aswinmprabhu** [comment]
Hey, @elithrar 
Has this issue been fixed?
I am new to Golang and was trying to fix this bug. But it seems to be working fine.

**Comment by elithrar** [comment]
@aswinmprabhu Can you show me your "working fine" example?

**Comment by aswinmprabhu** [comment]
@elithrar Its the same one in the original comment.

**Comment by aswinmprabhu** [comment]
@elithrar Is my example right?

**Comment by aswinmprabhu** [comment]
@elithrar Can you please tell me if my example is alright or if I have made some mistake?

**Comment by elithrar** [comment]
I've taken a look and your example works as expected for me. It's been a while since I originally tested, and thus I'm unsure whether my repro was the same.

Adding tests with leading underscores to the test suite did not induce a failure.

@ribice - can you reconfirm this, and include how you're testing from the client side? I'm going to close this out as invalid for now.

**Comment by ribice** [comment]
I confirm that it does work now. Curious which commit fixed it 🤔.

**Comment by coolboi567** [comment]
@ribice No need to worry till it works 😬
