### ISSUE TITLE
getting syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by ajay-aravind** [gorilla/mux#388]
go version go1.10.2 darwin/amd64

git rev-parse HEAD
cb4698366aa625048f3b815af6a0dea8aef9280a

When I tried to run server program which is having just only two paths and a dummy server I am getting below error

 `./server
./server: line 1: syntax error near unexpected token `newline'
./server: line 1: !<arch>'`

Please help me resolve the problem.

**Comment by elithrar** [comment]
Please share your code.

**Comment by elithrar** [comment]
Your package should be `package main` if it has a main() function.

**Comment by ashar111** [comment]
> Please share your code.

im also getting the same error with this code
/var/www/html/index.html: line 1: syntax error near unexpected token `newline'
/var/www/html/index.html: line 1: `<html>'

**Comment by elithrar** [comment]
@ashar111 your error seems unrelated to this package / software.

**Comment by UtkarshSaxenautk** [comment]
package main 

import (
	"net/http"
	"github.com/gorilla/mux"
)
const (
	CONN_HOST = "localhost"
	CONN_PORT = "3030"
)

var GetHandler = http.HandlerFunc ( func(w http.ResponseWriter ,
 r * http.Request){ w.Write([]byte("Hello World"))} )

var PostHandler = http.HandlerFunc ( func(w http.ResponseWriter ,
 r * http.Request){ w.Write([]byte("It is a post request"))} )

var PathHandler = http.HandlerFunc ( func(w http.ResponseWriter , 
r * http.Request){ 
                  vars := mux.Vars(r) 
                  name := vars["name"]  
                 w.Write([]byte("Hi" , name))
                 }
)

func main(){
	router := mux.Router()
	router.Handle("/" , GetHandler).Methods("GET")
	router.Handle("/post" , PostHandler).Methods("POST")
	router.Handler("/hello/{name}" , PathHandler).Methods("GET" , "POST")
	http.ListenAndServe(CONN_HOST + ":" + CONN_PORT)
}


i have error in this program which is : \muxrouter.go:22:50: syntax error: unexpected newline, expecting comma or )
