### ISSUE TITLE
Using Methods(...) with Subrouter() doesn't work

### ISSUE THREAD

**Issue by fstanis** [gorilla/mux#389]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.9.4 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
cb4698366aa625048f3b815af6a0dea8aef9280a

**Describe your problem** (and what you have tried so far)
It seems that creating a Subrouter to filter out methods doesn't work. #300 is possibly related.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
```go
func main() {
	r := mux.NewRouter().Methods("POST").Subrouter()
	r.Path("/test").Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	http.Handle("/", r)
	http.ListenAndServe(":8080", nil)
}
```
Navigating to http://localhost:8080/test returns an empty page.

Compare with:

```go
func main() {
	r := mux.NewRouter()
	r.Methods("POST").Path("/test").Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	http.Handle("/", r)
	http.ListenAndServe(":8080", nil)
}
```

...where it returns 405.

**Comment by elithrar** [comment]
Thanks for the report.

Are you interested in PR’ing a failing test (first), and then we can look
to resolve?

**Comment by fstanis** [comment]
Sure, created a PR for a quick minimal test, seems to failing (as expected).
