### ISSUE TITLE
Middleware does not work because of  subrouter order

### ISSUE THREAD

**Issue by zhyq0826** [gorilla/mux#393]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.10.3 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

ded0c29b24f96f46cf349e6701b099db601cf8ec

**Describe your problem** (and what you have tried so far)

The problem is that middleware does not work because of the subrouter order。

I have some subrouter like this:
```go
func InitRoutes(router *mux.Router) *mux.Router {
	appRouter := router.PathPrefix("/v1/gitlab").Subrouter()
	appRouter.Use(FormatResponseMiddleware)
	appRouter.HandleFunc("/projects", getProjects).Methods("GET")
	return router
}
```

These subrouter will be invoked like this:
```go
	router := mux.NewRouter()
	router = domain.InitRoutes(router)
	router = computer.InitRoutes(router)
	router = service.InitRoutes(router)
	router = consul.InitRoutes(router)
	router = app.InitRoutes(router)
	router = gitlab.InitRoutes(router) 
	router = home.InitRoutes(router)  
	return router
```

The home subrouter is special like this:
```go
func InitRoutes(router *mux.Router) *mux.Router {
	appRouter := router.PathPrefix("/").Subrouter()
	appRouter.HandleFunc("/index", home)
	appRouter.HandleFunc("/", home)
	return router
}

func home(w http.ResponseWriter, r *http.Request) {
	t := template.Must(template.ParseFiles("templates/index.html"))
	t.Execute(w, "hello world")
}
```
If you place gitlab subrouter invoking after home subrouter like this:
```go
	router = home.InitRoutes(router)  
	router = gitlab.InitRoutes(router) 
```
then middleware in gitlab does not work, it seems that the subrouter order have impact on the middleware.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

This is demo https://github.com/zhyq0826/muxdemo

**Comment by elithrar** [comment]
Thanks for the report. I don't have time to look at this in-depth until later this week (at best), so if you're interested in helping fix it, writing:

1. A failing test case (cases)
2. A PR to address that test case

... would be super helpful.

**Comment by zhyq0826** [comment]
I will have a try. It may take more time to fix it. ^_^

**Comment by zhyq0826** [comment]
@elithrar  I have tried to trace this problem today and found that it seems that  #378  has fix it. The reason for this problem is that when in subRouter has not found matched route, then `match.MatchErr = ErrNotFound`，then later in other subRouter，the check : 
```go
if match.MatchErr == nil {
    for i := len(r.middlewares) - 1; i >= 0; i-- {
        match.Handler = r.middlewares[i].Middleware(match.Handler)
    }
}
```
will fail.

**Comment by bestform** [comment]
I am experiencing the same problem. I tried the proposed changes in #378 and they did indeed fix it for me.

**Comment by bestform** [comment]
There is a merged PR in the context of this whole problem. I will try with the changes of #422 and see if this fixes my issue and close it if it does.
