### ISSUE TITLE
Route.name can not be overwritten

### ISSUE THREAD

**Issue by smith-30** [gorilla/mux#394]
**What version of Go are you running?** (Paste the output of `go version`)

```
$ go version
go version go1.10.3 darwin/amd64
```

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

I am using dep, so I will post the contents of Gopkg.lock

```
[[projects]]
  name = "github.com/gorilla/mux"
  packages = ["."]
  revision = "e3702bed27f0d39777b0b37b664b6280e8ef8fbf"
  version = "v1.6.2"
```

**Describe your problem** (and what you have tried so far)

I was not able to rewrite the predefined Route Name later.
The Name method has comments that it can be rewritten, but the actual behavior is different.
https://github.com/gorilla/mux/blob/master/route.go#L139-L151

In this case, which is correct?
 It is better for me to be able to overwrite Route.name.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/test", func(rw http.ResponseWriter, r *http.Request) {}).Name("test")

	// override above route name
	r.GetRoute("test").Name("override")

	r.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		if route.GetName() != "" {
			key := route.GetName()

			// expect `override` but `test`
			fmt.Println(key)

			// output `mux: route already has name "test", can't set "override"`
			fmt.Println(route.GetError())
		}
		return nil
	})

	http.Handle("/", r)
}

```

**Comment by kisielk** [comment]
According to git blame that's been there since the beginning. Since it's been the behaviour for 6 years now I don't think it's worth changing, we should just delete the inaccurate comment.
