### ISSUE TITLE
Mux changes http.Request pointer address - question regarding middleware

### ISSUE THREAD

**Issue by matejkramny** [gorilla/mux#395]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.10.3 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
cb4698366aa625048f3b815af6a0dea8aef9280a

**Describe your problem** (and what you have tried so far)

The address of http.Request between my middleware and gorilla/mux handler seems to change. It does not change between middlewares, only when it gets to gorilla/mux.

I've tried debugging the code but to no avail.. We want our log handler to print the context of the request (such as user ID). The demo program attached (L16) wraps the mux router. It should be able to (at the end of the request) log the value of the context.

The issue is that the `*http.Request` pointer seems to change inside gorilla/mux.

There may be a better way to do this, any help/pointers appreciated!

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```
package main

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	muxRouter := mux.NewRouter()
	muxRouter.KeepContext = true
	muxRouter.HandleFunc("/", testHandler)

	// middleware (can be log handler etc)
	router := func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(wr http.ResponseWriter, r *http.Request) {
			fmt.Printf("middleware req: %p\n", r)
			h.ServeHTTP(wr, r)
		})
	}(muxRouter)

	http.ListenAndServe(":8080", router)
}

func testHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Printf("handler req: %p\n", r)
}
```

**Comment by kisielk** [comment]
You shouldn't rely on the pointer address to identify a request. mux uses `Request.WithContext` internally, which creates a shallow copy of the request.

**Comment by matejkramny** [comment]
Aha, sorry. The reason I'm tracking the addresses is that the `context` package uses them ([here](https://github.com/gorilla/context/blob/master/context.go#L15)) to store context data.
In my effort to find and recover some data from the (logging) middleware it would need to keep the same address.

It makes sense that if mux uses `WithContext`, then the gorilla/context package won't work with it. I will look into removing gorilla/context in favour of the new way.

PS: since `WithContext` is passed down the middleware chain, it won't be possible for any middleware at the top to find something like user ID being stored in middleware that happens afterwards. Is there any good way to do this?

Many thanks!

**Comment by elithrar** [comment]
The best way to “store” values in the request is in the context.Context -
accessed via Request.Context() - which is what WithContext() enables.

**Comment by matejkramny** [comment]
Many thanks
