### ISSUE TITLE
Question about middleware and routing order

### ISSUE THREAD

**Issue by matejkramny** [gorilla/mux#396]
**Describe your problem** (and what you have tried so far)
In the simple middleware example given, the chain of routes doesn't make sense:

```go
r := mux.NewRouter()
r.HandleFunc("/", handler)
r.Use(simpleMw)
```

This implies that if I visit `/`, the router will invoke `handler`. Any routes below the registration of `simpleMw` would invoke `simpleMw` and then subsequent routes.

However what happens is that `simpleMw` is invoked first anyway and then `handler` is invoked.

Is this correct behaviour?

Consider the example below: - only the `/test` handler should be having `simpleMw` in it's "routing stack"

```go
r := mux.NewRouter()
r.HandleFunc("/", handler)
r.Use(simpleMw)
r.HandleFunc("/test", handler)
```

**Comment by kisielk** [comment]
The order of operations doesn’t really matter in this case, the middleware applies to the whole router. If you want middleware only on /test then create a sub router at that path and place the middleware on the sub router.

**Comment by elithrar** [comment]
Closing as answered.
