### ISSUE TITLE
[docs] Improve Documentation for CORSMethodMiddleware

### ISSUE THREAD

**Issue by elithrar** [gorilla/mux#401]
There's been a few issues/questions raised about what the [`CORSMethodMiddleware`](https://godoc.org/github.com/gorilla/mux#CORSMethodMiddleware) does, and does not, do.

We should make it clearer that it:

* Automates generation of the `Access-Control-Allow-Methods` response header
* Requires addition of an `OPTIONS` method, or your own CORS middleware, for allowing origins or specific headers (ACAO, ACAH)
* Direct users to https://github.com/rs/cors or https://github.com/gorilla/handlers for the other pieces.
* Add an example to the documentation that lays out the requirements.

(Accepting PRs for this!)

**Comment by fharding1** [comment]
I added https://godoc.org/github.com/gorilla/mux#CORSMethodMiddleware and it's my bad that there isn't enough documentation. As such, I'm happy to take this issue on, if it's still wanted.
