### ISSUE TITLE
mux.Host("{domain}") ignored remote, but works locally

### ISSUE THREAD

**Issue by olliephillips** [gorilla/mux#404]
**What version of Go are you running?** (Paste the output of `go version`)

`go version go1.10 darwin/amd64`

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

`9e1f5955c0d22b55d9e20d6faa28589f83b2faca`

**Describe your problem** (and what you have tried so far)

Using `mux.Host` as a subrouter, I see different behavour running locally than on remote server. 

```
// router
mux.Host("{domain}").PathPrefix("/").HandlerFunc(SiteHandler).Methods("GET")

// SiteHandler function
func SiteHandler(w http.ResponseWriter, r *http.Request) {
  vars := mux.Vars(r)
  domain := vars["domain"] 
}
```
Locally the correct handler is called, and domain variable is initialised with the correct domain of the site being called.

Remotely (on Ubuntu 18.04), the expected handler is not called but instead the NotFoundHandler is called.

If I remove the subrouter the correct handler is called, but obviously I can't access `vars["domain']`. I can see the domain via `r.Host` however.

Locally, the subrouter works and with localhost and other hostnames set in `etc/hosts`

**Comment by elithrar** [comment]
Can you share:

1. how you are testing this from the client?

2. how your program runs locally vs. on the server? Reverse proxy? Etc.

**Comment by olliephillips** [comment]
Hello yes:
1) I'm testing local and server from the browser. There's a domain pointing at the server, and locally I'm using localhost and a domain configured in `/etc/hosts`  
2) There is no difference in terms of how they run, aside for the fact binary is cross compiled for Ubuntu before I transfer it to the server. I am running as a service, but I've also tested by running the binary directly.

**Comment by kisielk** [comment]
It would help if you provide a full log of the requests before they hit mux. You can wrap it in another handler which does the logging.

**Comment by elithrar** [comment]
To expand on this, the logs should log r.Host directly, as well as
r.URL.String()

e.g.

logger := func(next http.Handler) http.Hander {
    return http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {
        log.Printf("url=%s host=%s method=%s", r.URL.String(), r.Host,
r.Method)
       next.ServeHTTP(w, r)
    }
}

http.ListenAndServe(addr, logger(r)) // where "r" is a *mux.Router

**Comment by olliephillips** [comment]
Thanks, I had it, but was going to dump the entire request object.

Below just output requested:

Local:
`url=/ host=localhost:8081 method=GET`

Remote:
`url=/ host=fly2buy.co.uk:8081 method=GET`

**Comment by elithrar** [comment]
Passing test case:

```go
		{
			title:        "Host route with pattern (only)",
			route:        new(Route).Host("{domain}"),
			request:      newRequest("GET", "http://localhost:8081/"),
			vars:         map[string]string{"domain": "localhost:8081"},
			host:         "localhost:8081",
			path:         "",
			hostTemplate: `{domain}`,
			shouldMatch:  true,
		}
```
Failing test case - a host template attempting to match a hostname that contains dots fails. A partial 

```go
		{
			title:        "Host route with pattern (only) and subdomain",
			route:        new(Route).Host("{domain}"),
			request:      newRequest("GET", "http://fly2buy.co.uk:8081/"),
			vars:         map[string]string{"domain": "fly2buy.co.uk:8081"},
			host:         "fly2buy.co.uk:8081",
			path:         "",
			hostTemplate: `{domain}`,
			shouldMatch:  true,
		},
```

Subdomain match only:

```go
		{
			title:        "Host route with fixed ccTLD",
			route:        new(Route).Host("{domain}.co.uk"),
			request:      newRequest("GET", "http://fly2buy.co.uk:8081/"),
			vars:         map[string]string{"domain": "fly2buy"},
			host:         "fly2buy.co.uk",
			path:         "",
			hostTemplate: `{domain}.co.uk`,
			shouldMatch:  true,
		}
```

Existing host tests are defined here: https://github.com/gorilla/mux/blob/master/mux_test.go#L50-L211

**Comment by olliephillips** [comment]
Hey, is this something I need to act on, or can help with?

**Comment by elithrar** [comment]
I’m currently just logging progress. I don’t have a fix identified yet, and
it’s unlikely I will have any time to fix this until October.

Matt

**Comment by olliephillips** [comment]
I can take a look at this issue myself once I'm clear of my project if that helps? For the moment, I've reverted to parsing `r.Host` for the domain. No big deal.

**Comment by kisielk** [comment]
Help would be much appreciated. The test cases should be a good start.

**Comment by elithrar** [comment]
Suggestions:

- Add a series of new Host based tests, based on acceptable hostnames in the RFC - steal some from Go's own test suite for `r.Host` and `r.URL.Host` as applicable
- Investigate the regexp at https://github.com/gorilla/mux/blob/master/regexp.go#L53-L55

**Comment by elithrar** [comment]
https://regex101.com/r/bfzyDp/1 - the pattern is in the failing test output `regexp: regexp.MustCompile("^(?P<v0>[^.]+)$")` - you can see it doesn't match as it *intentionally* does not match periods.

> Named Capture Group v0 (?P<v0>[^.]+)
> Match a single character not present in the list below
> [^.]+
> + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
> . matches the character . literally (case sensitive)
> $ asserts position at the end of a line
