### ISSUE TITLE
methodNotAllowed should respond with Allow Header

### ISSUE THREAD

**Issue by jbowen93** [gorilla/mux#405]
Link to code location: https://github.com/gorilla/mux/blob/9e1f5955c0d22b55d9e20d6faa28589f83b2faca/mux.go#L583

Per http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.7 it would be great if the methodNotAllowed handler automatically population the Allow header for you. 

It's not clear to me how this should be done, the issue I'm struggling to wrap my head around is how the handler can be aware of the allowable methods.

**Comment by elithrar** [comment]
See how this is done here: https://github.com/gorilla/mux/blob/9e1f5955c0d22b55d9e20d6faa28589f83b2faca/middleware.go#L42-L59

You could factor that out, then re-use the route-walking approach in both cases.

**Comment by elithrar** [comment]
(if you want to take a crack at that, let me know - tests -> factor out the shared logic -> submit PR!) 💯

**Comment by jbowen93** [comment]
Scrolling through old threads it seems like the suggested workaround is to use the gorilla/handlers methodHandler. This is what I've done as it gets the jobs done (on a deadline I'm afraid). I'll keep this in mind but don't have a lot of free time right now. Thanks for elaborating on logic.
