### ISSUE TITLE
Mux is not listening on Debian Stretch (Error 503 from Apache Proxy) but is on Windows 10

### ISSUE THREAD

**Issue by akkelw** [gorilla/mux#406]
**What version of Go are you running?** (Paste the output of `go version`)
Debian: go version go1.11 linux/amd64
Windows: go version go1.11 windows/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
9e1f5955c0d22b55d9e20d6faa28589f83b2faca

**Describe your problem** (and what you have tried so far)
Setting up a mux router application on Windows 10 works perfectly fine, but trying the exact same code on a Debian Stretch server returns error 503 in the browser. I have checked all logs for errors, warnings etc and there is nothing. I tried using an older application where I use the default net/http package with standard routing system and that works good.

It's worth mentioning I'm using Apache for proxying the server. The server can not be accessed locally either without returning 503. Again there are no logs or info provided by Apache either. The needed ports are open. We are not using any server-side firewalls that'd block this, and no CloudFlare or anything like that. 

Normally 503 is what the server returns when the application is not running. The thing though is that I've done multiple tests and when the application is running I am able to ping it and get a response back, while I'm not getting a response back when the application is not running. For what's it worth, I have tried running it without an Apache proxy server and it seems like mux isn't listening.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
I have it structured in a certain way. I call a function in my middleware package that sets the route, allowing for better formating when defining them in my route package.

**middleware.go**

```
func SetRoute(r *mux.Router, uri string, handle func(http.ResponseWriter, *http.Request), methods string) {
    r.HandleFunc(uri, handle).Methods(methods)
    r.Use(MiddlewareHandle)
}

func MiddlewareHandle(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        start := time.Now()

        defer func() {
            log.Println(r.URL.Path, time.Since(start))
        }()

        next.ServeHTTP(w, r)
    })
}
```

**route.go**

```
r := mux.NewRouter()

middleware.SetRoute(r, "/", index.Index, "GET")

srv := &http.Server{
    Handler:      r,
    Addr:         "127.0.0.1:8080",
    WriteTimeout: 15 * time.Second,
    ReadTimeout:  15 * time.Second,
}

log.Fatal(srv.ListenAndServe())
```

**handle**

 ```
func Index(w http.ResponseWriter, r *http.Request) {
    fmt.Println("Hello World")
}
```

**Comment by elithrar** [comment]
To confirm, both Windows & Debian have the same version of mux?

**Comment by elithrar** [comment]
>  I tried using an older application where I use the default net/http
package with standard routing system and that works good.


- Is the only change you make here to replace *mux.Router with
*http.ServeMux? (I want to be precise/clear)
- Or are there other changes?
- Are you sure the Apache server is hitting the Go backend at all?
- The only case where Go returns a HTTP 503 is in
https://github.com/golang/go/blob/77c575d2e2cc320b62cbbdefbc6840a8cff2163c/src/net/http/server.go#L3135-L3180
- in the timeout handling part.
- If you remove the timeouts, or increase them, does the problem persist?
(try both, report both cases)

This is not a trivial issue to debug - nothing in your code points to a
problem nor would I expect a problem - so specificity is important.

**Comment by akkelw** [comment]
> To confirm, both Windows & Debian have the same version of mux?


Correct. Both of them use the same version of mux.

- **Is the only change you make here to replace *mux.Router with
*http.ServeMux? (I want to be precise/clear)**: This one is a bit tricky. When using `net/http` I don't have to pass the route like so `r *mux.Router` in `SetRoute()` - this is the middleware package for that use case [link](https://pastebin.com/PQWPrG9N) - and as seen in the pastebin my old middleware did things a bit differently. My current middleware package used for mux are only those two functions in the issue.
- **Are you sure the Apache server is hitting the Go backend at all?**: I'm sure. I tried running the application without Apache, on a different non-related (but still open and valid) port, and it refused my connection.
**- The only case where Go returns a HTTP 503 is in
https://github.com/golang/go/blob/77c575d2e2cc320b62cbbdefbc6840a8cff2163c/src/net/http/server.go#L3135-L3180**: It's not Go returning HTTP 503, that is the default response from Apache when my server is not up and listening to the webserver port.
- **in the timeout handling part. If you remove the timeouts, or increase them, does the problem persist?**: The problem persists if I remove them or increase the value.

I'm going to see if I can try it out on a different distro/server later, that way we can exclude if there's something wrong with the actual code or if it's due to improper server configuration from my part.

**Comment by akkelw** [comment]
My Windows firewall logs are sending and receiving. When telnet'ing the Go service running on Linux it throws `Unable to connect to remote host: Connection refused`.

**Comment by elithrar** [comment]
Can you confirm it’s listening?

netstat -tunapl | grep “portnum”

**Comment by akkelw** [comment]
```
tcp        0      0 127.0.0.1:8080         0.0.0.0:*               LISTEN      32622/./app
```
It's listening.

**Comment by akkelw** [comment]
Okay I managed to solve it. The issue was that specifying the host AND the port in `http.Server` would mess it up. By only specifying the port `:8080` I got it to run. Thanks for the help!
