### ISSUE TITLE
PUT on URL with double slashes results in 301 code and confuses client libraries

### ISSUE THREAD

**Issue by xemul** [gorilla/mux#408]
**What version of Go are you running?** (Paste the output of `go version`)
1.9

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
9e1f5955c0d22b55d9e20d6faa28589f83b2faca

**Describe your problem** (and what you have tried so far)
I have a server driven by the mux framework. When a client sends PUT request on a URL with mistakenly set double /-s in path (e.g. like this PUT host/foo//bar) the server responds with 301 code providing the "fixed" (with all single slashes) URL in the Location header.

The standard golang net/http client lib says that RFC 7231 allows redirection of GET-s only and re-sends the original request with the method changed to GET. Server handles both, PUT and GET on the specified URL and works well, responding with the Success code.

Technically everything is correct, but this behavior apparently confuses the client, as it expects an updated object after PUT request or an error, indicating that something went wrong. Instead, it receives "all is OK" code, but no update happened.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
1. create a router with the
    r.HandleFunc("/foo/{bar}", handleFooBar).Methods("PUT", "GET")
2. call the go client library
    req := http.NewRequest("PUT", "host/foo//bar")
    http.Client.Do(req)

the request would succeed, but for GET method, not PUT.

**Comment by elithrar** [comment]
It's not clear what the issue is - re-directing to a GET is expected, and
that's how a Go client (and curl, etc) behaves:

➜  ~  go run client.go -url "http://localhost:8000/foo//bar" -method "GET"
HTTP status: 200
Got a GET

Where the meaningful part of my repro program is:

        r := mux.NewRouter()
        r.HandleFunc("/foo/{bar}", handler).Methods("PUT", "GET")

        log.Fatal(http.ListenAndServe("localhost:8000", r))

... and my client is:

        req, err := http.NewRequest(method, uri, nil)
        if err != nil {
                log.Fatal(err)
        }

        resp, err := client.Do(req)
        if err != nil {
                log.Fatal(err)
        }

        b, err := ioutil.ReadAll(resp.Body)
        if err != nil {
                log.Fatal(err)
        }

        fmt.Printf("HTTP status: %d\n", resp.StatusCode)
        fmt.Printf("%s\n", b)

If you wanted the client to retry with a POST/PUT/DELETE/PATCH (i.e. a
non-idempotent method), you'll need to return a HTTP 307 or 308. There's
some example middleware here that can do that for you:
https://github.com/gorilla/mux/issues/369#issuecomment-385550817

**Comment by xemul** [comment]
The issue was, well, unexpected and confusing (by me) behavior when an URL "looks correct from the first sight". Confusing, because no client's part reported any error, but the overall system didn't work properly, as the server-side object was not updated. The expected was either another automatic PUT or some code that would propagate back to client as an error (letting me fix the URL string).

But since this all conforms to standards, I'm OK with just using the proposed middleware and change error to 307/308, thank you!
