### ISSUE TITLE
Release a new tagged version that removes gorilla/context

### ISSUE THREAD

**Issue by pierrre** [gorilla/mux#410]
Hello !

Could you release a new tagged version that drops the supports for Go < 1.7 and removes gorilla/context ?
The latest tag `v1.6.2` requires it.

**Comment by pierrre** [comment]
This issue is still valid.

**Comment by pierrre** [comment]
resolved in https://github.com/gorilla/mux/releases/tag/v1.7

Thank you ! :+1:

**Comment by dhui** [comment]
Could you re-tag as `v1.7.0` since SemVer requires all versions (major, minor, and patch) to be specified?

**Comment by elithrar** [comment]
Fixed (typo; need automation around this)
