### ISSUE TITLE
Multiple handlers - undocumented or does not exist?

### ISSUE THREAD

**Issue by ORESoftware** [gorilla/mux#413]
Using Go version 1.11.1

```golang
r := mux.NewRouter()
r.HandleFunc("/nearby", nearby.First, nearby.Second, nearby.GetMany).Methods("GET")
```
I was hoping the above was possible, but I don't see anything in the readme that suggests we can put multiple function handlers as varargs there. Is there a way to do this? If I do the above I get "too many arguments..."

**Comment by elithrar** [comment]
The docs show that the method only accepts two arguments - path and a
handler type.

https://godoc.org/github.com/gorilla/mux#Router.HandleFunc

**Comment by ORESoftware** [comment]
the docs could have been missing it, but I guess they aren't. is there not a way to pass multiple handlers that can be strung together?

**Comment by elithrar** [comment]
Can you describe the goal / problem you are trying to solve?

I assume you might be looking at using middleware:
https://github.com/gorilla/mux/blob/master/README.md#middleware

**Comment by elithrar** [comment]
Closing as answered.
