### ISSUE TITLE
Feature request - add method to include HTTP verbs as primary argument

### ISSUE THREAD

**Issue by ORESoftware** [gorilla/mux#414]
Right now I have this:

```
s.HandleFunc("/products/", ProductsHandler).Methods("POST", "PUT")
```

but I am looking to do something like this:

```golang
s.HandleFunc(HandleWhatever{
   Route: "/products",
   Methods: [...]string{"POST", "PUT"},
   Handler: ProductsHandler
})
```

**Comment by kisielk** [comment]
If that's the API you prefer, you could easily write it yourself as a wrapper for mux. eg:

`
func MyHandle(HandleWhatever w) {
    s.HandleFunc(w.Route, w.Handler).Methods(w.Methods...)
}
`

No need to change the mux API for this purpose.

**Comment by ORESoftware** [comment]
ah ok, sorry kinda newb with Go, that sounds about right
