### ISSUE TITLE
Run middelware for all requests

### ISSUE THREAD

**Issue by janisz** [gorilla/mux#416]
**What version of Go are you running?**
`go version go1.11.1 linux/amd64`

**What version of gorilla/mux are you at?**  1.6.2 (e3702bed27f0d39777b0b37b664b6280e8ef8fbf)

**Describe your problem** Middleware handler is not called for built in requests. 405 and 404 errors are not logged.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```go
package main

import (
	"net/http"
	"fmt"
	"log"
	"os"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func loggingMiddleware(next http.Handler) http.Handler {
	return handlers.CombinedLoggingHandler(os.Stdout, next)
}

func main() {
	r := mux.NewRouter()
	r.Use(loggingMiddleware)
	r.HandleFunc("/x", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "OK")
	})
	log.Fatal(http.ListenAndServe(":8080", r))
}
```

```
curl localhost:8080/x
curl localhost:8080/y
```

Only one request is logged

**Comment by elithrar** [comment]
Correct. Middleware only executes on matches.

You can log all requests by wrapping the top level router itself before
passing it to a listener.

**Comment by janisz** [comment]
Can you show me example how to do it? I'd like to log 404 and 405 errors too

**Comment by 0xbkt** [comment]
```go
router.NotFoundHandler = router.NewRoute().BuildOnly().HandlerFunc(http.NotFound).GetHandler()
```

All declared middlewares on `router` will execute now. Notice `BuildOnly()` by the way. That gets this newly created route to never match. If you don't use it, the route will always acts as wildcard unless declared after your original routes.

**Comment by Rude-Monkey** [comment]
Hello @0xbkt!

While not putting `.BuildOnly()` makes the route act as a wildcard, doesn't putting it prevent any middleware from being used on top of its handler?

As seen [here](https://github.com/gorilla/mux/blob/eab9c4f3d22d907d728aa0f5918934357866249e/mux.go#L136): 
```go
func (r *Router) Match(req *http.Request, match *RouteMatch) bool {
	for _, route := range r.routes {
		if route.Match(req, match) {
			// Build middleware chain if no error was found
			if match.MatchErr == nil {
				for i := len(r.middlewares) - 1; i >= 0; i-- {
					match.Handler = r.middlewares[i].Middleware(match.Handler)
				}
			}
    .....
}
```

The middlewares are used if route.Match returns `true`... but as we can see [there](https://github.com/gorilla/mux/blob/master/route.go#L41): 
```go
func (r *Route) Match(req *http.Request, match *RouteMatch) bool {
	if r.buildOnly || r.err != nil {
		return false
	}
    ...
}
```

`route.Match()` will return `false` when using `BuildOnly()` on a new route... 

Is there something I am missing?

I could simply use 
```go
 router.NotFoundHandler = router.NewRoute().HandlerFunc(http.NotFound).GetHandler()
```
 after I registered all my other routes, yet my problem is I am trying to do that for both `NotFoundHandler` and `MethodNotAllowedHandler` handlers ^^'

**Comment by 0xbkt** [comment]
@Rude-Monkey Hi. I guess you are right. I actually encountered the same problem after I posted my comment but never had a chance to update it.

I looked up the code a little bit and found out that `r.middlewares` is not exported at all. If there was a public method to read it, furthermore, if even there was a wrapper type to store middlewares which can also `Apply` them to `Handler`s, that would really be nice.

**Comment by epelc** [comment]
Is there any way this could be made to work as expected by default?

As it is you have to use `router.NotFoundHandler = router.NewRoute().HandlerFunc(http.NotFound).GetHandler()` and be sure to set it after registering all other routes. It is confusing and you wouldn't expect your middleware to not run on 404 by default.

**Comment by elithrar** [comment]
This went both ways. The challenge with changing it now is that this would be a breaking change. 

Instead, just wrap the router (or your handlers) with your middleware directly:

```
wrappedRouter := myMiddleware(router)
```

... or, stack them:

```
wrappedRouter := recoveryHandler(
    loggingHandler(logConfig)(
    router
    )
)
```

It’s easier to have middleware wrap anything when it conforms to `http.Handler`. It’s harder to run middleware only on a route match.

**Comment by epelc** [comment]
@elithrar Alright thanks for the info! It is at least good to know this is the best way to do it pending a breaking change of some sort which would probably be worse tbh.

Thanks for the quick response!

**Comment by Rude-Monkey** [comment]
That works! I needed to take a different approach for my use case though...

I had a set of middleware functions (say `A, B, C, D` and `E`).

My problem was that I wanted middleware functions `A`, `B`, `D` and `E` to execute sequentially for every path by default, except I also wanted to execute `C` after `B` and before `D` for "correct" paths.
I could easily wrap my router so that `A` and `B` are run for every path - regardless of the existence of a match -, but I would still need to call the `Use()` function with `C`, `D` and `E` and customize both the router's `NotFoundHandler` and `MethodNotAllowedHandler`.

It ended up looking a little like that: 

```go
        router := mux.NewRouter()

	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Hello World!"))
	}).Methods("GET")

	router.Use(A(), B(), C(), D(), E())

	//Init error handlers
	router.NotFoundHandler = router.NewRoute().BuildOnly().HandlerFunc(http.NotFound).GetHandler()
	router.MethodNotAllowedHandler = router.NewRoute().BuildOnly().HandlerFunc(
                func(w http.ResponseWriter, r *http.Request) {
		        w.WriteHeader(http.StatusMethodNotAllowed)
		        w.Write([]byte("405 method not allowed"))
	        }
        ).GetHandler()

        WrapErrorHandlers(router, A(), B(), D(), E())
```

with `WrapErrorHandlers` being a custom function: 

```go
func WrapErrorHandlers(r *mux.Router, mwf ...mux.MiddlewareFunc) {
	
        var middlewareFunctions []mux.MiddlewareFunc
	
        handlers := map[string]http.Handler{
		"NotFoundHandler":         r.NotFoundHandler,
		"MethodNotAllowedHandler": r.MethodNotAllowedHandler,
	}

	for _, handlerFunction := range mwf {
		middlewareFunctions = append(middlewareFunctions, handlerFunction)
	}

	for name, handler := range handlers {
		if handler != nil {
			for i := len(middlewareFunctions) - 1; i >= 0; i-- {
				handler = middlewareFunctions[i].Middleware(handler)
			}
		} else {
			// Handle the error
		}
	}

}
```

That was what made the most sense to me back then, but maybe there is a simpler way to do that?

**Comment by allanrbo** [comment]
To anyone else arriving here looking for a way to just log all requests: I think this is what @elithrar meant when he said "log all requests by wrapping the top level router itself before passing it to a listener":
```
func main() {
	handler := mux.NewRouter()

	handler.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("world"))
	}).Methods("GET")

	handler2 := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println(r.Method + " " + r.URL.String())
		handler.ServeHTTP(w, r)
	})

	log.Fatal(http.ListenAndServe(":8080", handler2))
}
```

**Comment by elithrar** [comment]
(I also wrote a full blog post on how to do this, including a near copy-paste example: https://blog.questionable.services/article/guide-logging-middleware-go/)
