### ISSUE TITLE
Getting URL vars in order

### ISSUE THREAD

**Issue by Sterd** [gorilla/mux#419]
I'd like to map a route to a controller action that receives the URL vars as its arguments (using reflection). For that there needs to be a way to get the vars in order, but right now the only way is mux.Vars and that returns a map.

I figure RouteMatch needs an additional field (an array), and extractVars needs to fill that up too. Shouldn't be too hard? :)

**Comment by elithrar** [comment]
I don’t think it makes sense to do so for a single use-case like this: we
are then adding an array to every match, whether consumed or not.

Have you considered using named route variables to positionally number
them? Or giving them contextual names.

“/{one}/{two}/{etc}”

Alternatively you could use GetPathTemplate and determine the positions
from there: https://godoc.org/github.com/gorilla/mux#Route.GetPathTemplate
