### ISSUE TITLE
Use 308 instead of 301 for trailing slash at least for non-GET methods

### ISSUE THREAD

**Issue by or-else** [gorilla/mux#420]
This is a new issue to bring back the discussion of #285 

It seems like it has to be done at some point or at least it should be made configurable. The broken clients should not prevent newer clients from working correctly.

Maybe make it HTTP version-dependent, i.e.HTTP/ 1.0 should get 301 while HTTP/1.1 gets 308. Certainly HTTP/2.0 should get 308.

**Comment by elithrar** [comment]
Earmarking this for v2.0, but won’t change today.

You can use middleware to change 301/2’s into 307/8’s in the meantime.

**Comment by or-else** [comment]
Thanks!

I can sure find a workaround, the simplest being just to make sure all URLs have a trailing slash. 

It's that I just killed half a day trying to figure out why Android clients can't upload.
And the possible fix on Gorilla's side seems to be so trivial.

**Comment by drum445** [comment]
This would be a nice change, would mean I can delete my clunky middleware I am using currently

**Comment by elithrar** [comment]
I'd accept a PR that makes this an option on the Router, but am unlikely to change this as a default.
