### ISSUE TITLE
unable to get all query params via Queries

### ISSUE THREAD

**Issue by vtolstov** [gorilla/mux#421]
i have url like: /xxx?fields=name&fields=public_key
i have pattern like .Queries("fields", "{fields}") but in this case in mux.Vars i have only one field (first with name = name)

**Comment by elithrar** [comment]
.Queries is used for adding matches to a route -
https://godoc.org/github.com/gorilla/mux#Route.Queries

mux.Vars returns route variables, not query parameters. If you want to
fetch those, use r.URL.Query() to get a map of url.Values -
https://golang.org/pkg/net/url/#URL.Query
