### ISSUE TITLE
router.Use middleware not being hit

### ISSUE THREAD

**Issue by ORESoftware** [gorilla/mux#429]
**What version of Go are you running?** 
go version go1.10.4 linux/amd64

**What version of gorilla/mux are you at?**
`3d80bc801bb034e17cae38591335b3b1110f1c47`

**Describe your problem** (and what you have tried so far)
I am registering middleware, but they don't seem to be hit.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```golang
package main

import (
	"encoding/json"
	"fmt"
	"github.com/dgrijalva/jwt-go"
	"github.com/gorilla/context"
	"github.com/mitchellh/mapstructure"
	"huru/migrations"
	"huru/models"
	"huru/models/person"
	"huru/routes"
	"net/http"
	"os"

	"github.com/gorilla/mux"
	_ "github.com/lib/pq"
	log "github.com/sirupsen/logrus"
)

func loggingMiddleware(next http.Handler) http.Handler {

	log.Println("logging middleware registered");

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Do stuff here
		log.Println("Here is the request URI:",r.RequestURI)
		// Call the next handler, which can be another middleware in the chain, or the final handler.
		next.ServeHTTP(w, r)
	})
}

type Exception struct {
	Message string `json:"message"`
}

func authMiddleware(next http.Handler) http.Handler {

	log.Println("auth middleware registered");

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		params := r.URL.Query()
		fmt.Println("the params are:", params);

		token, _ := jwt.Parse(params["token"][0], func(token *jwt.Token) (interface{}, error) {
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, fmt.Errorf("there was an error")
			}
			return []byte("secret"), nil
		})
		claims, ok := token.Claims.(jwt.MapClaims)

		if ! (ok && token.Valid) {
			json.NewEncoder(w).Encode(Exception{Message: "Invalid authorization token"})
			return;
		}

		var user person.Model
		mapstructure.Decode(claims, &user)
		context.Set(r, "logged_in_user", user)
		next.ServeHTTP(w, r)
	})
}

func errorMiddleware(next http.Handler) http.Handler {

	log.Println("error handling middleware registered");

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {

				log.Error("Caught error in defer/recover middleware: ", err)
				originalError := err.(struct{ OriginalError error }).OriginalError

				if originalError != nil {
					log.Error("Original error in defer/recover middleware: ", originalError)
				}

				statusCode := err.(struct{ StatusCode int }).StatusCode

				if statusCode != 0 {
					w.WriteHeader(statusCode)
				} else {
					w.WriteHeader(http.StatusInternalServerError)
				}

				message := err.(struct{ Message string }).Message

				if message == "" {
					message = "Unknown error message."
				}

				json.NewEncoder(w).Encode(struct {
					ID string
				}{
					message,
				})
			}
		}()
		next.ServeHTTP(w, r)
	})
}

func main() {

	routerParent := mux.NewRouter()
	routerParent.Use(loggingMiddleware)
	routerParent.Use(errorMiddleware)
	routerParent.Use(authMiddleware)

	router := routerParent.PathPrefix("/api/v1").Subrouter();
	router.Use(loggingMiddleware)
	router.Use(errorMiddleware)
	router.Use(authMiddleware)


	// register and login
	{
		handler := routes.LoginHandler{}
		subRouter := router.PathPrefix("/").Subrouter()
		handler.Mount(subRouter, struct{}{});
	}

	{

		handler := routes.RegisterHandler{}
		subRouter := router.PathPrefix("/").Subrouter()
		handler.Mount(subRouter, struct{}{})
	}

	{
		// people
		handler := routes.PersonHandler{}
		subRouter := router.PathPrefix("/").Subrouter()
		subRouter.Use(authMiddleware)
		handler.Mount(subRouter, routes.PersonInjection{People: models.PersonInit()})
	}
}
```

none of these get logged:

```golang
	log.Println("error handling middleware registered");
	log.Println("auth middleware registered");
	log.Println("logging middleware registered");
```

and at runtime none of middleware routes seem to get hit, nothing is logged there.

**Comment by ORESoftware** [comment]
https://stackoverflow.com/questions/53846042/gorilla-mux-middleware-not-being-hit

**Comment by elithrar** [comment]
Keep in mind: Middleware only runs on a route match.

Are the routes you’re hitting valid & returning a 200 from mux?

**Comment by ORESoftware** [comment]
@elithrar the clue is that the middleware is not being registered, as  I said above:

> none of these are being logged:
> 
> ```
> 	log.Println("error handling middleware registered");
> 	log.Println("auth middleware registered");
> 	log.Println("logging middleware registered");
> ```

**Comment by ORESoftware** [comment]
@elithrar I have a git repo that can demo the problem, it doesn't make any db connections or anything, just responds to requests, so it's easy to reprodoce. Can you take a look? this problem is rough.

**Comment by elithrar** [comment]
I can take a look this weekend, but:

Note that adding middleware to the stack _does not run it_. Your logs will
not be written as the middleware only runs when a route is matched. It
doesn’t run when you call Router.Use - there’s no request to pass to it.

**Comment by ORESoftware** [comment]
@elithrar yeah the problem is real, the middleware gets registered if I do this:

```golang
func getMiddleware(h http.HandlerFunc)  http.Handler {
	return mw.Error(mw.Auth(mw.Logging(h)));
}

router.Handle("/share", getMiddleware(h.makeGetMany(v))).Methods("GET")
```

I get this logged:

```
INFO[0000] logging middleware registered                
INFO[0000] auth middleware registered                   
INFO[0000] error handling middleware registered  
```

but if I do this:

```golang
	router.Use(mw.Auth,mw.Logging,mw.Error);
	router.Handle("/share", h.makeGetMany(v)).Methods("GET")
```

then nothing gets logged and the middleware is never invoked

**Comment by elithrar** [comment]
Can you also make sure you’re using the latest version of mux? The hash you supplied is > 2 months old.

**Comment by ORESoftware** [comment]
@elithrar updated to latest using `go get -u` (I think that's all you have to run right?), same problem

**Comment by tomare** [comment]
I have similar issue, and I find something in Route.Match

**Comment by tomare** [comment]
`

**Comment by tomare** [comment]
match.MatchErr was contaminated in loop.

**Comment by maplebed** [comment]
After applying the patch that @tomare suggested, middleware runs as expected in [my example](https://github.com/maplebed/gorilla-mux-routing-example/tree/middleware_bug). In other words, I see middleware executed for all expected queries on both ports 8080 and 8081, whereas before they only matched on the curl against port 8081.

Here's the patch as I applied it:
```diff
:) (12/20/18T10:39) ~/hound/goroot/src/github.com/gorilla/mux@master✗ ✹
➜  git patch
diff --git a/route.go b/route.go
index acef919..022be5e 100644
--- a/route.go
+++ b/route.go
@@ -57,8 +57,8 @@ func (r *Route) Match(req *http.Request, match *RouteMatch) bool {
                }
        }

+       match.MatchErr = matchErr
        if matchErr != nil {
-               match.MatchErr = matchErr
                return false
        }
```

**Comment by ORESoftware** [comment]
@elithrar are you available to discuss this issue over skype? I can walk you through the repo I have

**Comment by elithrar** [comment]
I don't think Skype is a productive way to debug this. Here's what will help:

* Be clearer - provide a single piece of example code that reproduces the issue
* Provide either tests in Go or as `curl` requests that show expected vs. actual
* Do the same for "405's in weird places" - it is otherwise impossible to understand what the problem is.

**Comment by ORESoftware** [comment]
@elithrar please see this demo repo
https://github.com/ORESoftware/mux-problem-demo

the problem occurs in src/huru/main.go, the subRouters dont inherit the middleware of their parents, nor can I create middleware using subRouter.Use - it doesn't get hit

The repo is about as simple as can be, honestly if you are going to bother to take a look at it, a skype call with a verbal explanation would actually save time.

**Comment by elithrar** [comment]
I want to replicate your issue, be able to apply a fix/patch (if necessary), and re-run the requests to resolve it.

I understand the _problem_ you're describing, but being able to programatically reproduce it makes fixing it much easier, and avoids missing any cases you consider "broken" that I do not.

There is no need to get snarky - I'm volunteering my time to help you. 

Provide matching test cases in Go, or as simple `curl` requests, and I'm more than happy to help.

**Comment by ORESoftware** [comment]
@elithrar would accept test cases written in Node.js? The reason I would rather discuss first is perhaps this is just expected behavior.

**Comment by ORESoftware** [comment]
@elithrar ok here it is
https://github.com/ORESoftware/mux-problem-demo/blob/master/test/mia-mw.js

if we agree that there is a problem, I can write you tests with bash or golang, that you can use in the real test suite. just want to make sure that the problem actually exists first.

There is one test case in that file - it fails. In `main.go` you can see where the handler is for `/api/v1/foo`, basically the context should be set in the mw.ContextHandler middleware, but that middleware doesn't get called before the handler for `/api/v1/foo` gets called. Let me know if you have questions.

**Comment by elithrar** [comment]
```
# Before PR 431 was applied
➜  /mnt/c/Users/Gamer/repos/mux-problem-demo/src/huru (master) ✗  huru_api_port=3000 huru
INFO[0000] Huru API server listening on port 3000
INFO[0017] the logging handling middleware should have logged something before this.
INFO[0028] the logging handling middleware should have logged something before this.
^C
# After PR 431 was applied
^[➜  /mnt/c/Users/Gamer/repos/mux-problem-demo/src/huru (master) ✗  huru_api_port=3000 ./huru
INFO[0000] Huru API server listening on port 3000
INFO[0005] logging middleware registered
INFO[0005] logging middleware registered
INFO[0005] logging middleware registered
INFO[0005] logging middleware registered
INFO[0005] We are handling errors with defer.
INFO[0005] Here is the request URI: /api/v1/foo
INFO[0005] We are handling errors with defer.
INFO[0005] Here is the request URI: /api/v1/foo
INFO[0005] We are handling errors with defer.
```

**Comment by ORESoftware** [comment]
@elithrar that looks much better is that a new PR?
