### ISSUE TITLE
subrouter behaves differently when NotFoundHandler is defined

### ISSUE THREAD

**Issue by maplebed** [gorilla/mux#432]
**What version of Go are you running?** 
```bash
➜  go version
go version go1.11.4 darwin/amd64
```
**What version of gorilla/mux are you at?** 
```bash
➜  git rev-parse HEAD
6137e193cdcba2725f16de84eaf0db2b769d9668
```

**Describe your problem** (and what you have tried so far)
Routing behaves differently when a submux has a NotFoundHandler defined and other available routes might match.

**When a `NotFoundHandler` is defined** if route matches a prefix and descends into a subrouter but then does not find an exact match, **the match search stops** and returns the submux's NotFoundHandler

**When a `NotFoundHandler` is _not_ defined** if a route matches a prefix and descends into a subrouter but then does not find an exact match, **the match search continues** to other available routes in the parent mux.

I would not expect route selection to be influenced by whether on not a `NotFoundHandler` was default or custom. And if it is supposed to behave differently, I would hope to find a method of toggling the behavior while still being able to change the `NotFoundHandler`. In other words, I would like to separate the logic of whether a route matches from what happens when it doesn't. 

If this behavior is expected, I would like to consider updating the documentation to make more clear the effects of overriding the `NotFoundHandler`. 

As an aside, I believe that when #431 lands, it will also be the case that if a submux has the NotFoundHandler defined then middleware on the parent mux will run (whereas it would not run if the NotFoundHandler were default).

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
https://github.com/maplebed/gorilla-mux-routing-example/tree/notfound has a runnable example illustrating both cases.

**Comment by elithrar** [comment]
A custom NotFoundHandler should not prevent middleware from running on a
subrouter, so I would consider this a bug.
