### ISSUE TITLE
provide regexp with capturing group

### ISSUE THREAD

**Issue by vtolstov** [gorilla/mux#435]
for some or my reasons i need to have regexp for route not with indexed int like v0 v1 and so, but my capturing group. So if i specify /xxx/{id} i want to have in regexp like ^/xxx/(?P<id>[^/]+)$
and not ^/xxx/(?P<v0>[^/]+)$

**Comment by elithrar** [comment]
Can you be clearer about your reasons? You can provide named groups if needed.

**Comment by vtolstov** [comment]
How can i specify capture group? I need to auto fill struct with variables from path and other parameters, 
for variables i'm use reflection to fill struct fields, but also i want to fill and path based params.
P.S. i know about mux.Vars but this is not so usable for me use-case

**Comment by elithrar** [comment]
Can you show how mux.Vars is not usable?

Something like gorilla/schema or https://github.com/mitchellh/mapstructure should be able to do this for you.

**Comment by vtolstov** [comment]
i want to move all fill stuf to one place, but in case of mux.Vars i have 2 places , one is parsing in gorilla/mux and another - my own stuff.
May be i'm try to live with mux.Vars and thanks for https://github.com/mitchellh/mapstructure
