### ISSUE TITLE
 Visitor tracking use case 

### ISSUE THREAD

**Issue by kaihendry** [gorilla/mux#436]
Following up on https://groups.google.com/d/msg/gorilla-web/Ga1X6kTzImQ/whjJH89DDgAJ

First Matt, happy new year and thanks for answering my question, though I am stuck what you mean by Request in your pseudocode: http://play.golang.org/p/GZzJdAHDGu0

Tbh, I am a total newb when it comes to **context**, so I am little bewildered how it can replace the functionality of a cookie. Since the UA of the visitor might have a longer session than my running lambda server.

I am also a little puzzled how to get logging object back into the handler. I am more familiar with https://github.com/apex/log if you don't mind.

**Comment by elithrar** [comment]
Kai - can you perhaps outline how you want to “track” a user? Across all of
their visits to the site? How will you analyze it later? What is the goal
of tracking them?

**Comment by kaihendry** [comment]
I just want to be able to see their journey through the routes of the application.

1. /
2. /about
3. /bus/id?=12345
4. /bus/id?=41323
5. /contact

Without using JS. I think the easiest way to do that, is logging a cookie id in the middleware somehow.

**Comment by elithrar** [comment]
Yes, in that case, just give them a cookie. The concept of a “store” in
cookie parlance is to save it somewhere - in this case, the client computer.

I had interpreted your ask as “I want to trace a request through my
handlers & middleware”.

**Comment by kaihendry** [comment]
Just a thought: Another reason why I would want to use this, is the individually track a user who has his IP changing or something like that.

I think I've found the way to do it. Be good if you could review the code and perhaps publish it as an example?
https://play.golang.org/p/2jwrUKnAOvH
