### ISSUE TITLE
Status is 404 Not Found instead of 405 Method Not Allowed

### ISSUE THREAD

**Issue by g-w** [gorilla/mux#437]
**What version of Go are you running?**

```
go version go1.11.4 linux/amd64
```

**What version of gorilla/mux are you at?**

f3ff42f93a451d7ffb2ff11cb9485f3f88089c83

**Describe your problem**

Currently the router returns `404` instead of `405` if the path matches but not the method. This is only the case if another not matching route was registered after the matching one.

This issues seems to be introduced through the changes in ef912dd76ebe9d9848c6e0fd80eaebccc9a11631 .

**Paste a minimal, runnable, reproduction of your issue below**

```
func TestMethodNotAllowed(t *testing.T) {
	router := NewRouter()
	router.HandleFunc("/thing", func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(http.StatusOK) }).Methods(http.MethodGet)
	router.HandleFunc("/something", func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(http.StatusOK) }).Methods(http.MethodPost)

	w := NewRecorder()
	req := newRequest(http.MethodPut, "/thing")

	router.ServeHTTP(w, req)

	if w.Code != 405 {
		t.Fatalf("Expected status code 405 (got %d)", w.Code)
	}
}
```

**Comment by elithrar** [comment]
Thanks. Are you interested in submitting a PR that tackles this?

The challenge is that ef912dd and this are conflicting behaviour - you need
to track two "kinds" of matchErr (matchRouteErr, matchMethodErr?) in order
to handle this. That also won't solve host matches, etc.

**Comment by g-w** [comment]
I will have a look into this and try to provide a PR.

**Comment by g-w** [comment]
@elithrar I've created a PR #438.
