### ISSUE TITLE
Encoded slashes in a URL interact poorly with UseEncodedPath and StrictSlash

### ISSUE THREAD

**Issue by ellismg** [gorilla/mux#439]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.11.2 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

08e7f807d38d6a870193019bb439056118661505

**Describe your problem** (and what you have tried so far)

If a redirect happens because of `StrictSlash` settings, the location header includes the unescaped path. This causes problem when used in combination with `UseEncodedPath` on a router, because it can lead to a resource not matching.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

Run this server:

```
	router := mux.NewRouter().StrictSlash(true).UseEncodedPath()
	router.HandleFunc("/{a}/{b}", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
	})

	http.ListenAndServe(":8081", router)
```

Then run curl to a URL that will trigger a redirect due to strict slash:

```
$ curl -v http://localhost:8081/foo%2fbar/baz/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8081 (#0)
> GET /foo%2fbar/baz/ HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /foo/bar/baz
< Date: Sat, 12 Jan 2019 01:06:26 GMT
< Content-Length: 47
< 
<a href="/foo/bar/baz">Moved Permanently</a>.

* Connection #0 to host localhost left intact
```

You can see here that the redirected URL has changed the encoded `%2f` into a `/`.  But this is incorrect in light of `UseEncodedPath`, the correct URL should be: `/foo%2fbar/baz`

**Comment by ellismg** [comment]
I actually looked into this a little bit as well, I think a problem could be in `func (v routeRegexpGroup) setMatch(req *http.Request, m *RouteMatch, r *Route)`

I believe that the mutation of `Path` on `url.Url` invalidates whatever was in `.RawPath` meaning that it will be ignored `u.String()` is called to generate the URL for the redirect, since it is no longer a valid encoding of what is in Path.

**Comment by lblackstone** [comment]
This bug is still present on `github.com/gorilla/mux v1.8.1`
