### ISSUE TITLE
Document Usage Of Router.NotFoundHandler

### ISSUE THREAD

**Issue by evantbyrne** [gorilla/mux#44]
Right now on the website there isn't any documentation on how to handle 404 errors. Documentation should be added for this, because the functionality is included in the library and I'm sure a lot of people will use it! :)

Thank you,

Evan

**Comment by heisGarvit** [comment]
Please add 404 code to https://github.com/gorilla/mux page it took a while to look for it!
<pre>
mux.NewRouter()
r.NotFoundHandler = http.HandlerFunc(func (w http.ResponseWriter, req *http.Request) {
                 // Handle 404
}<pre>

**Comment by amlang** [comment]
for anybody googled that; a complete example to copy and paste
`
   ...	
   router := mux.NewRouter()
   router.NotFoundHandler = Handle404()
  ...
}

// Handle404 ...
func Handle404() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Error(w, "404 page not found", StatusNotFound)
		json.NewEncoder(w).Encode(HTTPError{Code: string(http.StatusNotFound), Message: http.StatusText(http.StatusNotFound)})
	})
}
`
