### ISSUE TITLE
Getting go server's base URI

### ISSUE THREAD

**Issue by IvanDelsinne** [gorilla/mux#440]
- go version: `go version go1.11.4 linux/amd64`
- `gorilla/mux` version: `ef912dd76ebe9d9848c6e0fd80eaebccc9a11631`

**Describe your problem** (and what you have tried so far)

I'd need to get the http server's base URI, but I'd like to avoid having to r-trim the Path URL of the route suffix in every route.

Is there an "automated" way of getting the "global" base URI no matter the route?

**Comment by elithrar** [comment]
Are you after the _server_ base URI, or the base URI for that router /
subrouter?

**Comment by IvanDelsinne** [comment]
The router base URI.

**Comment by elithrar** [comment]
Not directly. You can get the current Route from the request via
https://godoc.org/github.com/gorilla/mux#CurrentRoute - but not router vs.
subrouter vs. the route itself.

**Comment by elithrar** [comment]
Closing out, but let us know if you have a follow-up question!
