### ISSUE TITLE
When using mux.NewRouter in http.ListenAndServer, cannot show prometheus metrics

### ISSUE THREAD

**Issue by ssmails** [gorilla/mux#444]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.11.1 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
9e1f5955c0d22b55d9e20d6faa28589f83b2faca

**Describe your problem** (and what you have tried so far)
When using router from mux.NewRouter() in http.ListenAndServe, cannot see prometheus metrics using http://localhost:2112
When not using router in http.ListenAndServe, can see prometheus metrics using above curl command. 
See sample code below.
 
**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

-> go run main.go

package main
 
import (
        "net/http"
        "time"
        "fmt"
 
        "github.com/prometheus/client_golang/prometheus"
        "github.com/prometheus/client_golang/prometheus/promauto"
        "github.com/prometheus/client_golang/prometheus/promhttp"
        "github.com/gorilla/mux"
)
 
func recordMetrics() {
        go func() {
                for {
                        opsProcessed.Inc()
                        time.Sleep(2 * time.Second)
                }
        }()
}
 
var (
        opsProcessed = promauto.NewCounter(prometheus.CounterOpts{
                Name: "myapp_processed_ops_total",
                Help: "The total number of processed events",
        })
)
 
func MetricsGetHandler(w http.ResponseWriter, r *http.Request) {
   fmt.Printf("In MetricsGetHandler\n")
   promhttp.Handler()
}
 
func main() {
        recordMetrics()
 
       //NOT-WORKING - when using router
        router := mux.NewRouter()
        router.HandleFunc("/metrics", MetricsGetHandler).Methods("GET")
        http.ListenAndServe(":2112", router)
 
        //WORKING - when not using router
        //http.Handle("/metrics", promhttp.Handler())
        //http.ListenAndServe(":2112", nil)
}

**Comment by elithrar** [comment]
Have you tried just passing `promhttp.Handler()` as the handler, instead of wrapping it?

**Comment by ssmails** [comment]
Cannot pass promhttp.Handler() directly . instead of wrapping it in MetricsGetHandler, because of the requirement that router.HandleFunc(), should be a function that must implement (w http.ResponseWriter, r *http.Request)
router.HandleFunc("/metrics", MetricsGetHandler).Methods("GET")

**Comment by elithrar** [comment]
In the default `net/http` mux, you're calling `http.Handle`. mux has an identical method on its router - [`*Router.Handle()`](https://godoc.org/github.com/gorilla/mux#Router.Handle).

The `promhttp.Handler()` function returns a `http.Handler`, but when you call it in your function as you do, you're not passing the request or response to it.

Thus, either:

```
router.Handle("/metrics", promhttp.Handler()`)`
```

or

```
func metrics(w http.ResponseWriter, r *http.Request) {
    promhttp.Handler().ServeHTTP(w, r)
}
```

Either is valid. The second is unnecessary unless you want to wrap the metrics collection with additional logic.
