### ISSUE TITLE
Can Multiple Routers or Subrouters be used that use different middlewares?

### ISSUE THREAD

**Issue by jayeshguru** [gorilla/mux#445]
**What version of Go are you running?** (Paste the output of `go version`)
**_go version go1.11.2 darwin/amd64_**

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
_b57cb1605fd11ba2ecfa7f68992b4b9cc791934d_

**Describe your problem** (and what you have tried so far)
I have two endpoints for my go microservice 
- healthCheck endpoint
- GetId

I want to use some security checks for GetId endpoint but not for healthCheck, so i preferred using middleware by `router.Use(security.VerifySecurity)` 
My question here is - 
How can I use two different routers or subRouters for both endpoints, 1st using middleware doing security stuff and other not using any middleware as its just healthCheck?
Also both routers should be started on same port 
`http.ListenAndServe(":"+port, cors.Default().Handler(router))`

Any help in this is appreciable, struggling to get through this?

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

`for _, endpoint := range a.endpoints {
		log.WithFields(log.Fields{
			"endpoint": endpoint.endpoint,
			"method" : endpoint.method.String(),
			"function" : runtime.FuncForPC(reflect.ValueOf(endpoint.handler).Pointer()).Name(),
		}).Trace("Added endpoint")
		if strings.Contains(endpoint.endpoint,"health") {
			router2.Get(endpoint.endpoint, endpoint.handler)
		}else {
			router1.Get(endpoint.endpoint, endpoint.handler)
		}
}`

**Comment by elithrar** [comment]
Yes - you should use a Subrouter and PathPrefix to separate out where middleware needs to be applied: https://godoc.org/github.com/gorilla/mux#Route.Subrouter

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func MiddlewareOne(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		log.Println("middleware one")
		next.ServeHTTP(w, r)
	}

	return http.HandlerFunc(fn)
}

func MiddlewareTwo(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		log.Println("middleware two")
		next.ServeHTTP(w, r)
	}

	return http.HandlerFunc(fn)
}

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "hello")
}

func main() {
	r := mux.NewRouter()

	healthchecks := r.PathPrefix("/health").Subrouter()
	healthchecks.Use(MiddlewareOne)
	healthchecks.HandleFunc("/ready", handler)

	protected := r.PathPrefix("/admin").Subrouter()
	protected.Use(MiddlewareTwo)
	protected.HandleFunc("/dashboard", handler)

	log.Fatal(http.ListenAndServe("localhost:8000", r))
}
```

```
~/repos 
➜  curl localhost:8000/admin/dashboard 
hello
~/repos 
➜  curl localhost:8000/health/ready    
hello
```

```sh
➜  go run main.go
2019/02/13 06:32:27 middleware two 
2019/02/13 06:32:36 middleware one 
```

Let me know if any questions!

**Comment by elithrar** [comment]
PS: I would almost definitely reconsider how you're building routes using reflect - that's error prone and likely to panic if you misconfigure. It's hard to see from your very limited example, but a map of `map[string]YourHandlerType` would be easy to iterate over and build a subrouter from.
