### ISSUE TITLE
BUG: StrictSlash lost Method

### ISSUE THREAD

**Issue by rarpainting** [gorilla/mux#451]
**What version of Go are you running?** (Paste the output of `go version`)

go version go1.11 linux/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

a7962380ca08b5a188038c69871b8d3fbdf31e89

**Describe your problem** (and what you have tried so far)

After `StrictSlash`, the original route method will be "lost" AND become "GET"

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```golang
	r := mux.NewRouter()
	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			fmt.Println("in middle ware")
			next.ServeHTTP(w, r)
		})
	})
	r.StrictSlash(true).HandleFunc("/e/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(r.Method)
	}).Methods("POST")
	r.StrictSlash(true).HandleFunc("/e/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(r.Method)
	}).Methods("GET")

	http.ListenAndServe(":3000", r)
```

```http
POST http://localhost:3000/e
```

**Comment by elithrar** [comment]
This makes sense - if you are submitting a `POST` or a `PUT` (or any non-idempotent method), StrictSlash will *re-direct* to the right path.

Specifically: https://tools.ietf.org/html/rfc7231#section-6.4

> The first revision of HTTP/1.1 added 307 (Temporary Redirect) to
      indicate the former semantics without being impacted by divergent
      practice.  Over 10 years later, most user agents still do method
      rewriting for 301 and 302; therefore, this specification makes
      that behavior conformant when the original request is POST.

I'm about to post an example in https://github.com/gorilla/mux/pull/465 that shows how to customize 301/302 to a 307/308.
