### ISSUE TITLE
Question: Open Api support

### ISSUE THREAD

**Issue by zekth** [gorilla/mux#452]
Hi there, i'm currently using gorilla Toolkit on a github project and i have some questions on Mux. Especially on the router.

I'm looking for an easy way to implement OpenApi specification (https://github.com/OAI/OpenAPI-Specification). At the moment a lot of Go projects are using go-swagger to generate documentation but not using this specification as a middleware. By using this we can make sure the API and the specification on the API are tied.

For example in nodejs there is this kind of implementations:
https://github.com/APIDevTools/swagger-express-middleware

Is there any plan for developping this in Mux / gorilla toolkit package?

cheers

Note: Project is https://github.com/reef-pi/reef-pi

**Comment by elithrar** [comment]
There are no explicit plans to add this to mux - with router.Walk - http://www.gorillatoolkit.org/pkg/mux#Router.Walk - you could generate an OpenAPI compatible schema. 

An example in the documentation would be great; adding code would be a much higher bar due to the specificity of it.

**Comment by zekth** [comment]
I will look forward on it. Maybe if i find something usefull and revelant for this case do i submit a PR?

**Comment by elithrar** [comment]
If you can talk through your intent / plan first it’ll help - a PR that
adds code to mux for this is unlikely to be accepted.

**Comment by zekth** [comment]
I was meaning as an example for the documentation.

**Comment by vearutop** [comment]
If anyone is still looking for a way to instrument `gorilla/mux` router with OpenAPI, please check https://pkg.go.dev/github.com/swaggest/rest/gorillamux#NewOpenAPICollector (and example there).

**Comment by LinuxSuRen** [comment]
Thank @vearutop , I made a Mock server based on your solution and this project.

https://github.com/LinuxSuRen/api-testing/pull/410
