### ISSUE TITLE
 PathPrefix() and longest prefix match

### ISSUE THREAD

**Issue by rchirakk** [gorilla/mux#453]
**What version of Go are you running?** (Paste the output of `go version`)
```go version go1.10.3 ```

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
```a7962380ca08b5a188038c69871b8d3fbdf31e89```

**Describe your problem** (and what you have tried so far)
I register 2 paths using PathPrefix(),

```
r.PathPrefix("/foo").HandlerFunc(handler1)
r.PathPrefix("/foo/some").HandlerFunc(handler2)
```
when I run
```GET /foo/some/things```, handler1 is executed  instead of handler2, didn't match the longest prefix

if I change the order of registration, 
```
r.PathPrefix("/foo/some").HandlerFunc(handler2)
r.PathPrefix("/foo").HandlerFunc(handler1)

```
then it works.

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
```
package main
  
import (
        "fmt"
        "net/http"
        "net/http/httptest"
        "github.com/gorilla/mux"
)

func main() {
        r := mux.NewRouter()

        r.PathPrefix("/foo").HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
                fmt.Printf("+++ /foo :%s\n", req.URL.Path)
        })

        r.PathPrefix("/foo/some").HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
                fmt.Printf("+++ /foo/some :%s\n", req.URL.Path)
        })

        fmt.Println("GET /foo/some/things")
        req, _ := http.NewRequest("GET", "/foo/some/things", nil)
        r.ServeHTTP(&httptest.ResponseRecorder{}, req)
}

```

**Comment by elithrar** [comment]
mux matches based on registration order, not prefix length. 

Docs: https://github.com/gorilla/mux/blob/master/README.md#matching-routes

**Comment by nanmu42** [comment]
Got the same problem. Just see that from [README.md](https://github.com/gorilla/mux/blob/master/README.md#matching-routes):

> Routes are tested in the order they were added to the router. If two routes match, the first one wins.

I do hope this sentence be emphasized, though. :rofl:

**Comment by sdbaiguanghe** [comment]
i think longest match  would be more reasonable。why not find all matched route and chose the longest？ why the design？

**Comment by elithrar** [comment]
I don’t claim to know the _original_ design intent, but “longest path wins” is not a clear winner:

- What if two paths match?
- What if you have other non-path matchers - hosts, query params & methods? Which would win then?

First match wins is at least consistent - which can make things much simpler to debug.
