### ISSUE TITLE
can gorilla mux be used in product environment ? is there some examples ?

### ISSUE THREAD

**Issue by lianzeng** [gorilla/mux#461]
**What version of Go are you running?** (Paste the output of `go version`)
latest

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

latest

**Describe your problem** (and what you have tried so far)
i want to use gorrial mux to replace the native http.ServeMux in our product(object storage service), and i serach google, it show that Chi is similar with gorilla, but Chi are used in many company, so i want to know is there any company that use gorilla mux in product ?

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)
refer above describtion.

**Comment by elithrar** [comment]
https://godoc.org/github.com/gorilla/mux?importers

Docker & Kubernetes components both use mux.

I would say that mux & Chi aren’t so vastly different, though. Pick the
library with the API & documentation you understand best.

**Comment by lianzeng** [comment]
@elithrar 
Thanks  for your quick reply, i'm going to use Mux. it's really powerful and easy to understand.

**Comment by kisielk** [comment]
I became a maintainer of mux because I used it on several commercial projects. I was subsequently hired as a contractor on another few projects that also used mux. It's been a while since I've really had to use it a lot, but it's definitely suitable for production.
