### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by jonstacks** [gorilla/mux#467]
I would like to add something like [codecov.io](https://codecov.io/) to this project to help see where additional testing could be used. If this sounds good, I'd be glad to take this issue.

I'd also like to commit some common middlewares/features that I have in my own codebase that others might find useful. I think adding coverage would make it easy to see if I'm covering all paths through my code for any changes.

**Comment by elithrar** [comment]
I’m OK with codecov.

I’d like to know what middleware would be useful - my experience here is
that:

• it ends up needing to cover every use-case
• adds maintenance burden.

Most middleware is good as example code for the user to take & modify for
their own use-case.

**Comment by jonstacks** [comment]
Thanks for the quick response @elithrar. I'll go ahead and take adding codecov to the project.

One of the biggest ones that I think might be good, is to have a basic logging middleware that logs the request URI and the status code. I know there is a very basic example in the README, but I thought it might be nice to provide one out of the box for people to get going quickly and if it works for them, it means less code to copy/paste. Maybe it could even take in something that implements a logger interface so if someone was already using something like logrus, they could go ahead and just pass that in?

I was also looking at adding a ContentTypeMiddleware which checks the incoming `Content-Type` on the request and if it is not in a list of acceptable content types, it returns a `http.StatusUnsupportedMediaType` response.

I can open a separate issuse for the middleware though if you think this might be something others would use. I also understand that it might add more burden, so am fine leaving them out if you think so.

**Comment by jonstacks** [comment]
@elithrar, It looks like I could probably use the one in gorilla/handlers and make it a middleware like so, unless there is a better solution:

```go
func ContentTypeMiddleware(contentTypes ...string) func(http.Handler) http.Handler {
	return func(h http.Handler) http.Handler {
		return handlers.ContentTypeHandler(h, contentTypes...)
	}
}

r := mux.NewRouter()
r.Use(ContentTypeMiddleware("application/json", "text/html"))
```

Apologies for not finding that first.

**Comment by elithrar** [comment]
No problems.

The challenge with "logging middleware" (and I say this as the maintainer
of gorilla/handlers, which has one) is that:

- There's no standard logging interface
- Everyone wants a different log format (status code and URI, but then
bytes, and timing, and ...)
- etc

It starts to get complex, fast. I think mux works best as a component that
you wrap with other libraries using the http.Handler interface, rather than
trying to be gin, echo or other more "framework" like libraries.

**Comment by kisielk** [comment]
We also already have some logging middleware in gorilla/handlers ;)
