### ISSUE TITLE
Unexpected behaviours from router.handle when serving a static directory

### ISSUE THREAD

**Issue by tangsaidi** [gorilla/mux#469]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.11.5 darwin/amd64
go version go1.12.4 windows/amd64
Tested both

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)

c5c6c98bc25355028a63748a498942a6398ccd22

**Describe your problem** (and what you have tried so far)

I'm trying to serve a static directory using the standard mux router. But the server is only serving the top level contents, which means  I am not able to access any of the files nested inside the directory. Attemping to access the files lead to a 404 error. This behaviour is different from the behaviour of golang's net package `http.handle` which allows access to inner files. Is it specifically designed to be this way for some security reasons or a bug?

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

Here is the folder structure of a minimal project to demonstrate the problem
```
test
├── main.go
└── outer
    ├── index.html
    └── inner
        └── test.jpg
```
working directory would be within `test/`

**main.go**
The`main.go` code is a very simple serve that serves a static directory `outer/`. I wrote two versions of it, one with mux and one with net/http.

Version mux:
```
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()

	fs := http.FileServer(http.Dir("outer"))
	router.Handle("/static/", http.StripPrefix("/static/", fs))

	log.Println("Listening...")
	http.ListenAndServe(":3000", router)
}
```

Version net/http
```
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
)


func main() {
	fs := http.FileServer(http.Dir("outer"))
	http.Handle("/static/", http.StripPrefix("/static/", fs))

	log.Println("Listening...")
	http.ListenAndServe(":3000", nil)
}
```

**outer/index.html**
```
<h1>Hello world</h1>
<img src="inner/test.jpg" /> 
```

**outer/inner/test.jpg**
You may put any image in here

Then run `go build main.go` for two versions of `main.go` and go to `localhost:3000/static/`
The http/net loads image successfully, whereas the mux version fails to fetch.

net/http:
<img width="601" alt="Screen Shot 2019-04-22 at 5 22 24 PM" src="https://user-images.githubusercontent.com/22217989/56532181-4f49ad00-6523-11e9-9afc-a410cd88e35d.png">

mux:
<img width="425" alt="Screen Shot 2019-04-22 at 5 20 37 PM" src="https://user-images.githubusercontent.com/22217989/56532194-540e6100-6523-11e9-8536-df0c8d40f3ef.png">

**Comment by tangsaidi** [comment]
I just found a solution to this after reading more docs
```
func main() {
	router := mux.NewRouter()

	fs := http.FileServer(http.Dir("outer"))
	router.PathPrefix("/static/").Handler(http.StripPrefix("/static/", fs))

	log.Println("Listening...")
	http.ListenAndServe(":3000", router)
}
```
Solved the problem. Some explanations on the rationale of making it different from the default http would be appreciated. You may close the issue :D

**Comment by elithrar** [comment]
mux’s route matching mechanism is more strict (and more flexible) than the
net/http’s ServeMux, which is why you need to use PathPrefix.

net/http matches very loosely, but doesn’t have sub routers, regex, etc as
a result.
