### ISSUE TITLE
Regexp parentheses matching overwrites mux-defined keys

### ISSUE THREAD

**Issue by jadekler** [gorilla/mux#47]
NOTE: This may be similar / duplicate to issue #11.

Use case - avoiding duplication of 
```
r.HandleFunc("/user/view/{id:[0-9]+}", user.GetViewPage).Methods("GET")
r.HandleFunc("/user/{id:[0-9]+}", user.GetViewPage).Methods("GET")
```

With something like
```
r.HandleFunc("/user/{_:(view/)?}{id:[0-9]+}", user.GetViewPage).Methods("GET")
```

Results:
```
/user/5
2014/03/15 12:20:47 map[_: id:]
```
```
/user/view/5
2014/03/15 12:20:39 map[_:view/ id:view/]
```

As you can see, the regex matching view/ is somehow being assigned to id. The docs state that name:pattern matches a regexp pattern - as you can see above, this does not seem to be occurring properly.

**Comment by kisielk** [comment]
I believe this will be fixed in #117
