### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by omergunal** [gorilla/mux#470]
go version go1.6.3 linux/amd64

**What version of gorilla/mux are you at?** c5c6c98bc25355028a63748a498942a6398ccd22

When i type ```go get -u github.com/gorilla/mux``` , i got this error
```
package context: unrecognized import path "context" (import path does not begin with hostname)

```

**Comment by elithrar** [comment]
Upgrade your version of Go - Go 1.6 is very old.

**Comment by omergunal** [comment]
i upgraded to 1.12 and it solved
