### ISSUE TITLE
Strict Slashes don't work

### ISSUE THREAD

**Issue by swizzley** [gorilla/mux#472]
**What version of Go are you running?** (Paste the output of `go version`)
go version go1.12.5 darwin/amd64

**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
github.com/gorilla/mux v1.7.2

**Describe your problem** (and what you have tried so far)
rtr = mux.NewRouter().StrictSlash(true)
rtr.HandleFunc("/health/", health)

opening `/health` will always result in 404 instead of 301 

**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

```
package main

import (
	"github.com/gorilla/mux"
	"net/http"
	"encoding/json"
)

func main() {
	rtr := mux.NewRouter().StrictSlash(true)
	rtr.HandleFunc("/health/", health)
	s := &http.Server{
		Addr:           ":8080",
		Handler:        rtr,
	}
	s.ListenAndServe()

}

func health(w http.ResponseWriter, r *http.Request) {
	status := struct {
		Status string
	}{
		"OK",
	}
	w.Header().Set("Content-Type", "application/json")
	j, _ := json.Marshal(status)
	w.Write(j)
}
```

**Comment by elithrar** [comment]
Please upgrade to the latest version of mux - I'm not able to replicate
this on the latest version.

(5bbbb is from early 2018).

➜  curl -svL localhost:8080/health/ 2>&1 | rg '< HTTP'
< HTTP/1.1 200 OK
➜  curl -svL localhost:8080/health 2>&1 | rg '< HTTP'
< HTTP/1.1 301 Moved Permanently
< HTTP/1.1 200 OK

**Comment by msalcantara** [comment]
I'm usually configure my handle func more like this:

`rtr.HandleFunc("/health", health)`

and, when I call `/health` and `health/` I get status code 200 to both

**Comment by houspiller** [comment]
I have the same problem....

```
router := mux.NewRouter().StrictSlash(true)
	s := router.PathPrefix("/v0").Subrouter().StrictSlash(true)

	s.HandleFunc("/health/", HealthCheckHandler).Methods("GET")
	s.HandleFunc("/tags/", CreateTagHandler).Methods("POST")
	s.HandleFunc("/tags/", GetTagsHandler).Methods("GET")
```
1. The StrictSlash in subrouter dont work
2. When I post in tags without the final '/', the return is the GET. Its bizarre...

**Comment by elithrar** [comment]
Can you show how you're testing this?

**Comment by houspiller** [comment]
I made a post in Postman...

[POST] http://localhost:6000/v0/tags

and the body in response is the same body for the GET

**Comment by the-jackalope** [comment]
From the [docs](http://www.gorillatoolkit.org/pkg/mux#Router.StrictSlash)

> The re-direct is a HTTP 301 (Moved Permanently). Note that when this is set for routes with a non-idempotent method (e.g. POST, PUT), the subsequent re-directed request will be made as a GET by most clients. Use middleware or client settings to modify this behaviour as needed.

This may explain why some of you are hitting the GET handler instead of the POST when using strict slash.

**Comment by swizzley** [comment]
So I updated to the latest version of Mux and the issue persists

**Comment by elithrar** [comment]
It's not a _bug_ - this is the HTTP spec.

Returning a 301/302 to a POST/PUT/DELETE (any non-idempotent method) will
cause the client to retry as a GET, for safety.

Middleware can modify this to return a 307/308 instead, if need be.

**Comment by elithrar** [comment]
See my comments - https://github.com/gorilla/mux/issues/451#issuecomment-480126889 and [this full example of middleware](https://github.com/gorilla/mux/pull/465#issuecomment-480131080).
