### ISSUE TITLE
How to add a catch all handler after a FileServer handler? (needed for SPAs)

### ISSUE THREAD

**Issue by pablote** [gorilla/mux#475]
**What version of Go are you running?**
go version go1.12.5 darwin/amd64

**What version of gorilla/mux are you at?** 
v1.7.1

**Describe your problem** (and what you have tried so far)
I'm trying to add a catch all route handler after a FileServer route handler. Something like this:

```go
r.PathPrefix("/").Handler(http.FileServer(http.Dir("web2/public")))
r.Path("/*").Handler(&CatchAll{})
```

It seems that the FileServer it's always getting triggered, even if it doesn't find a matching file. The reason this is important is to support a SPA using the history browser API for routing. The idea is that any file found on / would get served, but if none found, then I would catch any route and serve the index file directly.

Is there anyway to handle this case?

**Comment by fharding1** [comment]
You're effectively telling `mux` to route all requests with path prefix `/` to your file server. `mux` doesn't do routing based off what the handler responds does. One solution would be to write a custom handler that checks if the file exists and uses the file server handler if it does, otherwise uses the catch all handler.

**Comment by elithrar** [comment]
Hi @pablote - let us know if you're still stuck. Closing for now, but re-open if you need more guidance!

**Comment by pablote** [comment]
Thanks, that helped. @fharding1 yea that was exactly what I meant and needed, do you know if such handler exists as part of gorilla or not already? That's exactly how the Express.js static handler works, and I though that it might be the same with this one. Thanks.

**Comment by fharding1** [comment]
Gorilla probably doesn't need to be concerned with this, the implementation could be as trivial as:

```
package main

import (
	"net/http"
	"os"
	"path/filepath"
)

func main() {
	const staticPath = "static"
	const indexPath = "index.html"

	fileServer := http.FileServer(http.Dir(staticPath))

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		path, err := filepath.Abs(r.URL.Path)
		if err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		path = filepath.Join(staticPath, path)

		_, err = os.Stat(path)
		if os.IsNotExist(err) {
			// file does not exist, serve index.html
			http.ServeFile(w, r, filepath.Join(staticPath, indexPath))
			return

		} else if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		fileServer.ServeHTTP(w, r)
	})

	http.ListenAndServe(":8080", nil)
}
```

```
➜  spa tree
.
├── go.mod
├── main.go
└── static
    ├── index.html
    └── js
        └── index.js

2 directories, 4 files
➜  spa curl localhost:8080 
<html>
</html>
➜  spa curl localhost:8080/js/index.js
console.log("hi");
➜  spa curl localhost:8080/nonexistent
<html>
</html>
```

**Comment by Kolakanmi** [comment]
I think, path = filepath.Join(staticPath, path) should be:
path = filepath.Join(staticPath, r.URL.Path)

**Comment by Kolakanmi** [comment]
> I think, path = filepath.Join(staticPath, path) should be:
> path = filepath.Join(staticPath, r.URL.Path)

path, err := filepath.Abs(r.URL.Path) returns the path joined with the current working directory. So, path = filepath.Join(staticPath, path) returns "static/C:/..."
