### ISSUE TITLE
route path

### ISSUE THREAD

**Issue by bluedragonflyliu** [gorilla/mux#479]
**What version of Go are you running?** (Paste the output of `go version`)

go1.11.5 linux/amd64
**What version of gorilla/mux are you at?** (Paste the output of `git rev-parse HEAD` inside `$GOPATH/src/github.com/gorilla/mux`)
ed099d42384823742bba0bf9a72b53b55c9e2e38

**Describe your problem** (and what you have tried so far)
tmplate
&lt; a class="play-btn" href="/play/64" &gt; video &lt; /a &gt;
router 
r := mux.NewRouter()
r.HandlerFunc("/",Index)
r.HandlerFunc("/play/{id}",Play)

I want when user click the button page will jump from index handler list to play page handler but some time it work some time it not, I can't Summarize the reasons, 
for example http://127.0.0.1:4567/play/1 is well but  http://127.0.0.1:4567/play/20 not  

play handler didn't do anything just fmt.Println(vars["id"])

I use go-micro frame
if anyone know how to solve the problem reply this thanks very much
**Paste a minimal, runnable, reproduction of your issue below** (use backticks to format it)

**Comment by elithrar** [comment]
Can you share more code? There is no reason the lines you have posted would
not “work”.

**Comment by bluedragonflyliu** [comment]
I try many time may bee cause by session.

**Comment by bluedragonflyliu** [comment]
because when I change machine or change service port it will be OK. thanks any way
