### ISSUE TITLE
Using a same name route wont distinguish based on request method

### ISSUE THREAD

**Issue by Faiz09** [gorilla/mux#480]
go version: `go version go1.12.4 linux/amd64`
What version of gorilla/mux are you at? `ed099d42384823742bba0bf9a72b53b55c9e2e38`

**My problem**
1. Using a same name route for both GET,POST always execute the first route, not deciding based on the method i guess but rather whenever the first name matches? 

```    
r.HandleFunc("/user/register", handler)
r.HandleFunc("/user/register", handler).Methods("POST")
```
I always get a response from the first route.

**Comment by elithrar** [comment]
mux (as per the docs) uses the first matching route.

Since the first route here accepts any method, a POST will match that and
not the second.

Either specify a .Methods() on the first route to make it more specific, or
swap the order.
