### ISSUE TITLE
"assignment to entry in nil map" in document

### ISSUE THREAD

**Issue by darknoll** [gorilla/mux#488]
amw := authenticationMiddleware{}
amw.Populate()

---------------------------------
amw := authenticationMiddleware{}
amw.tokenUsers = make(map[string]string)
amw.Populate()

**Comment by fharding1** [comment]
Runnable example: https://play.golang.org/p/a45X5e78c0h

**Comment by fharding1** [comment]
@darknoll I've opened a PR to fix this issue here: https://github.com/gorilla/mux/pull/489
