### ISSUE TITLE
[feature] Convert path to regexp

### ISSUE THREAD

**Issue by poy** [gorilla/mux#496]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

I can't use a path definition from Mux in something like Istio where it accepts regexp.

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

A function that converts a path to regexp for me to use in my configuration.

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

I've considered using a node project (https://github.com/pillarjs/path-to-regexp) to create the configuration, but this is till not a one-to-one. It also complicates the stack and risks translation bugs.

**Comment by elithrar** [comment]
Can you provide more details here?

You want to export paths in mux to regexp? mux paths can be defined as RE2
regexp patterns.

What is the output you expect / input into Istio config?

**Comment by poy** [comment]
> You want to export paths in mux to regexp?

Yes! There are quite a few apps that have a path of something like the following:
```
/v1/foo/{varable-1}/bar/{variable-2}
/v2/foo/{varable-1}/bar/{variable-2}
/v1/baz/
```
Where each path is serviced (ideally) by a different service. To do this though, Istio would require us to provide a regexp pattern. Building by hand the regexp of these paths isn't straightforward and error prone.

So it would be great if Route we could somehow convert the aforementioned paths into a regexp pattern.

**Comment by fharding1** [comment]
@poy something like this? https://play.golang.org/p/J0n7EHgZirr

**Comment by elithrar** [comment]
Yep, was just going to say that [`GetPathRegexp`](https://godoc.org/github.com/gorilla/mux#Route.GetPathRegexp) can handle this.

```go
	s, err := r.HandleFunc("/{name}/{action}", nil).GetPathRegexp()
```

... outputs:

```
^/(?P<v0>[^/]+)/(?P<v1>[^/]+)$
```

**Comment by poy** [comment]
Ah perfect! Thanks!
