### ISSUE TITLE
Route to Headers

### ISSUE THREAD

**Issue by varyumin** [gorilla/mux#497]
**Describe the problem you're having**
> Hi everyone!
I need to check requests custom Headers. If there is a header "X-Auth-Username" then will be a route to the web resources. 
…

**Versions**
> Go version: `go version go1.12.1 darwin/amd64`

> package version: run `8df51d95f8dffec20bcdb1cf60f8156e79de1298` inside the repo

…

**"Show me the code!"**
```
r := mux.NewRouter()
r.HandleFunc("/", h.HomeHandler).Headers("X-Auth-Username")
log.Printf("Web Server to 0.0.0.0:%v", p.Port)
srv := &http.Server{
  Handler:      r,
  Addr:         fmt.Sprintf(":%v", p.Port),
  WriteTimeout: time.Duration(p.WriteTimeOut) * time.Second,
  ReadTimeout:  time.Duration(p.ReadTimeOut) * time.Second,
}
if err := srv.ListenAndServe(); err != nil {
  log.Fatal(err)
}
```
**"Test"**
`curl -v -H "X-Auth-Username: user" http://127.0.0.1:9000`
```
* Rebuilt URL to: http://127.0.0.1:9000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: curl/7.54.0
> Accept: */*
> X-Auth-Username: user
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 04 Jul 2019 08:29:45 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 127.0.0.1 left intact
```
if I delete `.Headers("X-Auth-Username")` then I will get 200 OK

Can anyone help me? Do you have any ideas? What's the problem?
…

**Comment by elithrar** [comment]
See the docs for the `.Headers()` method: https://godoc.org/github.com/gorilla/mux#Route.Headers

> Headers adds a matcher for request header values. It accepts a sequence of key/value pairs to be matched. For example:
> The above route will only match if both request header values match. If the value is an empty string, it will match any value if the key is set.

If you only care about the header key being present, then:

```go
// note the empty string to denote "any value".
r.HandleFunc("/", h.HomeHandler).Headers("X-Auth-Username", "")
```
Let me know if any other questions!

**Comment by varyumin** [comment]
@elithrar Thx it solved my problem! You rock! And yes I skipped this is descriptions.
