### ISSUE TITLE
Multi-package issues with context bound data

### ISSUE THREAD

**Issue by dhaavi** [gorilla/mux#498]
I just resolved a _very interesting_ issue after pounding my head at it for a whole day.

This is not mux's fault (I think), but I want to report here, so that everyone is aware of this:

I am working on a big project that is split into multiple repos. Every repo has its own dependency state (golang dep) - and its own vendor folder. When compiling, every project takes dependencies from its own project folder.

I have set up a mux.Router in one project and then attempted to read path variables from the request in the other project. The variables were always empty!

Why? Because how `context` handles keys, they are somehow different depending on their source. So the vars get set with
`projectA/vendor/github.com/gorilla/mux.varsKey`
and then I tried to read the vars with
`projectB/vendor/github.com/gorilla/mux.varsKey`,
a different key.

At least this is how I understand it right now.

After understanding the problem, the fix was really easy. `projectA` now has a new function:
```
func GetMuxVars(r *http.Request) map[string]string {
	return mux.Vars(r)
}
```
Which is then called by `projectB`, instead of using `mux.Vars(r)` directly.

Maybe this is fixable, if not, please mention this in the docs!

**Comment by elithrar** [comment]
Good catch - I'd expect this is _very_ rare, but we'll probably see a little more of it as users adopt Modules more broadly (the other dep/vendoring tools were fairly niche).

The root cause is because the types[1] aren't equivalent (by design) - the two distinct import paths mean the two versions of mux are effectively different packages.

Is there a driving reason for having two different vendored versions of mux? Are both the packages vendoring it yours?



[1]: https://github.com/gorilla/mux/blob/master/mux.go#L422-L427

**Comment by dhaavi** [comment]
I am not sure if this actually affects go modules, as they make vendoring optional and I _think_ also share a cache between projects. So as long as the different repos/packages use the exact same version, they should not run into this problem.

No, there is no reason to have it vendored two times, but that is just how `dep` works. I chose `dep` because it is the other official tool, and I felt that go modules are not yet mature enough and would cost me more time than I want to spend on dependency management. Well, seems no approach is really mature yet.

To elaborate on the decision:
Support for `simultaneous edits of interdependent modules` is still being discussed: https://github.com/golang/go/issues/27542. All solutions to this with go modules seem very hacky at the moment.
With the (official) `dep` tool, I can use dependency management and still use `GOPATH` for local development.
