### ISSUE TITLE
how to define a router that can match all requests to the server

### ISSUE THREAD

**Issue by qibobo** [gorilla/mux#500]
I want to define a router that can match all requests, for example:

curl http://localhost:8080
curl http://localhost:8080/
curl http://localhost:8080/some
curl http://localhost:8080/some/some/some

Is there a way in mux to do it?

**Comment by elithrar** [comment]
r := mux.NewRouter()
r.PathPrefix(“/“).HandlerFunc(...)

https://godoc.org/github.com/gorilla/mux#Router.PathPrefix
