### ISSUE TITLE
use router.PathPrefix  Matching twice

### ISSUE THREAD

**Issue by hyahm** [gorilla/mux#504]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
Match handle `Index` twice
…

**Versions**
> Go version: `1.12.5`

> package version: run `git rev-parse HEAD` inside the repo
```
github.com/gorilla/mux v1.7.3
```
…

```
import (
	"fmt"
	"github.com/gorilla/mux"
	"log"
	"net/http"
)

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.Method)
	fmt.Println(11111)
}

func HttpServer() {
	router := mux.NewRouter()
	//route.HandleFunc("/hello", Hello)
	router.PathPrefix("/").HandlerFunc(Index)
	if err := http.ListenAndServe(":9999",router); err != nil {
		log.Fatal(err)
	}
}
```
> open url `localhost:9999` on browser this  result is
```
GET
11111
GET
11111
```

**Comment by elithrar** [comment]
The answer is that your browser is making a request for a favicon ☺️
