### ISSUE TITLE
[docs] - 

### ISSUE THREAD

**Issue by RavenHursT** [gorilla/mux#506]
Would be nice to have all the snippets in the documentation have complete import statements of all the packages referenced in each snippet code.

When a new Gopher comes along, trying to learn, and comes across a snippet like below.. It makes it really tough when snippets like this can't just be copy/pasted into things like, https://play.golang.org/ w/o first investigating and figuring out which packages need to be included.  There's nothing in the code snippet to _explicitly_ tell the Gopher where things like, `http`, `mux`, `httptest`, `fmt`, etc are coming from.

I know to a lot of seasoned folks, these things may seem "obvious" to them... But to new Gophers trying to learn how to use Golang, it's a big stumbling block...

![image](https://user-images.githubusercontent.com/496983/62718931-6fb34f80-b9cc-11e9-9740-d5b0595380c9.png)

**Comment by elithrar** [comment]
This is totally fair - although note that external package support only
came to the Playground pretty recently. L

Are you interested in PR’ing these improvements?

**Comment by RavenHursT** [comment]
Yeah.. I only used go playground as the example since it seems like the most widely used prototyping tool in Golangdom...  Personally, I've used Repl.it for years for a number of different server-side prototyping, and that's supported external packages for a while now..

Anyway.. yeah.. I could PR it.. if someone could maybe point me in the right direction... is it just `.md` file somewhere?

**Comment by RavenHursT** [comment]
Like I said... baby Gopher here. :/

**Comment by RavenHursT** [comment]
hmmm.. not seeing it here... https://github.com/gorilla/mux/blob/master/README.md#examples

**Comment by RavenHursT** [comment]
Trying to find the file for this example specifically: https://godoc.org/github.com/gorilla/mux#CORSMethodMiddleware

**Comment by elithrar** [comment]
Examples are typically in:

• files ending in _example.go
• the README.me
• doc.go

**Comment by RavenHursT** [comment]
Ok... let me see if I can do it...
