### ISSUE TITLE
[bug] Query parameters defined in route aren't matched on index route

### ISSUE THREAD

**Issue by ryan-berger** [gorilla/mux#507]
**Describe the bug**

When defining a route at the index "/", query parameters are not correctly matched.

I have a route that has an optional query parameter, so I defined the routes as such:

```go

subRouter := router.
		PathPrefix("/assignments").
		Subrouter()

subRouter.
		Path("/").
		Methods("GET").
		HandlerFunc(myFunc)

subRouter.
		Path("/").
		Methods("GET").
		Queries("classID", "{classID:[0-9]+}").
		HandlerFunc(myFunc2)
```

I made a request to `/assignments/?classID=10` but rather than `myFunc2` being called, `myFunc` was called. When I changed the order of the route definitions as such:

```go
subRouter.
		Path("/").
		Methods("GET").
		Queries("classID", "{classID:[0-9]+}").
		HandlerFunc(myFunc2)

subRouter.
		Path("/").
		Methods("GET").
		HandlerFunc(myFunc)
```

`myFunc` is now only called when requesting `/assignments/` and `myFunc2` is now called when requesting `/assignments/?classID=10` which is the correct behavior. 

…

**Versions**
> Go version: `go version` 1.12.5
> package version: run `git rev-parse HEAD` inside the repo: From my go.mod file: `	github.com/gorilla/mux v1.6.2`

…

**Steps to Reproduce**
> How can the bug be triggered?

Create a subrouter (not sure if this matters) and give it an index "/" route without query parameters and an index route with query parameters

…

**Expected behavior**
> What output or behaviour were you expecting instead?

I expect that `myFunc` shouldn't be called if I have a `?classID` because it is not a route match, just like I wouldn't expect `myFunc2` to be called if I didn't have a `?classID`

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).
```go

subRouter := router.
		PathPrefix("/assignments").
		Subrouter()

subRouter.
		Path("/").
		Methods("GET").
		HandlerFunc(myFunc)

subRouter.
		Path("/").
		Methods("GET").
		Queries("classID", "{classID:[0-9]+}").
		HandlerFunc(myFunc2)
```
…

**Comment by elithrar** [comment]
> I expect that myFunc shouldn't be called if I have a ?classID because it is not a route match, just like I wouldn't expect myFunc2 to be called if I didn't have a ?classID

Both routes match. A route that defines `/` as a path with no other matchers says "I will match on the explicit path `/` and on any method, with any headers or query params".

The reason it "changes" is that mux's matching is "first match wins" as per https://github.com/gorilla/mux#matching-routes

> Routes are tested in the order they were added to the router. If two routes match, the first one wins:

Your option would be to use route parameters instead of query parameters, which will give better control over your matching  e.g. `.Path("/class/{classID:[0-9]+}")` will match on `/class/1437138` or `/class/42`

Alternatively, use a handler that looks for any query parameters, and then calls the next handler - e.g. your handler on `/` is a proxy for other handlers.

**Comment by ryan-berger** [comment]
That makes sense. However, is the `/` route a special case? I haven't ever noticed this behavior doing this with exact paths like if I just put all the routes on the `/assignments/` route.

Also, am I missing the point of a sub-router? I thought that a sub-router was supposed to act as a proxy so that when I have a sub-router on `/assignments` and define a `/` route, it will truly be handling for `/assignments/` rather than acting on it's own and handling a catch-all `/`

**Comment by elithrar** [comment]
The “/“ path would be the only match if you had “/“ and “/classes” - but
what you have is two “/“ paths, and one of them matches “any” query params.

Hence, putting that route first will cause it to match any request with a
path of “/“.
