### ISSUE TITLE
Add SECURITY.md to outline how to report security vulnerabilities

### ISSUE THREAD

**Issue by fharding1** [gorilla/mux#512]
It would be good to have a process outlined for reporting high risk security vulnerabilities to gorilla/mux contributors outside of Github.

Stuff like this: https://github.com/gorilla/mux/issues/511

**Comment by elithrar** [comment]
Thanks. There is also a developer contact email at https://github.com/gorilla

**Comment by elithrar** [comment]
See https://github.com/gorilla/.github/blob/master/SECURITY.md

**Comment by elithrar** [comment]
This should show up on all gorilla/* repos now. Thanks for reminding me, @fharding1!
