### ISSUE TITLE
[question] Routes return 404 errors when accessed via FastCGI

### ISSUE THREAD

**Issue by jollyrogue** [gorilla/mux#518]
**Describe the problem you're having**
I'm having some issues getting Gorilla Mux and FastCGI to work together. This was working several weeks ago when I started experimenting, and now it's not, which is leaving me stumped.

The routes work fine when I'm using the Go webserver, but I get a "404 page not found" error from the binary on the Dreamhost server when accessing routes via fcgi.

I have a basic helloworld example using the http.HandleFunc() as a control sample, and it works fine on the Dreamhost server. 

Dreamhost documentation on fastcgi:
https://help.dreamhost.com/hc/en-us/articles/217298967-FastCGI-overview

**Versions**
- Go version: go1.12.9
- Package version: 884b5ffcbd3a11b730f0b75f5c86ac408753c34d
- Host: Dreamhost shared hosting
    - Description: Ubuntu 18.04.2 LTS
    - Apache with mod_fastcgi

**"Show me the code!"**
Minimal problematic example:
```
package main

import (
        "flag"
        "io"
        "log"
        "net/http"
        "net/http/fcgi"
        "runtime"

        "github.com/gorilla/mux"
)

var (
        local = flag.String("local", "", "serve as webserver, example: 0.0.0.0:8000")
)

func init() {
        runtime.GOMAXPROCS(runtime.NumCPU())
}

func homeView(w http.ResponseWriter, r *http.Request) {
        headers := w.Header()
        headers.Add("Content-Type", "text/html")
        io.WriteString(w, "<html><head></head><body><p>It works!</p></body></html>")
}

func main() {
        r := mux.NewRouter()

        r.HandleFunc("/", homeView)

        flag.Parse()
        var err error

        if *local != "" { // Run as a local web server
                err = http.ListenAndServe(*local, r)
        } else { // Run as FCGI via standard I/O
                err = fcgi.Serve(nil, r)
        }

        if err != nil {
                log.Fatal(err)
        }
}
```

Working code using http.HandleFunc().
```
package main

import (
	"fmt"
	"net/http"
	"net/http/fcgi"
)

func handler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-type", "text/plain; charset=utf-8")
	fmt.Fprintln(w, "This was generated by Go running as a FastCGI app")
}

func main() {
	http.HandleFunc("/", handler)

	if err := fcgi.Serve(nil, nil); err != nil {
		panic(err)
	}
}
```

**Comment by elithrar** [comment]
What is the full request path that the handler receives? e.g. `fmt.Fprintln(w, r.URL.String())`

The standard library router is much less strict about route matching.

**Comment by jollyrogue** [comment]
`https://dev.psi-green.net/dz/hello1.fcgi`

I'm working off the assumption the binary is matching whatever comes after `hello1.fcgi`. Like `hello1.fcgi/timeanddate` would match to the `timeanddate` route.

Is that a bad assumption to make?

**Comment by elithrar** [comment]
Depends what the FCGI process is passing to the Go server. Printing r.URL
will help.

**Comment by jollyrogue** [comment]
I'm sorry I wasn't clear. The working binary is at `https://dev.psi-green.net/dz/hello1.fcgi`, and it returns `https://dev.psi-green.net/dz/hello1.fcgi`.

Setting `r.HandleFunc("/dz/gorilla.fcgi", homeView)` works. 

Now the questions becomes how can that be trimmed since I don't have control of the server, and I'm limited to standard IO. :\

Anyway, I can work through that part now that the problem has been pinpointed. Thanks for the help!
