### ISSUE TITLE
[feature] allow to set additional documentation/help per route

### ISSUE THREAD

**Issue by klingtnet** [gorilla/mux#519]
I want to automatically generate a simple API documentation.
Unfortunately, this is currently limited to path, methods and an optional route name ([here is a simple usage example](https://play.golang.org/p/8IjNmUYKaAh)).

What I suggest is to add a `Help(msg string)` or `Help(doc interface{})` method to the router so one can add additional per route documentation.
A default documentation renderer that supports HTML/JSON output could also be provided  by default.

**Comment by elithrar** [comment]
What other information do you specifically want to attach to a Route?

**Comment by klingtnet** [comment]
@elithrar In the simplest case a string that stores a short resource description and in a more complex solution an `interface{}` value that can act like a "route context" for generating more detailed resource descriptions.

**Comment by klingtnet** [comment]
The documentation can then be generated by walking over all routes, as shown in the example linked in my initial comment.
