### ISSUE TITLE
Why is this not working ?

### ISSUE THREAD

**Issue by sonoman** [gorilla/mux#520]
**Describe the problem you're having**
> I have an endpoint with a query string variable that, if present, it should have the values "true" or "false", nothing else

the code is following 

`r.Path("/mypath/myendpoint").Queries("self", "(true|false)").HandlerFunc(updateInfo)`

I'm trying 
/mypath/myendpoint?self=false or 
/mypath/myendpoint?self=true

No luck. it always return  404

**Comment by andrewpillar** [comment]
> r.Path("/mypath/myendpoint").Queries("self",
> "(true|false)").HandlerFunc(updateInfo)

Have you tried the doing `{self:true|false}`? This seems to work for me
when I do it.
