### ISSUE TITLE
[question] Am I able to server an API and a website (static files) at the same time?

### ISSUE THREAD

**Issue by qb1tt** [gorilla/mux#521]
**Describe the problem you're having**
> A clear and concise description of what the problem is.

Greetings,
I'm currently working on a project which requires me to have server that can serve a website and an API at the same time.

I'm trying to serve:
- the website on "localhost:8080/----/----" or "localhost:8080/page/----/----"
- and the api on "localhost:8080/api/----/----"

I've tried a lot of different approaches but so far I have been unable to get the thing working.
Can I serve a "static site" and an API at the same time on two different routes?
…

**Versions**
> Go version: `go version go1.13 windows/amd64`

> package version: v1.7.3

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
```go
func main() {
	apiRtr := mux.NewRouter()
	apiRtr.HandleFunc("/admin/login", func(writer http.ResponseWriter, req *http.Request) {
		io.WriteString(writer, "Login")
	})
	apiRtr.HandleFunc("/participant/{name}/buzzer/trigger/", func(writer http.ResponseWriter, req *http.Request) {
		io.WriteString(writer, "Trigger")
	}).Methods("POST")

	mainRtr := mux.NewRouter()
	mainRtr.Handle("/", http.FileServer(http.Dir("./static/")))
	mainRtr.Handle("/api", apiRtr)

	srvr := &http.Server{
		Handler:      mainRtr,
		Addr:         "127.0.0.1:8080",
		WriteTimeout: 15 * time.Second,
		ReadTimeout:  15 * time.Second,
	}

	log.Fatalln(srvr.ListenAndServe())
}
```
FYI: I've tried a lot of different approaches. This is my previous one. I've tried so many approaches that I'm actually unable to list all of them.
…

**Comment by fharding1** [comment]
@qb1tt you might be able to do something like this:

```go
package main

import (
	"io"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()

	apiSubrouter := router.PathPrefix("/api/").Subrouter()

	apiSubrouter.HandleFunc("/admin/login", func(writer http.ResponseWriter, req *http.Request) {
		io.WriteString(writer, "Login")
	})
	apiSubrouter.HandleFunc("/participant/{name}/buzzer/trigger/", func(writer http.ResponseWriter, req *http.Request) {
		io.WriteString(writer, "Trigger")
	}).Methods("POST")

	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./static/")))

	log.Fatalln(http.ListenAndServe(":8080", router))
}
```

**Comment by qb1tt** [comment]
> It's also fairly common to use a server like NGINX to handle serving your frontend and routing your API requests to a server, so that might be another approach to look into.
Yeah I'm aware of that. That would have been the second choice if the current approach or "idea" wouldn't work.

> you might be able to do something like this (the trick is using PathPrefix rather than Handle):
So I did try it with the code you posted and the file server just works fine. But still, I'm unable to reach my API endpoints. `http://localhost:8080/api/admin/login` responds with `404 page not found`

**Comment by qb1tt** [comment]
WAIT HOLD ON A SECOND.

I re-arranged the code you posted to structure it a bit more well. Turns out that the re-arrangement is the reason why the API endpoints don't get recognized.

Thank you very much for the quick response!

**Comment by fharding1** [comment]
Glad I could help out!

**Comment by qb1tt** [comment]
Still encountered a problem: `localhost:8080/api/participant/marzy/buzzer/trigger` doesn't work properly.

The handler is defined like this but the server responds with `404`
```
apiSubrouter.HandleFunc("/participant/{name}/buzzer/trigger", func(writer http.ResponseWriter, req *http.Request) {
	io.WriteString(writer, "Trigger")
}).Methods("POST")
```

**Comment by fharding1** [comment]
It looks like you specified method POST there, are you testing with POST?

**Comment by qb1tt** [comment]
No, I tried with a plain GET request via my web browser.

I just made a POST request with Postman and it works, but normally I'd get a 405 response if I'd try accessing the API endpoint via GET in the web browser. That doesn't happen anymore. 

By all means, it works, the server responds with 404 when accessing with the web browser, but it feels kinda wrong.
