### ISSUE TITLE
[bug] empty subdomain is not recognised in version 1.7.3

### ISSUE THREAD

**Issue by sauravhaloi** [gorilla/mux#522]
**Describe the bug**
> A clear and concise description of what the bug is.

My application was using Mux version 1.6.1 and we have dynamic subdomain support implemented. We need the route to match both with/without a subdomain, basically match both the below routes:

http://localhost:8080
http://subdomain.localhost:8080

However, after upgrading to Mux version 1.7.3, an empty subdomain is not getting recognized and I am getting an HTTP 404. Meaning, _http://subdomain.localhost:8080_ is recognized as a route while _http://localhost:8080_ is not.

Is this is a potential regression, or the support for dynamic subdomain (a route with optional subdomain) is removed altogether? The route.go file seem to have changed a lot between the two version.
…

**Versions**
> Go version: `go version`: 1..13 (Linux, amd64)
> package version: run `git rev-parse HEAD` inside the repo
commit 00bdffe0f3c77e27d2cf6f5c70232a2d3e4d9c15 (HEAD, tag: v1.7.3)

…

**Steps to Reproduce**
> How can the bug be triggered?
…

Application code working in version 1.6.1 with dynamic subdomain won't work in 1.7.3

**Expected behavior**
> What output or behavior were you expecting instead?

After upgrading to 1.7.3, it was expected that the the application code would work as it is with 1.6.1
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

Working code with Mux version 1.6.1:

```
subRouter := r.Host("{subdomain:[a-zA-Z0-9\\-]*}" + "." + "locahost").Subrouter()
serveMux = http.NewServeMux()
serveMux.Handle("/", subRouter)
```

Any help will be highly appreciated. Thanks.

**Comment by elithrar** [comment]
See the changes in
https://github.com/gorilla/mux/releases/tag/v1.7.0 and
https://github.com/gorilla/mux/releases/tag/v1.7.2

**Comment by sauravhaloi** [comment]
Thanks for your reply @elithrar 
If you referred to the host:port matching incorporated in 1.7.0 and later relaxed in 1.7.2, the issue I observed with 1.7.3 vs. 1.6.1 looks different than that. 

```
subRouter := r.Host("{subdomain:[a-zA-Z0-9\\-]*}" + "." + "example.com").Subrouter()
serveMux = http.NewServeMux()
serveMux.Handle("/", subRouter)
```

The above piece of code, in version 1.6.1, with the regex for dynamic subdomain used to match an URL endpoint both with and without a subdomain. Both the following is matched:

_http://subdomain.example.com_ as well as _http://example.com_ 

However, in version 1.7.3, it can't match an URL endpoint without a subdomain. Only _http://subdomain.example.com_ is matched, and I get a 404 error for _http://example.com_ 

For now, I have downgraded my application to use Mux 1.6.1. But I really want to move to 1.7.3 for all the latest updates and improvements.

**Comment by elithrar** [comment]
Does the same problem exist if you use mux in full?

```
subRouter := r.Host("{subdomain:[a-zA-Z0-9\\-]*}" + "." + "locahost").Subrouter()
serveMux = mux.NewRouter()
serveMux.Handle("/", subRouter)
```

I haven’t validated your matching logic to see whether it’s valid - but the regex `*` looks potentially suspect?

**Comment by sauravhaloi** [comment]
I tried using mux in full, but to no avail.

For the following code:

```
package main
import(
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"log"
)

func Index(w http.ResponseWriter,req *http.Request){
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("Hello World!"))
}

func main(){
	fmt.Println("starting server...")

	r := mux.NewRouter().StrictSlash(true)
	s := r.Host("{subdomain:[a-zA-Z0-9\\-]*}" + "." + "localhost").Subrouter()
	s.HandleFunc("/",Index).Methods("GET")

	log.Fatal(http.ListenAndServe(":8081", s))
}
```
Here the outcomes with version 1.7.3:

```
$ curl -iX GET http://localhost:8081/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 10 Oct 2019 07:17:20 GMT
Content-Length: 19

404 page not found

$ curl -iX GET http://home.localhost:8081/
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 10 Oct 2019 07:17:26 GMT
Content-Length: 12

Hello World!
```

The Host regex generated for both 1.6.1 and 1.7.3 is: _^(?P<v0>[a-zA-Z0-9\-]*)\.localhost$_

There has been significant changes to SubRouter code between the two version as in 1.7.3, the whole parent route thingy is omitted. Do you think this is a regression?

I was just wondering how to accomplish a true wildcard dynamic subdomain in mux 1.7.3. Basically, to make the subdomain part optional in the host.

Thanks.
