### ISSUE TITLE
[bug] Timeouts not doing anything?

### ISSUE THREAD

**Issue by danfinn** [gorilla/mux#527]
I was playing around with your basic code examples this evening and I might be doing something wrong but it doesn't seem like the Timeouts that you suggest setting are actually doing anything?

```
package main

import (
        "flag"
        "github.com/gorilla/mux"
        "log"
        "net/http"
        "time"
)


func main() {
    var dir string

    flag.StringVar(&dir, "dir", ".", "the directory to serve files from. Defaults to the current dir")
    flag.Parse()
    r := mux.NewRouter()

    // This will serve files under http://localhost:8000/static/<filename>
    r.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir(dir))))

    srv := &http.Server{
        Handler:      r,
        Addr:         "127.0.0.1:8000",
        // Good practice: enforce timeouts for servers you create!
        WriteTimeout: 15 * time.Second,
        ReadTimeout:  15 * time.Second,
        IdleTimeout:  15 * time.Second,
    }

    log.Fatal(srv.ListenAndServe())
}
```

Running this I'd expect it to exit at 15 seconds but it continues to run indefinitely.  Am I missing something (highly likely)?

**Comment by elithrar** [comment]
What are you expecting to time out - the server? A connection?

Understanding how you are testing this will help me explain it.

**Comment by danfinn** [comment]
Sorry, should have been more clear.  I was assuming the code would exit, specifically when IdleTimeout was hit.

**Comment by elithrar** [comment]
Idle timeout will close the server side of the TCP connection, not the
server.

See the godoc for the *Timeout fields of http.Server here:
https://golang.org/pkg/net/http/#Server
