### ISSUE TITLE
[bug] mux@v1.7.3.debug.exe is not executable

### ISSUE THREAD

**Issue by imatmati** [gorilla/mux#529]
**Describe the bug**
> A clear and concise description of what the bug is.

On a Windows 10 64 bits platform, create a web application.
Set a breakpoint inside an IDE like LiteIDE.
Install Delve as debugger then start debugging.
The message is 
.... go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux@v1.7.3.debug.exe is not executable

When running the executable directly from command line the message from Windows is even more explicit : 16 bits Application not allowed (translated from the french message on my computer).

**Versions**
> Go version: `go version`
go version go1.13.3 windows/amd64

**Comment by elithrar** [comment]
This sounds unrelated to mux - and is likely a Delve issue.

What version of Delve is installed, and have you considered opening a bug
against Delve?

**Comment by imatmati** [comment]
Hi elithar,

I suspected Mux because when I try to execute the debug.exe, it fails directly from Windows not from Delve. Have a nice day.
