### ISSUE TITLE
[bug] Host matching not work without scheme?

### ISSUE THREAD

**Issue by pierreneter** [gorilla/mux#530]
**Describe the bug**

About: Matching Routes - Host

> https://github.com/gorilla/mux#matching-routes

The docs:

```go
r := mux.NewRouter()
// Only matches if domain is "www.example.com".
r.Host("www.example.com") // this
// Matches a dynamic subdomain.
r.Host("{subdomain:[a-z]+}.example.com")
```

It will not work if `the host` is passed in without a scheme.

**Versions**
> Go version: `go version go1.13.4 darwin/amd64`
> package version: `github.com/gorilla/mux v1.7.3`

**Steps to Reproduce / Code Snippets**

This not work:

```go
func main() {
	r := mux.NewRouter()
	r.Host("localhost:8080")
	r.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	}))
	http.ListenAndServe(":8080", r)
}
```

This work:

```go
func main() {
	r := mux.NewRouter()
	r.Host("http://localhost:8080")
	r.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	}))
	http.ListenAndServe(":8080", r)
}
```

**Expected behavior**

Work without scheme

**Comment by 76creates** [comment]
also to add:
when you match host like `r.Host("localhost:8080")` it acts as a inverse, allowing all but that host
when you match like `r.Host("http://localhost:8080")` it allows all hosts regardless

I found it only working as expected when you chain `.Host(...)` to the `r.Handle(...)`

**Comment by elithrar** [comment]
The examples in the docs may be a little confusing.

If you say `r.Host` without attaching a `Route`, you've created a matcher without a subsequent handler to call - which is why you see it "not allowing" that host.

You should either:

```
s := r.Host("sub.example.com").Subrouter()
s.HandleFunc("/", yourHandler)
```

... or use `.PathPrefix` to match all requests to that host. Calling `r.Host` on its own will effectively blackhole the matches.

**Comment by fharding1** [comment]
I've seen a few issues from people confused by this behavior, and I think it's just the nature of the builder pattern mux uses. It makes sense, it's just not very intuitive to people new to mux. It could help to add a sentence to the Matching Routes section of the README that says something along the lines of: "Matchers without attached handlers will still match routes, however they will 404, even taking priority over routes with handlers (if added first)." with maybe an example similar to @pierreneter 's.

**Comment by elithrar** [comment]
Agree. I think a new “How does mux Match Routes?” section in the README /
doc.go is warranted.

**Comment by teraflik** [comment]
I think https://github.com/gorilla/mux/pull/474 should resolve this.
