### ISSUE TITLE
1.7.3: router Schemes, doesn't work after "go mod init"?

### ISSUE THREAD

**Issue by bitsofinfo** [gorilla/mux#531]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

```
	router := mux.NewRouter()
	router.Path("/token/create-orphan").
		Methods("POST").
		Schemes("https").
		Headers("Content-Type", "application/json").
		HandlerFunc(CreateOrphanTokenHandler)
...
	srv := &http.Server{
		Handler: router,
...
```

When I do a POST to https://localhost:[myport]/token/create-orphan everything works as expected.

However, after I do a `go mod init; go build` then re-run my project, the POST fails with a 404. 

The only way I can get it work work after the `go mod init` change is when I comment out the `Schemes()` call.... which seems odd

When I remove the `go.mod/go.sum` and rebuild, then it works again with the `Schemes()` re-enabled.

**Versions**

mux: 1.7.3
go version go1.13.3 darwin/amd64

go.mod
```
...
require (
	github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
	github.com/gorilla/mux v1.7.3
	github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749 // indirect
	github.com/shurcooL/vfsgen v0.0.0-20181202132449-6a9ea43bcacd // indirect
	github.com/sirupsen/logrus v1.4.2
	github.com/tidwall/gjson v1.3.4
)
```

**"Show me the code!"**

See above

**Comment by fharding1** [comment]
@bitsofinfo Schemes was (sort of) broken in 1.7.3. Can you try running `go get github.com/gorilla/mux@master` after `go mod init` and see if running against master works for you (since AFAIK a release hasn't been cut)?

**Comment by bitsofinfo** [comment]
@fharding1 yes doing that fixes it.

However I'm confused, when I remove `go.mod`.... what version am I then using that works?

**Comment by bitsofinfo** [comment]
ah, its `master`... so fix must be in there 

I guess I could force 1.7.2 usage as well which might fix it for me.

**Comment by fharding1** [comment]
Yeah it would be falling back to whatever is in your $GOPATH without go.mod I believe. The issue was fixed in ff4e71f144166b1dfe3017a146f8ed32a82e688b, it is not fixed on 1.7.2.

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
this problem still exists! just started another project and burned another 2 hours repeating myself leading me back to this very issue again

**Comment by MarkSonghurst** [comment]
Ditto for me, Schemes("https") worked for me in v.1.7.3 but upgrading to v.1.7.4 means I always get a 404 response unless I comment out my call to Schemes(https)

**Comment by elithrar** [comment]
Looks like you’ve resolved this, but if there’s a specific documentation improvement that would help here, let me know.
