### ISSUE TITLE
[bug] StrictSlash redirect ignores subpaths.

### ISSUE THREAD

**Issue by jannesbraet** [gorilla/mux#533]
**Describe the bug**
> A clear and concise description of what the bug is.

We have an application running in kubernetes with url www.example.com and subpath /customer/someone.

In this application we use the mux as follows:
```
import (
	"net/http"
	//etc...

	"github.com/gorilla/mux"
)

func queryHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("content-type", "text/plain")

	code, err := w.Write([]byte("status ok"))
	if err != nil {
		logrus.Errorf("Can't deliver response: %v (status %v)", err, code)
	}
}

func main() {
	router := mux.NewRouter()
	router.StrictSlash(true)
	router.Methods(http.MethodPost).Path("/query/").Handler(http.HandlerFunc(queryHandler))
}
```

Now if a request to www.example.com/customer/someone/query is done the strictslash sees a missing slash and replies with a 301 REDIRECT to www.example.com/query/ thus omitting the subpath and this is not recognised by our ingress so we get a 404 eventually. I would expect the URL to go to www.example.com/customer/someone/query/

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

Go version: 

> go version go1.12.6 windows/amd64

> package version: d83b6ffe499a29cc05fc977988d0392851779620

**Steps to Reproduce**
> How can the bug be triggered?

Run a pod in kubernetes (or something similar) with an ingress that redirects the subpath to a certain pod. Inside that pod the code describe above causes an issue if a path without a slash is queried. 

**Expected behavior**
> What output or behaviour were you expecting instead?

I was expecting the path to stay after the redirect.

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

see original description

**Comment by DoubleDi** [comment]
@jannesbraet did you manage to solve this?

**Comment by jannesbraet** [comment]
I believe we eventually simply added a path for both the slash version and the non slash version:

router.Methods(http.MethodPost).Path("/query/").Handler(http.HandlerFunc(queryHandler))
router.Methods(http.MethodPost).Path("/query").Handler(http.HandlerFunc(queryHandler))

**Comment by DoubleDi** [comment]
Awesome! Thanks for the help!
So did you disable StrictSlash?

**Comment by jannesbraet** [comment]
Yes indeed
