### ISSUE TITLE
Example for SPA in README not working on windows

### ISSUE THREAD

**Issue by r03** [gorilla/mux#538]
In the README there is an example to serve SPA.
This example works fine on Linux, but not on Windows.

This seems to be the problem:
```
// get the absolute path to prevent directory traversal
path, err := filepath.Abs(r.URL.Path)
```
This seems to work like this:
Linux: `/favicon.ico` -> `/favicon.ico `
Windows: `/favicon.ico` -> `C:\favicon.ico`

The result on windows is a path like this: `public\C:\favicon.ico`

**Comment by elithrar** [comment]
Noted.

I’m not an expert with the filepath package, but is the resulting
filepath.Join (which runs a Clean()) not resolving this?

**Comment by r03** [comment]
The code below gets this result on Windows: `\static\C:\favicon.ico`

```
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	path, _ := filepath.Abs("/favicon.ico")
	path = filepath.Join("/static", path)
	fmt.Println(path)
}

```
