### ISSUE TITLE
[bug] Path not matched unless ending slash

### ISSUE THREAD

**Issue by Pitasi** [gorilla/mux#540]
**Describe the bug**

I'm using a PathPrefix subrouter /product, and it has a handler / (example taken from the mux readme).
I'm not sure if this is a bug or not, is not what I expected since StrictSlash is set to false.

…

**Versions**
> Go version: go version go1.13.5 linux/amd64
> package version: v1.7.3

…

**Steps to Reproduce**
> How can the bug be triggered?

See attached code.
…

**Expected behavior**
> What output or behaviour were you expecting instead?

One of:
* Both requests work
* The first is 200 OK, the second is 301 redirected to the first

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

func ProductsHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Println("handler called!")
}

func main() {
	r := mux.NewRouter()
	s := r.PathPrefix("/products").Subrouter()
	s.HandleFunc("/", ProductsHandler)

	go func() {
		log.Fatal(http.ListenAndServe(":3333", r))
	}()

	time.Sleep(time.Second)

	res, err := http.Get("http://localhost:3333/products")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Status code: %s\n", res.Status) // 404 not found

	res, err = http.Get("http://localhost:3333/products/")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Status code: %s\n", res.Status) // 200 ok
}
```
…

**Comment by kobayashi** [comment]
I think this is expected behavior. This is described in [docs](https://www.gorillatoolkit.org/pkg/mux#Route.PathPrefix)
