### ISSUE TITLE
[feature] Add Description on Route

### ISSUE THREAD

**Issue by henri9813** [gorilla/mux#542]
I'm working on a documentation generator, and it could be very kind to have a description attribute on a route.

We currently have ".Name(name string)", is it possible to have .Description(description string)
```
router.HandleFunc("/post", createPostHandler).Methods("POST").Name("create_post").Description("Create a new post")
router.HandleFunc("/post", getPostsHandler).Methods("GET").Name("get_posts").Description("Get a Post collection")
```

Is it possible ?

Happy New year and regards !

**Comment by fharding1** [comment]
Name has a purpose beyond documentation, it's used to identify routes. I think adding a no-op method for annotating route descriptions specifically for 3rd party documentation generators seems a little unnecessary. It doesn't really seem like it's something mux itself should be concerned with to me.

**Comment by henri9813** [comment]
Oh okay, thank you for your answer, i will use name for that :)

Have a nice day 👍

**Comment by fharding1** [comment]
@henri9813 would you mind closing this issue if you're satisfied with my reply? Thanks!

**Comment by henri9813** [comment]
Oh sorry, i forget this ! .

Thanks ! :)
