### ISSUE TITLE
How to debug Mux router for a request fired from browser or postman[question] 

### ISSUE THREAD

**Issue by ankur0101** [gorilla/mux#546]
**Describe the problem you're having**
> A clear and concise description of what the question is.

Hello everyone,
I am using windows environment with VS code. I have a basic Hello world program written in go using mux. I placed a breakpoint in main function and clicked Debug > Start debugging then refreshed my mux page, it loaded text hello world without invoking a breakpoint in vs code. How to trigger a breakpoint for an external requests?
…

**Versions**
> Go version: `go version`
1.13.5
> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

**main.go**
```
package main
import (
	"../lib/mux"
	"../handlers"
	"net/http"
	"fmt"
)
func main() {
	fmt.Println("hello")

	r := mux.NewRouter()
	r.HandleFunc("/{entity}", handlers.HomeHandler).Methods("GET")
	http.ListenAndServe(":8000", r)
}
```
**HomeHandler.go**
```
package handlers

import (
	"fmt"
	"../lib/mux"
	"net/http"
	"../models"
)

func HomeHandler(w http.ResponseWriter, rr *http.Request) {
	//Some code here
	params := mux.Vars(rr)
	entityName := params["entity"]
	w.Header().Set("Content-Type", "text/html")	

	var barr = models.SampleModel{Id: 11,Line: 22,Foo: "aa", Bar: "bb"}
	fmt.Println(barr)
	fmt.Fprintf(w, entityName)
}
```
> Hint: wrap it with backticks to format it

…

**Comment by elithrar** [comment]
Where is your breakpoint, specifically?

**Comment by ankur0101** [comment]
I set breakpoints at following lines

**HomeHandler.go**
`params := mux.Vars(rr)
`
**main.go**
`fmt.Println("hello")`

When I run Debug > Start debugging from VS code, it triggers a breakpoint from main.go. How can I trigger breakpoints in go mux when a request is fired from browser?

**Comment by elithrar** [comment]
Send a request to the running server started by the debug process - e.g. on
the port it is listening on.

**Comment by ankur0101** [comment]
@elithrar I was trying to do the same but it was not working. All of sudden it is working now. I all did was refresh web page couple of times.
Thanks for your support.
