### ISSUE TITLE
Prevent duplicate request for short time

### ISSUE THREAD

**Issue by ingtarius** [gorilla/mux#549]
Hello! I am new in golang, so my question can be very strange and stupid.

I have http server with gorilla/mux and gorilla/handlers
In some router (/routertwo) i want to store requests for short limit of time (1, 2, 3 min etc) and not to  duplicate request. How to make it?

**Comment by elithrar** [comment]
Can you expand? What do you mean “store” a request?

What is the use-case / overall problem you are trying to solve?

**Comment by ingtarius** [comment]
Yea, some more information :)
if you post some to url (like http://127.0.0.1:8080/routertwo) it will make notify in slack about this event. Sometimes it happen many times with same data, and i try to make ttl-lock for same requests.

**Comment by elithrar** [comment]
Do you mean you don’t want to make repeated calls to some backend server?
That you want to cache the responses if the request matches some key?

Reduce load on the server? (is that a problem?)

Slack webhooks are POST requests and include an authentication key in many
instances, and thus caching them without validation can be risky.

**Comment by ingtarius** [comment]
Yes, i don’t want to make repeated calls (it make spam noise in channel, like 4 or 5 identical posts)
This web-server is in local network, without external access. So, caching is fine.

**Comment by elithrar** [comment]
It sounds like you actually want rate limiting, not “storing” a response?

**Comment by ingtarius** [comment]
Yes, sounds like a true

**Comment by elithrar** [comment]
Look at
https://github.com/uber-go/ratelimit & similar.

**Comment by ingtarius** [comment]
Thanks for your support!
