### ISSUE TITLE
Can you please tag another release?

### ISSUE THREAD

**Issue by System-Glitch** [gorilla/mux#550]
**Describe the problem you're having**

The lastest tag, 1.7.3 is from Jun 30, 2019. There has been some bug fixes since then, such as #509, which is affecting me. Can you tag a new version please? In the meantime, I can just use the master branch in my module dependencies but for stability, I would prefer to avoid doing that.

**Versions**
> Go version: `go1.13.6 linux/amd64`

> package version: v1.7.3

**Comment by elithrar** [comment]
I can tag another release, but note that Go modules can pin to a specific
commit hash for stability too.

**Comment by bitsofinfo** [comment]
ditto! please tag a release please

**Comment by elithrar** [comment]
See https://github.com/gorilla/mux/releases/tag/v1.7.4
