### ISSUE TITLE
[bug] The default MethodNotAllowedHandler is not spec compliant

### ISSUE THREAD

**Issue by rocketspacer** [gorilla/mux#554]
[RFC 7231 Section 6.5.5](https://tools.ietf.org/html/rfc7231#section-6.5.5) 

States that 
> The origin server MUST generate an
>    Allow header field in a 405 response containing a list of the target
>    resource's currently supported methods.

Which is clearly not implemented right now
https://github.com/gorilla/mux/blob/75dcda0896e109a2a22c9315bca3bb21b87b2ba5/mux.go#L601-L603

Suggestion:
- Rather than assign a default MethodNotAllowedHandler just reuse the NotFoundHandler so it's both backward compatible and spec-compliant.

**Comment by elithrar** [comment]
Happy to take a PR + tests for this.

**Comment by rocketspacer** [comment]
@elithrar Would you prefer a flag to skip handling MethodNotAllowed or would you prefer me to remove the default MethodNotAllowed handler altogether? (meaning: MethodNotAllowed will only be handled if the handler is explicitly specified)

**Comment by elithrar** [comment]
See comments in https://github.com/gorilla/mux/pull/555
