### ISSUE TITLE
[question] URL encoded parameters not working

### ISSUE THREAD

**Issue by olivebay** [gorilla/mux#556]
I want to extract the URL from a request like this
`http://localhost:9090/v1/abc/https://news.com/search\?q\=test\&size\=10\&category\=us,politics,world,opinion,health`

But, using the following

```
r := mux.NewRouter().SkipClean(true).UseEncodedPath()
r.HandleFunc("/", Index)
r.HandleFunc(`/v1/abc/{v2:.+}`, URLHandler)

func URLHandler(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	fmt.Println(vars)
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "v2 : %v\n", vars["v2"])
}
```

I get only the following

```
v2 : https://news.com/search
```

**Versions**
go1.13.5
github.com/gorilla/mux v1.7.4

Is there a workaround?

**Comment by olivebay** [comment]
I was able to figure this out. I am just pasting what worked for me. If there is better way, please let me know

```
r := mux.NewRouter().SkipClean(true).UseEncodedPath()
r.HandleFunc("/", Index)
r.HandleFunc(`/v1/abc/{v2:.+}`, URLHandler)

func URLHandler(w http.ResponseWriter, r *http.Request) {
        URL, _ := url.PathUnescape(r.URL.RequestURI())
        ext := xurls.Strict().FindAllString(URL, -1)
	fmt.Fprintf(w, "v2 : %v\n", ext)
}
```

**Comment by iwamot** [comment]
I think the correct URL is http://localhost:9090/v1/abc/https%3A%2F%2Fnews.com%2Fsearch%3Fq%3Dtest%26size%3D10%26category%3Dus%2Cpolitics%2Cworld%2Copinion%2Chealth. Escaping with backslashes is not URL encoding.
