### ISSUE TITLE
[question] Error with mux.newRouter()

### ISSUE THREAD

**Issue by cloudybyte** [gorilla/mux#562]
Hey guys I'm having trouble with using mux.newRouter(), but it is only saying "cannot refer to unexported name mux.newRouter" and "undefined: mux.newRouter"...

My code looks like this: 
```
import "github.com/gorilla/mux"
func main() {
router := mux.newRouter()
router.HandleFunc("/create", CreateEndpoint).Methods("POST")
}
```

Any ideas?
I'm new to go, so I would really appreciate help :)

**Comment by cloudybyte** [comment]
* I am running go1.14.1 windows/amd64 and gorilla/mux 75dcda0896e109a2a22c9315bca3bb21b87b2ba5

**Comment by elithrar** [comment]
Go determines whether an identifier - such as a variable, function or method - is public (can be used by users of the package) or private (cannot) by whether the first letter of the identifier is upper-case or not.

In your case you’re referring to a private function that isn’t exported, hence the error.

You want to use `mux.NewRouter()` per the docs - https://godoc.org/github.com/gorilla/mux#NewRouter

**Comment by elithrar** [comment]
I also recommend stepping through https://tour.golang.org/basics/3 (Exported identifiers) and the rest of the Go tour if you’re new to Go!

**Comment by cloudybyte** [comment]
Thx man
