### ISSUE TITLE
[bug] 404 Not Found is returned when there's no match in request headers

### ISSUE THREAD

**Issue by davidlubomirov** [gorilla/mux#566]
```golang
router := mux.NewRouter()
authRoutes := router.PathPrefix("/api/v1/auth").Subrouter()
authRoutes.HandleFunc("/signup", routes.SignIn).Methods("POST").Headers("Content-Type", "application/json")
```

Having the above setup, when the HTTP Method is correct, but the Headers are non-existing or don't match the response is always `404 Not Found`

https://github.com/gorilla/mux/blob/75dcda0896e109a2a22c9315bca3bb21b87b2ba5/mux.go#L158-L167

Suggestion:

- if headers don't match the prerequisite return `400 Bad Request`

**Comment by elithrar** [comment]
The 404 is intended - when you specify `.Headers` as a matcher, failing to match is a HTTP 404.

If you want to change this, I would suggest writing a small piece of middleware that looks for headers and returns a 400.
