### ISSUE TITLE
[bug]  - not found handler doesn't seem to do its job

### ISSUE THREAD

**Issue by ORESoftware** [gorilla/mux#567]
go version go1.14.2 linux/amd64, and github.com/gorilla/mux v1.7.4

I have these "final handlers" the last ones that get registered

```golang
r.Path("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
   w.WriteHeader(405)
   w.Write([]byte(`{ "status": 405, "result": "405: not supported / not allowed" }`))
})

r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
   // this handler wasn't working as expected
  w.WriteHeader(501)
  w.Write([]byte(`{"status":501,"message":"501: Not implemented."}`))
})

```

I noticed some routes which had no match like `/xxx_no_match` that should be getting  a 501 according to the above, were getting a 405 in the browser. So I added this handler at the very end:

```golang
r.PathPrefix("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
  // this handler behaved as I would expect the r.NotFoundHandler to behave..
  w.WriteHeader(501)
  w.Write([]byte(`{"status":501,"message":"501: Not implemented."}`))
})
```

and that one matched missing routes, and I got the 501 instead of the 405. So... why doesn't the `r.NotFoundHandler = h...`  work in this case? seems odd.  I tried using `r.Use()` too, but that one seems to get hoisted into early position and mess up other stuff.

**Comment by elithrar** [comment]
Looking into this - a runnable reproduction would be helpful too [saves
time!]

>

**Comment by elithrar** [comment]
I'm not sure what you're testing explicitly, but the below example is working as I would expect:

```
package main

import (
	 "github.com/gorilla/mux"
	 "net/http"
	 "fmt"
	 "log"
)

func handler(w http.ResponseWriter, r *http.Request) {
	 fmt.Fprintln(w, "hello!")
}

func main() {
	r := mux.NewRouter()

	r.Path("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(405)
		w.Write([]byte(`{ "status": 405, "result": "405: not supported / not allowed" }`))
	})
	
	r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// this handler wasn't working as expected
	  w.WriteHeader(501)
	  w.Write([]byte(`{"status":501,"message":"501: Not implemented."}`))
	})
	
	log.Fatal(http.ListenAndServe(":8000", r))
}
```

Results:

```
# This matches: you have an explicit path of "/"
➜  curl localhost:8000/
{ "status": 405, "result": "405: not supported / not allowed" }%                                                        ~/Desktop

# This is working as intended - the server does not have a matcher for "/wont-match" 
➜  curl localhost:8000/wont-match
{"status":501,"message":"501: Not implemented."}% 
```

This changes when you use a `PathPrefix("/")` - which is basically saying "match all routes" since "/" is the broadest possible prefix.

Have I interpreted your problem differently?

**Comment by ORESoftware** [comment]
I honestly am not sure. All I am saying is that if this:

```golang
r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
   // this handler wasn't working as expected
  w.WriteHeader(501)
  w.Write([]byte(`{"status":501,"message":"501: Not implemented."}`))
})
```

is registered last, it should catch everything, but it wasn't catching everything. In order to catch everything, I actually had to add this as the final handler:

```golang
r.PathPrefix("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
  // this handler behaved as I would expect the r.NotFoundHandler to behave..
  w.WriteHeader(501)
  w.Write([]byte(`{"status":501,"message":"501: Not implemented."}`))
})
```

frankly I didn't like the `r.NotFoundHandler = http.HandlerFunc()` API call since it seems like it's an anomaly in terms of the API, so I am happy to use `r.PathPrefix('/').HandlerFunc` ..
