### ISSUE TITLE
Route Tags [feature] 

### ISSUE THREAD

**Issue by veverkap** [gorilla/mux#569]
**Is your feature request related to a problem? Please describe.**
> We are using the Route walk capability to generate a Ruby client for our API and would like the ability to "tag" the Route with key-values for this generation

**Describe the solution you'd like**
> Ideally, there would be a new member in the Route struct `tags` similar to Name

**Describe alternatives you've considered**
> None

I would be happy to open a PR for this but wanted to see if it would be something accepted first.

**Comment by elithrar** [comment]
Is overloading name not possible?

**Comment by veverkap** [comment]
Maybe?

Here's a better example of what I'm looking to do:

I have a POST route (say POST /api/widget) that will create a widget from a JSON body.
In Go, I make a WidgetRequest struct and convert the JSON request body -> a WidgetRequest.
That way I can marshal/unmarshal/validate/etc that struct in Go world.

But mux just knows about a route, a name, etc.  I want to be able to "tag" this route so that when I generate my Ruby client, I know that it takes a WidgetRequest JSON.

Does that make sense?  I'd like to generate the client from the routes including more complex types.

I could name the route "WidgetRequest" if that's what you mean.

**Comment by elithrar** [comment]
Right - using the .Name() method as a free-form text field that you can
parse as needed when walking over Routes.

Adding more methods to Route has a cost (UX) that I’d like to avoid for
such a niche use case.

**Comment by veverkap** [comment]
Fair enough. Thanks!
