### ISSUE TITLE
[Issue] Handler not able to handle slashes

### ISSUE THREAD

**Issue by ankur0101** [gorilla/mux#571]
> A clear and concise description of what the problem is.
I have a url as http://127.0.0.1:8000/bob('/foo/bar') and main function as below:

```
func main() {
	fmt.Println("नमस्कार, सर्व्हर प्रारंभ झाला आहे")
	r := mux.NewRouter()
	r.HandleFunc("/bob('{entity}')", bob).Methods("GET")
	http.ListenAndServe(":8000", r)
}
```

It keeps on showing 404 page not found. Here I want to capture **/foo/bar**. If I write a simple string as http://127.0.0.1:8000/bob('whisky'), then it triggers handler perfectly.
…

**Versions**
> Go version: `go version`
go version go1.13.6 linux/amd64

Are there additional steps need to be taken to get this output?
Not really

**Comment by elithrar** [comment]
How are you testing this - curl, or a browser?

**Comment by ankur0101** [comment]
> How are you testing this - curl, or a browser?

At this moment, I am using browser

**Comment by ankur0101** [comment]
Hello, Shall we convert it as a bug?

**Comment by samphillips** [comment]
You can achieve the functionality you're looking for with the following workaround, it will just require you to remove the excess captured characters after:

`r.HandleFunc("/bob{entity:\\('.*'\\)}", bob).Methods("GET")`

For a request to http://127.0.0.1:8000/bob('/foo/bar') :
`entity => ('/foo/bar')`

You can then easily get `/foo/bar` by stripping the first and last 2 characters:
`parsedEntity := entity[2:len(entity)-2]`

**Comment by ankur0101** [comment]
Thanks @samphillips
