### ISSUE TITLE
[bug] SPA example

### ISSUE THREAD

**Issue by jipson7** [gorilla/mux#574]
**Describe the bug**
The SPA example in the README has a bug, this line:
```
// prepend the path with the path to the static directory
path = filepath.Join(h.staticPath, path)
```

Should be `path = filepath.Join(path, h.staticPath)`

**Versions**
N/A

**Steps to Reproduce**
N/A

**Expected behavior**
N/A

**Code Snippets**
See above

**Comment by rnodal** [comment]
How is this not working? It's working fine for me under local env and app engine as is.
