### ISSUE TITLE
[question] Broken news link on http://www.gorillatoolkit.org/pkg/mux

### ISSUE THREAD

**Issue by phpclub** [gorilla/mux#576]
**Describe the problem you're having**
Broken news link on http://www.gorillatoolkit.org/pkg/mux

**Comment by sreeram77** [comment]
The url is redirecting to Google+, which is now shutdown. We should redirect to an alternative location.

**Comment by amurchick** [comment]
![image](https://user-images.githubusercontent.com/1515699/89365609-2987ed80-d6ff-11ea-9ace-bbbebfb07677.png)
https://goo.gl/aESk5L

**Comment by moficodes** [comment]
This is related to app engine, I guess thats where the site is hosted?

**Comment by elithrar** [comment]
We are working to fix this.
