### ISSUE TITLE
error: invalid reference to unexported identifier ‘controller.allUsers

### ISSUE THREAD

**Issue by mrbardia72** [gorilla/mux#580]
package routers

import (
	"github.com/gorilla/mux"
	"log"
	"net/http"
	"../controller"
)

func handleRequests() {
	r := mux.NewRouter().StrictSlash(true)
	r.HandleFunc("/users",controller.allUsers).Methods("GET")
	// r.HandleFunc("/user/{name}", deleteUser).Methods("DELETE")
	// r.HandleFunc("/user/{name}/{email}", updateUser).Methods("PUT")
	// r.HandleFunc("/user/{name}/{email}", newUser).Methods("POST")
	log.Fatal(http.ListenAndServe(":8081", r))
}

**Comment by elithrar** [comment]
Take a look at
https://tour.golang.org/basics/3 - you haven’t exported “allUsers” per the
error message.

This isn’t a gorilla issue - Go requires you capitalize the first letter of
a symbol to export it.

**Comment by mrbardia72** [comment]
thank you
``
r.HandleFunc("/users",controller.Allusers).Methods("GET")
``
