### ISSUE TITLE
[bug] mux router doesn't work with gorilla/websockets if wrapped in http.TimeoutHandler

### ISSUE THREAD

**Issue by NeilBotelho** [gorilla/mux#581]
When mux is wrapped in http.TimeoutHandler we get the panic:
 
``` websocket: response does not implement http.Hijacker   ```
it works fine when it isn't wrapped

**Versions**
Go version: ` go1.14.4 linux/amd64`
package version: 
- github.com/gorilla/mux v1.7.4
- github.com/gorilla/websocket v1.4.2

**Steps to Reproduce**
- Relevant code in the main function:
```
r := mux.NewRouter() //
	srv := &http.Server{
		// Wrap mux in a timeout Handler
		Handler: http.TimeoutHandler(r, 10*time.Second, "Timeout!\n"),
		Addr:    "127.0.0.1:"8000 ,
		// Enforce timeouts for server!
		WriteTimeout: 10 * time.Second,
		ReadTimeout:  10 * time.Second,
		IdleTimeout:  15 * time.Second,
	}

	r.HandleFunc("/ws", websocketHandler)
	r.HandleFunc("/test", HomeHandler)
```

- Relevant code in the ```websocketHandler``` function:
```
conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}
	//Do something with conn
```

…

**Expected behavior**
- Establish websocket connection with client

**Observed behavior**
- On client side connection is refused with error 500
- On server side we get the panic: 
``` websocket: response does not implement http.Hijacker   ```

**Comment by floyernick** [comment]
Is there any update on it?

**Comment by ashu8912** [comment]
What's the status of this?

**Comment by vlotech** [comment]
any update on this issue?
