### ISSUE TITLE
[bug] gorillatoolkit.org is down because of deprecated Go 1.9

### ISSUE THREAD

**Issue by sayanfaraz** [gorilla/mux#584]
**Describe the bug**
> A clear and concise description of what the bug is.

I am unable to access the Gorilla website because I receive the following error message:
"Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information."

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

n/A

**Steps to Reproduce**
> How can the bug be triggered?

Access https://www.gorillatoolkit.org/ through Chrome or Edge browsers.
![image](https://user-images.githubusercontent.com/5562153/89458855-bea5d900-d735-11ea-9b28-17bb26d774d1.png)

**Expected behavior**
> What output or behaviour were you expecting instead?

I was expecting to see the website.

**Comment by elithrar** [comment]
Please see the other issues around this.

**Comment by emmaly** [comment]
Duplicate of https://github.com/gorilla/site/issues/13.
