### ISSUE TITLE
[ec2-user@ip-10-0-0-150 ~]$ mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin                                                     [ec2-user@ip-10-0-0-150 ~]$ kubectl version --short --client /home/ec2-user/bin/kubectl: line 1: syntax error near unexpected token `newline' /home/ec2-user/bin/kubectl: line 1: `<?xml version="1.0" encoding="UTF-8"?>' [ec2-user@ip-10-0-0-150 ~]$ 

### ISSUE THREAD

**Issue by rafiskink123** [gorilla/mux#585]
**Describe the bug**
[ec2-user@ip-10-0-0-150 ~]$ mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
[ec2-user@ip-10-0-0-150 ~]$ kubectl version --short --client
/home/ec2-user/bin/kubectl: line 1: syntax error near unexpected token `newline'
/home/ec2-user/bin/kubectl: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
[ec2-user@ip-10-0-0-150 ~]$ 
…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> Here we are getting the error. actually it works fine. but in some times it giving this error. expected output is it should give output as it's version. but it giving error.

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by rafiskink123** [comment]
I would like to know where I'd missing to get exact result.

**Comment by rafiskink123** [comment]
Once again I executed command it works fine. But I need to figure out where I did missed. since I run the same command before, not worked.

**Comment by elithrar** [comment]
This seems unrelated to this package (mux) and project.
