### ISSUE TITLE
[bug]  installing the latest version gives an error in bench_test.go

### ISSUE THREAD

**Issue by megamayoy** [gorilla/mux#596]
**Describe the bug**
whenever I try to install the package, it give me an error `can't load package: package github.com/gorilla/mux: 
../go/pkg/mod/github.com/gorilla/mux@v1.8.0/bench_test.go:1:1: expected 'package', found 'EOF'
`

…

**Versions**
> Go version: `go version go1.14.7 linux/amd64`
> package version: v1.8.0

…

**Steps to Reproduce**
> How can the bug be triggered?

… run `go get -u github.com/gorilla/mux` in the terminal

**Comment by elithrar** [comment]
Remove the folder and start over. It sounds like you have a truncated file.

**Comment by megamayoy** [comment]
installed successfully
 thank you
