### ISSUE TITLE
Concurrency of Upgrader.Upgrade() not documented

### ISSUE THREAD

**Issue by cameronelliott** [gorilla/mux#599]
**Describe the bug**

For Upgrader.Upgrade() the concurrency section of the docs doesn't describe the concurrency characteristics
of this method.

Forgive me if I missed something, I triple read the section on concurrency to see if I could determine the thread safetyness of Upgrader.Upgrade()

**Versions**
> Go version: N/A
> package version: c3dd95aea9779669bb3daafbd84ee0530c8ce1c1

**Comment by elithrar** [comment]
Did you mean for this to be filed against gorilla/websocket?

**Comment by cameronelliott** [comment]
I'm sorry, silly me.
