### ISSUE TITLE
Return a 405 when HTTP method is not supported

### ISSUE THREAD

**Issue by moraes** [gorilla/mux#6]
What steps will reproduce the problem?
1. Register a URL & handler with r.HandleFunc("/foo", myHandlerFunc).Methods("POST")
2. Using a web browser, or cURL, hit the endpoint using an HTTP GET request

What is the expected output? What do you see instead?
Ideally, a 405 Method Not Allowed status should be returned, but the response status is a 404 File Not Found.

(issue moved from Google Code: http://code.google.com/p/gorilla/issues/detail?id=50)

**Comment by sandeepraju** [comment]
is there any progress?

**Comment by martensson** [comment]
I will join the thread since I was looking for a solution to the 405 problem and everything was leading to this issue.

**Comment by bkeroackdsc** [comment]
+1

**Comment by binarylogic** [comment]
+1, would like to see this supported as well.

**Comment by elithrar** [comment]
@kisielk — did we want to recommend your https://godoc.org/github.com/gorilla/handlers#MethodHandler as the canonical solution for this one?

The other alternative is to [provide an AutomaticOptions middleware](https://github.com/zenazn/goji/blob/master/web/middleware/options.go#L62-L75) like Goji provides, and populate the request context based on the contents of [`Methods`](https://github.com/gorilla/mux/blob/f15e0c49460fd49eebe2bcc8486b05d1bef68d3a/route.go#L292-L301)? I haven't looked into this too deeply but may represent a simple approach.

**Comment by kisielk** [comment]
I think so. I don't think it's possible to add it to the library without rewriting most of the route matching.

**Comment by kisielk** [comment]
I'm going to close this as WontFix for now since I don't see any obvious solution to this problem given the current way the router is implemented. My suggestion is to use MethodHandler from gorilla/handlers if you really need this functionality. If someone comes up with a good solution to integrate this in to mux, I'd be happy to look at it.

**Comment by paddyforan** [comment]
I implemented this crudely as part of our fork of mux, in 3 commits:

https://github.com/DramaFever/mux/commit/dcdec4c5bd3a42e787fe707eaea0e9ae8127683c
https://github.com/DramaFever/mux/commit/a18be6ab3ee63fa23d339c4ec3fc1abe13f7d184
https://github.com/DramaFever/mux/commit/8051bd6b1896148d25b231079b9ce4765296837b

I'd be happy to clean it up, add some tests, and contribute it back.

Note that it doesn't _automatically_ send back the 405, but the NotFound handler can then be extended to do so:

```go
r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		methods := r.GetMethods(req)
		if len(methods) > 0 {
                        // return 405
			return
		}
                // return 404
		return
	})
```

Additionally, with a bit more intrusive hacking, a MethodNotAllowed property could be added.

Again, happy to contribute this back if this is something that's desired in the upstream.
