### ISSUE TITLE
[bug] Named routes in nested Subrouter not accessible in parent router

### ISSUE THREAD

**Issue by mrngm** [gorilla/mux#604]
**Describe the bug**

Named routes in nested Subrouter not accessible in parent router

**Versions**
> Go version: go version go1.15.1 linux/amd64
> package version: v1.8.0

**Steps to Reproduce**

Consider the following structure:

```go
r := mux.NewRouter()

foo := r.PathPrefix("/foo").Subrouter()
bar := foo.PathPrefix("/bar").Subrouter()
route := bar.Path("route").Name("foo-bar").Methods("GET")

fmt.Printf("foo-bar: %+v\n", r.Get("foo-bar"))
fmt.Printf("route: %+v\n", route)
```
([playground](https://play.golang.org/p/r-2t4grqDIR))

`r`, the main router, cannot access route with name `foo-bar`:
```
foo-bar: <nil>
route: &{handler:<nil> buildOnly:false name: err:0xc000012cb0 namedRoutes:map[] routeConf:{useEncodedPath:false strictSlash:false skipClean:false regexp:{host:<nil> path:0xc00013c5b0 queries:[]} matchers:[0xc00013c1c0 0xc00013c4d0] buildScheme: buildVarsFunc:<nil>}}
```

**Expected behavior**

`r`, the main router can access all route names in all nested subrouters.

**Code Snippets**

See above and [the Go playground](https://play.golang.org/p/r-2t4grqDIR)

**Comment by vaibhavdesai16** [comment]
Anyone working on this bug? I am willing to contribute.

**Comment by mrngm** [comment]
> Anyone working on this bug? I am willing to contribute.

As far as I know, you would be the first :-)

**Comment by RickyBoyd** [comment]
I think the problem here is actually that there's an error in the route because the path must start with a "/".

The following line:
```
route := bar.Path("route").Name("foo-bar").Methods("GET")
```

should be

```
route := bar.Path("/route").Name("foo-bar").Methods("GET")
```

**Comment by mrngm** [comment]
> I think the problem here is actually that there's an error in the route because the path must start with a "/".
> 
> The following line:
> 
> ```
> route := bar.Path("route").Name("foo-bar").Methods("GET")
> ```
> 
> should be
> 
> ```
> route := bar.Path("/route").Name("foo-bar").Methods("GET")
> ```

You are absolutely correct. Thanks for clarifying.
