### ISSUE TITLE
[question] What's the correct form of error handling?

### ISSUE THREAD

**Issue by mrngm** [gorilla/mux#605]
**Describe the problem you're having**

When adding routes to a `mux.Router`, it may happen that the user accidentally forgets a closing brace `}` when using both URL variables and a regular expression. Internally, `mux` does some sanity checks, but they are only exposed through  `mux.Route.GetError()` that retrieves a stored error (or `nil`) of that route. Another option is to use `mux.Router.Walk(mux.WalkFunc)` to iterate over routes stored in the router.

I was wondering what would be preferable, and perhaps add that to the README.

**"Show me the code!"**

```go
r := mux.NewRouter()
err := r.Path("/foo").GetError()
if err != nil {
    // handle
}
err = r.Path("/bar/{variable:[a-zA-Z]{38}").GetError()
if err != nil {
    // handle
}
```

vs.

```go
r := mux.NewRouter()
r.Path("/foo")
r.Path("/bar/{variable:[a-zA-Z]{38}")
err := r.Walk(func(route *mux.Route, rtr *mux.Router, ancestors []*mux.Route) {
    if err := route.GetError(); err != nil {
        return err
    }
}
if err != nil {
    // handle
}
```

vs.

```go
// Your error handling code here
```

**Comment by elithrar** [comment]
Is not Walking the routing tree at startup of the application the same as
writing tests for your handlers? :-)

**Comment by mrngm** [comment]
Thanks for your reply. As I understand it, you assume a user of this framework either writes tests for all their handlers, or uses `mux.Walk()` for verification?

**Comment by elithrar** [comment]
Right - given the power of matchers, and regular expressions in general,
relying on compile-time checks is ultimately limited.

**Comment by mrngm** [comment]
Thanks!
