### ISSUE TITLE
[question] does mux middleware support bi-directional filtering

### ISSUE THREAD

**Issue by bxshcn** [gorilla/mux#614]
**the mux.Match builds a middlware chain with closure, when a request incomes, the handler closures apply one by one in the order they registered** 

> it seems that we can not add business logic for request and response respectively in a middleware,  does it exists some way to implement the bi-directional filtering? what i can do with this requirement? 
…

**Versions**
> Go version: 1.15.2 windows/amd64

> package version: d07530f46e1eec4e40346e24af34dcc6750ad39f

thanks!

**Comment by elithrar** [comment]
You can - like all middleware, you call response action after you call the
next handler.

What have you tried?
