### ISSUE TITLE
[bug] handling junk input in URI

### ISSUE THREAD

**Issue by spyroot** [gorilla/mux#617]
**Describe the bug**
> A clear and concise description of what the bug is.

I was testing input validation.   In my case, I have the following string in a unit test.
"!@#$%^&*

and it leads to a crash in ServeHTTP crashing.   

```
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001b2300, 0x1a062a0, 0xc001026080, 0x0)
/Users/spyroot/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:177 +0x226
```

It looks like req.URL.Path can be niI,  think nil check must be done for req.URL.Path

```
if !r.skipClean {
		path := req.URL.Path
		if r.useEncodedPath {
			path = req.URL.EscapedPath()
		}
```
…

**Versions**
> Go version: `go version`

go version go1.15.5 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo

	github.com/gorilla/mux v1.7.3

…

**Steps to Reproduce**
> How can the bug be triggered?

in my case simple test

```
req, _ := http.NewRequest("POST", ApiTest + "!@#$%^&*", nil)

foor
rr := httptest.NewRecorder()
c.localServer.rest.router.ServeHTTP(rr, req)
```

A router is a gorilla mux instance.
!@#$%^&* passed via request. 

Handler just pass this directly
router.HandleFunc(ApiTest + "/{name}", api.getRoleByName).Methods("GET")
…

**Expected behavior**
> What output or behavior was you expecting instead?

Sanity check inside func (r *Router) ServeHTTP(w http.ResponseWriter, req *http.Request)
not a crash :)
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Stack Trace**

testing.tRunner.func1.1(0x1814c80, 0x2748fb0)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000300900)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1075 +0x41a
panic(0x1814c80, 0x2748fb0)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001b2300, 0x1a062a0, 0xc001026080, 0x0)
	/Users/spyroot/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:177 +0x226
github.com/spyroot/callisto/pkg/server.executeRequest(0xc000300900, 0xc00020e000, 0x0, 0x4)
	/Users/spyroot/go/src/callisto/pkg/server/roles_test.go:41 +0x258
github.com/spyroot/callisto/pkg/server.TestRestful_createRole.func1(0xc000300900)
	/Users/spyroot/go/src/callisto/pkg/server/roles_test.go:212 +0x12c
testing.tRunner(0xc000300900, 0xc00090eea0)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1168 +0x2b3

**Comment by elithrar** [comment]
What happens if you don’t ignore the error?
