### ISSUE TITLE
[bug] Readme: defers will not be run when using os.Exit

### ISSUE THREAD

**Issue by julez-dev** [gorilla/mux#618]
**Describe the bug**
The [Graceful Shutdown](https://github.com/gorilla/mux#graceful-shutdown) example in the readme makes a deferred cancel() call.

When using os.Exit() to exit a go program defers will not be run so cancel() will never be called.

```go
  // Create a deadline to wait for.
  ctx, cancel := context.WithTimeout(context.Background(), wait)

  defer cancel() // Will never be called

  // Doesn't block if no connections, but will otherwise wait
  // until the timeout deadline.
  srv.Shutdown(ctx)
  // Optionally, you could run srv.Shutdown in a goroutine and block on
  // <-ctx.Done() if your application should wait for other services
  // to finalize based on context cancellation.
  log.Println("shutting down")
  os.Exit(0)
```

**Versions**
any

**Expected behavior**
Dont defer the call to cancel()

**Comment by ilia-tsyplenkov** [comment]
It is True. https://golang.org/pkg/os/#Exit. The example needs to be updated.
