### ISSUE TITLE
I can't get url in path params

### ISSUE THREAD

**Issue by mohsensamiei** [gorilla/mux#619]
**Describe the bug**
I want to get URL as path parameter, but mux return invalid url

**Versions**
> Go version: 1.14
> package version: v1.7.3

**Steps to Reproduce**
I have a handle function with this path `/pages/{url:.*}` on GET method
When I call api with path param like `https://www.google.com` such as: `curl -X GET "http://localhost:9081/pages/https%3A%2F%2Fwww.google.com" -H "accept: application/json"`
In handle function I get this `https:/www.google.com`
So this is invalid !

**Expected behavior**
I want to get `https://www.google.com`

**Comment by elithrar** [comment]
Please share the code where you are attempting to get the param.

**Comment by mohsensamiei** [comment]
This is sample code:
```go
package main

import (
	"github.com/gorilla/mux"
	"net/http"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/pages/{url:.*}", load).Methods(http.MethodGet)
	panic(http.ListenAndServe(":8080", r))
}

func load(res http.ResponseWriter, req *http.Request) {
	println(mux.Vars(req)["url"])
}
```
When you run this command
```shell
curl --location --request GET 'http://localhost:8080/pages/https://github.com/gorilla/mux/issues/619'
```
Print `https:/github.com/gorilla/mux/issues/619`
Instead  of `https://github.com/gorilla/mux/issues/619`

**Comment by elithrar** [comment]
That’s because the double slashes are being collapsed. See
https://pkg.go.dev/github.com/gorilla/mux#Router.SkipClean - there is an
example that matches exactly what you are trying to do.

**Comment by mohsensamiei** [comment]
oooooo, got it...
thanks so much
