### ISSUE TITLE
no response when inserting this code "go get -u github.com/gorilla/mux" 

### ISSUE THREAD

**Issue by Natannegara** [gorilla/mux#623]
Hi, I am currently using Golang, I am new in this language.

i was trying to download gorilla/mux but when I put the code like:
go get -u github.com/gorilla/mux 
there is no response at all.

i am not sure what is the problem, but i could download other package/module
using this comman like go get github.com/blabla/blabla
it succeded. !!

do you have any idea about my difficulties.?

**Comment by vortex-17** [comment]
Heyy
You will not get any response. This is how it works. You can check whether it has been installed or not by checking go/src/github.com path (This is the path where your golang has been installed ).

**Comment by mityukov** [comment]
There is nothing under `~/go/src/github.com`

All the installed packages are under `~/go/pkg/mod/github.com` somehow and they're not picked up from there…

Note: did everything (except of GVM part) from this article to install go on my OS: https://jimkang.medium.com/install-go-on-mac-with-homebrew-5fa421fc55f5

**Comment by masterkeysrd** [comment]
You will get a kind of response like this:
```bash
$ go get -u github.com/gorilla/mux
go: downloading github.com/gorilla/mux v1.8.0
```

**Comment by soundkitchen** [comment]
@Natannegara Is this problem going to be solved?
