### ISSUE TITLE
mux.Vars empty without Queries()

### ISSUE THREAD

**Issue by DmitriyVTitov** [gorilla/mux#625]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I have a handler. If I register it like this
```
api.r.HandleFunc("/api/public/v1/routes", api.PublicRoutesInfoHandler).Methods(http.MethodGet, http.MethodOptions).Queries("key", "{key}")
```
then `mux.Vars(r)["key"]` is not empty when I test this route with Postman.

But when I remove Queries("key", "{key}") Vars become empty.
I don't understand why this happens.

…

**Versions**

Go version: `1.16`

> package version: run `git rev-parse HEAD` inside the repo

github.com/gorilla/mux v1.7.3

**Comment by elithrar** [comment]
Vars returns route variables  - e.g. {key} in your case.

If you don’t have any route variables, Vars isn’t populated.
https://pkg.go.dev/github.com/gorilla/mux#Vars

**Comment by DmitriyVTitov** [comment]
OK, i thought it parses the URL and extracts vars from request.

**Comment by elithrar** [comment]
It extracts *mux* variables.

If you want to get query parameters more generally, the http.Request allows
you to parse parameters via r.FormValue().

**Comment by DmitriyVTitov** [comment]
@elithrar Thanks, I forgot that :)
