### ISSUE TITLE
[question] How to match with " And "&" and get the corresponding value?

### ISSUE THREAD

**Issue by guanzhanyi** [gorilla/mux#627]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
I can't get the values of text and ID while matching the URL below
```http://106.52.19.86/api/v1.0/smscode/1455205153@qq.com?text=1111qq&id=91b23fd8-6795-4da2-b490-c9f7d17a947f```

**Versions**
> Go version: `go version`
`go 1.16`
> package version: run `git rev-parse HEAD` inside the repo
`github.com/gorilla/mux v1.8.0`
…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
Neither of the following methods works
```
r.Methods("GET").Path(`/api/v1.0/smscode/{mail}?{text:[a-zA-Z0-9]+}&{id:[a-zA-Z0-9-]+}`).Handler(serverHandler)

r.Host("/api/v1.0/smscode").Path("/{mail}").Queries("text","{text}").Handler(serverHandler)
```
> Hint: wrap it with backticks to format it

…

**Comment by elithrar** [comment]
`text=1111qq&id=91b23fd8-6795-4da2-b490-c9f7d17a947f` are query parameters, and not part of the path.

- If you want to **match** on query parameters, use https://pkg.go.dev/github.com/gorilla/mux#Route.Queries in addition to Route.Path -

- You could also just match on the Path, and then subsequently get the parameters in your handler from the `http.Request` - https://golang.org/pkg/net/http/#Request

**Comment by elithrar** [comment]
Further: `Host("/api/v1.0/smscode")` is not a host, but a path, and thus will never match.

I suggest taking a look at a few examples in our docs to help you along: https://pkg.go.dev/github.com/gorilla/mux#readme-examples

**Comment by guanzhanyi** [comment]
> Further: `Host("/api/v1.0/smscode")` is not a host, but a path, and thus will never match.
> 
> I suggest taking a look at a few examples in our docs to help you along: https://pkg.go.dev/github.com/gorilla/mux#readme-examples

**Comment by guanzhanyi** [comment]
**Thank you for your patience. I got a lot.**
