### ISSUE TITLE
[question] Mac Os cannot build this package by using go get or go build

### ISSUE THREAD

**Issue by crownk1997** [gorilla/mux#630]
**Describe the problem you're having**
> I am trying to install the package by using go get or go build. However, I always got the following error message 

# runtime/cgo
clang-4.0: error: unable to execute command: Segmentation fault: 11
clang-4.0: error: linker command failed due to signal (use -v to see invocation)

…

**Versions**
> Go version: go1.16.5 darwin/amd64

> package version: v1.8.0
…

…

**Comment by Kruemelmann** [comment]
Hey @crownk1997 are u still facing this issue? 
I tryed it with the 1.16.5 on darwin/amd64 and it worked like charm:)
So maybe you can provide some more information about this to get better understanding of the problem.

**Comment by Volatus** [comment]
@crownk1997 Any idea why your Clang version is that old? Can you provide results of `which clang` and `clang --version` ?

**Comment by crownk1997** [comment]
@Volatus Please check the following information.

clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /opt/anaconda3/bin

**Comment by Volatus** [comment]
@crownk1997 you may be running into an issue where the anaconda bundled clang is messing with the Go builds. Can you paste the result of `echo $PATH | sed 's/:/\n/g'`?
