### ISSUE TITLE
[question] How to increase max header size when handling requests?

### ISSUE THREAD

**Issue by PierreAdrienDelisle** [gorilla/mux#631]
**Describe the problem you're having**

I'm currenlty using gorilla mux.router to serve my http routes.
However, I faced a problem where my client was receiving: Error 400 - Bad Request and the handling function wasn't called.
Client's header were quite big and by removing or shortening those headers, the connection is going well.
There has been other people that got the same "big header problem": [link stack-overflow](https://stackoverflow.com/questions/41954474/client-gets-400-bad-request-but-server-didt-receive-any-request)

I was wondering if there is any method or config for mux.router to increase max header size while handling request.

**Versions**
> Go version: `go version`
go version go1.15.8 windows/amd64

> package version: run `git rev-parse HEAD` inside the repo
4aac8aa7c6e5bfcc260c4dedbf629a4a9b91e932

**"Show me the code!"**

```
router := web.NewMux("test-mux")
router.HandleFunc("/", testFunc)

func testFunc(w http.ResponseWriter, r *http.Request) {
	log.Println("Handling message")
        return
}
```

**Comment by elithrar** [comment]
This isn't specific to mux' API - you should configure a `http.Server`'s `MaxHeaderBytes` (mindful of potential DoS/memory usage concerns) - https://golang.org/pkg/net/http/#Server

e.g.

```
r := mux.NewRouter()
// Your routes here

srv := &http.Server{
    Handler: r,
    Addr: "0.0.0.0:8000",
}

if err := srv.ListenAndServe(); err != nil {
    // handle the error
}
```

If you have another proxy in front of mux, also make sure it is configured correctly as well.

**Comment by elithrar** [comment]
As an example from one of my own projects:

```go
func (s *Server) Run(ctx context.Context, addr string) error {
	if addr == "" {
		addr = ":8000"
	}

	if len(s.commands) == 0 {
		return fmt.Errorf("cannot start server: no commands are registered (%d known commands)", len(s.commands))
	}

	if s.HTTPServer == nil {
		s.HTTPServer = &http.Server{
			Addr: addr,
			// Set reasonable defaults: we handle small webhook payloads, and
			// thus should not take seconds to read requests or write responses.
			ReadHeaderTimeout: time.Second * 5,
			ReadTimeout:       time.Second * 10,
			WriteTimeout:      time.Second * 10,
			MaxHeaderBytes:    10 * 1e3, // 10KiB
		}

		r := http.NewServeMux()
		r.Handle("/api/interactions", s)
		r.HandleFunc("/healthz", healthCheckHandler)
		r.HandleFunc("/commands", listCommandsHandler)
		r.HandleFunc("/", healthCheckHandler)
		// TODO: is this too magic?
		s.HTTPServer.Handler = LoggingMiddleware(s.Logger)(r)
	}

	return s.HTTPServer.ListenAndServe()
}
```

**Comment by elithrar** [comment]
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ as some additional reading I recommend.

**Comment by elithrar** [comment]
(Closing as answered)

**Comment by PierreAdrienDelisle** [comment]
> This isn't specific to mux' API - you should configure a `http.Server`'s `MaxHeaderBytes` (mindful of potential DoS/memory usage concerns) - https://golang.org/pkg/net/http/#Server
> 
> e.g.
> 
> ```
> r := mux.NewRouter()
> // Your routes here
> 
> srv := &http.Server{
>     Handler: r,
>     Addr: "0.0.0.0:8000",
>     MaxHeaderBytes: 10 * 1e3, // 10KiB
> }
> 
> if err := srv.ListenAndServe(); err != nil {
>     // handle the error
> }
> ```
> 
> If you have another proxy in front of mux, also make sure it is configured correctly as well.

Thank you for your answer ! It works perfectly with setting this server attribute 😄
