### ISSUE TITLE
Cors handler in router

### ISSUE THREAD

**Issue by GuoGuiRong** [gorilla/mux#633]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

…

**Describe the solution you'd like**
when I use this lib in a go-kit project, I find it may be not graceful to add a options router alone just for CORS problem.
![image](https://user-images.githubusercontent.com/22836006/124218142-39d16400-db2c-11eb-9960-167e378219c5.png)

I have many path need to add CROS, it's Complicated!!, so I write the CROS middleware by myself.

```
func corsMiddleware(next http.Handler) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                w.Header().Set("Access-Control-Allow-Origin", "*")                                                            // 允许访问所有域，可以换成具体url，注意仅具体url才能带cookie信息
                w.Header().Add("Access-Control-Allow-Headers", "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token") //header的类型
                w.Header().Add("Access-Control-Allow-Credentials", "true")                                                    //设置为true，允许ajax异步请求带cookie信息
                w.Header().Add("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")                             //允许请求方法
                w.Header().Set("content-type", "application/json;charset=UTF-8")                                              //返回数据格式是json
                if r.Method == "OPTIONS" {
                        w.WriteHeader(http.StatusNoContent)
                        return
                }
                next.ServeHTTP(w, r)
        })
}

```

and just use it in router

```
// use gorilla/mux for routing
        router := mux.NewRouter()
        router.Use(corsMiddleware)
```

then add options Method in origin Router Map

```
// http handlers for game info receive
        r.Methods(http.MethodPost, http.MethodOptions).Path(HawkGameInfoReceiveURI).Handler(httptransport.NewServer(
                endpoints.XXXEndpoint,
                decodeXXXRequest,
                encodeXXXResponse,
                options...,
        ))
```

my problem is if my idea graceful， and what's thinks when design the CORS Middleware

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

…

**Comment by msiner** [comment]
Take a look at the Gorilla [handlers](https://github.com/gorilla/handlers) module. There is a [CORS](https://pkg.go.dev/github.com/gorilla/handlers#CORS) middleware implementing a relatively easy to use functional options pattern.
