### ISSUE TITLE
requests not working suddenly without crash binary[bug] 

### ISSUE THREAD

**Issue by MatejMagat305** [gorilla/mux#634]
I have similar problém like:
https://stackoverflow.com/questions/57245294/why-do-this-go-http-server-stop-responding-after-several-requests
sometime stop and nothing, I have inside "reset" funkcion, which create request to my server every 7 second and if find error it print reset and restart server, "reset" function is not printing anything and server do not work, how it is possible?

**Comment by ouzsrcm** [comment]
you have solve this problem? you still getting that error?

**Comment by MatejMagat305** [comment]
it is the wildely problem al http servers........., you can close.........

**Comment by Volatus** [comment]
Seems ok to close @elithrar ?
