### ISSUE TITLE
[feature] Execute Middleware Even If Route Is Not Matched

### ISSUE THREAD

**Issue by marwan-at-work** [gorilla/mux#636]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

Hi there :wave: 

I really like using mux's middleware API (router.Use(...)) but the only issue I'm encountering is that those middleware functions are only executed if the route matches. However, there are many use cases where I'd like to use a middleware on the entire server _before_ the routing logic is even executed (a server behind global authentication would be a good example use case).

…

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?
Add a new API such as `router.UseAlways` or add an option to Use such as `router.Use(middleware).AlwaysMatch()` 

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

Of course an easy solution to the above is by manually wrapping my "always on" middleware separately from gorilla/mux entirely. I'm also happy with this alternative but I think it's more elegant to let the router always be the top level. But I'm happy either way if the mux API is fixed. 

Thanks!
…

**Comment by toyorg** [comment]
Look here, there is a workaround to this https://stackoverflow.com/a/56937571
