### ISSUE TITLE
[question] Paths have variables from a Array?

### ISSUE THREAD

**Issue by SaturnsVoid** [gorilla/mux#638]
Can Paths have variables but from a array of already known one?

For example if i have a array 

`FileExtentions = [...]string{".php", ".asp", ".html", ".js", ".css", ".png", ".jpeg", ".gif", ".mp4", ".mp3", ".iso", ".json", ".txt", ".csv", ".pdf"}`

and i want the Router to be able to tell if the path contains one of these FileExtentions

**Comment by elithrar** [comment]
You can use regular expressions in matchers - for example, you can match on
the path and provide your array of “file extensions” (suffixes) with a
capturing (or non-capturing) group:

r.HandleFunc(“/{file:.*(.php|.asp|.html)}/“, handler)

(This is untested as I’m on mobile, so please verify)

See the full docs:
https://pkg.go.dev/github.com/gorilla/mux

**Comment by msiner** [comment]
Here is a working example that creates two unique handlers for routes that match on sets of file extensions. The file name and file extension are passed down to the handler as fname and fext vars respectively.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"

	"github.com/gorilla/mux"
)

func main() {
	pageExts := []string{".php", ".asp", ".html"}
	jsExts := []string{".js", ".json"}

	r := mux.NewRouter()

	// Route and handler for URLs with extensions commonly associated
	// with whole pages.
	r.HandleFunc(
		fmt.Sprintf(`/foo/{fname:.*}{fext:(?:%s)}`, strings.Join(pageExts, "|")),
		func(w http.ResponseWriter, r *http.Request) {
			vars := mux.Vars(r)
			w.WriteHeader(http.StatusOK)
			fmt.Fprintln(w, "page request", vars)
		},
	)

	// Route and handler for URLs with extensions commonly associated
	// with JavaScript data.
	r.HandleFunc(
		fmt.Sprintf(`/foo/{fname:.*}{fext:(?:%s)}`, strings.Join(jsExts, "|")),
		func(w http.ResponseWriter, r *http.Request) {
			vars := mux.Vars(r)
			w.WriteHeader(http.StatusOK)
			fmt.Fprintln(w, "JS request", vars)
		},
	)
	ts := httptest.NewServer(r)
	defer ts.Close()

	exts := []string{".asp", ".js", ".html", ".php", ".json"}
	for _, ext := range exts {
		pth := "/foo/bar" + ext
		resp, err := http.Get(ts.URL + pth)
		if err != nil {
			log.Fatal(err)
		}
		defer resp.Body.Close()
		body, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s => %s", pth, body)
	}
}
```

When run, it produces the following output that displays which handler was used for each path and the vars created by mux.

```
/foo/bar.asp => page request map[fext:.asp fname:bar]
/foo/bar.js => JS request map[fext:.js fname:bar]
/foo/bar.html => page request map[fext:.html fname:bar]
/foo/bar.php => page request map[fext:.php fname:bar]
/foo/bar.json => JS request map[fext:.json fname:bar]
```
