### ISSUE TITLE
Debug Diagnostic feature / green - 200 / POST / GET - different colors.

### ISSUE THREAD

**Issue by johndpope** [gorilla/mux#643]
**Is your feature request related to a problem? Please describe.**
In debug . dev mode show routes incoming in console like this

<img width="863" alt="Screen Shot 2021-09-16 at 5 04 09 pm" src="https://user-images.githubusercontent.com/289994/133591654-69df17cc-23f7-4606-8d12-00e2e3694adf.png">

…

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

this is achieved here
https://github.com/plaid/quickstart/blob/master/go/server.go

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

logging manually.

**Comment by francescomari** [comment]
@johndpope `mux` is not directly concerned with logging, which is a task better served by a middleware. You can find some useful middleware at [github.com/gorilla/handlers](https://github.com/gorilla/handlers). In particular, you could plug your own preferred logging framework in your app using a [CustomLoggingHandler](https://pkg.go.dev/github.com/gorilla/handlers#CustomLoggingHandler).

**Comment by soundkitchen** [comment]
@francescomari I agree with you.
I think it's better to use handlers, so that each user can use the logger they are used to.
