### ISSUE TITLE
[feature] - show some warning when not using http.Handle("/", app.Router)

### ISSUE THREAD

**Issue by johndpope** [gorilla/mux#644]
```
	app.SetupRouter()

	log.Println("Starting HTTP server")
	// log.Fatal()
	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
		log.Printf("Defaulting to port %s", port)
	}
	log.Printf("Setting up http handle")
	// http.Handle("/", app.Router) < - work on my imac + docker without this - but fails on centos / ec2. 
	log.Printf("Listening on port %s", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatal(err)
	}

```

http.Handle("/", app.Router) < - works on my imac + docker without this - but fails on centos / ec2. Total time waster. Same problem here - https://stackoverflow.com/questions/14081066/gae-golang-gorilla-mux-404-page-not-found

**Comment by francescomari** [comment]
@johndpope I don't think there is a way for `mux` to know that you are not using it in your HTTP server. The issue is not platform-dependent: it's a problem in the configuration of your HTTP server.

**Comment by youngkin** [comment]
I'm new to gorilla mux, but it's not clear to me how this code snippet is using gorilla mux. For me, it would be helpful to know what 'app.Router' is.

**Comment by francescomari** [comment]
@youngkin I assume that the code that is not shown looks something like this:

```go
type App struct {
	Router *mux.Router
}

func (a *App) SetupRouter() {
	a.Router = mux.NewRouter()
	// Add handlers here
}

var app App
```

This is just my assumption, OP is in a better position to clarify it.
