### ISSUE TITLE
Version of  github.com/gorilla/mux is not printed in Docker File

### ISSUE THREAD

**Issue by NehaMittal3010** [gorilla/mux#645]
Using below command in Docker file:-
RUN go get github.com/gorilla/mux

Need to Print the version details while building the image..

Please help me how i can print the version details of gorilla/mux while building the image...

**Comment by elithrar** [comment]
You should/can use the `go mod` tools to print resolved versions of your dependencies - e.g. https://golang.org/ref/mod#go-mod-graph

```
go mod graph
```

... if you want to capture the dependency graph in logs during build.

**Comment by ninadingole** [comment]
when you run `go get -u github.com/gorilla/mux` it would print the version of the lib downloaded like this:
```
go: downloading github.com/gorilla/mux v1.8.0
go get: added github.com/gorilla/mux v1.8.0
```
