### ISSUE TITLE
"strange" matching rule behaviour

### ISSUE THREAD

**Issue by KrullBorg** [gorilla/mux#646]
i have this "very simple" matching regex "/scansioni/dir/{.*}"

2 problems:
- it doesn't match "/scansioni/dir/" (i had to create another matching rule without the regex part to match this case)
- it doesn't match "/scansioni/dir/1983/1404' (i tried also "/scansioni/dir/{[0-9/]*}

it works, as expected, for example with "/scansioni/dir/1983"

what am I doing wrong?

thanks in advance

**Comment by elithrar** [comment]
That regex is correct is not matching /scansioni/dir/ because the regex is NOT optional. `.*` is one or more characters.

**Comment by KrullBorg** [comment]
> That regex is correct is not matching /scansioni/dir/ because the regex is NOT optional. `.*` is one or more characters.

i'm not regex expert, but `*` is 0 or more, `+` is 1 or more, `?` is 0 or 1

maybe go uses another regex dialect? or i don't understand

**Comment by bluebrown** [comment]
I would assume the issues is correct as stated.  * is 0 to unlimited amount of times  of the previous token. Regex 101 seems to agree with that. https://regex101.com/r/CkMqK0/1/

**Comment by elithrar** [comment]
Right, but that's not quite how mux behaves, because it operates on path segments. 

Further, without seeing all of the routes from the OP - because route order matters - we can't be sure something else isn't taking precedence for the match.

**Comment by KrullBorg** [comment]
> Right, but that's not quite how mux behaves, because it operates on path segments.
> 
> Further, without seeing all of the routes from the OP - because route order matters - we can't be sure something else isn't taking precedence for the match.

sorry for delay on reply; now i understood how gorilla/mux works (on segments), so for my second issue is clear why it doesn't work

i think you can close the issue

**Comment by amustaque97** [comment]
> > Right, but that's not quite how mux behaves, because it operates on path segments.
> > Further, without seeing all of the routes from the OP - because route order matters - we can't be sure something else isn't taking precedence for the match.
> 
> sorry for delay on reply; now i understood how gorilla/mux works (on segments), so for my second issue is clear why it doesn't work
> 
> i think you can close the issue

@elithrar let's close this issue.
