### ISSUE TITLE
SubRouter PathPrefix

### ISSUE THREAD

**Issue by waywardgod** [gorilla/mux#648]
>Subrouter doesn't route to the base pathprefix.

**Versions**
> Go version: `go1.16.3`
> package version: `1.8.0`

**Steps to Reproduce**

```
router :=  mux.NewRouter()
booksRouter := router.PathPrefix("/books").Subrouter().StrictSlash(true)
booksRouter.HandleFunc("/", getBooks).Methods(http.MethodGet)
```

**Expected behavior**
>  making a get request to` /books` should route to getBooks but it doesn't unless its` /books/`

**Comment by FaheemuddinKhan** [comment]
@waywardgod 
I tested the scenario explained above and got the desired result.

## Code

```
	booksRouter := router.PathPrefix("/books").Subrouter().StrictSlash(true)
	booksRouter.HandleFunc("/", getBooks).Methods(http.MethodGet)
```

```
func getBooks(rw http.ResponseWriter, r *http.Request){
	logger.Info("In getbooks")
	fmt.Fprintf(rw,"%s","From getBooks")
}
```

## Test

1 curl --location --request GET 'localhost:8000/books'
1 curl --location --request GET 'localhost:8000/books/'

## Output

Both the requests gets routed to getBooks

**Comment by DeltaRays** [comment]
@elithrar could you please close this issue? Op hasn't replied to it for 2 months
