### ISSUE TITLE
[bug] Vars only extracts the last url param 

### ISSUE THREAD

**Issue by bbest-airmatrix** [gorilla/mux#649]
**Describe the bug**
The function `Vars` being called on a Request to extract the parameter values from a url are not grabbing all of the params, and only grabbing the last one it seems.
…

**Versions**
> Go version: 1.17.2
> package version: v1.8.0

**Steps to Reproduce**
> How can the bug be triggered?

Ex.
```golang
// request url is http://localhost:8080/foo/{id}/bar/{next_id}
params := mux.Vars(request)
fmt.Println(params)
// Outputs
// map[id:<next id value>]
```

**Expected behavior**

You would expect a the map to contain `map[id:<id value>, next_id:<next id value>]`

**Comment by FaheemuddinKhan** [comment]
@bbest-airmatrix 
I have tested the scenario explained above by you and it works as expected on my mac.

### Code Tested

This is the code specific to the problem that you were facing.

```
th := TestHandler{}
router.HandleFunc("/foo/{id}/bar/{next_id}",th.FooBar).Methods(http.MethodGet)
```

```
type TestHandler struct {
}

func (h *TestHandler) FooBar(rw http.ResponseWriter, r *http.Request){
	logger.Info("In FooBar")
	data := mux.Vars(r)
	fmt.Println(data)
	fmt.Fprintf(rw, "%v", data)
}
```

### Test Data

curl --location --request GET 'localhost:8000/foo/hello/bar/world'

### Output

map[id:hello next_id:world]
