### ISSUE TITLE
[question] Unable to reach anything other than root ("/")

### ISSUE THREAD

**Issue by ajpinedam** [gorilla/mux#650]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

Hi!

I have a service running on a cloud provider. The service is configured on the route: 

https://mydomain.com/contacts/ on port 8004

using the configuration below:

```go
r := mux.NewRouter()

r.HandleFunc("/", root).Methods("GET")
r.HandleFunc("/{id}", contact).Methods("GET")
r.HandleFunc("/records/", contacts).Methods("GET")

log.Fatal(srv.ListenAndServe(":8004", r))
```
As expected, I can access the root path on URL

`https://mydomain.com/contacts/`

but no matter what I do I cannot access the other handlers.

`https://mydomain.com/contacts/12334343` will also serve the root but I want this to serve the  `contact` method. 

The same way `https://mydomain.com/contacts/records` is not doing what I expected which is serving the `contacts` method.

If I remove "/" from the configuration then I never reach any of the other handlers.

I have tried many things but nothing seems to work. Your help would be really appreciated.

Thanks

…

**Versions**
> Go version: `1.15.3`

> package version: run `d07530f46e1eec4e40346e24af34dcc6750ad39f` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise, we're left guessing!
Above

> Hint: wrap it with backticks to format it

…

**Comment by roberthstrand** [comment]
Routes look fine but you are referencing a `srv` when running the server, how have you defined that?

**Comment by FaheemuddinKhan** [comment]
@ajpinedam 

I am trying to replicate it at my end and I am not sure how the requests are forwarded from a cloud provider to Go Mux.
To debug further, could you please put some debug statements in Handler function(s) which is/are getting triggered.

+ 	log.Println(request.Host)
+	log.Println(request.RequestURI)

**Comment by elithrar** [comment]
The order of the routes matters.

**Comment by elithrar** [comment]
https://pkg.go.dev/github.com/gorilla/mux#section-readme

> Routes are tested in the order they were added to the router. If two routes match, the first one wins

Put the more specific routes at the top. Your "root" or "index" route should be last.
