### ISSUE TITLE
[feature] dedupe/deduplicate middleware

### ISSUE THREAD

**Issue by komuw** [gorilla/mux#654]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"
- Imagine we have a middleware that collects metrics, or does logging
```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"github.com/gorilla/mux"
)

func homehandler() http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(""))
	}
	return http.HandlerFunc(fn)
}

func metricsMiddleware(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		// Increment some metric counters and send to our metrics dashboard
		fmt.Println("metricsMiddleware called.")
		next.ServeHTTP(w, r)
	}
	return http.HandlerFunc(fn)
}

func main() {
	r := mux.NewRouter()
	r.Use(metricsMiddleware) // bug, middleware added thrice.
	r.Use(metricsMiddleware) // bug, middleware added thrice.
	r.Use(metricsMiddleware) // bug, middleware added thrice.
	r.Handle("/home", homehandler())

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/home", nil)
	r.ServeHTTP(rec, req)
}
```
```sh
metricsMiddleware called.
metricsMiddleware called.
metricsMiddleware called.
```

Now, our middleware is called thrice and we have triple counted our metrics.
The fix, would be to remove the bug and not add the middleware twice. But I feel like `mux` could help us here and dedupe middlewares.

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?
- `mux` to dedupe middleware

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?
- Audit codebase to make sure we do not call `mux.Use` more than once for the same middleware

**Comment by elithrar** [comment]
How would you "de-dupe" middleware, here? What would be the "key" that you identify a duplicate on, without reflection? (and even with reflection)

In many cases, users may want to (and do, in practice) call `router.Use()` over the same "middleware", passing it different parameters or config - e.g. you could have multiple logging or metrics instances with different destinations configured, or authentication middleware, etc.

It's unclear how mux, or any router, can reliably be in a position to deduplicate. Any attempt to do so is likely to introduce _more_ bugs and implicit behaviour.

**Comment by komuw** [comment]
Yeah it would have to be via reflection.

**Comment by komuw** [comment]
Come to think of it, this might be better if implemented elsewhere.
