### ISSUE TITLE
[feature] Write a statement in README describing why this is better than net/http

### ISSUE THREAD

**Issue by davidmichaelkarr** [gorilla/mux#655]
I often read statements about implementing REST services in go saying that "net/http is all you need".  When I had to implement one, I did a rough survey of what frameworks were available, and I thought that perhaps gorilla/mux provided a little more convenience than net/http, but I concluded that without much specific evidence. It would be very useful if the documentation for this project made it clear what its advantages are over net/http in a short list of bullet items.

**Comment by RaboliotLeGris** [comment]
I second this. 

I had this "argument" with a colleague of mine this morning.
Plus the whole toolkit, the syntax I prefer, the main reason, he saw the light was that with the standard "net/http" library you can't have out of the box variable in your path (`/pathwith/:args/in/it`). 
[Here](https://benhoyt.com/writings/go-routing/) is an awesome article that talk about this specific topic.

I will continue a bit my research and propose something about this.

**Comment by davidmichaelkarr** [comment]
From my small experience with this, I think that is the main functional advantage.  If I understand this correctly, since it also just uses net/http for the actual network communication, the performance impact should be minimal.
