### ISSUE TITLE
[question] Is gorilla mux under active development?

### ISSUE THREAD

**Issue by maheshimac** [gorilla/mux#656]
I am new to go lang.
I just came to know about gorilla/mux and I want to use it.

But last two years there is no update on this plugin.
Though it is not necessary to have update, I want to make sure that this plugin is under development or not

Please let me know 

Thanks

**Comment by elithrar** [comment]
See https://github.com/gorilla/mux/issues/659

Note that the [last release](https://github.com/gorilla/mux/releases/tag/v1.8.0) was Aug, 2020 - not sure where "2 years" comes in here. It's also worth noting that mux is fairly stable, and outside of general URL matching and middleware semantics, is unlikely to require large, wholesale changes going forward.
