### ISSUE TITLE
[feature] Update import paths for go.opentelemetry.io/otel/semconv 

### ISSUE THREAD

**Issue by MariuszJu** [gorilla/mux#657]
Recently after upgrade `go.opentelemetry.io/otel` to the current version `v1.2.0` I got errors:
```
../../../../../go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.18.0/mux.go:29:2: no required module provides package go.opentelemetry.io/otel/semconv; to add it:
	go get go.opentelemetry.io/otel/semconv
```
but in current otel version import paths are slightly different:
`/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.18.0/mux.go`:

currently is:
`"go.opentelemetry.io/otel/semconv"`
and should be:
`"go.opentelemetry.io/otel/semconv/v.1.7.0"` (available versions: 1.4.0, 1.5.0, 1.6.1, 1.7.0).

**Comment by elithrar** [comment]
This is not something we can do - any imports need to be managed by the OpenTelemetry project. mux is just a dependency.
