### ISSUE TITLE
[question] Unclear behaviour of Subrouter and PathPrefix

### ISSUE THREAD

**Issue by kwiat1990** [gorilla/mux#664]
**Describe the problem you're having**

Hi, both Go and Gorilla are new to me and I'm trying different things out while building a small microservice. For this purpose I've created a simple routing, in which I wanted to take advantage of declaring path prefix for all API routes. So in order to achieve this came up with something like this:

```go
        router := mux.NewRouter()
	router.StrictSlash(true)

	apiRouter := router.PathPrefix("/api")
	
        // variant #1: does not work and returns 404 for all pages listed below
	getRouter := apiRouter.Methods(http.MethodGet).Subrouter()

        // variant #2: oddly, it does work but why?
        getRouter := router.PathPrefix("/api").Methods(http.MethodGet).Subrouter()

	getRouter.HandleFunc("/", teamsHandler.GetTeams)
	getRouter.HandleFunc("/{id:[0-9]+}", teamsHandler.GetTeam)

        // as intended, it works with both variants (not affected by prefixing)
        router.Handle("/docs", swaggerHandler)
```

The full code can be found in my repo [here](https://github.com/kwiat1990/go-microservice/tree/59d5c9f8bb4d15888c104c904e938c0345ea8048).

I can't wrap my head why does this code work as soon as the `PathPrefix` is defined directly on `getRouter` variable but not when it's stored into a separate `apiRouter` variable. I have assumed both variants should be the same. It turns out they're not and I would like to understand why it is so. Could someone please explain it to me?

**Versions**
> Go version: `1.17.5`

> package version: `v1.8.0`

**Comment by DavidLarsKetch** [comment]
Hey @kwiat1990! Sorry to hear you're having trouble. Unfortunately, I'm not able to replicate the issue. When I do:
```go
router := mux.NewRouter()
router.StrictSlash(true)

test := router.PathPrefix("/test")
getRouter := test.Methods(http.MethodGet).Subrouter()
getRouter.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { w.Write([]byte("Hello, world!")) })
```
And use `router` in an `http.Server`, requesting `/test` writes "Hello, world!". Did I misunderstand something about your code snippet above?

In your [linked repo](https://github.com/kwiat1990/go-microservice/blob/59d5c9f8bb4d15888c104c904e938c0345ea8048/main.go), I didn't notice a reference to `PathPrefix`. Did you have a different snippet in mind that you were having issues with? I also noticed you're using `handlers.CORS`, could the issue be there?

**Comment by kwiat1990** [comment]
@DavidLarsKetch thanks for responding. [Here](https://github.com/kwiat1990/go-microservice/blob/59d5c9f8bb4d15888c104c904e938c0345ea8048/main.go) you can find the updated version of the code, which defines the prefixed paths. 

I don’t quite liked the way it is implemented but it works. The other variant (visible in the above code snippet) doesn’t worked for me, although I think it doesn’t make anything else than the implemented version. Both should act the same.
