### ISSUE TITLE
I have a question about github.com/gorilla/mux and I'm getting import cycle not allowed error

### ISSUE THREAD

**Issue by Ujjwalroy** [gorilla/mux#668]
Hi, I'm currently using Golang and I'm facing some issues in Golang  on github.com/gorilla/mux 
I'm getting import cycle not allowed error

could not import github.com/gorilla/mux (no required module provides package "github.com/gorilla/mux")compilerBrokenImport
import cycle not allowedgo list

if anyone has any idea about my difficulties please help me.

**Versions**
> go version go1.17.5 windows/amd64

**" the code!"**
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"github.com/gorilla/mux"
)

func homepage(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to home page")
	fmt.Println("Endpoint hit: homepage")

}

func handlerequests() {
	myRouter := mux.NewRouter().StrictSlash(true)
	myRouter.HandleFunc("/", homepage)
	myRouter.HandleFunc("/articles", returnAllArticles)
	log.Fatal(http.ListenAndServe(":10000", myRouter))

}

type Article struct {
	Title   string `json:"Title"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
}

var Articles []Article

func returnAllArticles(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpointhit: ReturnAllArticle")
	json.NewEncoder(w).Encode(Articles)

}

func main() {
	Articles = []Article{
		{Title: "Hello", Desc: "Article Description", Content: "Article Content"},
		{Title: "Hello 2", Desc: "Article Description", Content: "Article Content"},
	}
	handlerequests()
}

**Comment by ya5u** [comment]
@Ujjwalroy I've run your code, but no error has occurred. What command did you run when you've encountered the error? Is that all of your code? Is there `go.mod` file in your project root?

**Comment by Ujjwalroy** [comment]
@ya5u 
The command I used is:  go run .\Router.go(FileName)
**Error**:  could not import github.com/gorilla/mux (no required module provides package "github.com/gorilla/mux")compilerBrokenImport
import cycle, not allowed go list

I have put all of my code and yes I have **go.mod** file in my project root.

**Comment by ya5u** [comment]
@Ujjwalroy Thank you for the details. Running `go mod tidy` before `go run` might help the situation.

**Comment by Ujjwalroy** [comment]
> @Ujjwalroy Thank you for the details. Running `go mod tidy` before `go run` might help the situation.

 yeah, I run `go mod tidy` but still get the same error.

**Comment by ya5u** [comment]
@Ujjwalroy umm... Is the file structure in your directory like below? What are the contents of `go.mod` and `go.sum`?

```
.
+-- go.mod
+-- go.sum
+-- Router.go
```

**Comment by Ujjwalroy** [comment]
Here is my code and error image [https://drive.google.com/file/d/1-Z4HY0VacHiiQFXTj3NHs6MdjMMLt_q5/view?usp=sharing](URL)

**Comment by Ujjwalroy** [comment]
This is my code and error image link https://drive.google.com/file/d/1-Z4HY0VacHiiQFXTj3NHs6MdjMMLt_q5/view?usp=sharing

**Comment by ya5u** [comment]
@Ujjwalroy ok, I know the error you face, but could you answer my questions??

>  Is the file structure in your directory like below? What are the contents of go.mod and go.sum?
> 
> ```
> .
> +-- go.mod
> +-- go.sum
> +-- Router.go
>  ```

Especially, show me the contents of `go.mod` and `go.sum` to check if the command `go mod tidy` made these files properly.

**Comment by Ujjwalroy** [comment]
`go.mod` is a video like a file.  https://drive.google.com/file/d/1bycEZ7lYWo935Wy2NCyKSy_H9YGHm_ce/view?usp=sharing

`go.sum` file contents https://drive.google.com/file/d/1kQ01QPgq0u70HedzhyFwkerLFqTmRQv0/view?usp=sharing

**Comment by ya5u** [comment]
@Ujjwalroy `go.mod` must be a text file and it's bad that there isn't `github.com/gorilla/mux` in your `go.sum`. If your Go environment is installed correctly, `go mod tidy` should generate proper `go.mod` and `go.sum`.  
So this is a problem specific to your Go development environmet, not gorilla/mux issue.

[This doc](https://go.dev/ref/mod) may help you to understand Go Modules.  
I'm not good at Windows and PowerShell environment, so if you want to know further, I suggest you to search or post a question in stackoverflow or similar.

**Comment by Ujjwalroy** [comment]
@ya5u
**This is the output of a program**  
maybe this is helpful to understand the error 

[Info  - 4:21:28 pm] 2022/02/08 16:21:28 go env for C:\Users\ujjwa\OneDrive\Desktop\GoFiles\router
(root C:\Users\ujjwa\OneDrive\Desktop\GoFiles\router)
(go version go version go1.17.6 windows/amd64)
(valid build configuration = true)
(build flags: [])
GOPRIVATE=
GOMODCACHE=C:\Users\ujjwa\go\pkg\mod
GOPROXY=https://proxy.golang.org,direct
GOROOT=C:\Program Files\Go
GOFLAGS=
GOPATH=C:\Users\ujjwa\go
GOMOD=C:\Users\ujjwa\OneDrive\Desktop\GoFiles\router\go.mod
GONOPROXY=
GOSUMDB=sum.golang.org
GOCACHE=C:\Users\ujjwa\AppData\Local\go-build
GONOSUMDB=
GO111MODULE=
GOINSECURE=


[Info  - 4:21:30 pm] 2022/02/08 16:21:30 go/packages.Load
	snapshot=0
	directory=C:\Users\ujjwa\OneDrive\Desktop\GoFiles\router
	query=[builtin github.com/gorilla/mux/...]
	packages=2

[Info  - 4:21:31 pm] 2022/02/08 16:21:31 discovered missing identifiers: map[memRecordCycle:true pageBits:true]
	package="runtime"

[Info  - 4:21:31 pm] 2022/02/08 16:21:31 discovered missing identifiers: map[options:true]
	package="vendor/golang.org/x/text/unicode/bidi"

[Info  - 4:22:01 pm] 2022/02/08 16:22:01 background imports cache refresh starting

[Info  - 4:22:02 pm] 2022/02/08 16:22:02 background refresh finished after 840.7016ms

[Info  - 4:28:12 pm] 2022/02/08 16:28:12 background imports cache refresh starting

[Info  - 4:28:12 pm] 2022/02/08 16:28:12 background refresh finished after 47.0445ms

[Error - 4:29:58 pm] 2022/02/08 16:29:58 command error: err: exit status 1: stderr: package github.com/gorilla/mux
	imports github.com/gorilla/mux: import cycle not allowed


[Error - 4:29:58 pm] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: package github.com/gorilla/mux
	imports github.com/gorilla/mux: import cycle not allowed

  Code: 0 
[Info  - 4:30:10 pm] 2022/02/08 16:30:10 background imports cache refresh starting

[Info  - 4:30:10 pm] 2022/02/08 16:30:10 background refresh finished after 63.242ms

**Comment by ya5u** [comment]
@elithrar It would be appropriate to close this issue.

**Comment by Ujjwalroy** [comment]
thanks, @ya5u I have slove issue with the system environment thanks for your time

**Comment by Mwawaka** [comment]
Very helpful. Thanks a lot
