### ISSUE TITLE
Debugging output

### ISSUE THREAD

**Issue by autarch** [gorilla/mux#68]
It would be really helpful if I could set a debug flag on a router and have it spit out log messages telling me what it's doing when it's asking to handle a request. As it is, debugging routing failures requires a lot of guess work.

I'd be happy to work on a PR if you could give me some guidance on the API.

**Comment by kisielk** [comment]
I think this would be pretty complicated to add and I don't have much inclination to work on it. If someone has a good idea or implementation that wouldn't impact performance with debugging turned off, I'd be willing to look at PR.

**Comment by roshan3133** [comment]
In python flask  framework has this debug mode, will you be able to possible for you to have a look into it.

**Comment by stephanwesten** [comment]
I would like to see the request body content when debug is turned on

**Comment by elithrar** [comment]
The best way to do this is to write middleware that walks routes & adds other useful debug info. The challenge is that “useful” is defined differently from person to person. 

Open to a documentation PR with an example of said middleware, but not including by default.
