### ISSUE TITLE
This may be Typosquatting?

### ISSUE THREAD

**Issue by aoisensi** [gorilla/mux#682]
github,com / go**llir**a
He has many cloned package.

**Comment by amustaque97** [comment]
@aoisensi , please don't try your hacking stuff here. Next time you will be banned from this project. If you have any serious questions/queries or any proposal, feel free to ask for the help. 

thank you

@elithrar  "close this"

**Comment by aoisensi** [comment]
This is not me.
I just found it today.

**Comment by aoisensi** [comment]
It could be dangerous, and I used it, so I just made an issue to call attention.

**Comment by amustaque97** [comment]
> This is not mine. I just found it today.

Apologise for confusion. Thank you for bringing it to our attention @aoisensi  👏🏻 

Github username: GOLLIRA is a different account and it has nothing to do with any of the GORILLA projects. 

Both accounts are different.

**Comment by aoisensi** [comment]
No problem. Sorry for bad English.
Not a few Japanese-language articles have made referrals to suspicious packages, which should be addressed.
