### ISSUE TITLE
Can not import mux in my project

### ISSUE THREAD

**Issue by autumnnn111** [gorilla/mux#690]
**Describe the problem you're having**
> when I run 'go get -u github.com/gorilla/mux', i can find the package in /go/pkg/mod, but it still trouble when i import gorilla/mux in my project

…

**Versions**
> Go version: 1.18

> package version: mux @v1.8.0

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by amustaque97** [comment]
Hi @autumnnn111, can you show us the code for how are you importing the mux project?

>Hint: wrap it with backticks to format it

**Comment by autumnnn111** [comment]
> Hi @autumnnn111, can you show us the code for how are you importing the mux project?
> 
> > Hint: wrap it with backticks to format it

import "github.com/gorilla/mux"

> go.mod
// note:Unresolved dependency 
require github.com/gorilla/mux v1.8.0 // indirect

**Comment by amustaque97** [comment]
Could you share your `go env` values. Looks like something is wrong with the path. That's why it is not able to resolve the path of `/go/pkg/mod`

In my case this is how it look and it is working on my machine: 
<img width="1301" alt="Screenshot 2022-07-30 at 2 44 04 PM" src="https://user-images.githubusercontent.com/21127788/181903899-6792460a-5d6b-4adb-93af-15c3b20893f8.png">


<img width="1790" alt="image" src="https://user-images.githubusercontent.com/21127788/181903940-32ad539a-30c1-495a-9bf6-7e30e751b451.png">

**Comment by autumnnn111** [comment]
i am truly sorry that i can not show you the picture of my go env  values, but my **GOPATH, GOMODCACHE**and other 
params are highly similar as yours, thanks for your help!

**Comment by autumnnn111** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/71487129/181904428-03c57149-ce67-4b2e-8a53-1dd93134c2af.png">

**Comment by amustaque97** [comment]
is it resolved? have you run `go mod tidy`?

**Comment by autumnnn111** [comment]
i have tried before, but it does't work; i even tried delete the directory and reinstall again😢

**Comment by amustaque97** [comment]
I don't think then this issue is related to the mux package. If you're getting any error related to the `go get` then probably look for go config issues.

**Comment by autumnnn111** [comment]
i agree, i will post the solution when i figure it out, thank you!

**Comment by autumnnn111** [comment]
i found out the problems, that's dumb cause i create my project in path"go/src",that's why i can`t resolve the dependcies,
i already fix it ,thanks again for your help👍!

**Comment by amustaque97** [comment]
@autumnnn111,  yay, glad you fixed it. can you please close this issue?
