### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Aann102030** [gorilla/mux#707]
**Describe the bug**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by amustaque97** [comment]
@Aann102030, there are no bug details. Can you please close the issue?

**Comment by amustaque97** [comment]
Hey, @coreydaley I saw your activity on the repo and AFAIK the gorilla project is in archive mode why anyone would bother to update the repo? Or are we planning to revive the project again? 

Thank you

**Comment by AlexVulaj** [comment]
Hi there @amustaque97 - a group of us have banded together to revive and maintain the project. As of now all of the individual repositories are unarchived, but we're still in the transition process.

**Comment by amustaque97** [comment]
> Hi there @amustaque97 - a group of us have banded together to revive and maintain the project. As of now all of the individual repositories are unarchived, but we're still in the transition process.

That's great news. Horray, looking forward to more contributions.

**Comment by ptheunis** [comment]
Amazing news!

**Comment by catatsuy** [comment]
I'm so happy to see this project back. Thank you for making this happen.

I'm interested in helping with the project too. How can I join you in the maintenance work?

Thanks and looking forward to your reply.

**Comment by coreydaley** [comment]
@catatsuy Make sure that you have joined the mailing list and we will announce when we have completed the transition of the project, and when we are going to have triage sessions for the existing issues and pull requests.

**Comment by catatsuy** [comment]
@coreydaley Thank you for your response. I am excited to help with the project.

I understand that I need to join the project mailing list, but I'm not sure how to do that. Could you please guide me on how to join the mailing list?

**Comment by coreydaley** [comment]
@catatsuy Sure, go to https://groups.google.com/g/gorilla-web and click the `Join group` button at the top of the page.

**Comment by catatsuy** [comment]
@coreydaley I've joined the mailing list now. Thank you for your help.

I'm excited to be a part of the project.

**Comment by coreydaley** [comment]
@catatsuy Thank you for wanting to be a part of it!

We will announce the triage sessions on the list hopefully soon after July 31st, so stay tuned!

**Comment by cuishuang** [comment]
Very happy to hear this news. come on

**Comment by Melkeydev** [comment]
This is big W

**Comment by FirstWhack** [comment]
> @catatsuy Sure, go to https://groups.google.com/g/gorilla-web and click the `Join group` button at the top of the page.

This link is full of spam, cracked games and malicious links.

**Comment by jaitaiwan** [comment]
Still working on all the Gorilla projects to bring them back to life. There’s a lot of maintenance work we’re having to do to get things up to scratch for instance enabling discussions in gitlab etc.

**Comment by FirstWhack** [comment]
> Still working on all the Gorilla projects to bring them back to life. There’s a lot of maintenance work we’re having to do to get things up to scratch for instance enabling discussions in gitlab etc.

The readme could use an update to acknowledge the archival and subsequent un-archival. Googling Gorilla Mux brings very confusing results - articles for how to migrate after the deprecation, reddit posts about the project becoming active again, the malicious google group content.
