### ISSUE TITLE
[feature] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by crenshaw-dev** [gorilla/mux#711]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

I didn't know the project was short on dev help until the repo was archived. I'd like to stay a bit active and help if possible, since Argo CD currently depends on mux.

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

If there are regular contributors meetings or a mailing list or anything else that would be helpful for contributors, it would be good to add that to CONTRIBUTING.md. Also, if there's a way to donate, that should be documented.

I'm happy to write this up, if a maintainer can drop a quick bullet list of things the doc should include.

**Comment by theghostmac** [comment]
Hey, I would love to support in any way. I kept using Mux locally despite it being archive. 

_My code editor raises warnings every time I use it (which is actually all the time). Seeing today that it works normally made me come check out the repo, and viola! it's back up._

I will keep an eye out for recent documentation needs and quick fixes.

**Comment by coreydaley** [comment]
All of our documents such as CONTRIBUTING.md live in the .github repo for this organization which is located at https://github.com/gorilla/.github , though it might be a good idea to point people towards that in the README of each repo.

All of our supported communication avenues are listed under the Community section of the website https://gorilla.github.io/#community.

We are hoping to finish up the bulk of the transition and updates that we are doing by the end of July, then we will start announcing some community meetings to triage up all of the issues and pull requests across the organization https://github.com/orgs/gorilla/projects/4 .

**Comment by crenshaw-dev** [comment]
Perfect, thanks!
