### ISSUE TITLE
[question] Is it true? Is the GWT unarchived, for real?

### ISSUE THREAD

**Issue by clockworksoul** [gorilla/mux#715]
I noticed that the project has been unarchived and the "this project is archived" message removed from the README.

Can this be interpreted as the project being supported once again?

**Comment by AlexVulaj** [comment]
Yes, and we'll have a small announcement up soon.

**Comment by clockworksoul** [comment]
You've made my day. Thank you.

**Comment by anthonycorbacho** [comment]
I literally almost cried.
