### ISSUE TITLE
JSON parsing failed

### ISSUE THREAD

**Issue by zorro0799** [gorilla/mux#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"strconv"

	"github.com/gorilla/mux"
)

// Book struct (Model)
type Book struct {
	ID    string `json:"id"`
	Isbn  string `json:"isbn"`
	Title string `json:"title"`
	//Author *Author `json:"author"`
}

// Author struct
type Author struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

// Init books var as a slice Book struct
var books []Book

// Get all books
func getBooks(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(books)
}

// Get single book
func getBook(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	params := mux.Vars(r) // Gets params
	// Loop through books and find one with the id from the params
	for _, item := range books {
		if item.ID == params["id"] {
			json.NewEncoder(w).Encode(item)
			return
		}
	}
	json.NewEncoder(w).Encode(&Book{})
}

// Add new book
func createBook(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	var book Book
	var vv error = json.NewDecoder(r.Body).Decode(&book)
	println(vv)
	book.ID = strconv.Itoa(rand.Intn(100000000)) // Mock ID - not safe
	books = append(books, book)
	json.NewEncoder(w).Encode(book)
	fmt.Println("isbn", book.Isbn, "title", book.Title)
}

// Update book
func updateBook(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	params := mux.Vars(r)
	for index, item := range books {
		if item.ID == params["id"] {
			books = append(books[:index], books[index+1:]...)
			var book Book
			_ = json.NewDecoder(r.Body).Decode(&book)
			book.ID = params["id"]
			books = append(books, book)
			json.NewEncoder(w).Encode(book)
			return
		}
	}
}

// Delete book
func deleteBook(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	params := mux.Vars(r)
	for index, item := range books {
		if item.ID == params["id"] {
			books = append(books[:index], books[index+1:]...)
			break
		}
	}
	json.NewEncoder(w).Encode(books)
}

// Main function
func main() {
	// Init router
	r := mux.NewRouter()

	// Hardcoded data - @todo: add database
	//books = append(books, Book{ID: "1", Isbn: "438227", Title: "Book One", Author: &Author{Firstname: "John", Lastname: "Doe"}})
	//books = append(books, Book{ID: "2", Isbn: "454555", Title: "Book Two", Author: &Author{Firstname: "Steve", Lastname: "Smith"}})
	books = append(books, Book{ID: "1", Isbn: "438227", Title: "Book One"})
	books = append(books, Book{ID: "2", Isbn: "454555", Title: "Book Two"})

	// Route handles & endpoints
	r.HandleFunc("/books", getBooks).Methods("GET")
	r.HandleFunc("/books/{id}", getBook).Methods("GET")
	r.HandleFunc("/books", createBook).Methods("POST")
	r.HandleFunc("/books/{id}", updateBook).Methods("PUT")
	r.HandleFunc("/books/{id}", deleteBook).Methods("DELETE")

	// Start server
	log.Fatal(http.ListenAndServe(":8000", r))
}
```

// Request sample
// {
// 	"isbn":"4545454",
// 	"title":"Book Three",
// 	"author":{"firstname":"Harry","lastname":"White"}
// }

Postman simulates the post event and calls createBook
JSON parsing failed

### Expected Behavior

json decode success

### Steps To Reproduce

1.mac os Monterey
2.
json data
// Request sample
// {
// 	"isbn":"4545454",
// 	"title":"Book Three",
// 	"author":{"firstname":"Harry","lastname":"White"}
// }

Postman simulates the post event and calls createBook
JSON parsing failed

**Comment by coreydaley** [comment]
I am not able to reproduce your error using the following curl command:
`curl --header "Content-Type: application/json"   --request POST   --data '{"isbn":"4545454","title":"Book Three","author":{"firstname":"Harry","lastname":"White"}}'   http://localhost:8000/books`

Can you provide the actual error that you are getting?

**Comment by jackgris** [comment]
I tested that and everything works well for me. When I make the POST request with that data, I receive a response like this:
```json
{
    "id": "42982700",
    "isbn": "4545454",
    "title": "Book Three"
}
```
And also  I added log to check the errors when encode the json.
```go
	err := json.NewEncoder(w).Encode(book)
	if err != nil {
		log.Println(err)
	}
```

**Comment by coreydaley** [comment]
It could be a problem with your `postman` setup, I am guessing this is what you are using?
https://www.postman.com/

**Comment by zorro0799** [comment]
> 可能是你的`postman`设置有问题，我猜你用的是这个？ https://www.postman.com/

Indeed, I am using postman, my environment is,
macos 12.6.8, go version go1.21.0
I tried to use RapidApi to simulate the post request, the result is correct, but the shopping store is always lost with postman
![截屏2023-08-15 21 28 29](https://github.com/gorilla/mux/assets/8001326/9daf751e-d2a6-4a44-9165-3a82b5b651e1)
![截屏2023-08-15 21 24 27](https://github.com/gorilla/mux/assets/8001326/379d062f-ff5d-4c84-b269-c080db67e7ba)
![截屏2023-08-15 21 25 07](https://github.com/gorilla/mux/assets/8001326/df306083-9b4b-48d6-af1e-22df5be6d0c3)

**Comment by coreydaley** [comment]
Does postman persist your application? Does it keep it running in the background? If not, and it restarts it for every request, that would remove the data that you just submitted from memory since you are not using a persistent data store.

**Comment by zorro0799** [comment]
> Does postman persist your application? Does it keep it running in the background? If not, and it restarts it for every request, that would remove the data that you just submitted from memory since you are not using a persistent data store.
> 
> I have never used postman so I have no idea how it works, but it seems like this is not an issue with the mux library.

I confirm that I clean up the process every time I test, and then run a new instance, the same program, simulated with other tools, such as RApidApi (Paw), there is no problem, it seems to be a problem with postman, thank you for your answer
