### ISSUE TITLE
[BUG] Go can't find v2.0

### ISSUE THREAD

**Issue by Philio** [gorilla/mux#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
% go get github.com/gorilla/mux@v2.0  
go: github.com/gorilla/mux@v2.0: no matching versions for query "v2.0"
```

### Anything else?

I assume it's because the `v2.0` tag doesn't follow the major.minor.patch version number format

**Comment by coreydaley** [comment]
This should be fixed now, the new release for gorilla/mux is v1.8.1
