### ISSUE TITLE
Cannot install gorilla/mux with new install command of go

### ISSUE THREAD

**Issue by foragerDev** [gorilla/mux#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I run this command its says something liket his: 
```
PS C:\Users\DELL\shop-server> go install github.com/gorilla/mux@latest
package github.com/gorilla/mux is not a main package
```

### Expected Behavior

It should install the package

### Steps To Reproduce

Just try to install this package on go 1.20.

**Comment by coreydaley** [comment]
You can also use the `go get` command to add it to your project
