### ISSUE TITLE
Can't use path variables in subrouter

### ISSUE THREAD

**Issue by KoFish** [gorilla/mux#75]
In the following application I expected a request to `/foo/bar/11` and `/foo/11` to both return the same response; `Vars: map[id:11]`. But it turns out that `/foo/bar/11` instead returns a 404 error.

```go
package main

import (
    "fmt"
    "github.com/gorilla/mux"
    "net/http"
)

func Test(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Vars: %v", mux.Vars(r))
}

func main() {
    root := mux.NewRouter()
    foo := root.Path("/foo/").Subrouter()
    foobar := foo.Path("/bar/").Subrouter()

    foo.HandleFunc("/{id}", Test).Name("foo")
    foobar.HandleFunc("/{id}", Test).Name("bar")

    http.Handle("/", foo)

    http.ListenAndServe(":8080", nil)
}
```

**Comment by runcom** [comment]
this code just handle `/foo/11` and `/bar/11`. Based on what are you expecting to request `/foo/bar/11`?!

**Comment by KoFish** [comment]
Since the foo router is a subrouter to root on the path /foo/ I expect adding the path /bar/ to it would serve /foo/bar/
Honestly it's been too long since I wrote this ticket for me to actually care any more.

**Comment by eastwood** [comment]
This is how I achieve the desired result. I believe the idiomatic way to achieve this is using `PathPrefix`
```
func main() {
	r := mux.NewRouter()
	foo := r.PathPrefix("/foo").Subrouter()
	foo.Path("/{key}").HandlerFunc(Test)
	bar := foo.PathPrefix("/bar").Subrouter()
	bar.Path("/").HandlerFunc(Test)
	bar.Path("/baz").HandlerFunc(Test)

	http.ListenAndServe(":8080", r)

}
```

**Comment by djgilcrease** [comment]
@KoFish There is a big difference between Path & PathPrefix

In your example the only paths that would actually be matched are

```
/foo/
/bar/
/{id}
/
```

Path changes the regex used to match to be ```<path>$``` which means that the whole path must end with ```<path>``` So in almost all cases you want to use PathPrefix
