### ISSUE TITLE
Maybe a Gorilla Issue...

### ISSUE THREAD

**Issue by achedeuzot** [gorilla/mux#76]
Hello,

I have a strange error using Gorilla Mux. Maybe it's the way I'm using it or maybe it's something else. I just posted a link on stackoverflow about this strange problem I'm having: the route works once then I get `404 page not found`.

http://stackoverflow.com/questions/26653152/gorilla-mux-router-from-inside-handler-only-works-once-then-gives-404-page-not-f

Thanks for pointing out what may be the poblem.

**Comment by kisielk** [comment]
Closing this for now since it's vague. If you are still having problems please file a new issue with a runnable code example.

**Comment by fesja** [comment]
Hi kisielk!

I'm having this problem. You can see here a [code example that other person posted on SO almost a year ago](http://stackoverflow.com/questions/26653152/gorilla-mux-router-from-inside-handler-only-works-once-then-gives-404-page-not-f). Here you can find [another example in SO](http://stackoverflow.com/questions/23553061/how-to-call-a-route-by-its-name-from-inside-a-handler).

The problem appears when we try to get another route URL form inside a Handler. For example from the PostUpdateHandler we want to redirect the user to the PostShowHandler. On those examples people (and myself) are trying to do:

    rootUrl, err := mux.CurrentRoute(r).Subrouter().Get("PostShow").URL()

but this changes the original Router. So then it's when we have the problem with the 404 error.

A solution could be to use a global router variable, but I'm trying to avoid having global variables (I'm doing a clean architecture). I've tried to add the router to my Handler class but it appears to be nil on the Handler.

Any idea on how can we solve this?

thanks a lot!

**Comment by kisielk** [comment]
You just have to save the router or subrouter somewhere where you can access it from your route to call the `URL()` method. Either a global or a field on your handler struct would work. I usually just use global routers and subrouters in the majority of apps. If they are only modified at initialization time there's nothing wrong with that...
