### ISSUE TITLE
[BUG] <Docker build problems with go get command> 

### ISSUE THREAD

**Issue by Esimseitm** [gorilla/mux#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello. I study the Docker course on the coursera.com.  
I use the command go get github.com/gorilla/mux . An error is coming out. Please help me solve the problem. I tried changing it to go install, it didn't help.
<img width="540" alt="Screenshot 2024-06-24 110156" src="https://github.com/gorilla/mux/assets/98973420/009bc8fc-5fd3-48cd-b160-4fa55bb5ec6b">

**Comment by thaJeztah** [comment]
You're using Go 1.15, which is EOL and doesn't support the `any` type. (fwiw, Ubuntu 18.04 also is EOL)

**Comment by jaitaiwan** [comment]
The any keyword happened in Go 1.18. I’d recommend an image something like golang:1.20-alpine at least.

When you are looking at golang repos in the future take a look at the go version listed in go.mod. That will help indicate to you what minimum version you’ll need.

All the best with your project!

**Comment by Esimseitm** [comment]
> The any keyword happened in Go 1.18. I’d recommend an image something like golang:1.20-alpine at least.
> 
> When you are looking at golang repos in the future take a look at the go version listed in go.mod. That will help indicate to you what minimum version you’ll need.
> 
> All the best with your project!

I changed to 1.18 version and try 1.20. But it didn't solve problem.  
Terminal output: go: 'go install' requires a version when current directory is not in a module
                                  Try 'go install github.com/gorilla/mux@latest' to install the latest version
                                  The command '/bin/sh -c go install github.com/gorilla/mux' returned a non-zero code: 1 
Then I tried go install github.com/gorilla/mux@latest. And this again didn't help.

**Comment by thaJeztah** [comment]
Yes, I suspect the code / example code you're trying to build is outdated; go nowadays requires a version to be specified if you run `go install`, but if the code is rewritten to have a `go.mod`, then the `go install` steps may not be needed.
