### ISSUE TITLE
WithContext breaks mux.Vars

### ISSUE THREAD

**Issue by PhillipWhillier** [gorilla/mux#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the WithContext is used the mux.Vars are unavailable in the route handler.

 github.com/gorilla/mux v1.8.1

### Expected Behavior

When the WithContext is used the mux.Vars are available in the route handler.

 github.com/gorilla/mux v1.8.1

### Steps To Reproduce

  // Store the username in the context
  ctx := context.WithValue(context.Background(), "username", claims.Username)
  requestWithContext := request.WithContext(ctx)

// Update handles PUT requests to update an existing Item
func (this *ItemController) Update(response http.ResponseWriter, request *http.Request) {

    vars := mux.Vars(request)
    uuid := vars["uuid"]

**Comment by guidog** [comment]
One should use context coming w/ the request as base for WithContext. context.Background() returns an empty context, so all information already in the request context is lost.

**Comment by PhillipBSDL** [comment]
That's great, thanks for the tip, it works now
