### ISSUE TITLE
[BUG] Error causing build image to fail when creating buildagent via Dockerfile. Error: undefined : any

### ISSUE THREAD

**Issue by j-maltese** [gorilla/mux#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@AlexVulaj could you double check commit: https://github.com/gorilla/mux/commit/10f71ea482969adafbfc9dcbac1bd11691e23708
particularly the route.go file and its use of "any" on lines: 28, 134, 136, 144, 149, 155, 165 ?

I'm not a Go developer, but we use gorilla / mux in an application I work on and when we try to build the image for the build agent, I am getting an error pointing to this file.

We are running this command as part of the Dockerfile: `RUN go get -u github.com/gorilla/mux`

We had a successful build on April 19. This code was added in June and there have been no changes to the Dockerfile we are are running on our end.

I am attaching a screenshot of the errors we get on the failed build.
![Screenshot 2024-08-07 171328](https://github.com/user-attachments/assets/74c70264-f07c-487e-b092-8e553583ae56)

I'm happy to supply additional information if that is helpful. 

### Expected Behavior

Expect the go get command to successfully download https://github.com/gorilla/mux
Screenshot from April 19:
![Screenshot 2024-08-07 173259](https://github.com/user-attachments/assets/b956ef12-ab71-46c9-a716-066a4422fa34)

### Steps To Reproduce

RUN `go get -u github.com/gorilla/mux`

**Comment by ghost** [comment]
Upgrade to the version of Go required by this package, Go 1.20 or later.  

The type alias `any` was introduced in Go 1.18.
