### ISSUE TITLE
API automatic binding and OpenAPI document automatic generation

### ISSUE THREAD

**Issue by HHC26** [gorilla/mux#769]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

API automatic binding: API definition and controller are automatically bound, API parameters are automatically verified, simplifying the API development process and improving development efficiency.

OpenAPI document automatic generation: Supports automatic generation of OpenAPI specification documents, facilitating API debugging and integration.

### Describe the solution that you would like.

For example, the functionality of the implementation of the goframe v2 framework

### Describe alternatives you have considered.

https://github.com/gogf/gf

### Anything else?

For example, the functionality of the implementation of the goframe v2 framework
https://github.com/gogf/gf

**Comment by jaitaiwan** [comment]
Feature request outside the scope of the project. Better implemented by external libraries that make use of mux. Won't do.
