### ISSUE TITLE
Subroutes using PathPrefix don't redirect on POST

### ISSUE THREAD

**Issue by DisruptiveMind** [gorilla/mux#79]
Looking at #31 looks like it's a similar issue with POST though.

Using

``` go
bookRoute := router.PathPrefix("/book").Subrouter()
bookRoute.Handle("/", createBookHandler).Methods("POST")
```

Will only POST to **/book/** and not **/book** without the trailing slash
Trying to append **StrictSlash(true)** to the **Subrouter()** has no effect.

Is there something I'm missing in the setup?

In addition, maybe this is stupid here, but when I POST to the GET route it responds properly. So the following would both succeed, but obviously supports GET requests as well.

``` go
bookRoute := router.PathPrefix("/book").Subrouter()
get := router.Methods("GET").Subrouter()

get.Handle("/book", createBookHandler) // Handles both GET and POST
bookRoute.Handle("/", createBookHandler).Methods("POST")
```

If I remove the **bookRoute** there would only be a 404.

**Comment by dcelasun** [comment]
Sorry to resurrect an old issue, but this is still relevant in 2016 and it isn't specific to `POST`. Here's an example:

```go
adminRouter := router.PathPrefix("/admin").Subrouter()
adminRouter.HandleFunc("", someHandler)
adminRouter.HandleFunc("/", someHandler)
```

With this configuration, `/admin/` works, but `/admin` does not.

**Comment by elithrar** [comment]
Just to clarify, when you say "`/admin/` works, but `/admin` does not" do you mean `/admin` does not work at all and causes a 404?

**Comment by dcelasun** [comment]
Exactly.

**Comment by konradjurk** [comment]
@kisielk Why did you close this, it is still relevant right?

**Comment by husainaloos** [comment]
@kisielk Why is this closed? I am experiencing this problem also.

**Comment by eskombro** [comment]
Relevant in 2020!

**Comment by regnaio** [comment]
Relevant in 2021

**Comment by chancetudor** [comment]
soon to be relevant in 2022...
