### ISSUE TITLE
FileServer not working properly (or at least how it works in the standard net/http package)

### ISSUE THREAD

**Issue by thepixelmonk** [gorilla/mux#8]
`router.Handle("/", http.FileServer(http.Dir("../")))` only seems to work the the path is exactly at the root. So navigating to "/" loads index.html but all the assets fail. "/index.html", "/css/mycss.css", "/imgs/myimg.png", etc. all return 404s. However if I just replace mux with the standard routing everything's fine.

**Comment by batfolx** [comment]
Thank you. I saw a ton of other examples before I saw this one. And this seems to be the simplest, easiest way to do this.
