### ISSUE TITLE
deleting routes

### ISSUE THREAD

**Issue by rbucker** [gorilla/mux#82]
Last night I read all of the stdlib net/http code in order to determine whether or not it was possible to delete a route once it was added and it seems that while you can add handlers at runtime you cannot delete them.  Looking at the Gorilla Mux documentation I see much of the same. Is there any particular use-case against being able to delete routes?

**Comment by kisielk** [comment]
I think a better question is whether there's a use case *for* deleting routes.

**Comment by Knetic** [comment]
I'd +1 this, I use mostly dynamically-mapped routes loaded from a mappings file. Being able to reload the file (and change the routes) without restarting the service (and thereby having to drain connections) would be ideal.

I'm currently using a forked Go stdlib muxer that supports route deregistration, but it's clunky and i'd prefer to use Gorilla's mux.

**Comment by avrtno** [comment]
@Knetic The router does not concurrent modification and request routing. If you want to reload routes, then you should create a new router and swap it with the old one.  For example:

    type routerSwapper struct {
         mu sync.Mutex
        root *mux.Router
    }
  
    func (rs *routerSwapper) Swap(newRouter *mux.Router) {
         rs.mu.Lock()
         rs.root = newRoot
         rs.mu.Unlock
    }

    func (rs *routerSwappter) ServeHTTP(w http.ResponsWriter, r *http.Request) {
        rs.mu.Lock()
        root := rs.root
       rs.mu.Unlock()
       root(w, r)
    }

Use routerSwapper as the root handler with the HTTP server. Call Swap wit a newly constructed router.

**Comment by kisielk** [comment]
I agree with @avrtno 's comment on this. Allowing deleting or modification of routes while the router is running would be troublesome to add at this point, and there's not many uses for it.

**Comment by mogthesprog** [comment]
Hey guys. I know this is an old issue, but i had a question about the method outlined above.

If i've got an open websocket connection being routed by the router when i call `rs.Swap()`, will those connections stay up until they're closed by either client/server, or will the router tare down those connections during the swap?

A little more detail, i'm using gorilla/mux and gorilla/websocket to reverse proxy multiple users and wanted to use this method to update the router on the fly. But i'm wondering whether the swapping process will interfere with already established connections.

**Comment by elithrar** [comment]
The connections will stay up.

**Comment by mogthesprog** [comment]
thank you sir!

**Comment by clarencefoy** [comment]
> @Knetic The router does not concurrent modification and request routing. If you want to reload routes, then you should create a new router and swap it with the old one. For example:
> 
> ```
> (...)
> func (rs *routerSwappter) ServeHTTP(w http.ResponsWriter, r *http.Request) {
>     rs.mu.Lock()
>     root := rs.root
>    rs.mu.Unlock()
>    root(w, r)
> }
> ```
> 
> Use routerSwapper as the root handler with the HTTP server. Call Swap wit a newly constructed router.

When I try this, I get: ```cannot call non-function root (type *mux.Router)```

Any ideas? I have tried simply removing it, and then using the Swap() function, but that seems to keep all routes the same?

**Comment by SmartPhoneJava** [comment]
instead of
```go
 root(w, r)
 ```
use 
```go
root.ServeHTTP(w, r)
```
