### ISSUE TITLE
mux.Vars is empty - and shoudn't be

### ISSUE THREAD

**Issue by tcurdt** [gorilla/mux#84]
I bet it's just me doing something wrong - but then I would ask to improve the docs.
Here is what I am trying:

    router := mux.NewRouter()
    http.Handle("/", handler.LoggingInterceptor(handler.AuthenticationInterceptor(router)))
    router.HandleFunc("/project/{project:[0-9a-zA-Z]+}", handler.PutProject).Methods("PUT")

With the interceptors along the lines of:

    func AuthenticationInterceptor(router http.Handler) http.Handler {
      return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
        vars := mux.Vars(req)
        glog.Infof("Vars: [%q] but %s", vars, req.URL.Path)
        router.ServeHTTP(res, req)
      })
    }

and

    func LoggingInterceptor(router http.Handler) http.Handler {
      return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
        router.ServeHTTP(res, req)
      })
    }

Pretty straight forward. But somehow the variables are empty inside the interceptor.

    Vars: [map[]] but /project/test

As you can see from the logs the request does get matched correctly and the request uri looks OK - but there is no var "project".

What am I missing here?

**Comment by kisielk** [comment]
Your interceptor is calling `mux.Vars` before it calls the router, so the router code which extracts the route vars hasn't run yet.

**Comment by tcurdt** [comment]
Ahhhhhhhh!

Not sure there is a suggested way of handling such things but simple chaining did the trick for me:

    router.HandleFunc("/feedback/{project:[0-9a-zA-Z]+}", handler.Test(handler.PutProject)).Methods("PUT")

And then I can either call the callback to pass it on in the chain or handle it myself

    func Test(router http.HandlerFunc) http.HandlerFunc {
      return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {

        vars := mux.Vars(req)
        glog.Infof("Vars: [%q]", vars)

        router(res, req)
      })
    }
