### ISSUE TITLE
getNamedRoutes not exported

### ISSUE THREAD

**Issue by keans** [gorilla/mux#85]
For debugging purposes it would be nice to get all routes, but the getNamedRoutes function is not exported. Is there any reason for that?

**Comment by martinp** [comment]
I agree. Being able to retrieve all defined routes would be useful.

**Comment by oveddan** [comment]
+1

**Comment by kisielk** [comment]
Well, the main reason it's not exported is that it's generally not that useful. The named routes just contains whatever routes you've added to the router and then named with .Name...

**Comment by oveddan** [comment]
It would be useful to be able to be able to grab all of the routes from the outside.  Let's say we want to print them in development environment, or generate some sort of documentation based off of what the routes are and their paths/constraints.

**Comment by kisielk** [comment]
There's another issue for that. getNamedRoutes won't do anything to help you.

**Comment by cfchris** [comment]
Will someone please provide the link to the issue mentioned by @kisielk? I looked and could not find it. We would really like to generate documentation of our API tree using a method to retrieve registered routes. We would even be willing to write the functionality.

**Comment by kisielk** [comment]
I was referring to #83

**Comment by kisielk** [comment]
I just merged #106 which implements the walk functionality originally proposed in #83. It should should be able to do what you need.
