### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by gotjosh** [gorilla/mux#87]
I'm trying to access the site in order to take a look at the documentation and it's giving me a 500 error.

**Comment by garyburd** [comment]
Yup, something is wrong witht site. You can read the documentation at http://godoc.org/github.com/gorilla/mux.

**Comment by gotjosh** [comment]
Thanks buddy.

**Comment by kisielk** [comment]
Site seems to be working fine here. I haven't been very good at keeping on top of it though :/
