### ISSUE TITLE
Header constraint not working

### ISSUE THREAD

**Issue by JorgeRdg** [gorilla/mux#91]
Hi everyone!

I'm developing a small webserver and I've tried to limit access only to Cloudfront, by ensuring the header 'User-Agent' is set to 'Amazon Cloudfront'. I know it's not the safest thing in the world, but at least avoids unintentional requests.

However, I haven't managed to apply this constraint. This is my code so far:
```
r := mux.NewRouter()

// Constraints
s := r.Headers("User-Agent", "Amazon Cloudfront").PathPrefix("/{connection_id}").Subrouter()

// Routes
s.HandleFunc("/product-images/{model_id}", ProductImagesHandler)
s.HandleFunc("/product-images/{model_id}/{max_dimension:[0-9]+}", ProductImagesHandler)
s.HandleFunc("/nav-item-images/{model_id}", NavItemImagesHandler)
s.HandleFunc("/nav-item-images/{model_id}/{max_dimension:[0-9]+}", NavItemImagesHandler)
http.Handle("/", s)

// Keep listening
http.ListenAndServe(":3000", s)
```
However, all the requests go through. Is this a bug? Am I missing something?

I'm using latest Go (1.4.2).

Thanks in advance! ;)

**Comment by kisielk** [comment]
Would need more details about what the request looks like, and what you mean by "all requests go through"... do they actually get routed to the desired handlers regardless of the header? or? May be better to post this to the mailing list: https://groups.google.com/forum/#!forum/gorilla-web

**Comment by JorgeRdg** [comment]
Yes, they just ignore the header value and are handled by the proper handler. The request would be a normal GET request from Chrome: `http://localhost:3000/anything/product-images/whatever`.

Didn't know of that mailing list. Gonna check it ;) Thanks!

**Comment by elithrar** [comment]
See https://groups.google.com/d/msg/gorilla-web/WR3yOKeas5o/Y7bUgR58JtQJ

The issue was that the sub-router was being passed to the `DefaultServeMux` via `http.Handle("/", s)` instead of the `mux.Router` instance.

**Comment by kisielk** [comment]
Cool, thanks for helping out :)
