### ISSUE TITLE
StrictSlash Redirect Still Executes Original Controller

### ISSUE THREAD

**Issue by bieber** [gorilla/mux#92]
I'm not sure how yet, but if I have a router with StrictSlash turned on, and I send a request to, say

    /some/path

it will correctly redirect to

    /some/path/

but in the process it also seems to call the original handler bound to the route.  I'm planning on investigating some more tomorrow and seeing if I can figure out what's causing this, or at least get you a minimal repro example, but before I start in on that I'd appreciate it if you could confirm for me that it's not actually intended behavior?

**Comment by kisielk** [comment]
That shouldn't be happening, and I've never seen that behaviour before. Some code to reproduce would be helpful :+1:

**Comment by bieber** [comment]
Awesome, I went to sleep, went to work, came home and tried to set into it again...and now after rebuilding with a debug.PrintStack() thrown in I can't repro any more.  So I'll just assume it was some bizarre compilation bug or something and you can pretend you never heard from me :p
