### ISSUE TITLE
Queries cannot take queries without values

### ISSUE THREAD

**Issue by fkautz** [gorilla/mux#95]
There does not appear to be a way to match a URL containing a query without a value such as `http://localhost:9000/hello?world` 

`Queries("world", "")` expects to match `"world=.*"` but never `world`

**Comment by crafet** [comment]
same problem happened to me

**Comment by gulyasm** [comment]
I think this issue was resolved. I've run the following test:
`main.go`
```go
func A(rw http.ResponseWriter, r *http.Request) {
    log.Println("Called: " + r.URL.String())
}   
func main() {
    r := mux.NewRouter()
    r.HandleFunc("/hello", A).Queries("world", "")
    http.ListenAndServe(":4999", r)
}   
```

The output was:
```bash
gofix $ go run main.go 
2016/02/27 23:59:41 Called: /hello?world
```
