### ISSUE TITLE
Not possible to extract base64 values through GET function

### ISSUE THREAD

**Issue by rogierlommers** [gorilla/mux#96]
I'm using the following path: `/add/{base64url} to store urls into a database. You can find the handleFunc declaration below. However when the base64-encoded url contains a `/`-character, I get a 404 from mux. 

As an example, see this url: `http://localhost:8080/add/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1UbWlLOXNrZWYzcw==`

As you can see, the "value" which should be inside base64url contains a `/`-character. This is conflicting and I'm not sure how to solve this.

`r.HandleFunc("/add/{base64url}", dao.AddArticle(&database))`

**Comment by zeebo** [comment]
You should use urlsafe base64 encoding that avoids the / character. See http://golang.org/pkg/encoding/base64/#pkg-variables

**Comment by rogierlommers** [comment]
Wow, that's quick :). Still in the process of editing my post :).

**Comment by kisielk** [comment]
So can this be closed?

**Comment by rogierlommers** [comment]
Yes, thanks.
