### ISSUE TITLE
expose routeRegexp?

### ISSUE THREAD

**Issue by bmarini** [gorilla/mux#97]
I have a need to have access to the `routeRegexp` for my routes. The use case is to add an instrumentation middleware for my routes.

I'm trying to add some instrumentation middleware, something along these lines:

``` go
func (h *InstrumentMiddleware) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	routeName := fmt.Sprintf("%s %s", r.Method, r.URL.Path)
	h.instrumenter.Start(routeName)
	defer h.instrumenter.End()
	h.handler.ServeHTTP(w, r)
}
```

What I really want for the `routeName` is the matched path template. If this were exposed on the Route, I'd be able to get at it by injecting the router into my middleware, fetching the matching route, and from there the path template.

Would you be open to a PR to expose the routeRegexp? If you have a better idea please let me know, thanks!

**Comment by djgilcrease** [comment]
Take a look at https://github.com/gorilla/mux/pull/104 and see if it would meet your requirments

**Comment by kisielk** [comment]
I'm inclined not to merge this because it relies on an internal implementation detail. I think we would lose some flexibility in changing the inner functioning of mux if we committed to returning a path template in a particular format. Feel free to re-open for discussion if you disagree.
